import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Coverage: Unit 10, course days 163-180; integrated capstone standards. Decimal money is stored as integer cents. */
export const GRADE5_MATH_UNIT10_ITEM_TYPES=['choose-operation','whole-number-model','division-model','decimal-budget','fraction-project','scale-project','volume-plan','coordinate-data','model-argument'] as const
export type Grade5MathUnit10ItemType=typeof GRADE5_MATH_UNIT10_ITEM_TYPES[number]
type Op={groups:number; each:number; extra:number};type Whole={a:number;b:number};type Div={dividend:number;divisor:number};type Budget={items:number; centsEach:number; feeCents:number};type Fraction={leftN:number;leftD:number;rightN:number;rightD:number};type Scale={whole:number; numerator:number; denominator:number; multiplier:number};type Volume={length:number;width:number;height:number};type Coordinate={x:number;y:number;right:number;up:number};type Argument={length:number;width:number;height:number;claim:number}
type U10<T extends Grade5MathUnit10ItemType,P>=CurriculumQuestion<T,P>
export type Grade5MathUnit10Question=U10<'choose-operation',Op>|U10<'whole-number-model',Whole>|U10<'division-model',Div>|U10<'decimal-budget',Budget>|U10<'fraction-project',Fraction>|U10<'scale-project',Scale>|U10<'volume-plan',Volume>|U10<'coordinate-data',Coordinate>|U10<'model-argument',Argument>
type Standard='5.OA.1'|'5.NBT.5'|'5.NBT.6'|'5.NBT.7'|'5.NF.1'|'5.NF.4'|'5.MD.5'|'5.G.2'|'MP.4';type Def={standard:Standard;lessonFocus:string;workedExample:CurriculumWorkedExample};const ex=(prompt:string,answer:string,...steps:string[]):CurriculumWorkedExample=>({prompt,answer,steps})
export const GRADE5_MATH_UNIT10_ITEM_DEFINITIONS={
 'choose-operation':{standard:'5.OA.1',lessonFocus:'choosing operations',workedExample:ex('6 packs hold 8 pencils each and 3 are loose. How many pencils?','51','Multiply: 6 × 8 = 48.','Add 3 loose pencils: 51.')},
 'whole-number-model':{standard:'5.NBT.5',lessonFocus:'multi-step modeling',workedExample:ex('Find 24 × 13.','312','24 × 10 = 240.','24 × 3 = 72; total 312.')},
 'division-model':{standard:'5.NBT.6',lessonFocus:'constraints and assumptions',workedExample:ex('156 chairs are shared equally among 12 tables. How many per table?','13','12 × 13 = 156.','So each table has 13 chairs.')},
 'decimal-budget':{standard:'5.NBT.7',lessonFocus:'budgeting and measurement',workedExample:ex('3 tickets cost $2.45 each and there is a $1.20 fee. What is the total?','$8.55','3 × 245 cents = 735 cents.','Add 120 cents: 855 cents = $8.55.')},
 'fraction-project':{standard:'5.NF.1',lessonFocus:'multi-step modeling',workedExample:ex('A project uses 1/3 m of blue ribbon and 1/6 m of gold ribbon. How much ribbon?','1/2','Use sixths: 1/3 = 2/6.','2/6 + 1/6 = 3/6 = 1/2.')},
 'scale-project':{standard:'5.NF.4',lessonFocus:'constraints and assumptions',workedExample:ex('A 3/4-meter path is scaled by 2. What length?','1 1/2','Multiply: 3/4 × 2 = 6/4.','Simplify 6/4 to 1 1/2.')},
 'volume-plan':{standard:'5.MD.5',lessonFocus:'budgeting and measurement',workedExample:ex('A box is 4 by 3 by 2 unit cubes. What is its volume?','24 cubic units','Multiply length × width × height.','4 × 3 × 2 = 24.')},
 'coordinate-data':{standard:'5.G.2',lessonFocus:'data and graphs',workedExample:ex('A point is at (2, 3). Move right 4 and up 1. Where is it?','(6, 4)','Right increases x to 6.','Up increases y to 4.')},
 'model-argument':{standard:'MP.4',lessonFocus:'presenting mathematical arguments',workedExample:ex('A student says a 4 by 3 by 2 box has volume 9. Is the claim correct?','No; the volume is 24 cubic units.','Volume uses all three dimensions.','4 × 3 × 2 = 24, not 9.')},
} as const satisfies Record<Grade5MathUnit10ItemType,Def>
function q<T extends Grade5MathUnit10ItemType,P>(itemType:T,difficulty:Difficulty,prompt:string,correctAnswer:string,distractors:string[],parameters:P):U10<T,P>{const d=GRADE5_MATH_UNIT10_ITEM_DEFINITIONS[itemType];return makeCurriculumQuestion({itemType,difficulty,prompt,correctAnswer,distractors,parameters,standard:d.standard,lessonFocus:d.lessonFocus,workedExample:d.workedExample,distractorMode:'distinct'})}
const fmt=(c:bigint)=>`$${c/100n}.${String(c%100n).padStart(2,'0')}`;const gcd=(a:bigint,b:bigint):bigint=>b===0n?a:gcd(b,a%b);function mixed(n:bigint,d:bigint){const g=gcd(n,d);n/=g;d/=g;const w=n/d,r=n%d;return r===0n?String(w):w===0n?`${r}/${d}`:`${w} ${r}/${d}`}
export function generateChooseOperationQuestion(difficulty:Difficulty):U10<'choose-operation',Op>{const p={groups:ri(2,difficulty===1?8:15),each:ri(2,12),extra:ri(1,20)};const a=p.groups*p.each+p.extra;return q('choose-operation',difficulty,`${p.groups} packs hold ${p.each} markers each, and ${p.extra} markers are loose. How many markers are there?`,String(a),[String(a+1),String(a+2),String(a+3),String(a+4)],p)}
export function generateWholeNumberModelQuestion(difficulty:Difficulty):U10<'whole-number-model',Whole>{const p={a:ri(12,difficulty===1?30:99),b:ri(11,difficulty===1?20:50)};const a=BigInt(p.a)*BigInt(p.b);return q('whole-number-model',difficulty,`Find ${p.a} × ${p.b}.`,String(a),[String(a+BigInt(p.a)),String(a-BigInt(p.a)),String(BigInt(p.a)+BigInt(p.b)),String(a+1n)],p)}
export function generateDivisionModelQuestion(difficulty:Difficulty):U10<'division-model',Div>{const divisor=ri(2,difficulty===1?9:20),quotient=ri(3,difficulty===1?15:50),p={dividend:divisor*quotient,divisor};return q('division-model',difficulty,`${p.dividend} supplies are shared equally among ${p.divisor} teams. How many supplies does each team receive?`,String(quotient),[String(quotient+1),String(quotient+2),String(quotient+3),String(quotient+4)],p)}
export function generateDecimalBudgetQuestion(difficulty:Difficulty):U10<'decimal-budget',Budget>{const p={items:ri(2,5),centsEach:ri(125,difficulty===1?499:999),feeCents:ri(25,250)};const a=BigInt(p.items)*BigInt(p.centsEach)+BigInt(p.feeCents);return q('decimal-budget',difficulty,`${p.items} tickets cost ${fmt(BigInt(p.centsEach))} each and there is a ${fmt(BigInt(p.feeCents))} fee. What is the total cost?`,fmt(a),[fmt(a+100n),fmt(a-BigInt(p.feeCents)),fmt(BigInt(p.items)*BigInt(p.centsEach)),fmt(a+BigInt(p.centsEach))],p)}
export function generateFractionProjectQuestion(difficulty:Difficulty):U10<'fraction-project',Fraction>{const d=pick([6,8,10,12] as const),leftN=ri(1,d-2),rightN=ri(1,d-leftN-1),p={leftN,leftD:d,rightN,rightD:d};const a=mixed(BigInt(leftN+rightN),BigInt(d));return q('fraction-project',difficulty,`A project uses ${leftN}/${d} meter of blue ribbon and ${rightN}/${d} meter of gold ribbon. How much ribbon is used?`,a,[mixed(BigInt(leftN+rightN+1),BigInt(d)),mixed(BigInt(Math.abs(leftN-rightN)),BigInt(d)),mixed(BigInt(leftN*rightN),BigInt(d*d)),mixed(BigInt(leftN+rightN),BigInt(d+1))],p)}
export function generateScaleProjectQuestion(difficulty:Difficulty):U10<'scale-project',Scale>{const d=pick([2,3,4,5,6] as const),n=ri(1,d-1),m=ri(2,difficulty===1?3:5),p={whole:0,numerator:n,denominator:d,multiplier:m};const a=mixed(BigInt(n*m),BigInt(d));return q('scale-project',difficulty,`A ${n}/${d}-meter path is scaled by ${m}. What is the new length in meters?`,a,[mixed(BigInt(n+m),BigInt(d)),mixed(BigInt(n),BigInt(d*m)),mixed(BigInt(n*m+1),BigInt(d)),mixed(BigInt(n),BigInt(d))],p)}
export function generateVolumePlanQuestion(difficulty:Difficulty):U10<'volume-plan',Volume>{const p={length:ri(2,8),width:ri(2,8),height:ri(2,difficulty===1?5:10)};const a=BigInt(p.length)*BigInt(p.width)*BigInt(p.height);return q('volume-plan',difficulty,`A storage box is ${p.length} units long, ${p.width} units wide, and ${p.height} units high. What is its volume in cubic units?`,String(a),[String(p.length+p.width+p.height),String(p.length*p.width),String(a+BigInt(p.height)),String(a-BigInt(p.height))],p)}
export function generateCoordinateDataQuestion(difficulty:Difficulty):U10<'coordinate-data',Coordinate>{const p={x:ri(0,8),y:ri(0,8),right:ri(1,5),up:ri(1,5)};while(p.x+p.right===p.y+p.up)p.y=(p.y+1)%9;const a=`(${p.x+p.right}, ${p.y+p.up})`;return q('coordinate-data',difficulty,`A data point is at (${p.x}, ${p.y}). Move right ${p.right} and up ${p.up}. What is the new point?`,a,[`(${p.y+p.up}, ${p.x+p.right})`,`(${p.x+p.right+1}, ${p.y+p.up})`,`(${p.x+p.right}, ${p.y+p.up+1})`,`(${p.x}, ${p.y})`],p)}
export function generateModelArgumentQuestion(difficulty:Difficulty):U10<'model-argument',Argument>{const p={length:ri(2,8),width:ri(2,8),height:ri(2,8),claim:0};const v=p.length*p.width*p.height;p.claim=pick([p.length+p.width+p.height,p.length*p.width,v+1]);const a=`No; the volume is ${v} cubic units.`;return q('model-argument',difficulty,`A student says a ${p.length} by ${p.width} by ${p.height} box has volume ${p.claim}. Is the claim correct?`,a,[`Yes; the volume is ${p.claim} cubic units.`,`No; the volume is ${v+1} cubic units.`,`No; the volume is ${v+2} cubic units.`,`No; the volume is ${v+3} cubic units.`],p)}
export const GRADE5_MATH_UNIT10_GENERATORS={'choose-operation':generateChooseOperationQuestion,'whole-number-model':generateWholeNumberModelQuestion,'division-model':generateDivisionModelQuestion,'decimal-budget':generateDecimalBudgetQuestion,'fraction-project':generateFractionProjectQuestion,'scale-project':generateScaleProjectQuestion,'volume-plan':generateVolumePlanQuestion,'coordinate-data':generateCoordinateDataQuestion,'model-argument':generateModelArgumentQuestion} satisfies Record<Grade5MathUnit10ItemType,CurriculumGenerator<Grade5MathUnit10Question>>
export function generateGrade5MathUnit10Question<T extends Grade5MathUnit10ItemType>(itemType:T,difficulty:Difficulty):Extract<Grade5MathUnit10Question,{itemType:T}>{return (GRADE5_MATH_UNIT10_GENERATORS[itemType] as CurriculumGenerator<Extract<Grade5MathUnit10Question,{itemType:T}>>)(difficulty)}
