import type { Difficulty } from '../types'
import { ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'
/** Coverage contract: Unit 8, course days 127-144, standards 5.MD.1-5. */
export const GRADE5_MATH_UNIT8_ITEM_TYPES=['measurement-conversion','line-plot-fraction-data','volume-unit-cubes','volume-formula','additive-volume','measurement-design'] as const
export type Grade5MathUnit8ItemType=typeof GRADE5_MATH_UNIT8_ITEM_TYPES[number]
type P={a:bigint;b:bigint;c:bigint;d:bigint;mode:string};type Q<T extends Grade5MathUnit8ItemType>=CurriculumQuestion<T,P>;export type Grade5MathUnit8Question={ [T in Grade5MathUnit8ItemType]:Q<T>}[Grade5MathUnit8ItemType]
type Def={standard:'5.MD.1'|'5.MD.2'|'5.MD.3'|'5.MD.4'|'5.MD.5';lessonFocus:string;workedExample:CurriculumWorkedExample};const ex=(prompt:string,answer:string):CurriculumWorkedExample=>({prompt,answer,steps:['Identify the measurement relationship or dimensions.','Compute exactly and include the correct unit.']})
export const GRADE5_MATH_UNIT8_ITEM_DEFINITIONS={
 'measurement-conversion':{standard:'5.MD.1',lessonFocus:'measurement conversions',workedExample:ex('Convert 3 feet to inches.','36 inches')},'line-plot-fraction-data':{standard:'5.MD.2',lessonFocus:'line plots with fractional data',workedExample:ex('A plot has 3 marks at 1/2. What total length do they show?','1 1/2')},'volume-unit-cubes':{standard:'5.MD.3',lessonFocus:'volume as unit cubes',workedExample:ex('A rectangular prism is 2 by 3 by 4 cubes. How many cubes?','24 cubic units')},'volume-formula':{standard:'5.MD.5',lessonFocus:'volume formulas',workedExample:ex('Find the volume of a 3 by 4 by 5 prism.','60 cubic units')},'additive-volume':{standard:'5.MD.5',lessonFocus:'additive volume',workedExample:ex('Two prisms have volumes 12 and 18 cubic units. What total?','30 cubic units')},'measurement-design':{standard:'5.MD.4',lessonFocus:'real-world measurement design',workedExample:ex('A box is 2 by 3 by 5 inches. What capacity does it have?','30 cubic inches')},
} as const satisfies Record<Grade5MathUnit8ItemType,Def>
const q=(itemType:Grade5MathUnit8ItemType,difficulty:Difficulty,prompt:string,answer:string,parameters:P)=>{const unit=itemType==='measurement-conversion'?'inches':itemType==='line-plot-fraction-data'?'meters':itemType==='measurement-design'?'cubic inches':'cubic units';const pool=[`0 ${unit}`,`1 ${unit}`,`2 ${unit}`,`3 ${unit}`,`4 ${unit}`,`5 ${unit}`].filter(x=>x!==answer);return makeCurriculumQuestion({itemType,difficulty,prompt,correctAnswer:answer,distractors:pool,distractorMode:'distinct',parameters,...GRADE5_MATH_UNIT8_ITEM_DEFINITIONS[itemType]})}
const dims=(d:Difficulty)=>({a:BigInt(ri(2,d+3)),b:BigInt(ri(2,d+4)),c:BigInt(ri(2,d+5))})
export function generateMeasurementConversionQuestion(difficulty:Difficulty){const a=BigInt(ri(2,difficulty+8)),b=12n;return q('measurement-conversion',difficulty,`Convert ${a} feet to inches.`,`${a*b} inches`,{a,b,c:0n,d:0n,mode:'feet-inches'})}
export function generateLinePlotFractionDataQuestion(difficulty:Difficulty){const a=BigInt(ri(2,difficulty+5)),b=BigInt(ri(1,3)),c=2n;const n=a*b;const answer=n%c===0n?`${n/c}`:`${n/c} ${n%c}/${c}`;return q('line-plot-fraction-data',difficulty,`A line plot has ${a} marks at 1/2 meter. What total length do the marks represent?`,`${answer} meters`,{a,b,c,d:0n,mode:'halves'})}
export function generateVolumeUnitCubesQuestion(difficulty:Difficulty){const{a,b,c}=dims(difficulty);return q('volume-unit-cubes',difficulty,`A rectangular prism is ${a} unit cubes long, ${b} wide, and ${c} high. How many unit cubes fill it?`,`${a*b*c} cubic units`,{a,b,c,d:0n,mode:'cubes'})}
export function generateVolumeFormulaQuestion(difficulty:Difficulty){const{a,b,c}=dims(difficulty);return q('volume-formula',difficulty,`Find the volume of a rectangular prism with length ${a}, width ${b}, and height ${c} units.`,`${a*b*c} cubic units`,{a,b,c,d:0n,mode:'formula'})}
export function generateAdditiveVolumeQuestion(difficulty:Difficulty){const{a,b,c}=dims(difficulty);const d=BigInt(ri(2,difficulty+4));const left=a*b*c,right=a*b*d;return q('additive-volume',difficulty,`Two prisms share a base of ${a} by ${b} units and have heights ${c} and ${d} units. What is their combined volume?`,`${left+right} cubic units`,{a,b,c,d,mode:'additive'})}
export function generateMeasurementDesignQuestion(difficulty:Difficulty){const{a,b,c}=dims(difficulty);return q('measurement-design',difficulty,`A storage box is ${a} inches by ${b} inches by ${c} inches. What is its capacity?`,`${a*b*c} cubic inches`,{a,b,c,d:0n,mode:'design'})}
export const GRADE5_MATH_UNIT8_GENERATORS={'measurement-conversion':generateMeasurementConversionQuestion,'line-plot-fraction-data':generateLinePlotFractionDataQuestion,'volume-unit-cubes':generateVolumeUnitCubesQuestion,'volume-formula':generateVolumeFormulaQuestion,'additive-volume':generateAdditiveVolumeQuestion,'measurement-design':generateMeasurementDesignQuestion} satisfies Record<Grade5MathUnit8ItemType,CurriculumGenerator<Grade5MathUnit8Question>>
export function generateGrade5MathUnit8Question<T extends Grade5MathUnit8ItemType>(type:T,difficulty:Difficulty):Extract<Grade5MathUnit8Question,{itemType:T}>{return GRADE5_MATH_UNIT8_GENERATORS[type](difficulty) as Extract<Grade5MathUnit8Question,{itemType:T}>}
