import type { Difficulty } from '../types'
import { amortizedLoanTotalInterestCents, makeFinLitQuestion, money, pick, type CurriculumGenerator, type FinLitQuestion } from './grade8FinLitCore'
export const GRADE8_FINLIT_UNIT5_ITEM_TYPES=['amortized-loan-interest'] as const
export type Grade8FinLitUnit5ItemType=typeof GRADE8_FINLIT_UNIT5_ITEM_TYPES[number]
export interface Grade8FinLitUnit5Parameters { principalCents: bigint; annualRateBps: bigint; monthlyPaymentCents: bigint }
export type Grade8FinLitUnit5Question=FinLitQuestion<'amortized-loan-interest',Grade8FinLitUnit5Parameters>
const definition={standard:'FL.8.L',lessonFocus:'reading an amortized loan schedule',workedExample:{prompt:'A $100.00 loan at 0% is paid with $25.00 each month. What total interest is paid?',answer:'$0.00',steps:['A 0% rate produces $0.00 interest each month.','The payments only reduce principal.']}} as const
export function generateAmortizedLoanInterestQuestion(difficulty:Difficulty):Grade8FinLitUnit5Question {const scenario=pick([{principalCents:1_00000n,annualRateBps:600n,monthlyPaymentCents:17_000n},{principalCents:1_50000n,annualRateBps:800n,monthlyPaymentCents:27_000n},{principalCents:2_00000n,annualRateBps:900n,monthlyPaymentCents:37_000n}] as const);const answer=amortizedLoanTotalInterestCents(scenario.principalCents,scenario.annualRateBps,scenario.monthlyPaymentCents);return makeFinLitQuestion({itemType:'amortized-loan-interest',difficulty,prompt:`A neutral sample loan has principal ${money(scenario.principalCents)}, nominal annual rate ${(Number(scenario.annualRateBps)/100).toFixed(2)}%, and fixed monthly payments of ${money(scenario.monthlyPaymentCents)}. Each month compute interest as balance × annual rate ÷ 12, rounded to the nearest cent with a half-cent rounded up; add it, then apply the payment (the last payment may be smaller). What is the total interest paid?`,correctAnswer:money(answer),distractors:[money(answer+100n),money(answer+500n),money(answer-100n),money(answer+1_000n)],parameters:scenario,definition})}
export const GRADE8_FINLIT_UNIT5_GENERATORS={'amortized-loan-interest':generateAmortizedLoanInterestQuestion} satisfies Record<Grade8FinLitUnit5ItemType,CurriculumGenerator<Grade8FinLitUnit5Question>>
export const generateGrade8FinLitUnit5Question=generateAmortizedLoanInterestQuestion
