import type { Difficulty } from '../types'
import { makeFinLitQuestion, money, ri, type CurriculumGenerator, type FinLitQuestion } from './grade8FinLitCore'
export const GRADE8_FINLIT_UNIT9_ITEM_TYPES=['total-cost-comparison'] as const
export type Grade8FinLitUnit9ItemType=typeof GRADE8_FINLIT_UNIT9_ITEM_TYPES[number]
export interface Grade8FinLitUnit9Parameters { unitACents: bigint; quantityA: bigint; unitBCents: bigint; quantityB: bigint }
export type Grade8FinLitUnit9Question=FinLitQuestion<'total-cost-comparison',Grade8FinLitUnit9Parameters>
const definition={standard:'FL.8.B',lessonFocus:'comparing total costs',workedExample:{prompt:'Option A has three items at $4.00 each. Option B has two items at $5.00 each. Which option has the lower total cost?',answer:'Option B, $10.00',steps:['Find each total: Option A is 3 × $4.00 = $12.00 and Option B is 2 × $5.00 = $10.00.','Compare the totals: $10.00 is lower, so choose Option B.']}} as const
export function generateTotalCostComparisonQuestion(difficulty:Difficulty):Grade8FinLitUnit9Question {let quantityA=BigInt(ri(2,3+difficulty)),quantityB=BigInt(ri(2,3+difficulty)),unitACents=BigInt(ri(250,650+difficulty*150)),unitBCents=BigInt(ri(250,650+difficulty*150));if(quantityA*unitACents===quantityB*unitBCents)unitBCents+=1n;const totalA=quantityA*unitACents,totalB=quantityB*unitBCents,answer=totalA<totalB?`Option A, ${money(totalA)}`:`Option B, ${money(totalB)}`;return makeFinLitQuestion({itemType:'total-cost-comparison',difficulty,prompt:`Option A costs ${money(unitACents)} each for ${quantityA} items. Option B costs ${money(unitBCents)} each for ${quantityB} items. Which option has the lower total cost?`,correctAnswer:answer,distractors:[`Option A, ${money(totalA)}`,`Option B, ${money(totalB)}`,`Option A, ${money(totalB)}`,`Option B, ${money(totalA)}`].filter(x=>x!==answer),parameters:{unitACents,quantityA,unitBCents,quantityB},definition})}
export const GRADE8_FINLIT_UNIT9_GENERATORS={'total-cost-comparison':generateTotalCostComparisonQuestion} satisfies Record<Grade8FinLitUnit9ItemType,CurriculumGenerator<Grade8FinLitUnit9Question>>
export const generateGrade8FinLitUnit9Question=generateTotalCostComparisonQuestion
