import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source: Unit 10, Integrated Algebraic Modeling Capstone (8.EE.7, 8.EE.8, 8.F.4, 8.G.7, 8.SP.3, MP.4). */
export const GRADE8_MATH_UNIT10_ITEM_TYPES=['define-variable','state-model-assumption','select-linear-or-nonlinear-model','solve-model-equation','solve-system-constraint','geometry-measurement-model','interpret-data-trend','identify-model-limitation','choose-mathematical-evidence','communicate-model-conclusion'] as const
export type Grade8MathUnit10ItemType=(typeof GRADE8_MATH_UNIT10_ITEM_TYPES)[number]
type P={a:number;b:number;c:number;x?:number;mode?:'linear'|'nonlinear';trend?:'positive'|'negative'}
type Q<T extends Grade8MathUnit10ItemType>=CurriculumQuestion<T,P>
export type Grade8MathUnit10Question={ [T in Grade8MathUnit10ItemType]:Q<T> }[Grade8MathUnit10ItemType]
const worked=(prompt:string,answer:string):CurriculumWorkedExample=>({prompt,answer,steps:['Define the relevant quantities and assumptions.','Use the selected model consistently.','State a conclusion with its limitation or evidence.']})
const d:Record<Grade8MathUnit10ItemType,{standard:string;lessonFocus:string;workedExample:CurriculumWorkedExample}>={
  'define-variable':{standard:'MP.4',lessonFocus:'defining variables and assumptions',workedExample:worked('A trip cost depends on miles traveled. Define x.','x = miles traveled')},
  'state-model-assumption':{standard:'MP.4',lessonFocus:'defining variables and assumptions',workedExample:worked('A taxi model uses a fixed rate per mile. State an assumption.','The rate per mile stays constant.')},
  'select-linear-or-nonlinear-model':{standard:'8.F.4',lessonFocus:'selecting linear or nonlinear models',workedExample:worked('A quantity increases by 4 each hour. Select a model type.','linear')},
  'solve-model-equation':{standard:'8.EE.7',lessonFocus:'selecting linear or nonlinear models',workedExample:worked('Solve 3x + 4 = 19.','5')},
  'solve-system-constraint':{standard:'8.EE.8',lessonFocus:'systems and constraints',workedExample:worked('Solve y = 2x + 1 and y = x + 5.','(4, 9)')},
  'geometry-measurement-model':{standard:'8.G.7',lessonFocus:'geometry and measurement',workedExample:worked('A right triangle has legs 5 and 12. Find its diagonal.','13')},
  'interpret-data-trend':{standard:'8.SP.3',lessonFocus:'data trends and uncertainty',workedExample:worked('As study time increases, scores tend to increase. Identify the trend.','positive')},
  'identify-model-limitation':{standard:'MP.4',lessonFocus:'data trends and uncertainty',workedExample:worked('A line predicts beyond observed data. State a limitation.','The prediction is an extrapolation and may be less reliable.')},
  'choose-mathematical-evidence':{standard:'MP.4',lessonFocus:'mathematical communication',workedExample:worked('Choose evidence supporting a model.','show calculations and compare predictions to data')},
  'communicate-model-conclusion':{standard:'MP.4',lessonFocus:'mathematical communication',workedExample:worked('Choose a complete model conclusion.','State the result, units, assumption, and limitation.')},
}
function ask<T extends Grade8MathUnit10ItemType>(itemType:T,difficulty:Difficulty,prompt:string,answer:string,distractors:string[],parameters:P):Q<T>{const z=d[itemType];return makeCurriculumQuestion({itemType,difficulty,prompt,correctAnswer:answer,distractors,parameters,standard:z.standard,lessonFocus:z.lessonFocus,workedExample:z.workedExample,distractorMode:'distinct'})}
export function generateDefineVariableQuestion(difficulty:Difficulty):Q<'define-variable'>{return ask('define-variable',difficulty,'A moving company charges by the number of hours worked. Which definition of x best models this situation?','x = number of hours worked',['x = total cost in dollars','x = number of workers','x = company name'],{a:0,b:0,c:0})}
export function generateStateModelAssumptionQuestion(difficulty:Difficulty):Q<'state-model-assumption'>{return ask('state-model-assumption',difficulty,'A service is modeled by C = 12h + 25, where h is hours. Which assumption supports this model?','The hourly charge remains $12 for every hour.',['The flat fee changes each hour.','The number of hours is always zero.','Every service has the same total cost.'],{a:12,b:25,c:0})}
export function generateSelectLinearOrNonlinearModelQuestion(difficulty:Difficulty):Q<'select-linear-or-nonlinear-model'>{const mode=pick(['linear','nonlinear'] as const),prompt=mode==='linear'?'A savings balance increases by $15 each week. Which model type is appropriate?':'The area of a square changes as its side length is squared. Which model type is appropriate?';return ask('select-linear-or-nonlinear-model',difficulty,prompt,mode,[mode==='linear'?'nonlinear':'linear','constant','not a model'],{a:0,b:0,c:0,mode})}
export function generateSolveModelEquationQuestion(difficulty:Difficulty):Q<'solve-model-equation'>{const a=ri(2,difficulty===1?6:12),x=ri(2,12),b=ri(-10,20),c=a*x+b;return ask('solve-model-equation',difficulty,`A model gives ${a}x ${b>=0?'+':'-'} ${Math.abs(b)} = ${c}. What is x?`,String(x),[String(x+1),String(x-1),String(c-b)],{a,b,c,x})}
export function generateSolveSystemConstraintQuestion(difficulty:Difficulty):Q<'solve-system-constraint'>{const x=ri(2,10),a=ri(1,5),b=ri(-5,8),c=ri(6,12),y=a*x+b,d0=y-c;return ask('solve-system-constraint',difficulty,`Two constraints are y = ${a}x ${b>=0?'+':'-'} ${Math.abs(b)} and y = ${c}x ${d0>=0?'+':'-'} ${Math.abs(d0)}. What is their shared solution?`,`(${x}, ${y})`,[`(${x+1}, ${y+1})`,`(${x-1}, ${y+1})`,`(${x+2}, ${y-1})`],{a,b,c,x})}
export function generateGeometryMeasurementModelQuestion(difficulty:Difficulty):Q<'geometry-measurement-model'>{const triples=[[3,4,5],[5,12,13],[8,15,17]] as const,p=pick(triples);return ask('geometry-measurement-model',difficulty,`A rectangular design has side lengths ${p[0]} units and ${p[1]} units. What is its diagonal?`,`${p[2]} units`,[`${p[0]+p[1]} units`,`${p[2]+1} units`,`${p[2]-1} units`],{a:p[0],b:p[1],c:p[2]})}
export function generateInterpretDataTrendQuestion(difficulty:Difficulty):Q<'interpret-data-trend'>{const trend=pick(['positive','negative'] as const),text=trend==='positive'?'hours practiced increase and performance scores generally increase':'hours of screen time increase and hours of sleep generally decrease';return ask('interpret-data-trend',difficulty,`In a data set, ${text}. What association is shown?`,trend,[trend==='positive'?'negative':'positive','no association','causation'],{a:0,b:0,c:0,trend})}
export function generateIdentifyModelLimitationQuestion(difficulty:Difficulty):Q<'identify-model-limitation'>{return ask('identify-model-limitation',difficulty,'A line of fit was made from data for temperatures 40° through 80°. It is used to predict a temperature at 120°. Which limitation is most important?','The prediction is an extrapolation and may be less reliable.',['The line proves causation.','The prediction must be exactly correct.','The data range no longer matters.'],{a:40,b:80,c:120})}
export function generateChooseMathematicalEvidenceQuestion(difficulty:Difficulty):Q<'choose-mathematical-evidence'>{return ask('choose-mathematical-evidence',difficulty,'Which action provides the strongest evidence that a model fits a situation?','show calculations and compare predictions to data',['state an answer without units','choose the first equation written','ignore data that disagree'],{a:0,b:0,c:0})}
export function generateCommunicateModelConclusionQuestion(difficulty:Difficulty):Q<'communicate-model-conclusion'>{return ask('communicate-model-conclusion',difficulty,'Which conclusion communicates a mathematical model responsibly?','State the result, units, assumption, and limitation.',['State only a number.','Claim the model is always correct.','Hide the assumption and data source.'],{a:0,b:0,c:0})}
export const GRADE8_MATH_UNIT10_GENERATORS={'define-variable':generateDefineVariableQuestion,'state-model-assumption':generateStateModelAssumptionQuestion,'select-linear-or-nonlinear-model':generateSelectLinearOrNonlinearModelQuestion,'solve-model-equation':generateSolveModelEquationQuestion,'solve-system-constraint':generateSolveSystemConstraintQuestion,'geometry-measurement-model':generateGeometryMeasurementModelQuestion,'interpret-data-trend':generateInterpretDataTrendQuestion,'identify-model-limitation':generateIdentifyModelLimitationQuestion,'choose-mathematical-evidence':generateChooseMathematicalEvidenceQuestion,'communicate-model-conclusion':generateCommunicateModelConclusionQuestion} satisfies Record<Grade8MathUnit10ItemType,CurriculumGenerator<Grade8MathUnit10Question>>
export function generateGrade8MathUnit10Question<T extends Grade8MathUnit10ItemType>(itemType:T,difficulty:Difficulty):Extract<Grade8MathUnit10Question,{itemType:T}>{return GRADE8_MATH_UNIT10_GENERATORS[itemType](difficulty) as Extract<Grade8MathUnit10Question,{itemType:T}>}
