import type { Difficulty } from '../types'
import { fmtFrac, pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source coverage: Grade 7 Mathematics Unit 10 (days 163-180), 7.SP.5-8. */
export const GRADE7_MATH_UNIT10_ITEM_TYPES = ['probability-scale', 'simple-event-probability', 'experimental-probability', 'predict-from-rate', 'uniform-probability-model', 'compound-event-probability'] as const
export type Grade7MathUnit10ItemType = typeof GRADE7_MATH_UNIT10_ITEM_TYPES[number]
type Params = { favorable?: number; sampleSize?: number; multiplier?: number }
type Q<T extends Grade7MathUnit10ItemType> = CurriculumQuestion<T, Params>
export type Grade7MathUnit10Question = { [T in Grade7MathUnit10ItemType]: Q<T> }[Grade7MathUnit10ItemType]
type Def = { standard: '7.SP.5' | '7.SP.6' | '7.SP.7' | '7.SP.8'; lessonFocus: string; workedExample: CurriculumWorkedExample }
const example = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Identify the favorable outcomes and the total possible outcomes.', 'Write the probability as a reduced fraction, or use it to predict a count.'] })
export const GRADE7_MATH_UNIT10_ITEM_DEFINITIONS = {
  'probability-scale': { standard: '7.SP.5', lessonFocus: 'probability and likelihood', workedExample: example('A probability of 1 means an event is...', 'certain') },
  'simple-event-probability': { standard: '7.SP.5', lessonFocus: 'probability of simple events', workedExample: example('A bag has 2 red and 3 blue marbles. What is P(red)?', '2/5') },
  'experimental-probability': { standard: '7.SP.6', lessonFocus: 'experimental probability', workedExample: example('A coin was flipped 20 times and landed heads 9 times. What is the experimental probability of heads?', '9/20') },
  'predict-from-rate': { standard: '7.SP.6', lessonFocus: 'predicting outcomes from a rate', workedExample: example('A player made 6 of 10 free throws. About how many would you expect to make out of 30 attempts?', '18') },
  'uniform-probability-model': { standard: '7.SP.7', lessonFocus: 'uniform probability models', workedExample: example('A fair 4-section spinner is spun 40 times. About how many times would you expect a particular section to come up?', '10') },
  'compound-event-probability': { standard: '7.SP.8', lessonFocus: 'probability of compound events', workedExample: example('Two fair coins are flipped. What is the probability both land heads?', '1/4') },
} as const satisfies Record<Grade7MathUnit10ItemType, Def>
const q = (itemType: Grade7MathUnit10ItemType, difficulty: Difficulty, prompt: string, answer: string, parameters: Params, distractors: string[]) => makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, distractorMode: 'distinct', parameters, ...GRADE7_MATH_UNIT10_ITEM_DEFINITIONS[itemType] })
const LIKELIHOOD_SCALE = [
  { value: '0', label: 'impossible' },
  { value: '1/10', label: 'unlikely' },
  { value: '1/2', label: 'equally likely to happen or not happen' },
  { value: '9/10', label: 'likely' },
  { value: '1', label: 'certain' },
] as const
const DICE_SUMS = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const
const DICE_SUM_WAYS: Record<number, number> = { 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 5, 9: 4, 10: 3, 11: 2, 12: 1 }
export function generateProbabilityScaleQuestion(difficulty: Difficulty) { const item = pick(LIKELIHOOD_SCALE); const others = LIKELIHOOD_SCALE.filter((x) => x.label !== item.label).map((x) => x.label); return q('probability-scale', difficulty, `An event has a probability of ${item.value}. How would you describe how likely the event is to happen?`, item.label, {}, others) }
export function generateSimpleEventProbabilityQuestion(difficulty: Difficulty) { const red = ri(2, difficulty * 2 + 3); const blue = red + ri(1, 3); const green = red + ri(4, difficulty + 6); const total = red + blue + green; const answer = fmtFrac(red, total); return q('simple-event-probability', difficulty, `A bag has ${red} red, ${blue} blue, and ${green} green marbles. If one marble is drawn at random, what is P(red)?`, answer, { favorable: red, sampleSize: total }, [fmtFrac(blue, total), fmtFrac(green, total), fmtFrac(blue + green, total), fmtFrac(total - 1, total)]) }
export function generateExperimentalProbabilityQuestion(difficulty: Difficulty) { const outcomes = ri(2, difficulty + 3) * 10; const success = ri(2, Math.floor(outcomes / 2)); const answer = fmtFrac(success, outcomes); return q('experimental-probability', difficulty, `A spinner was spun ${outcomes} times and landed on blue ${success} times. Based on this experiment, what is the experimental probability of landing on blue?`, answer, { favorable: success, sampleSize: outcomes }, [fmtFrac(success - 1, outcomes), fmtFrac(success + 1, outcomes), fmtFrac(success + 2, outcomes), fmtFrac(Math.max(0, success - 2), outcomes)]) }
export function generatePredictFromRateQuestion(difficulty: Difficulty) { const attempts = ri(3, difficulty + 5) * 5; const made = ri(2, attempts - 2); const multiplier = ri(2, difficulty + 3); const future = attempts * multiplier; const answer = made * multiplier; return q('predict-from-rate', difficulty, `A basketball player made ${made} of ${attempts} free throws in practice. Based on this rate, about how many would you expect to make out of ${future} attempts?`, String(answer), { favorable: made, sampleSize: attempts, multiplier }, [String(made), String(future - answer), String(answer + multiplier), String(answer - multiplier)]) }
export function generateUniformProbabilityModelQuestion(difficulty: Difficulty) { const sections = pick([4, 5, 6, 8, 10] as const); const spins = sections * ri(5, difficulty * 10 + 15); const answer = spins / sections; const belowSections = answer - sections > 0 ? answer - sections : answer + sections + 1; return q('uniform-probability-model', difficulty, `A fair spinner is divided into ${sections} equal sections numbered 1 to ${sections}. If you spin it ${spins} times, about how many times would you expect to land on a particular number, using the uniform probability model?`, String(answer), { multiplier: sections, sampleSize: spins }, [String(answer + sections), String(belowSections), String(spins), String(Math.max(1, Math.round(spins / (sections + 1))))]) }
export function generateCompoundEventProbabilityQuestion(difficulty: Difficulty) { const target = pick(DICE_SUMS); const ways = DICE_SUM_WAYS[target]; const answer = fmtFrac(ways, 36); const candidates = DICE_SUMS.filter((s) => s !== target).map((s) => fmtFrac(DICE_SUM_WAYS[s], 36)); const distractors = [...new Set(candidates)].filter((c) => c !== answer); return q('compound-event-probability', difficulty, `Two fair six-sided dice are rolled. What is the probability that the sum is ${target}?`, answer, { multiplier: target, favorable: ways }, distractors) }
export const GRADE7_MATH_UNIT10_GENERATORS = { 'probability-scale': generateProbabilityScaleQuestion, 'simple-event-probability': generateSimpleEventProbabilityQuestion, 'experimental-probability': generateExperimentalProbabilityQuestion, 'predict-from-rate': generatePredictFromRateQuestion, 'uniform-probability-model': generateUniformProbabilityModelQuestion, 'compound-event-probability': generateCompoundEventProbabilityQuestion } satisfies Record<Grade7MathUnit10ItemType, CurriculumGenerator<Grade7MathUnit10Question>>
export function generateGrade7MathUnit10Question<T extends Grade7MathUnit10ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade7MathUnit10Question, { itemType: T }> { return GRADE7_MATH_UNIT10_GENERATORS[itemType](difficulty) as Extract<Grade7MathUnit10Question, { itemType: T }> }
