import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Unit 10: volume and bivariate data (8.G.9, 8.SP.1–4). */
export const GRADE8_MATH_UNIT10_ITEM_TYPES = ['cylinder-volume', 'cone-volume', 'sphere-volume', 'compare-solid-volumes', 'identify-scatter-association', 'line-of-fit-prediction', 'interpolation-or-extrapolation', 'two-way-table-relative-frequency', 'interpret-relative-frequency', 'association-in-context'] as const
export type Grade8MathUnit10ItemType = (typeof GRADE8_MATH_UNIT10_ITEM_TYPES)[number]
type P = { r: number; h: number; x?: number; y?: number; slope?: number; intercept?: number; askedX?: number; numerator?: number; denominator?: number; association?: 'positive' | 'negative' | 'none' }
type Q<T extends Grade8MathUnit10ItemType> = CurriculumQuestion<T, P>
export type Grade8MathUnit10Question = { [T in Grade8MathUnit10ItemType]: Q<T> }[Grade8MathUnit10ItemType]
const ex = (prompt: string, answer: string, steps: readonly string[]): CurriculumWorkedExample => ({ prompt, answer, steps })
const defs: Record<Grade8MathUnit10ItemType, { standard: string; lessonFocus: string; workedExample: CurriculumWorkedExample }> = {
  'cylinder-volume': { standard: '8.G.9', lessonFocus: 'volume of cylinders', workedExample: ex('Find the volume of a cylinder with radius 3 and height 5.', '45π cubic units', ['Use V = πr²h.', 'V = π(3²)(5).', 'V = 45π cubic units.']) },
  'cone-volume': { standard: '8.G.9', lessonFocus: 'volume of cones', workedExample: ex('Find the volume of a cone with radius 3 and height 12.', '36π cubic units', ['Use V = (1/3)πr²h.', 'V = (1/3)π(9)(12).', 'V = 36π cubic units.']) },
  'sphere-volume': { standard: '8.G.9', lessonFocus: 'volume of spheres', workedExample: ex('Find the volume of a sphere with radius 3.', '36π cubic units', ['Use V = (4/3)πr³.', 'V = (4/3)π(27).', 'V = 36π cubic units.']) },
  'compare-solid-volumes': { standard: '8.G.9', lessonFocus: 'comparing volumes', workedExample: ex('A cylinder and cone have the same radius and height. Which has greater volume?', 'the cylinder', ['A cylinder has volume πr²h.', 'A cone has one-third that volume.', 'The cylinder has greater volume.']) },
  'identify-scatter-association': { standard: '8.SP.1', lessonFocus: 'scatter plots', workedExample: ex('As practice time increases, scores generally increase. Identify the association.', 'positive', ['Both variables tend to increase together.', 'That pattern is positive association.']) },
  'line-of-fit-prediction': { standard: '8.SP.2', lessonFocus: 'lines of fit', workedExample: ex('A line of fit is y = 3x + 2. Predict y when x = 4.', '14', ['Substitute x = 4.', 'y = 3(4) + 2 = 14.']) },
  'interpolation-or-extrapolation': { standard: '8.SP.2', lessonFocus: 'interpolation and extrapolation', workedExample: ex('Data use x-values from 2 through 10. Predicting at x = 6 is what kind of prediction?', 'interpolation', ['6 is within the observed range.', 'A prediction within the range is interpolation.']) },
  'two-way-table-relative-frequency': { standard: '8.SP.4', lessonFocus: 'relative frequency', workedExample: ex('18 of 30 students prefer reading. What is the relative frequency?', '3/5', ['Relative frequency is favorable divided by total.', '18/30 reduces to 3/5.']) },
  'interpret-relative-frequency': { standard: '8.SP.4', lessonFocus: 'relative-frequency interpretation', workedExample: ex('The relative frequency is 0.70. What does it mean?', '70% of the group', ['0.70 = 70/100.', 'So 70% of the group has the stated characteristic.']) },
  'association-in-context': { standard: '8.SP.3', lessonFocus: 'association in data', workedExample: ex('As absences increase, grades tend to decrease. Identify the association.', 'negative', ['One variable tends to decrease as the other increases.', 'That is negative association.']) },
}
function question<T extends Grade8MathUnit10ItemType>(itemType: T, difficulty: Difficulty, prompt: string, answer: string, distractors: string[], parameters: P): Q<T> { const d = defs[itemType]; return makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, parameters, standard: d.standard, lessonFocus: d.lessonFocus, workedExample: d.workedExample, distractorMode: 'distinct' }) }
function dimensions(difficulty: Difficulty): Pick<P, 'r' | 'h'> { const r = pick(difficulty === 1 ? [2, 3, 4] as const : [2, 3, 4, 5, 6] as const); return { r, h: ri(3, difficulty === 1 ? 8 : 15) * 3 } }
const piVolume = (n: number) => `${n}π cubic units`
export function generateCylinderVolumeQuestion(difficulty: Difficulty): Q<'cylinder-volume'> { const p = dimensions(difficulty), n = p.r * p.r * p.h; return question('cylinder-volume', difficulty, `Find the volume of a cylinder with radius ${p.r} units and height ${p.h} units. Express your answer in terms of π.`, piVolume(n), [piVolume(n / 3), piVolume(n + p.r), piVolume(n * 2)], p) }
export function generateConeVolumeQuestion(difficulty: Difficulty): Q<'cone-volume'> { const p = dimensions(difficulty), n = p.r * p.r * p.h / 3; return question('cone-volume', difficulty, `Find the volume of a cone with radius ${p.r} units and height ${p.h} units. Express your answer in terms of π.`, piVolume(n), [piVolume(n * 3), piVolume(n + p.r), piVolume(n / 2)], p) }
export function generateSphereVolumeQuestion(difficulty: Difficulty): Q<'sphere-volume'> { const r = pick([3, 6, 9] as const), n = 4 * r * r * r / 3; return question('sphere-volume', difficulty, `Find the volume of a sphere with radius ${r} units. Express your answer in terms of π.`, piVolume(n), [piVolume(n / 4), piVolume(n * 3 / 4), piVolume(n * 3)], { r, h: 0 }) }
export function generateCompareSolidVolumesQuestion(difficulty: Difficulty): Q<'compare-solid-volumes'> { const p = dimensions(difficulty); return question('compare-solid-volumes', difficulty, `A cylinder and a cone each have radius ${p.r} units and height ${p.h} units. Which solid has the greater volume?`, 'the cylinder', ['the cone', 'they have equal volume', 'not enough information'], p) }
function association(): 'positive' | 'negative' | 'none' { return pick(['positive', 'negative', 'none'] as const) }
export function generateIdentifyScatterAssociationQuestion(difficulty: Difficulty): Q<'identify-scatter-association'> { const a = association(); const text = a === 'positive' ? 'As x increases, y generally increases.' : a === 'negative' ? 'As x increases, y generally decreases.' : 'As x increases, y shows no consistent change.'; return question('identify-scatter-association', difficulty, `${text} What type of association does this describe?`, a, [...['positive', 'negative', 'none'].filter(x => x !== a), 'causation'], { r: 0, h: 0, association: a }) }
export function generateLineOfFitPredictionQuestion(difficulty: Difficulty): Q<'line-of-fit-prediction'> { const slope = ri(1, difficulty === 1 ? 5 : 9), intercept = ri(-5, 10), askedX = ri(2, 10), y = slope * askedX + intercept; return question('line-of-fit-prediction', difficulty, `A line of fit is y = ${slope}x ${intercept >= 0 ? '+' : '-'} ${Math.abs(intercept)}. Predict y when x = ${askedX}.`, String(y), [String(y + slope + 1), String(y - slope - 1), String(y + 2 * slope + 1)], { r: 0, h: 0, slope, intercept, askedX, y }) }
export function generateInterpolationOrExtrapolationQuestion(difficulty: Difficulty): Q<'interpolation-or-extrapolation'> { const low = ri(1, 4), high = low + ri(6, 12), inside = ri(0, 1) === 1, askedX = inside ? ri(low + 1, high - 1) : high + ri(2, 8), answer = inside ? 'interpolation' : 'extrapolation'; return question('interpolation-or-extrapolation', difficulty, `A data set has x-values from ${low} through ${high}. A prediction is made at x = ${askedX}. Is this interpolation or extrapolation?`, answer, [answer === 'interpolation' ? 'extrapolation' : 'interpolation', 'causation', 'a census'], { r: low, h: high, askedX }) }
export function generateTwoWayTableRelativeFrequencyQuestion(difficulty: Difficulty): Q<'two-way-table-relative-frequency'> { const denominator = pick([20, 25, 30, 40, 50] as const), numerator = pick([1, 2, 3, 4] as const) * denominator / 5; const n = numerator / (denominator / 5), answer = `${n}/5`; return question('two-way-table-relative-frequency', difficulty, `In a survey, ${numerator} of ${denominator} students chose option A. What is the relative frequency for option A?`, answer, [`${5 - n}/5`, `${numerator}/${denominator}`, `${n + 2}/5`], { r: 0, h: 0, numerator, denominator }) }
export function generateInterpretRelativeFrequencyQuestion(difficulty: Difficulty): Q<'interpret-relative-frequency'> { const numerator = pick([1, 2, 3, 4] as const), denominator = 5, percent = numerator * 20; return question('interpret-relative-frequency', difficulty, `A category has relative frequency ${numerator}/${denominator}. What does this mean?`, `${percent}% of the group is in the category.`, [`${100 - percent}% of the group is in the category.`, `${numerator} students are in the category.`, 'The category causes the outcome.'], { r: 0, h: 0, numerator, denominator }) }
export function generateAssociationInContextQuestion(difficulty: Difficulty): Q<'association-in-context'> { const a = pick(['positive', 'negative'] as const), text = a === 'positive' ? 'hours studied increase and quiz scores tend to increase' : 'hours of screen time increase and hours of sleep tend to decrease'; return question('association-in-context', difficulty, `In a data set, ${text}. What type of association is shown?`, a, [a === 'positive' ? 'negative' : 'positive', 'none', 'causation'], { r: 0, h: 0, association: a }) }
export const GRADE8_MATH_UNIT10_GENERATORS = { 'cylinder-volume': generateCylinderVolumeQuestion, 'cone-volume': generateConeVolumeQuestion, 'sphere-volume': generateSphereVolumeQuestion, 'compare-solid-volumes': generateCompareSolidVolumesQuestion, 'identify-scatter-association': generateIdentifyScatterAssociationQuestion, 'line-of-fit-prediction': generateLineOfFitPredictionQuestion, 'interpolation-or-extrapolation': generateInterpolationOrExtrapolationQuestion, 'two-way-table-relative-frequency': generateTwoWayTableRelativeFrequencyQuestion, 'interpret-relative-frequency': generateInterpretRelativeFrequencyQuestion, 'association-in-context': generateAssociationInContextQuestion } satisfies Record<Grade8MathUnit10ItemType, CurriculumGenerator<Grade8MathUnit10Question>>
export function generateGrade8MathUnit10Question<T extends Grade8MathUnit10ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade8MathUnit10Question, { itemType: T }> { return GRADE8_MATH_UNIT10_GENERATORS[itemType](difficulty) as Extract<Grade8MathUnit10Question, { itemType: T }> }
