import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { compoundCents, cents, example, finLitQuestion, money, pct, type FinLitDefinition, type FinLitQuestion } from './grade7FinLitCore'
import type { CurriculumGenerator } from './generatorCore'

/** Derived only from source lessons U5 l01-l06. Compound growth is exact rational cents, never floating point. */
export const GRADE7_FINLIT_UNIT5_ITEM_TYPES = ['saving-versus-investing','risk-return-time','diversification','compound-growth','insurance-purpose','identity-protection'] as const
export type Grade7FinLitUnit5ItemType = typeof GRADE7_FINLIT_UNIT5_ITEM_TYPES[number]
type P = { principalCents: bigint; annualBasisPoints: bigint; years: bigint; compoundsPerYear: bigint }
export type Grade7FinLitUnit5Question = FinLitQuestion<Grade7FinLitUnit5ItemType, P>
const defs = {
  'saving-versus-investing': { standard: 'PF5 foundations', lessonFocus: 'saving versus investing', workedExample: example('Money needed next month is best kept accessible.', 'saving', ['Time horizon affects the choice.']) },
  'risk-return-time': { standard: 'PF5 foundations', lessonFocus: 'risk return and time horizon', workedExample: example('A near-term goal needs accessible money.', 'short time horizon', ['A goal date changes risk choices.']) },
  diversification: { standard: 'PF5 foundations', lessonFocus: 'diversification concept', workedExample: example('Using more than one investment type can spread risk.', 'diversification', ['Spreading does not guarantee outcomes.']) },
  'compound-growth': { standard: 'PF5 foundations', lessonFocus: 'compound growth', workedExample: example('Grow $100.00 at 10% for 1 year.', '$110.00', ['Apply the rate to the balance.']) },
  'insurance-purpose': { standard: 'PF6 foundations', lessonFocus: 'insurance purpose', workedExample: example('Insurance can help with covered unexpected losses.', 'protection from risk', ['Coverage has terms and limits.']) },
  'identity-protection': { standard: 'PF6 foundations', lessonFocus: 'identity theft protection', workedExample: example('Keep account passwords private.', 'protect identity', ['Use trusted channels.']) },
} as const satisfies Record<Grade7FinLitUnit5ItemType, FinLitDefinition>
export function generateGrade7FinLitUnit5Question(type: Grade7FinLitUnit5ItemType, difficulty: Difficulty): Grade7FinLitUnit5Question {
  const principalCents = cents(100, 900 + difficulty * 300); const annualBasisPoints = pick([500n, 1000n, 2500n] as const); const years = BigInt(ri(1, 2 + difficulty)); const compoundsPerYear = pick([1n, 4n] as const); const grown = compoundCents(principalCents, annualBasisPoints, years, compoundsPerYear); let prompt: string; let answer: string; let distractors: string[]
  if (type === 'saving-versus-investing') { const purchase = pick(['a school trip','a replacement laptop','a bicycle repair','a music lesson'] as const); prompt = `A fictional learner needs ${money(principalCents)} for ${purchase} next month. Which choice best fits this short-term goal?`; answer = 'saving in an accessible account'; distractors = ['a long-term investment chosen only for high return','sharing the money with a stranger','ignoring the goal date','borrowing without a plan'] }
  else if (type === 'risk-return-time') { const goal = pick(['a training course','a future vehicle','a school trip','a home repair'] as const); prompt = `A fictional ${goal} goal of ${money(principalCents)} is needed in ${years} year(s). Which factor should guide how much risk is appropriate?`; answer = 'the time horizon'; distractors = ['an advertisement alone','a password','a receipt','the color of a card'] }
  else if (type === 'diversification') { const asset = pick(['one company','one industry fund','one local business','one online venture'] as const); prompt = `A fictional investor has ${money(principalCents)} and considers putting all of it into ${asset}. What approach can spread risk?`; answer = 'diversification'; distractors = ['guaranteeing a return','hiding the investment','borrowing more automatically','sharing credentials'] }
  else if (type === 'compound-growth') { const periodName = compoundsPerYear === 1n ? 'once per year' : 'four times per year'; prompt = `A fictional account starts with ${money(principalCents)} at ${pct(Number(annualBasisPoints))} annual interest, compounded ${periodName}, for ${years} year(s). Compute with exact rational cents and round to the nearest cent only at the end (do not round each period). What is the ending balance?`; answer = money(grown); distractors = [money(principalCents), money(grown + 100n), money(grown - 100n), money(principalCents + principalCents * annualBasisPoints * years / 10_000n)] }
  else if (type === 'insurance-purpose') { const loss = pick(['storm damage','a vehicle accident','a stolen bicycle','a medical emergency'] as const); prompt = `A fictional family considers coverage for ${loss} with a possible loss of ${money(principalCents)}. What is insurance mainly intended to provide?`; answer = 'protection from covered financial risk'; distractors = ['a guaranteed profit','a savings account','a credit score','an advertisement'] }
  else { const request = pick(['asks for an account number','asks for a password to “unlock” the account','requests a verification code','demands payment by gift card'] as const); prompt = `A message about ${money(principalCents)} ${request}. What is the safest action?`; answer = 'do not share personal account information'; distractors = ['reply with private information','post it publicly','send a password too','trust every urgent message'] }
  return finLitQuestion(type, difficulty, defs[type], prompt, answer, { principalCents, annualBasisPoints, years, compoundsPerYear }, distractors)
}
export const GRADE7_FINLIT_UNIT5_GENERATORS = Object.fromEntries(GRADE7_FINLIT_UNIT5_ITEM_TYPES.map(type => [type, (d: Difficulty) => generateGrade7FinLitUnit5Question(type, d)])) as Record<Grade7FinLitUnit5ItemType, CurriculumGenerator<Grade7FinLitUnit5Question>>
