import { afterEach, describe, expect, it } from 'vitest'
import { setRng } from '../genUtils'
import { curriculumAnswer } from './generatorCore'
import { GRADE5_MATH_UNIT9_GENERATORS, GRADE5_MATH_UNIT9_ITEM_DEFINITIONS, GRADE5_MATH_UNIT9_ITEM_TYPES, generateGrade5MathUnit9Question, type Grade5MathUnit9Question } from './grade5MathUnit9Generator'
afterEach(()=>setRng(null));const N=200;const seeded=(seed:number)=>{let s=seed>>>0;return()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)/0x100000000)}
function oracle(q:Grade5MathUnit9Question):string{const p=q.prompt;switch(q.itemType){case'identify-coordinate-axes':return p.includes('horizontal')?'x-axis':'y-axis';case'read-ordered-pair':case'graph-context-point':{const m=/x(?:-coordinate| = )\s*(\d+) and y(?:-coordinate| = )\s*(\d+)/.exec(p);if(!m)throw Error(p);return `(${m[1]}, ${m[2]})`}case'classify-shape-properties':if(p.includes('four equal sides'))return'rhombus';if(p.includes('3 sides'))return'triangle';return p.includes('4 right angles')?'rectangle':'parallelogram';case'shape-hierarchy':return /hierarchy \w+ .+? (\w+) .+? quadrilateral/.exec(p)?.[1]??'';case'geometric-vocabulary':return p.startsWith('Lines that meet')?'perpendicular':p.startsWith('Lines in a plane')?'parallel':'vertex';case'coordinate-route':{const m=/\((\d+), (\d+)\).*right (\d+) and up (\d+)/.exec(p);if(!m)throw Error(p);return `(${+m[1]+ +m[3]}, ${+m[2]+ +m[4]})`}}}
function well(q:Grade5MathUnit9Question){expect(curriculumAnswer(q)).toBe(oracle(q));expect(new Set(q.choices).size).toBe(4);for(const c of q.choices){expect(c.trim()).not.toBe('');expect(c).not.toMatch(/-\d/)}}
function validMostSpecific(prompt:string):Set<string>{if(prompt.includes('3 sides'))return new Set(['triangle']);if(prompt.includes('four equal sides')&&prompt.includes('0 right angles'))return new Set(['rhombus']);if(prompt.includes('4 right angles')&&prompt.includes('adjacent sides are unequal'))return new Set(['rectangle']);if(prompt.includes('0 right angles')&&prompt.includes('adjacent sides are unequal'))return new Set(['parallelogram']);throw Error(prompt)}
describe('Grade 5 Math Unit 9 coverage contract',()=>{it('has every source-derived type, definition, and generator',()=>{expect(Object.keys(GRADE5_MATH_UNIT9_GENERATORS)).toEqual([...GRADE5_MATH_UNIT9_ITEM_TYPES]);expect(Object.keys(GRADE5_MATH_UNIT9_ITEM_DEFINITIONS)).toEqual([...GRADE5_MATH_UNIT9_ITEM_TYPES]);expect(new Set(Object.values(GRADE5_MATH_UNIT9_ITEM_DEFINITIONS).map(x=>x.standard))).toEqual(new Set(['5.G.1','5.G.2','5.G.3','5.G.4']))});it('reaches every type at every difficulty',()=>{for(const t of GRADE5_MATH_UNIT9_ITEM_TYPES)for(const d of [1,2,3] as const)expect(generateGrade5MathUnit9Question(t,d).difficulty).toBe(d)})})
describe('Grade 5 Math Unit 9 independent prompt oracles',()=>{for(const[i,t]of GRADE5_MATH_UNIT9_ITEM_TYPES.entries())it(`${t}: 600 independently parsed items`,()=>{setRng(seeded(0x9000+i));for(const d of[1,2,3]as const)for(let n=0;n<N;n++)well(generateGrade5MathUnit9Question(t,d))})})
describe('Grade 5 Math Unit 9 semantic choice validation',()=>{it('has no classification distractor valid as the stated most-specific classification',()=>{setRng(seeded(0xc1a55));for(const d of[1,2,3]as const)for(let n=0;n<300;n++){const q=generateGrade5MathUnit9Question('classify-shape-properties',d);const valid=validMostSpecific(q.prompt);expect(valid).toEqual(new Set([curriculumAnswer(q)]));for(const choice of q.choices)if(choice!==curriculumAnswer(q))expect(valid.has(choice)).toBe(false)}});it('uses an explicit hierarchy step with no distractor naming that next category',()=>{setRng(seeded(0x481));for(const d of[1,2,3]as const)for(let n=0;n<300;n++){const q=generateGrade5MathUnit9Question('shape-hierarchy',d);const next=/hierarchy \w+ .+? (\w+) .+? quadrilateral/.exec(q.prompt)?.[1];expect(curriculumAnswer(q)).toBe(next);for(const choice of q.choices)if(choice!==next)expect(choice).not.toBe(next)}})})
