import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { cents, example, finLitQuestion, money, type FinLitDefinition, type FinLitQuestion } from './grade7FinLitCore'
import type { CurriculumGenerator } from './generatorCore'

/** Derived only from source lessons U1 l01-l06: income, skills, gross pay, benefits, entrepreneurship, rights. */
export const GRADE7_FINLIT_UNIT1_ITEM_TYPES = ['income-sources','training-and-skills','gross-pay-and-deductions','benefits','entrepreneurship','workplace-rights'] as const
export type Grade7FinLitUnit1ItemType = typeof GRADE7_FINLIT_UNIT1_ITEM_TYPES[number]
type P = { payCents: bigint; deductionCents: bigint; weeks: number }
export type Grade7FinLitUnit1Question = FinLitQuestion<Grade7FinLitUnit1ItemType, P>
const defs = {
  'income-sources': { standard: 'PF1 foundations', lessonFocus: 'income sources', workedExample: example('A person earns money by tutoring. Is this income?', 'yes', ['Money earned for work is income.']) },
  'training-and-skills': { standard: 'PF1 foundations', lessonFocus: 'education training and skills', workedExample: example('Which step builds a job skill?', 'practice a relevant skill', ['Training can build skills for work.']) },
  'gross-pay-and-deductions': { standard: 'PF1 foundations', lessonFocus: 'gross pay and deductions concepts', workedExample: example('Gross pay is $50 and deductions are $8. Net pay?', '$42.00', ['Subtract deductions from gross pay.']) },
  benefits: { standard: 'PF1 foundations', lessonFocus: 'benefits', workedExample: example('Health coverage offered with a job is a benefit.', 'benefit', ['Benefits are compensation beyond wages.']) },
  entrepreneurship: { standard: 'PF1 foundations', lessonFocus: 'entrepreneurship', workedExample: example('A person starts a lawn-care service.', 'entrepreneurship', ['Starting and running a business is entrepreneurship.']) },
  'workplace-rights': { standard: 'PF1 foundations', lessonFocus: 'workplace rights and responsibilities foundations', workedExample: example('Following safety rules is a workplace responsibility.', 'responsibility', ['Rights and responsibilities are different.']) },
} as const satisfies Record<Grade7FinLitUnit1ItemType, FinLitDefinition>
export function generateGrade7FinLitUnit1Question(type: Grade7FinLitUnit1ItemType, difficulty: Difficulty): Grade7FinLitUnit1Question {
  const payCents = cents(40, 300 + difficulty * 100); const deductionCents = cents(1, 39); const weeks = ri(2, 8 + difficulty); let prompt: string; let answer: string; let distractors: string[]
  if (type === 'income-sources') { const scenario = pick([{ text: `earns ${money(payCents)} by walking dogs for neighbors`, answer: 'yes' }, { text: `earns ${money(payCents)} by selling original art at a school fair`, answer: 'yes' }, { text: `receives ${money(payCents)} as a birthday gift`, answer: 'no' }, { text: `receives a ${money(payCents)} reimbursement for a purchase already made`, answer: 'no' }] as const); prompt = `A fictional student ${scenario.text}. Is this an income source?`; answer = scenario.answer; distractors = answer === 'yes' ? ['no','only if it is saved','only if it is cash','cannot tell'] : ['yes','only if it is saved','only if it is cash','cannot tell'] }
  else if (type === 'training-and-skills') { const skill = pick(['typing accurately','repairing bicycles','organizing inventory'] as const); prompt = `After earning ${money(payCents)} through paid practice work over ${weeks} weeks, which action best builds the work skill of ${skill}?`; answer = `practice ${skill}`; distractors = ['ignore feedback','skip all instruction','claim the skill without evidence','avoid using the skill'] }
  else if (type === 'gross-pay-and-deductions') { prompt = `A fictional worker's gross pay is ${money(payCents)}. Listed deductions total ${money(deductionCents)}. What is the net pay?`; answer = money(payCents - deductionCents); distractors = [money(payCents + deductionCents), money(deductionCents), money(payCents - deductionCents - 100n), money(payCents - deductionCents + 100n)] }
  else if (type === 'benefits') { const benefit = pick(['paid sick time','health coverage','retirement match','paid family leave'] as const); prompt = `A job pays ${money(payCents)} per week and also provides ${benefit}. This is best described as what?`; answer = 'a benefit'; distractors = ['a deduction','gross pay','a tax','a loan'] }
  else if (type === 'entrepreneurship') { const scenario = pick([{ text: `plans to offer lawn care for ${money(payCents)} per customer for ${weeks} weeks`, answer: 'entrepreneurship' }, { text: `starts a pet-sitting service for ${money(payCents)} per customer`, answer: 'entrepreneurship' }, { text: `works scheduled shifts for ${money(payCents)} per week at someone else’s store`, answer: 'not entrepreneurship' }, { text: `is hired for ${weeks} weeks at a fixed wage by an existing business`, answer: 'not entrepreneurship' }] as const); prompt = `A fictional student ${scenario.text}. This is what?`; answer = scenario.answer; distractors = answer === 'entrepreneurship' ? ['not entrepreneurship','a payroll deduction','a workplace benefit','a tax'] : ['entrepreneurship','a payroll deduction','a workplace benefit','a tax'] }
  else { const scenario = pick([{ text: 'uses safety equipment when required', answer: 'responsibility' }, { text: 'records work hours accurately', answer: 'responsibility' }, { text: 'is paid for every hour worked', answer: 'right' }, { text: 'works in a safe workplace', answer: 'right' }] as const); prompt = `At a fictional workplace paying ${money(payCents)} per week, a worker ${scenario.text}. This is a workplace what?`; answer = scenario.answer; distractors = answer === 'right' ? ['responsibility','benefit','deduction','subscription'] : ['right','benefit','deduction','subscription'] }
  return finLitQuestion(type, difficulty, defs[type], prompt, answer, { payCents, deductionCents, weeks }, distractors)
}
export const GRADE7_FINLIT_UNIT1_GENERATORS = Object.fromEntries(GRADE7_FINLIT_UNIT1_ITEM_TYPES.map(type => [type, (d: Difficulty) => generateGrade7FinLitUnit1Question(type, d)])) as Record<Grade7FinLitUnit1ItemType, CurriculumGenerator<Grade7FinLitUnit1Question>>
