import type { Difficulty } from '../types'
import { ri, pick } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'
/** Grade 7 U3, days 37-54 (7.EE.1-2). Expressions use signed integer coefficients/constants; derived values are integer arithmetic only. */
export const GRADE7_MATH_UNIT3_ITEM_TYPES=['distribute','combine-like-terms','factor-expression','equivalent-form','interpret-expression','context-expression'] as const
export type Grade7MathUnit3ItemType=typeof GRADE7_MATH_UNIT3_ITEM_TYPES[number];type P={a:number;b:number;c:number;d:number;kind:Grade7MathUnit3ItemType};export type Grade7MathUnit3Question=CurriculumQuestion<Grade7MathUnit3ItemType,P>
const ex:CurriculumWorkedExample={prompt:'Expand -3(x - 4).',answer:'-3x + 12',steps:['Multiply -3 by both terms.','-3x + 12 is equivalent.']};const defs:Record<Grade7MathUnit3ItemType,{standard:'7.EE.1'|'7.EE.2';lessonFocus:string;workedExample:CurriculumWorkedExample}>={distribute:{standard:'7.EE.1',lessonFocus:'distributive property',workedExample:ex},'combine-like-terms':{standard:'7.EE.1',lessonFocus:'combining like terms',workedExample:ex},'factor-expression':{standard:'7.EE.1',lessonFocus:'factoring simple expressions',workedExample:ex},'equivalent-form':{standard:'7.EE.1',lessonFocus:'equivalent forms',workedExample:ex},'interpret-expression':{standard:'7.EE.2',lessonFocus:'interpreting parts of expressions',workedExample:ex},'context-expression':{standard:'7.EE.2',lessonFocus:'writing expressions from contexts',workedExample:ex}}
const term=(n:number,v='x')=>n===1?v:n===-1?`-${v}`:`${n}${v}`;const signed=(n:number)=>n<0?` - ${-n}`:` + ${n}`
const make=(kind:Grade7MathUnit3ItemType,difficulty:Difficulty):Grade7MathUnit3Question=>{const a=pick([-1,1] as const)*ri(2,5+difficulty),b=pick([-1,1] as const)*ri(1,5+difficulty),c=pick([-1,1] as const)*ri(1,5+difficulty),d=pick([-1,1] as const)*ri(1,5+difficulty);let correct:string,prompt:string
if(kind==='distribute'){correct=`${term(a)}x${signed(a*b)}`;prompt=`Expand ${a}(x ${b<0?'-':'+'} ${Math.abs(b)}).`}else if(kind==='combine-like-terms'){correct=`${term(a+c)}x${signed(b+d)}`;prompt=`Combine like terms: ${term(a)}x${signed(b)} ${c<0?'-':'+'} ${term(Math.abs(c))}x${signed(d)}.`}else if(kind==='factor-expression'){const g=ri(2,5+difficulty),inside=pick([-1,1] as const)*ri(1,5+difficulty);correct=`${g}(x ${inside<0?'-':'+'} ${Math.abs(inside)})`;prompt=`Factor ${g}x${signed(g*inside)} using the greatest common factor.`}else if(kind==='equivalent-form'){correct=String(a*(c+b));prompt=`Evaluate ${a}(x ${b<0?'-':'+'} ${Math.abs(b)}) when x = ${c}.`}else if(kind==='interpret-expression'){correct=`${a} per group`;prompt=`In ${term(a,'n')}${signed(b)}, what does ${a} represent?`}else{correct=`${term(a,'t')}${signed(b)}`;prompt=`A trip has a ${b} dollar starting adjustment and costs ${a} dollars per ticket t. Write an expression.`}const choices=[`${term(a+1)}x${signed(a*b)}`,`${term(a)}x${signed(b)}`,`${term(a+c)}x${signed(b+d)}`,String(a+b+c)];const definition=defs[kind];return makeCurriculumQuestion({itemType:kind,standard:definition.standard,lessonFocus:definition.lessonFocus,difficulty,prompt,correctAnswer:correct,distractors:choices,parameters:{a,b,c,d,kind},workedExample:definition.workedExample,distractorMode:'distinct'})}
export const GRADE7_MATH_UNIT3_GENERATORS=Object.fromEntries(GRADE7_MATH_UNIT3_ITEM_TYPES.map(k=>[k,(d:Difficulty)=>make(k,d)])) as Record<Grade7MathUnit3ItemType,CurriculumGenerator<Grade7MathUnit3Question>>;export const generateGrade7MathUnit3Question=(itemType:Grade7MathUnit3ItemType,difficulty:Difficulty)=>GRADE7_MATH_UNIT3_GENERATORS[itemType](difficulty);export {defs as GRADE7_MATH_UNIT3_ITEM_DEFINITIONS}
