import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source coverage: Grade 7 Mathematics Unit 6 (days 91-108), 7.G.1-2. */
export const GRADE7_MATH_UNIT6_ITEM_TYPES = ['scale-factor', 'scale-drawing', 'actual-drawing-dimensions', 'reproduce-at-new-scale', 'construct-triangle', 'unique-triangle-conditions'] as const
export type Grade7MathUnit6ItemType = typeof GRADE7_MATH_UNIT6_ITEM_TYPES[number]
type Params = { drawing: number; actual: number; scale: number; newScale: number; drawingScale?: number; a?: number; b?: number; c?: number; measure?: 'length' | 'area' }
type Q<T extends Grade7MathUnit6ItemType> = CurriculumQuestion<T, Params>
export type Grade7MathUnit6Question = { [T in Grade7MathUnit6ItemType]: Q<T> }[Grade7MathUnit6ItemType]
type Def = { standard: '7.G.1' | '7.G.2'; lessonFocus: string; workedExample: CurriculumWorkedExample }
const example = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Write the scale as a ratio with matching units.', 'Multiply or divide consistently, then check whether the dimensions are possible.'] })
export const GRADE7_MATH_UNIT6_ITEM_DEFINITIONS = {
  'scale-factor': { standard: '7.G.1', lessonFocus: 'scale factors', workedExample: example('A 4 cm drawing represents 20 cm. What is the scale factor from drawing to actual?', '5') },
  'scale-drawing': { standard: '7.G.1', lessonFocus: 'scale drawings', workedExample: example('At a scale of 1 cm : 3 m, what actual length does 5 cm represent?', '15 m') },
  'actual-drawing-dimensions': { standard: '7.G.1', lessonFocus: 'actual and drawing dimensions', workedExample: example('A 24 m wall is drawn at 1 cm : 4 m. How long is the drawing?', '6 cm') },
  'reproduce-at-new-scale': { standard: '7.G.1', lessonFocus: 'reproducing a drawing at a new scale', workedExample: example('A 6 cm segment is enlarged by scale factor 3. What is its new length?', '18 cm') },
  'construct-triangle': { standard: '7.G.2', lessonFocus: 'constructing triangles', workedExample: example('Can segments 3, 4, and 5 form a triangle?', 'yes') },
  'unique-triangle-conditions': { standard: '7.G.2', lessonFocus: 'conditions for unique triangles', workedExample: example('Which information guarantees one triangle: three side lengths, or only one side length?', 'three side lengths') },
} as const satisfies Record<Grade7MathUnit6ItemType, Def>
const q = (itemType: Grade7MathUnit6ItemType, difficulty: Difficulty, prompt: string, answer: string, parameters: Params, distractors: string[]) => makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, distractorMode: 'distinct', parameters, ...GRADE7_MATH_UNIT6_ITEM_DEFINITIONS[itemType] })
const facts = (difficulty: Difficulty) => { const scale = ri(2, difficulty + 5); const drawing = ri(2, difficulty * 4 + 6); return { drawing, actual: drawing * scale, scale, newScale: ri(2, difficulty + 4) } }
export function generateScaleFactorQuestion(difficulty: Difficulty) { const p = facts(difficulty); return q('scale-factor', difficulty, `A ${p.drawing} cm drawing represents ${p.actual} cm. What is the scale factor from drawing to actual?`, String(p.scale), p, [String(p.scale - 1), String(p.scale + 1), String(p.scale + 2), String(p.scale + 3)]) }
export function generateScaleDrawingQuestion(difficulty: Difficulty) { const p = facts(difficulty); const drawingScale = ri(1, 3); const scale = ri(2, difficulty + 6); const units = ri(2, difficulty * 4 + 6) * drawingScale; const actual = units / drawingScale * scale; return q('scale-drawing', difficulty, `A map scale is ${drawingScale} cm : ${scale} m. What actual distance does ${units} cm represent?`, `${actual} m`, { ...p, drawing: units, actual, scale, drawingScale }, [`${actual + 1} m`, `${actual + 2} m`, `${actual + 3} m`, `${actual + 4} m`]) }
export function generateActualDrawingDimensionsQuestion(difficulty: Difficulty) { const p = facts(difficulty); return q('actual-drawing-dimensions', difficulty, `A ${p.actual} m path is drawn at 1 cm : ${p.scale} m. What is its drawing length?`, `${p.drawing} cm`, p, [`${p.drawing + 1} cm`, `${p.drawing + 2} cm`, `${p.drawing + 3} cm`, `${p.drawing + 4} cm`]) }
export function generateReproduceAtNewScaleQuestion(difficulty: Difficulty) { const p = facts(difficulty); const measure = difficulty === 3 ? pick(['length', 'area'] as const) : 'length'; if (measure === 'area') { const answer = p.drawing * p.newScale * p.newScale; return q('reproduce-at-new-scale', difficulty, `A drawing has area ${p.drawing} cm² and is reproduced using a scale factor of ${p.newScale}. What is its new area?`, `${answer} cm²`, { ...p, measure }, [`${answer + 1} cm²`, `${answer + 2} cm²`, `${answer + 3} cm²`, `${answer + 4} cm²`]) } const answer = p.drawing * p.newScale; return q('reproduce-at-new-scale', difficulty, `A ${p.drawing} cm segment is reproduced using a scale factor of ${p.newScale}. What is its new length?`, `${answer} cm`, { ...p, measure }, [`${answer + 1} cm`, `${answer + 2} cm`, `${answer + 3} cm`, `${answer + 4} cm`]) }
export function generateConstructTriangleQuestion(difficulty: Difficulty) { const p = facts(difficulty); const a = ri(2, 7), b = ri(3, 9), c = pick([a + b - 1, a + b] as const); const answer = c < a + b ? 'yes' : 'no'; return q('construct-triangle', difficulty, `Can segments of lengths ${a}, ${b}, and ${c} form a triangle?`, answer, { ...p, a, b, c }, [answer === 'yes' ? 'no' : 'yes', 'only if all sides are equal', 'only if one angle is right', 'not enough information']) }
export function generateUniqueTriangleConditionsQuestion(difficulty: Difficulty) { const p = facts(difficulty); const sufficient = pick(['SSS', 'SAS', 'ASA'] as const); const insufficient = pick(['SSA', 'AAA'] as const); const otherInsufficient = insufficient === 'SSA' ? 'AAA' : 'SSA'; const askSufficient = pick([true, false] as const); const answer = askSufficient ? sufficient : insufficient; return q('unique-triangle-conditions', difficulty, askSufficient ? `Which condition determines a unique triangle: ${sufficient}, ${insufficient}, ${otherInsufficient}, or one side length?` : `Which condition does not determine a unique triangle: ${insufficient}, SSS, SAS, or ASA?`, answer, p, askSufficient ? [insufficient, otherInsufficient, 'one side length', 'a perimeter only'] : ['SSS', 'SAS', 'ASA', 'three side lengths']) }
export const GRADE7_MATH_UNIT6_GENERATORS = { 'scale-factor': generateScaleFactorQuestion, 'scale-drawing': generateScaleDrawingQuestion, 'actual-drawing-dimensions': generateActualDrawingDimensionsQuestion, 'reproduce-at-new-scale': generateReproduceAtNewScaleQuestion, 'construct-triangle': generateConstructTriangleQuestion, 'unique-triangle-conditions': generateUniqueTriangleConditionsQuestion } satisfies Record<Grade7MathUnit6ItemType, CurriculumGenerator<Grade7MathUnit6Question>>
export function generateGrade7MathUnit6Question<T extends Grade7MathUnit6ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade7MathUnit6Question, { itemType: T }> { return GRADE7_MATH_UNIT6_GENERATORS[itemType](difficulty) as Extract<Grade7MathUnit6Question, { itemType: T }> }
