import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source coverage: Grade 7 Mathematics Unit 9 (days 145-162), 7.SP.1-4. */
export const GRADE7_MATH_UNIT9_ITEM_TYPES = ['valid-random-sample', 'population-proportion-estimate', 'multiple-sample-estimates', 'distribution-overlap', 'mean-absolute-deviation', 'compare-two-populations'] as const
export type Grade7MathUnit9ItemType = typeof GRADE7_MATH_UNIT9_ITEM_TYPES[number]
type Params = { population?: number; sampleSize?: number; favorable?: number; multiplier?: number; estimates?: number[]; meanA?: number; meanB?: number; mad?: number; values?: number[]; rangeA?: number; rangeB?: number }
type Q<T extends Grade7MathUnit9ItemType> = CurriculumQuestion<T, Params>
export type Grade7MathUnit9Question = { [T in Grade7MathUnit9ItemType]: Q<T> }[Grade7MathUnit9ItemType]
type Def = { standard: '7.SP.1' | '7.SP.2' | '7.SP.3' | '7.SP.4'; lessonFocus: string; workedExample: CurriculumWorkedExample }
const example = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Identify what the sample or data actually shows.', 'Use the sample proportion, mean, or spread to draw a conclusion about the population.'] })
export const GRADE7_MATH_UNIT9_ITEM_DEFINITIONS = {
  'valid-random-sample': { standard: '7.SP.1', lessonFocus: 'valid random sampling methods', workedExample: example('Which method produces a random sample of a school\'s students?', 'assign each student a number and use a random number generator to select respondents') },
  'population-proportion-estimate': { standard: '7.SP.2', lessonFocus: 'estimating a population from a sample proportion', workedExample: example('A random sample of 20 out of 200 students found 5 prefer art. About how many of the 200 students prefer art?', '50') },
  'multiple-sample-estimates': { standard: '7.SP.2', lessonFocus: 'comparing estimates from multiple samples', workedExample: example('Four samples estimated 40, 44, 48, and 52 supporters. What is the mean of these estimates?', '46') },
  'distribution-overlap': { standard: '7.SP.3', lessonFocus: 'comparing the overlap of two distributions', workedExample: example('Group A has a mean of 50 and a MAD of 5. Group B has a mean of 60 with the same MAD. The difference in means is how many MADs?', '2') },
  'mean-absolute-deviation': { standard: '7.SP.4', lessonFocus: 'measures of variability', workedExample: example('A data set is 10, 15, 20, 25, 30. The mean is 20. What is the mean absolute deviation?', '6') },
  'compare-two-populations': { standard: '7.SP.4', lessonFocus: 'comparing two populations using center and variability', workedExample: example('Group A has a range of 8. Group B has a range of 15 for the same measure. Which group is more consistent?', 'Group A') },
} as const satisfies Record<Grade7MathUnit9ItemType, Def>
const q = (itemType: Grade7MathUnit9ItemType, difficulty: Difficulty, prompt: string, answer: string, parameters: Params, distractors: string[]) => makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, distractorMode: 'distinct', parameters, ...GRADE7_MATH_UNIT9_ITEM_DEFINITIONS[itemType] })
const SAMPLE_SCENARIOS = [
  { population: 'the 500 students at Lincoln Middle School', valid: 'assign each student a number and use a random number generator to select respondents', invalid: ['survey only the students in the marching band', 'survey the first 50 students who arrive at school', 'survey only students who volunteer after an announcement'] },
  { population: 'the 3,000 registered voters in a town', valid: 'assign each voter a number and use a random number generator to select 100 voters', invalid: ['survey only voters at a rally for one candidate', 'survey the 100 voters who live closest to the researcher', 'survey only voters who call in to a radio show'] },
  { population: 'the 1,200 employees at a company', valid: 'put every employee ID in a hat and draw 60 IDs at random', invalid: ['survey only employees who eat in the cafeteria', 'survey only employees in the marketing department', 'survey the 60 employees who reply first to an email'] },
  { population: 'the 800 shoppers who visit a mall on a Saturday', valid: 'use a random number generator to select shoppers from the full list of receipts', invalid: ['survey only shoppers at one specific store', 'survey only shoppers who enter through the main doors', 'survey only shoppers between 10 a.m. and 11 a.m.'] },
] as const
const CONTEXTS = [
  { labelA: 'City A', labelB: 'City B' },
  { labelA: 'Store A', labelB: 'Store B' },
  { labelA: 'Team A', labelB: 'Team B' },
] as const
export function generateValidRandomSampleQuestion(difficulty: Difficulty) { const s = pick(SAMPLE_SCENARIOS); return q('valid-random-sample', difficulty, `A researcher wants a sample that fairly represents ${s.population}. Which sampling method is most likely to produce a valid random sample?`, s.valid, {}, [...s.invalid]) }
export function generatePopulationProportionEstimateQuestion(difficulty: Difficulty) { const sampleSize = ri(2, difficulty + 3) * 10; const multiplier = ri(4, difficulty * 3 + 6); const population = sampleSize * multiplier; const favorable = ri(2, sampleSize - 2); const answer = favorable * multiplier; return q('population-proportion-estimate', difficulty, `A random sample of ${sampleSize} out of ${population} students found that ${favorable} prefer science class best. Based on this sample, about how many of the ${population} students prefer science class best?`, String(answer), { sampleSize, multiplier, population, favorable }, [String(answer + multiplier), String(answer - multiplier), String(favorable), String(population - favorable)]) }
export function generateMultipleSampleEstimatesQuestion(difficulty: Difficulty) { const base = ri(20, difficulty * 30 + 40); const step = ri(2, difficulty + 3); const total = ri(400, difficulty * 300 + 600); const estimates = [base - 3 * step, base - step, base + step, base + 3 * step]; return q('multiple-sample-estimates', difficulty, `Four random samples of a town's ${total} residents estimated the number who support a new park. The estimates were ${estimates[0]}, ${estimates[1]}, ${estimates[2]}, and ${estimates[3]} residents. What is the mean of these four estimates?`, String(base), { estimates, meanA: base, population: total }, [String(estimates[0]), String(estimates[3]), String(base - 2 * step), String(base + step)]) }
export function generateDistributionOverlapQuestion(difficulty: Difficulty) { const mad = ri(2, difficulty + 3); const multiplier = ri(2, difficulty + 4); const meanA = ri(20, 60); const meanB = meanA + mad * multiplier; return q('distribution-overlap', difficulty, `Team A has a mean score of ${meanA} with a mean absolute deviation (MAD) of ${mad}. Team B has a mean score of ${meanB} with the same MAD. The difference in means is how many MADs?`, String(multiplier), { meanA, meanB, mad, multiplier }, [String(multiplier - 1), String(multiplier + 1), String(meanB - meanA), String(mad)]) }
export function generateMeanAbsoluteDeviationQuestion(difficulty: Difficulty) { const mean = ri(30, difficulty * 15 + 40); const kMax = Math.max(1, Math.min(difficulty + 2, Math.floor(mean / 10))); const k = ri(1, kMax); const d = 5 * k; const values = [mean - 2 * d, mean - d, mean, mean + d, mean + 2 * d]; const answer = 6 * k; return q('mean-absolute-deviation', difficulty, `A data set has the values ${values.join(', ')}. The mean is ${mean}. What is the mean absolute deviation (MAD)?`, String(answer), { values, mad: answer, meanA: mean }, [String(answer + k), String(answer - k), String(2 * d), String(k)]) }
export function generateCompareTwoPopulationsQuestion(difficulty: Difficulty) { const ctx = pick(CONTEXTS); const rangeA = ri(5, difficulty * 5 + 10); const rangeB = rangeA + ri(1, difficulty * 3 + 3); return q('compare-two-populations', difficulty, `${ctx.labelA} has a range of ${rangeA} in its data, and ${ctx.labelB} has a range of ${rangeB} for the same measure. Which group's data is more consistent (less variable)?`, ctx.labelA, { rangeA, rangeB }, [ctx.labelB, 'Both are equally consistent', 'Cannot be determined from range alone', `${ctx.labelA} and ${ctx.labelB} have the same variability`]) }
export const GRADE7_MATH_UNIT9_GENERATORS = { 'valid-random-sample': generateValidRandomSampleQuestion, 'population-proportion-estimate': generatePopulationProportionEstimateQuestion, 'multiple-sample-estimates': generateMultipleSampleEstimatesQuestion, 'distribution-overlap': generateDistributionOverlapQuestion, 'mean-absolute-deviation': generateMeanAbsoluteDeviationQuestion, 'compare-two-populations': generateCompareTwoPopulationsQuestion } satisfies Record<Grade7MathUnit9ItemType, CurriculumGenerator<Grade7MathUnit9Question>>
export function generateGrade7MathUnit9Question<T extends Grade7MathUnit9ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade7MathUnit9Question, { itemType: T }> { return GRADE7_MATH_UNIT9_GENERATORS[itemType](difficulty) as Extract<Grade7MathUnit9Question, { itemType: T }> }
