import type { Difficulty } from '../types'
import { makeFinLitQuestion, money, ri, roundHalfUp, type CurriculumGenerator, type FinLitQuestion } from './grade8FinLitCore'
export const GRADE8_FINLIT_UNIT6_ITEM_TYPES=['insurance-out-of-pocket'] as const
export type Grade8FinLitUnit6ItemType=typeof GRADE8_FINLIT_UNIT6_ITEM_TYPES[number]
export interface Grade8FinLitUnit6Parameters { lossCents: bigint; deductibleCents: bigint; coverageBps: bigint }
export type Grade8FinLitUnit6Question=FinLitQuestion<'insurance-out-of-pocket',Grade8FinLitUnit6Parameters>
const definition={standard:'FL.8.R',lessonFocus:'computing insurance cost sharing',workedExample:{prompt:'A covered $500.00 loss has a $100.00 deductible and 80% coverage after it. What is paid out of pocket?',answer:'$180.00',steps:['Pay the $100.00 deductible first.','Twenty percent of the remaining $400.00 is $80.00, so total is $180.00.']}} as const
export function generateInsuranceOutOfPocketQuestion(difficulty:Difficulty):Grade8FinLitUnit6Question {const deductibleCents=BigInt(ri(50*difficulty,200*difficulty)*100),lossCents=deductibleCents+BigInt(ri(200*difficulty,1_000*difficulty)*100),coverageBps=BigInt(ri(7,9)*1000),remaining=lossCents-deductibleCents,share=roundHalfUp(remaining*(10_000n-coverageBps),10_000n),answer=deductibleCents+share;return makeFinLitQuestion({itemType:'insurance-out-of-pocket',difficulty,prompt:`A sample covered loss is ${money(lossCents)}. The deductible is ${money(deductibleCents)}, then coverage pays ${(Number(coverageBps)/100).toFixed(0)}% of the remaining amount. Round the remaining out-of-pocket share to the nearest cent, with a half-cent rounded up. What is paid out of pocket?`,correctAnswer:money(answer),distractors:[money(lossCents-answer),money(deductibleCents),money(share),money(answer+100n)],parameters:{lossCents,deductibleCents,coverageBps},definition})}
export const GRADE8_FINLIT_UNIT6_GENERATORS={'insurance-out-of-pocket':generateInsuranceOutOfPocketQuestion} satisfies Record<Grade8FinLitUnit6ItemType,CurriculumGenerator<Grade8FinLitUnit6Question>>
export const generateGrade8FinLitUnit6Question=generateInsuranceOutOfPocketQuestion
