import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Coverage contract: Grade 8 Mathematics Unit 7 (days 109-126), 8.G.1-5. */
export const GRADE8_MATH_UNIT7_ITEM_TYPES = [
  'identify-translation-rule', 'apply-translation', 'reflect-across-axis', 'rotate-90-degrees',
  'dilate-coordinate', 'find-scale-factor', 'classify-rigid-transformation', 'identify-congruent-figures',
  'identify-similar-figures', 'sequence-transformations', 'angle-relationships', 'informal-geometric-argument',
] as const
export type Grade8MathUnit7ItemType = typeof GRADE8_MATH_UNIT7_ITEM_TYPES[number]
type Point = { x: number; y: number }
type Params = { p: Point; q?: Point; dx?: number; dy?: number; factor?: number; operation?: string; candidate?: Point }
type Q<T extends Grade8MathUnit7ItemType> = CurriculumQuestion<T, Params>
export type Grade8MathUnit7Question = { [T in Grade8MathUnit7ItemType]: Q<T> }[Grade8MathUnit7ItemType]
type Def = { standard: '8.G.1' | '8.G.2' | '8.G.3' | '8.G.4' | '8.G.5'; lessonFocus: string; workedExample: CurriculumWorkedExample }
const example = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Identify the rule and apply it to each coordinate or corresponding side.', 'Check that the resulting coordinates or ratios match the transformation.'] })
export const GRADE8_MATH_UNIT7_ITEM_DEFINITIONS = {
  'identify-translation-rule': { standard: '8.G.1', lessonFocus: 'translations', workedExample: example('Point (2, -1) maps to (5, 3). What translation rule is used?', '(x + 3, y + 4)') },
  'apply-translation': { standard: '8.G.1', lessonFocus: 'translations', workedExample: example('Translate (-2, 4) by (x + 3, y - 5).', '(1, -1)') },
  'reflect-across-axis': { standard: '8.G.1', lessonFocus: 'reflections', workedExample: example('Reflect (3, -2) across the y-axis.', '(-3, -2)') },
  'rotate-90-degrees': { standard: '8.G.1', lessonFocus: 'rotations', workedExample: example('Rotate (2, 5) 90 degrees counterclockwise about the origin.', '(-5, 2)') },
  'dilate-coordinate': { standard: '8.G.3', lessonFocus: 'dilations', workedExample: example('Dilate (3, -2) from the origin by scale factor 2.', '(6, -4)') },
  'find-scale-factor': { standard: '8.G.3', lessonFocus: 'dilations', workedExample: example('A side of length 4 maps to a side of length 10. What is the scale factor?', '5/2') },
  'classify-rigid-transformation': { standard: '8.G.1', lessonFocus: 'rigid transformations', workedExample: example('Which transformation preserves both lengths and angle measures?', 'rotation') },
  'identify-congruent-figures': { standard: '8.G.2', lessonFocus: 'congruence', workedExample: example('Two triangles have side lengths 3, 4, 5 and 3, 4, 5. How are they related?', 'congruent') },
  'identify-similar-figures': { standard: '8.G.4', lessonFocus: 'similarity', workedExample: example('Rectangles 3 by 5 and 6 by 10 are related how?', 'similar') },
  'sequence-transformations': { standard: '8.G.2', lessonFocus: 'congruence through transformations', workedExample: example('Translate (1, 2) by (3, -1), then reflect across the x-axis.', '(4, -1)') },
  'angle-relationships': { standard: '8.G.5', lessonFocus: 'angle relationships', workedExample: example('Two supplementary angles include an angle of 68 degrees. Find the other angle.', '112°') },
  'informal-geometric-argument': { standard: '8.G.2', lessonFocus: 'informal geometric arguments', workedExample: example('Why is a translated figure congruent to the original?', 'A translation preserves lengths and angle measures.') },
} as const satisfies Record<Grade8MathUnit7ItemType, Def>
const point = (p: Point) => `(${p.x}, ${p.y})`
const limit = (d: Difficulty) => d === 1 ? 4 : d === 2 ? 7 : 10
const randomPoint = (d: Difficulty): Point => ({ x: ri(-limit(d), limit(d)), y: ri(-limit(d), limit(d)) })
const distinct = (answer: string, values: string[]) => [...new Set(values)].filter((value) => value !== answer)
function question<T extends Grade8MathUnit7ItemType>(itemType: T, difficulty: Difficulty, prompt: string, correctAnswer: string, parameters: Params, distractors: string[]): Q<T> {
  return makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer, distractors: distinct(correctAnswer, distractors), distractorMode: 'distinct', parameters, ...GRADE8_MATH_UNIT7_ITEM_DEFINITIONS[itemType] })
}
export function generateIdentifyTranslationRuleQuestion(difficulty: Difficulty) {
  const p = randomPoint(difficulty); const dx = ri(-limit(difficulty), limit(difficulty)) || 1; const dy = ri(-limit(difficulty), limit(difficulty)) || -1; const q = { x: p.x + dx, y: p.y + dy }; const answer = `(x ${dx >= 0 ? '+' : '-'} ${Math.abs(dx)}, y ${dy >= 0 ? '+' : '-'} ${Math.abs(dy)})`
  return question('identify-translation-rule', difficulty, `Point ${point(p)} maps to ${point(q)}. Which translation rule maps the point?`, answer, { p, q, dx, dy }, [`(x ${dx >= 0 ? '-' : '+'} ${Math.abs(dx)}, y ${dy >= 0 ? '-' : '+'} ${Math.abs(dy)})`, `(x ${dy >= 0 ? '+' : '-'} ${Math.abs(dy)}, y ${dx >= 0 ? '+' : '-'} ${Math.abs(dx)})`, `(x, y)`, `(x + ${Math.abs(dx) + 1}, y + ${Math.abs(dy) + 1})`])
}
export function generateApplyTranslationQuestion(difficulty: Difficulty) { const p = randomPoint(difficulty); const dx = ri(-limit(difficulty), limit(difficulty)) || 2; const dy = ri(-limit(difficulty), limit(difficulty)) || -2; const answer = point({ x: p.x + dx, y: p.y + dy }); return question('apply-translation', difficulty, `Translate ${point(p)} using (x ${dx >= 0 ? '+' : '-'} ${Math.abs(dx)}, y ${dy >= 0 ? '+' : '-'} ${Math.abs(dy)}).`, answer, { p, dx, dy }, [point({ x: p.x - dx, y: p.y - dy }), point({ x: p.x + dy, y: p.y + dx }), point({ x: p.x + dx, y: p.y - dy }), point({ x: p.x + dx + 1, y: p.y + dy + 1 })]) }
export function generateReflectAcrossAxisQuestion(difficulty: Difficulty) { const p = randomPoint(difficulty); if (p.x === 0) p.x = 1; if (p.y === 0) p.y = -1; const operation = pick(['x-axis', 'y-axis'] as const); const answerPoint = operation === 'x-axis' ? { x: p.x, y: -p.y } : { x: -p.x, y: p.y }; const answer = point(answerPoint); return question('reflect-across-axis', difficulty, `Reflect ${point(p)} across the ${operation}.`, answer, { p, operation }, [point({ x: -p.x, y: -p.y }), point(p), point(operation === 'x-axis' ? { x: -p.x, y: p.y } : { x: p.x, y: -p.y })]) }
export function generateRotate90DegreesQuestion(difficulty: Difficulty) { const p = randomPoint(difficulty); if (p.x === 0) p.x = 1; if (p.y === 0) p.y = -1; const operation = pick(['counterclockwise', 'clockwise'] as const); const answerPoint = operation === 'counterclockwise' ? { x: -p.y, y: p.x } : { x: p.y, y: -p.x }; const answer = point(answerPoint); return question('rotate-90-degrees', difficulty, `Rotate ${point(p)} 90 degrees ${operation} about the origin.`, answer, { p, operation }, [point({ x: p.y, y: p.x }), point({ x: -p.x, y: -p.y }), point(p), point({ x: answerPoint.x + 1, y: answerPoint.y + 1 })]) }
export function generateDilateCoordinateQuestion(difficulty: Difficulty) { const p = randomPoint(difficulty); if (p.x === 0) p.x = 1; if (p.y === 0) p.y = -1; const factor = pick([2, 3, 4] as const); const answer = point({ x: p.x * factor, y: p.y * factor }); return question('dilate-coordinate', difficulty, `Dilate ${point(p)} about the origin by scale factor ${factor}.`, answer, { p, factor }, [point({ x: p.x + factor, y: p.y + factor }), point({ x: p.x * factor, y: p.y }), point({ x: p.x, y: p.y * factor }), point({ x: p.x * factor + 1, y: p.y * factor + 1 }), point({ x: p.x * factor - 1, y: p.y * factor - 1 })]) }
export function generateFindScaleFactorQuestion(difficulty: Difficulty) { const factor = pick([2, 3, 4] as const); const base = ri(2, limit(difficulty)); const answer = String(factor); return question('find-scale-factor', difficulty, `A segment of length ${base} maps to a segment of length ${base * factor}. What is the dilation scale factor?`, answer, { p: { x: base, y: base * factor }, factor }, [String(base * factor), String(factor + 1), String(base), String(factor + 2), String(factor + 3)]) }
export function generateClassifyRigidTransformationQuestion(difficulty: Difficulty) { const operation = pick(['translation', 'reflection', 'rotation'] as const); return question('classify-rigid-transformation', difficulty, `Which transformation is described as a ${operation} and preserves lengths and angle measures?`, operation, { p: { x: 0, y: 0 }, operation }, distinct(operation, ['translation', 'reflection', 'rotation', 'dilation'])) }
export function generateIdentifyCongruentFiguresQuestion(difficulty: Difficulty) { const base = ri(2, limit(difficulty)); const factor = pick([1, 2, 3] as const); const answer = factor === 1 ? 'congruent' : 'not congruent'; return question('identify-congruent-figures', difficulty, `Triangle A has side lengths ${base}, ${base + 1}, ${base + 2}. Triangle B has corresponding side lengths ${base * factor}, ${(base + 1) * factor}, ${(base + 2) * factor}. Are the triangles congruent?`, answer, { p: { x: base, y: factor }, factor }, distinct(answer, ['congruent', 'not congruent', 'cannot be determined', 'only similar'])) }
export function generateIdentifySimilarFiguresQuestion(difficulty: Difficulty) { const base = ri(2, limit(difficulty)); const factor = pick([2, 3] as const); const answer = 'similar'; return question('identify-similar-figures', difficulty, `Rectangle A is ${base} by ${base + 2}. Rectangle B is ${base * factor} by ${(base + 2) * factor}. How are the rectangles related?`, answer, { p: { x: base, y: base + 2 }, factor }, ['congruent', 'neither similar nor congruent', 'perpendicular']) }
export function generateSequenceTransformationsQuestion(difficulty: Difficulty) { const p = randomPoint(difficulty); const dx = ri(-limit(difficulty), limit(difficulty)) || 1; const dy = ri(-limit(difficulty), limit(difficulty)) || -1; const translated = { x: p.x + dx, y: p.y + dy }; const answerPoint = { x: translated.x, y: -translated.y }; const answer = point(answerPoint); return question('sequence-transformations', difficulty, `Translate ${point(p)} by (${dx}, ${dy}), then reflect the image across the x-axis. What is the final point?`, answer, { p, dx, dy }, [point(translated), point({ x: -translated.x, y: translated.y }), point({ x: -translated.x, y: -translated.y }), point({ x: answerPoint.x + 2, y: answerPoint.y + 1 }), point({ x: answerPoint.x - 2, y: answerPoint.y - 1 }), point({ x: answerPoint.x + 3, y: answerPoint.y - 2 }), point({ x: answerPoint.x - 3, y: answerPoint.y + 2 })]) }
export function generateAngleRelationshipsQuestion(difficulty: Difficulty) { const angle = ri(20, 160); const answer = `${180 - angle}°`; return question('angle-relationships', difficulty, `Two adjacent angles form a straight line. One angle measures ${angle}°. What is the other angle measure?`, answer, { p: { x: angle, y: 180 - angle } }, [`${angle}°`, `${90 - angle}°`, `${180 + angle}°`, `${181 - angle}°`, `${179 - angle}°`]) }
export function generateInformalGeometricArgumentQuestion(difficulty: Difficulty) { const operation = pick(['translation', 'reflection', 'rotation'] as const); const answer = `A ${operation} preserves lengths and angle measures.`; return question('informal-geometric-argument', difficulty, `A figure is mapped onto another figure by a ${operation}. Which statement justifies that the figures are congruent?`, answer, { p: { x: 0, y: 0 }, operation }, ['The figures have the same position.', 'A dilation always preserves lengths.', 'Congruent figures must have different orientations.']) }
export const GRADE8_MATH_UNIT7_GENERATORS: Record<Grade8MathUnit7ItemType, CurriculumGenerator<Grade8MathUnit7Question>> = {
  'identify-translation-rule': generateIdentifyTranslationRuleQuestion, 'apply-translation': generateApplyTranslationQuestion, 'reflect-across-axis': generateReflectAcrossAxisQuestion, 'rotate-90-degrees': generateRotate90DegreesQuestion, 'dilate-coordinate': generateDilateCoordinateQuestion, 'find-scale-factor': generateFindScaleFactorQuestion, 'classify-rigid-transformation': generateClassifyRigidTransformationQuestion, 'identify-congruent-figures': generateIdentifyCongruentFiguresQuestion, 'identify-similar-figures': generateIdentifySimilarFiguresQuestion, 'sequence-transformations': generateSequenceTransformationsQuestion, 'angle-relationships': generateAngleRelationshipsQuestion, 'informal-geometric-argument': generateInformalGeometricArgumentQuestion,
}
export const generateGrade8MathUnit7Question = (itemType: Grade8MathUnit7ItemType, difficulty: Difficulty) => GRADE8_MATH_UNIT7_GENERATORS[itemType](difficulty)
