import type { Difficulty } from '../types'
import { ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Grade 7 U2, days 19-36 (7.NS.1-3). Signed rational values are integer numerator/positive-denominator pairs; arithmetic is exact integer arithmetic. */
export const GRADE7_MATH_UNIT2_ITEM_TYPES = ['add-signed','subtract-signed','multiply-signed','divide-signed','signed-fractions','multi-step-rational'] as const
export type Grade7MathUnit2ItemType = typeof GRADE7_MATH_UNIT2_ITEM_TYPES[number]
type P={a:number;b:number;den:number;kind:Grade7MathUnit2ItemType}; export type Grade7MathUnit2Question=CurriculumQuestion<Grade7MathUnit2ItemType,P>
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a); const f=(n:number,d:number)=>{const g=gcd(n,d);return d/g===1?String(n/g):`${n/g}/${d/g}`}
const sample: CurriculumWorkedExample={prompt:'-3 + 7 = ?',answer:'4',steps:['Subtract magnitudes because the signs differ.','Keep the sign of the greater magnitude.']}
const defs:Record<Grade7MathUnit2ItemType,{standard:'7.NS.1'|'7.NS.2'|'7.NS.3';lessonFocus:string;workedExample:CurriculumWorkedExample}>={
 'add-signed':{standard:'7.NS.1',lessonFocus:'adding signed numbers',workedExample:sample},'subtract-signed':{standard:'7.NS.1',lessonFocus:'subtracting signed numbers',workedExample:sample},'multiply-signed':{standard:'7.NS.2',lessonFocus:'multiplying signed numbers',workedExample:sample},'divide-signed':{standard:'7.NS.2',lessonFocus:'dividing signed numbers',workedExample:sample},'signed-fractions':{standard:'7.NS.3',lessonFocus:'fractions and decimals',workedExample:sample},'multi-step-rational':{standard:'7.NS.3',lessonFocus:'multi-step rational-number problems',workedExample:sample}}
const make=(kind:Grade7MathUnit2ItemType,difficulty:Difficulty):Grade7MathUnit2Question=>{let a=ri(-6-difficulty,6+difficulty),b=ri(-6-difficulty,6+difficulty),den=ri(2,6+difficulty);if(!a)a=1;if(!b)b=-1;let n:number,prompt:string;if(kind==='add-signed'){n=a+b;prompt=`${a} + (${b}) = ?`}else if(kind==='subtract-signed'){n=a-b;prompt=`${a} - (${b}) = ?`}else if(kind==='multiply-signed'){n=a*b;prompt=`${a} * (${b}) = ?`}else if(kind==='divide-signed'){b=Math.max(1,Math.abs(b));a*=b;n=a/b;prompt=`${a} / (${b}) = ?`}else if(kind==='signed-fractions'){n=a+b;prompt=`${a}/${den} + ${b}/${den} = ?`}else{n=a+b*den;prompt=`${a} + (${b} * ${den}) = ?`}const correct=kind==='signed-fractions'?f(n,den):String(n),d=defs[kind];const distractors=kind==='signed-fractions'?[f(n+den,den),f(n-den,den),f(-n,den),f(n+2*den,den)]:[String(n+1),String(n-1),String(-n),String(n+2)];return makeCurriculumQuestion({itemType:kind,standard:d.standard,lessonFocus:d.lessonFocus,difficulty,prompt,correctAnswer:correct,distractors,parameters:{a,b,den,kind},workedExample:d.workedExample,distractorMode:'distinct'})}
export const GRADE7_MATH_UNIT2_GENERATORS=Object.fromEntries(GRADE7_MATH_UNIT2_ITEM_TYPES.map(k=>[k,(d:Difficulty)=>make(k,d)])) as Record<Grade7MathUnit2ItemType,CurriculumGenerator<Grade7MathUnit2Question>>
export const generateGrade7MathUnit2Question=(itemType:Grade7MathUnit2ItemType,difficulty:Difficulty)=>GRADE7_MATH_UNIT2_GENERATORS[itemType](difficulty);export {defs as GRADE7_MATH_UNIT2_ITEM_DEFINITIONS}
