import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source coverage: Grade 7 Mathematics Unit 4 (days 55-72), 7.EE.3-4. */
export const GRADE7_MATH_UNIT4_ITEM_TYPES = ['multi-step-numerical-problem', 'two-step-equation', 'two-step-inequality', 'solution-set', 'graph-inequality', 'check-and-interpret-solution'] as const
export type Grade7MathUnit4ItemType = typeof GRADE7_MATH_UNIT4_ITEM_TYPES[number]
type Params = { a: number; b: number; c: number; solution: number; denominator?: number; relation?: '>=' | '<='; negativeCoefficient?: boolean }
type Q<T extends Grade7MathUnit4ItemType> = CurriculumQuestion<T, Params>
export type Grade7MathUnit4Question = { [T in Grade7MathUnit4ItemType]: Q<T> }[Grade7MathUnit4ItemType]
type Def = { standard: '7.EE.3' | '7.EE.4'; lessonFocus: string; workedExample: CurriculumWorkedExample }
const example = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Undo operations in reverse order, keeping both sides equivalent.', 'Substitute or test a boundary value to check the result.'] })
export const GRADE7_MATH_UNIT4_ITEM_DEFINITIONS = {
  'multi-step-numerical-problem': { standard: '7.EE.3', lessonFocus: 'multi-step numerical problems', workedExample: example('A $40 item is discounted 25% and then taxed $3. What is the final cost?', '$33') },
  'two-step-equation': { standard: '7.EE.4', lessonFocus: 'two-step equations', workedExample: example('Solve 3x + 5 = 26.', '7') },
  'two-step-inequality': { standard: '7.EE.4', lessonFocus: 'two-step inequalities', workedExample: example('Solve 2x - 3 ≥ 11.', 'x ≥ 7') },
  'solution-set': { standard: '7.EE.4', lessonFocus: 'solution sets', workedExample: example('Which integer is a solution of x + 4 < 9?', '4') },
  'graph-inequality': { standard: '7.EE.4', lessonFocus: 'graphing inequalities', workedExample: example('Graph x ≥ 3.', 'closed circle at 3, shaded right') },
  'check-and-interpret-solution': { standard: '7.EE.3', lessonFocus: 'checking and interpreting solutions', workedExample: example('A $12 fee plus $4 per ticket totals $36. How many tickets?', '6') },
} as const satisfies Record<Grade7MathUnit4ItemType, Def>
const q = (itemType: Grade7MathUnit4ItemType, difficulty: Difficulty, prompt: string, answer: string, parameters: Params, distractors: string[]) => makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, distractorMode: 'distinct', parameters, ...GRADE7_MATH_UNIT4_ITEM_DEFINITIONS[itemType] })
const facts = (difficulty: Difficulty) => { const a = ri(2, difficulty + 5); const x = ri(2, difficulty * 4 + 5); const b = ri(1, difficulty * 5 + 6); return { a, b, x, c: a * x + b } }
const integerText = (value: number) => String(value)
const signedTerm = (value: number) => value < 0 ? `- ${-value}` : `+ ${value}`
export function generateMultiStepNumericalProblemQuestion(difficulty: Difficulty) { const p = facts(difficulty); const count = ri(2, difficulty + 4); const unit = ri(3, difficulty * 5 + 8); const fee = ri(1, 9); const answer = count * unit + fee; return q('multi-step-numerical-problem', difficulty, `A group buys ${count} passes at $${unit} each and pays a $${fee} service fee. What is the total cost?`, `$${answer}`, { ...p, c: count, solution: answer }, [`$${answer - 1}`, `$${answer + 1}`, `$${answer + 2}`, `$${answer + 3}`]) }
export function generateTwoStepEquationQuestion(difficulty: Difficulty) { if (difficulty === 3) { const a = pick([-6, -4, 4, 6] as const); const denominator = Math.abs(a) === 4 ? pick([2, 4] as const) : pick([2, 3] as const); const numerator = denominator === 3 ? pick([-7, -5, -4, -2, 1, 2, 4, 5, 7] as const) : denominator === 4 ? pick([-7, -5, -3, 1, 3, 5, 7] as const) : pick([-7, -5, -3, 1, 5, 7] as const); const b = pick([-12, -6, 3, 9] as const); const c = b + a / denominator * numerator; const answer = `${numerator}/${denominator}`; return q('two-step-equation', difficulty, `Solve ${a}x ${signedTerm(b)} = ${c}. Write the answer in simplest form.`, answer, { a, b, c, solution: numerator, denominator }, [`${numerator + 2}/${denominator}`, `${numerator - 2}/${denominator}`, integerText(c - b), `${numerator}/${denominator === 2 ? 3 : 2}`]) } const p = facts(difficulty); const b = difficulty === 2 ? -ri(1, 14) : p.b; const solution = difficulty === 2 ? -ri(1, 10) : p.x; const c = p.a * solution + b; return q('two-step-equation', difficulty, `Solve ${p.a}x ${signedTerm(b)} = ${c}.`, String(solution), { ...p, b, c, solution }, [String(solution - 1), String(solution + 1), String(c - b), String(c / p.a)]) }
export function generateTwoStepInequalityQuestion(difficulty: Difficulty) { const p = facts(difficulty); const negativeCoefficient = difficulty === 3 ? pick([true, false] as const) : false; const relation = pick(['>=', '<='] as const); const shownSign = relation === '>=' ? '≥' : '≤'; const answerRelation = negativeCoefficient ? (relation === '>=' ? '<=' : '>=') : relation; const answerSign = answerRelation === '>=' ? '≥' : '≤'; const coefficient = negativeCoefficient ? `-${p.a}` : String(p.a); const right = negativeCoefficient ? p.b - p.a * p.x : p.c; const answer = `x ${answerSign} ${p.x}`; return q('two-step-inequality', difficulty, `Solve ${coefficient}x + ${p.b} ${shownSign} ${right}.`, answer, { ...p, c: right, solution: p.x, relation: answerRelation, negativeCoefficient }, [`x ${answerSign} ${p.x - 1}`, `x ${answerSign} ${p.x + 1}`, `x ${answerRelation === '>=' ? '≤' : '≥'} ${p.x}`, `x ${answerRelation === '>=' ? '≤' : '≥'} ${p.x + 1}`]) }
export function generateSolutionSetQuestion(difficulty: Difficulty) { const p = facts(difficulty); const upperBound = p.x + 1; return q('solution-set', difficulty, `Which integer satisfies ${p.a}x + ${p.b} ≥ ${p.c} and x < ${upperBound}?`, String(p.x), { ...p, solution: p.x, relation: '>=' }, [String(p.x - 1), String(p.x + 1), String(p.x + 2), String(p.x + 3)]) }
export function generateGraphInequalityQuestion(difficulty: Difficulty) { const p = facts(difficulty); const relation = pick(['>=', '<='] as const); const answer = relation === '>=' ? `closed circle at ${p.x}, shaded right` : `closed circle at ${p.x}, shaded left`; const opposite = relation === '>=' ? `closed circle at ${p.x}, shaded left` : `closed circle at ${p.x}, shaded right`; return q('graph-inequality', difficulty, `Which graph describes x ${relation === '>=' ? '≥' : '≤'} ${p.x}?`, answer, { ...p, solution: p.x, relation }, [opposite, `open circle at ${p.x}, shaded right`, `open circle at ${p.x}, shaded left`, `closed circle at ${p.x + 1}, shaded right`]) }
export function generateCheckAndInterpretSolutionQuestion(difficulty: Difficulty) { const p = facts(difficulty); return q('check-and-interpret-solution', difficulty, `A club charges $${p.b} plus $${p.a} per session for a total of $${p.c}. How many sessions were purchased?`, String(p.x), { ...p, solution: p.x }, [String(p.x - 1), String(p.x + 1), String(p.c / p.a), String(p.c - p.b)]) }
export const GRADE7_MATH_UNIT4_GENERATORS = { 'multi-step-numerical-problem': generateMultiStepNumericalProblemQuestion, 'two-step-equation': generateTwoStepEquationQuestion, 'two-step-inequality': generateTwoStepInequalityQuestion, 'solution-set': generateSolutionSetQuestion, 'graph-inequality': generateGraphInequalityQuestion, 'check-and-interpret-solution': generateCheckAndInterpretSolutionQuestion } satisfies Record<Grade7MathUnit4ItemType, CurriculumGenerator<Grade7MathUnit4Question>>
export function generateGrade7MathUnit4Question<T extends Grade7MathUnit4ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade7MathUnit4Question, { itemType: T }> { return GRADE7_MATH_UNIT4_GENERATORS[itemType](difficulty) as Extract<Grade7MathUnit4Question, { itemType: T }> }
