import type { Difficulty } from '../types'
import { ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'
/** Coverage contract: Unit 7, course days 109-126, standards 5.NBT.3, 5.NBT.4, 5.NBT.7. Decimal values are scaled integers. */
export const GRADE5_MATH_UNIT7_ITEM_TYPES=['decimal-addition','decimal-subtraction','decimal-multiplication','decimal-division','money-measurement-context','decimal-estimation-check'] as const
export type Grade5MathUnit7ItemType=typeof GRADE5_MATH_UNIT7_ITEM_TYPES[number]
type P={a:bigint;b:bigint;scale:bigint;mode:string};type Q<T extends Grade5MathUnit7ItemType>=CurriculumQuestion<T,P>;export type Grade5MathUnit7Question={ [T in Grade5MathUnit7ItemType]:Q<T>}[Grade5MathUnit7ItemType]
type Def={standard:'5.NBT.3'|'5.NBT.4'|'5.NBT.7';lessonFocus:string;workedExample:CurriculumWorkedExample};const ex=(prompt:string,answer:string):CurriculumWorkedExample=>({prompt,answer,steps:['Align place values using a common power of ten.','Compute with whole-number scaled values, then place the decimal point.']})
export const GRADE5_MATH_UNIT7_ITEM_DEFINITIONS={
 'decimal-addition':{standard:'5.NBT.7',lessonFocus:'decimal addition',workedExample:ex('Find 2.35 + 1.4.','3.75')},'decimal-subtraction':{standard:'5.NBT.7',lessonFocus:'decimal subtraction',workedExample:ex('Find 5.2 - 1.35.','3.85')},'decimal-multiplication':{standard:'5.NBT.7',lessonFocus:'decimal multiplication',workedExample:ex('Find 1.2 × 3.','3.6')},'decimal-division':{standard:'5.NBT.7',lessonFocus:'decimal division',workedExample:ex('Find 4.8 ÷ 3.','1.6')},'money-measurement-context':{standard:'5.NBT.3',lessonFocus:'money and measurement contexts',workedExample:ex('Three notebooks cost $1.25 each. What is the cost?','$3.75')},'decimal-estimation-check':{standard:'5.NBT.4',lessonFocus:'operation estimation and checking',workedExample:ex('Estimate 4.7 + 3.2 by rounding to whole numbers.','8')},
} as const satisfies Record<Grade5MathUnit7ItemType,Def>
const fmt=(n:bigint,s:bigint):string=>{const neg=n<0n;if(neg)n=-n;const w=n/s,r=n%s;return `${neg?'-':''}${w}.${r.toString().padStart(s.toString().length-1,'0')}`.replace(/\.0+$/,'')};const q=(itemType:Grade5MathUnit7ItemType,difficulty:Difficulty,prompt:string,answer:string,parameters:P)=>{const money=itemType==='money-measurement-context';const pool=(money?['$0','$1','$2','$3','$4','$5']:['0','1','2','3','4','5','6']).filter(x=>x!==answer);return makeCurriculumQuestion({itemType,difficulty,prompt,correctAnswer:answer,distractors:pool,distractorMode:'distinct',parameters,...GRADE5_MATH_UNIT7_ITEM_DEFINITIONS[itemType]})}
const values=(d:Difficulty)=>({a:BigInt(ri(120,d===1?999:9999)),b:BigInt(ri(110,d===1?899:8999)),scale:100n})
export function generateDecimalAdditionQuestion(difficulty:Difficulty){const{a,b,scale}=values(difficulty);return q('decimal-addition',difficulty,`Find ${fmt(a,scale)} + ${fmt(b,scale)}.`,fmt(a+b,scale),{a,b,scale,mode:'add'})}
export function generateDecimalSubtractionQuestion(difficulty:Difficulty){let{a,b,scale}=values(difficulty);if(a<b)[a,b]=[b,a];return q('decimal-subtraction',difficulty,`Find ${fmt(a,scale)} - ${fmt(b,scale)}.`,fmt(a-b,scale),{a,b,scale,mode:'subtract'})}
export function generateDecimalMultiplicationQuestion(difficulty:Difficulty){const a=BigInt(ri(12,99)),b=BigInt(ri(2,difficulty+4)),scale=10n;return q('decimal-multiplication',difficulty,`Find ${a/scale}.${a%scale} × ${b}.`,fmt(a*b,scale),{a,b,scale,mode:'multiply'})}
export function generateDecimalDivisionQuestion(difficulty:Difficulty){const b=BigInt(ri(2,difficulty+4)),answer=BigInt(ri(12,99)),scale=10n,a=b*answer;return q('decimal-division',difficulty,`Find ${a/scale}.${a%scale} ÷ ${b}.`,fmt(answer,scale),{a,b,scale,mode:'divide'})}
export function generateMoneyMeasurementContextQuestion(difficulty:Difficulty){const a=BigInt(ri(125,999)),b=BigInt(ri(2,difficulty+4)),scale=100n;return q('money-measurement-context',difficulty,`${b} tickets cost $${fmt(a,scale)} each. What is the total cost?`, `$${fmt(a*b,scale)}`,{a,b,scale,mode:'money'})}
export function generateDecimalEstimationCheckQuestion(difficulty:Difficulty){const{a,b,scale}=values(difficulty);const r=(x:bigint)=>((x+50n)/100n)*100n;return q('decimal-estimation-check',difficulty,`Round each number to the nearest whole number to estimate ${fmt(a,scale)} + ${fmt(b,scale)}.`,fmt(r(a)+r(b),scale),{a,b,scale,mode:'estimate'})}
export const GRADE5_MATH_UNIT7_GENERATORS={'decimal-addition':generateDecimalAdditionQuestion,'decimal-subtraction':generateDecimalSubtractionQuestion,'decimal-multiplication':generateDecimalMultiplicationQuestion,'decimal-division':generateDecimalDivisionQuestion,'money-measurement-context':generateMoneyMeasurementContextQuestion,'decimal-estimation-check':generateDecimalEstimationCheckQuestion} satisfies Record<Grade5MathUnit7ItemType,CurriculumGenerator<Grade5MathUnit7Question>>
export function generateGrade5MathUnit7Question<T extends Grade5MathUnit7ItemType>(type:T,difficulty:Difficulty):Extract<Grade5MathUnit7Question,{itemType:T}>{return GRADE5_MATH_UNIT7_GENERATORS[type](difficulty) as Extract<Grade5MathUnit7Question,{itemType:T}>}
