import type { Difficulty } from '../types'
import { ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'
/** Grade 7 U1, days 1-18 (7.RP.1-2). Ratios remain integer numerator/denominator pairs and are reduced by Euclid; no floating point is used. */
export const GRADE7_MATH_UNIT1_ITEM_TYPES=['unit-rate-fraction','proportional-table','constant-of-proportionality','equation-from-rate','proportional-or-not','reasonableness'] as const
export type Grade7MathUnit1ItemType=typeof GRADE7_MATH_UNIT1_ITEM_TYPES[number];type P={a:number;b:number;c:number;proportional:boolean;kind:Grade7MathUnit1ItemType};export type Grade7MathUnit1Question=CurriculumQuestion<Grade7MathUnit1ItemType,P>
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);const f=(a:number,b:number)=>{const g=gcd(a,b);return b/g===1?String(a/g):`${a/g}/${b/g}`};const ex:CurriculumWorkedExample={prompt:'3/4 mile in 1/2 hour: unit rate?',answer:'3/2',steps:['Divide by the number of hours.','Reduce the resulting fraction.']}
const defs:Record<Grade7MathUnit1ItemType,{standard:'7.RP.1'|'7.RP.2';lessonFocus:string;workedExample:CurriculumWorkedExample}>={'unit-rate-fraction':{standard:'7.RP.1',lessonFocus:'unit rates with fractions',workedExample:ex},'proportional-table':{standard:'7.RP.2',lessonFocus:'proportional relationships',workedExample:ex},'constant-of-proportionality':{standard:'7.RP.2',lessonFocus:'constant of proportionality',workedExample:ex},'equation-from-rate':{standard:'7.RP.2',lessonFocus:'tables graphs and equations',workedExample:ex},'proportional-or-not':{standard:'7.RP.2',lessonFocus:'explaining whether a relationship is proportional',workedExample:ex},reasonableness:{standard:'7.RP.1',lessonFocus:'precision and reasonableness',workedExample:ex}}
const make=(kind:Grade7MathUnit1ItemType,difficulty:Difficulty):Grade7MathUnit1Question=>{const a=ri(2,6+difficulty),b=ri(2,6+difficulty),c=ri(2,6+difficulty),proportional=ri(0,1)===1;let correct:string,prompt:string,distractors:string[];if(kind==='unit-rate-fraction'){correct=`${f(a,b)} units per item`;prompt=`${a} units for ${b} items. What is the unit rate?`;distractors=[`${f(a+1,b)} units per item`,`${f(a,b+1)} units per item`,`${f(a+b,b)} units per item`,`${f(a+2,b)} units per item`]}else if(kind==='proportional-table'){correct=String(a*c);prompt=`A proportional table has ${a} per item. What is the output for ${c} items?`;distractors=[String(a*c+1),String(a*c-1),String(a+c),String(a*c+2)]}else if(kind==='constant-of-proportionality'){correct=f(a,b);prompt=`For y = kx, y = ${a} when x = ${b}. What is k?`;distractors=[f(a+1,b),f(a,b+1),f(a+b,b),f(a+2,b)]}else if(kind==='equation-from-rate'){correct=`y = ${a}x`;prompt=`A relationship has ${a} output units for each input unit. Write its equation.`;distractors=[`y = ${a+1}x`,`y = ${a+2}x`,`y = x + ${a}`,`y = ${a+3}x`]}else if(kind==='proportional-or-not'){correct=proportional?'proportional':'not proportional';prompt=proportional?`Are (1, ${a}), (2, ${2*a}), and (3, ${3*a}) proportional?`:`Are (1, ${a}), (2, ${2*a}), and (3, ${3*a+1}) proportional? The final ratio deliberately breaks the pattern.`;distractors=correct==='proportional'?['not proportional','cannot tell','neither','both']:['proportional','cannot tell','neither','both']}else{const claimed=a*c+(proportional?0:ri(1,4));correct=claimed===a*c?'yes':'no';prompt=`A price is ${a} dollars per item. Is ${claimed} dollars the exact total for ${c} items?`;distractors=correct==='yes'?['no','approximately','cannot tell','only if discounted']:['yes','approximately','cannot tell','only if discounted']}const d=defs[kind];return makeCurriculumQuestion({itemType:kind,standard:d.standard,lessonFocus:d.lessonFocus,difficulty,prompt,correctAnswer:correct,distractors,parameters:{a,b,c,proportional,kind},workedExample:d.workedExample,distractorMode:'distinct'})}
export const GRADE7_MATH_UNIT1_GENERATORS=Object.fromEntries(GRADE7_MATH_UNIT1_ITEM_TYPES.map(k=>[k,(d:Difficulty)=>make(k,d)])) as Record<Grade7MathUnit1ItemType,CurriculumGenerator<Grade7MathUnit1Question>>;export const generateGrade7MathUnit1Question=(itemType:Grade7MathUnit1ItemType,difficulty:Difficulty)=>GRADE7_MATH_UNIT1_GENERATORS[itemType](difficulty);export {defs as GRADE7_MATH_UNIT1_ITEM_DEFINITIONS}
