import type { Difficulty } from '../types'
import { ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Grade 7 U2, days 19-36 (7.NS.1-3). Every item has a negative operand; fractions retain signed numerators and positive denominators and use integer cross-products only. */
export const GRADE7_MATH_UNIT2_ITEM_TYPES = ['add-signed','subtract-signed','multiply-signed','divide-signed','signed-fractions','multi-step-rational'] as const
export type Grade7MathUnit2ItemType = typeof GRADE7_MATH_UNIT2_ITEM_TYPES[number]
type P={a:number;b:number;da:number;db:number;kind:Grade7MathUnit2ItemType}; export type Grade7MathUnit2Question=CurriculumQuestion<Grade7MathUnit2ItemType,P>
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);const f=(n:number,d:number)=>{const g=gcd(n,d);return d/g===1?String(n/g):`${n/g}/${d/g}`};const proper=(d:number)=>ri(1,d-1)
const example:CurriculumWorkedExample={prompt:'-5/6 + 1/4 = ?',answer:'-7/12',steps:['Use 12 as the common denominator.','-10/12 + 3/12 = -7/12.']}
const defs:Record<Grade7MathUnit2ItemType,{standard:'7.NS.1'|'7.NS.2'|'7.NS.3';lessonFocus:string;workedExample:CurriculumWorkedExample}>={'add-signed':{standard:'7.NS.1',lessonFocus:'adding signed numbers',workedExample:example},'subtract-signed':{standard:'7.NS.1',lessonFocus:'subtracting signed numbers',workedExample:example},'multiply-signed':{standard:'7.NS.2',lessonFocus:'multiplying signed numbers',workedExample:example},'divide-signed':{standard:'7.NS.2',lessonFocus:'dividing signed numbers',workedExample:example},'signed-fractions':{standard:'7.NS.3',lessonFocus:'fractions and decimals',workedExample:example},'multi-step-rational':{standard:'7.NS.3',lessonFocus:'multi-step rational-number problems',workedExample:example}}
const make=(kind:Grade7MathUnit2ItemType,difficulty:Difficulty):Grade7MathUnit2Question=>{const m=5+difficulty;let a=-ri(2,m+2),b=ri(1,m),da=ri(3,6+difficulty),db=ri(3,7+difficulty);if(db===da)db=db===7+difficulty?3:db+1;let n:number,d=1,prompt:string
 if(kind==='add-signed'){if(difficulty>1)b=ri(1,Math.abs(a)-1);n=a+b;prompt=`${a} + ${b} = ?`}else if(kind==='subtract-signed'){b=ri(1,m);n=a-b;prompt=`${a} - ${b} = ?`}else if(kind==='multiply-signed'){n=a*b;prompt=`${a} * ${b} = ?`}else if(kind==='divide-signed'){b=ri(2,m);a=-b*ri(2,m);n=a/b;prompt=`${a} / ${b} = ?`}else if(kind==='signed-fractions'){let na=-proper(da),nb=proper(db);if(difficulty>1){if(db<=da)db=da+1;na=-proper(da);const maxPositiveNumerator=Math.floor(((-na)*db-1)/da);nb=ri(1,maxPositiveNumerator)}n=na*db+nb*da;d=da*db;a=na;b=nb;prompt=`${na}/${da} + ${nb}/${db} = ?`}else {b=ri(2,m);const c=ri(2,m);n=a+b*c;prompt=`${a} + (${b} * ${c}) = ?`;db=c}
 const correct=f(n,d),definition=defs[kind], distractors=[f(n+d,d),f(n-d,d),f(-n,d),f(n+2*d,d)]
 return makeCurriculumQuestion({itemType:kind,standard:definition.standard,lessonFocus:definition.lessonFocus,difficulty,prompt,correctAnswer:correct,distractors,parameters:{a,b,da,db,kind},workedExample:definition.workedExample,distractorMode:'distinct'})}
export const GRADE7_MATH_UNIT2_GENERATORS=Object.fromEntries(GRADE7_MATH_UNIT2_ITEM_TYPES.map(k=>[k,(d:Difficulty)=>make(k,d)])) as Record<Grade7MathUnit2ItemType,CurriculumGenerator<Grade7MathUnit2Question>>
export const generateGrade7MathUnit2Question=(itemType:Grade7MathUnit2ItemType,difficulty:Difficulty)=>GRADE7_MATH_UNIT2_GENERATORS[itemType](difficulty);export {defs as GRADE7_MATH_UNIT2_ITEM_DEFINITIONS}
