import type { Difficulty } from '../types'
import { makeFinLitQuestion, money, pick, type CurriculumGenerator, type FinLitQuestion } from './grade8FinLitCore'
export const GRADE8_FINLIT_UNIT9_ITEM_TYPES=['total-cost-comparison'] as const
export type Grade8FinLitUnit9ItemType=typeof GRADE8_FINLIT_UNIT9_ITEM_TYPES[number]
export interface Grade8FinLitUnit9Parameters { unitACents: bigint; quantityA: bigint; unitBCents: bigint; quantityB: bigint }
export type Grade8FinLitUnit9Question=FinLitQuestion<'total-cost-comparison',Grade8FinLitUnit9Parameters>
const definition={standard:'FL.8.B',lessonFocus:'comparing total costs',workedExample:{prompt:'Three items cost $4.00 each; two other items cost $5.00 each. Which total is lower?',answer:'The first total, $12.00',steps:['Find each total: 3 × $4.00 = $12.00 and 2 × $5.00 = $10.00.','Actually $10.00 is lower, so compare multiplication carefully.']}} as const
export function generateTotalCostComparisonQuestion(difficulty:Difficulty):Grade8FinLitUnit9Question {const p=pick([{quantityA:3n,unitACents:400n,quantityB:2n,unitBCents:650n},{quantityA:4n,unitACents:350n,quantityB:3n,unitBCents:500n},{quantityA:5n,unitACents:275n,quantityB:2n,unitBCents:700n}] as const);const totalA=p.quantityA*p.unitACents,totalB=p.quantityB*p.unitBCents;const answer=totalA<totalB?`Option A, ${money(totalA)}`:`Option B, ${money(totalB)}`;return makeFinLitQuestion({itemType:'total-cost-comparison',difficulty,prompt:`Option A costs ${money(p.unitACents)} each for ${p.quantityA} items. Option B costs ${money(p.unitBCents)} each for ${p.quantityB} items. Which option has the lower total cost?`,correctAnswer:answer,distractors:[`Option A, ${money(totalA)}`,`Option B, ${money(totalB)}`,`Option A, ${money(totalB)}`,`Option B, ${money(totalA)}`].filter(x=>x!==answer),parameters:p,definition})}
export const GRADE8_FINLIT_UNIT9_GENERATORS={'total-cost-comparison':generateTotalCostComparisonQuestion} satisfies Record<Grade8FinLitUnit9ItemType,CurriculumGenerator<Grade8FinLitUnit9Question>>
export const generateGrade8FinLitUnit9Question=generateTotalCostComparisonQuestion
