import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Unit 9: Pythagorean theorem and coordinate-plane distance (8.G.6–8). */
export const GRADE8_MATH_UNIT9_ITEM_TYPES = ['find-hypotenuse', 'find-missing-leg', 'classify-by-side-lengths', 'distance-on-grid', 'pythagorean-converse', 'right-triangle-context', 'irrational-distance-estimate', 'coordinate-distance', 'choose-pythagorean-triple', 'analyze-pythagorean-error'] as const
export type Grade8MathUnit9ItemType = (typeof GRADE8_MATH_UNIT9_ITEM_TYPES)[number]

type P = { a: number; b: number; c: number; x?: number; y?: number; mode?: 'right' | 'acute' | 'obtuse' }
type Q<T extends Grade8MathUnit9ItemType> = CurriculumQuestion<T, P>
export type Grade8MathUnit9Question = { [T in Grade8MathUnit9ItemType]: Q<T> }[Grade8MathUnit9ItemType]

const triples: readonly P[] = [{ a: 3, b: 4, c: 5 }, { a: 5, b: 12, c: 13 }, { a: 6, b: 8, c: 10 }, { a: 8, b: 15, c: 17 }, { a: 7, b: 24, c: 25 }, { a: 9, b: 12, c: 15 }]
const example = (prompt: string, answer: string, steps: readonly string[]): CurriculumWorkedExample => ({ prompt, answer, steps })
const definitions: Record<Grade8MathUnit9ItemType, { standard: string; lessonFocus: string; workedExample: CurriculumWorkedExample }> = {
  'find-hypotenuse': { standard: '8.G.6', lessonFocus: 'Pythagorean theorem', workedExample: example('A right triangle has legs 6 and 8. Find its hypotenuse.', '10', ['Use a² + b² = c².', '6² + 8² = 36 + 64 = 100.', 'c = √100 = 10.']) },
  'find-missing-leg': { standard: '8.G.6', lessonFocus: 'Pythagorean theorem', workedExample: example('A right triangle has hypotenuse 13 and one leg 5. Find the other leg.', '12', ['Use a² + b² = c².', 'b² = 13² - 5² = 144.', 'b = 12.']) },
  'classify-by-side-lengths': { standard: '8.G.6', lessonFocus: 'classifying triangles', workedExample: example('Classify sides 6, 8, and 10.', 'right', ['6² + 8² = 100.', '10² = 100.', 'The sums are equal, so the triangle is right.']) },
  'distance-on-grid': { standard: '8.G.8', lessonFocus: 'distance in the coordinate plane', workedExample: example('Two points differ by 9 horizontally and 12 vertically. Find their distance.', '15', ['Draw a right triangle with legs 9 and 12.', '9² + 12² = 225.', 'The distance is √225 = 15.']) },
  'pythagorean-converse': { standard: '8.G.6', lessonFocus: 'converse of Pythagorean theorem', workedExample: example('Do sides 5, 12, and 13 form a right triangle?', 'yes', ['5² + 12² = 25 + 144 = 169.', '13² = 169.', 'The values match, so yes.']) },
  'right-triangle-context': { standard: '8.G.7', lessonFocus: 'real-world Pythagorean theorem', workedExample: example('A 15-foot ladder has its base 9 feet from a wall. How high does it reach?', '12 feet', ['The wall, ground, and ladder form a right triangle.', 'h² = 15² - 9² = 144.', 'h = 12 feet.']) },
  'irrational-distance-estimate': { standard: '8.G.7', lessonFocus: 'irrational square roots', workedExample: example('Estimate √20 to the nearest tenth.', '4.5', ['4² = 16 and 5² = 25.', '√20 is between 4 and 5.', '√20 ≈ 4.5.']) },
  'coordinate-distance': { standard: '8.G.8', lessonFocus: 'coordinate-plane distance', workedExample: example('Find the distance from (1, 2) to (4, 6).', '5', ['The horizontal and vertical changes are 3 and 4.', '3² + 4² = 25.', 'The distance is 5.']) },
  'choose-pythagorean-triple': { standard: '8.G.6', lessonFocus: 'Pythagorean triples', workedExample: example('Which set is a Pythagorean triple?', '8, 15, 17', ['Check the largest number as c.', '8² + 15² = 64 + 225 = 289.', '17² = 289.']) },
  'analyze-pythagorean-error': { standard: '8.G.6', lessonFocus: 'reasoning with the theorem', workedExample: example('A student says 3² + 4² = 7². Analyze the claim.', 'The claim is incorrect; 3² + 4² = 5².', ['3² + 4² = 9 + 16 = 25.', '7² = 49, not 25.', 'Since 5² = 25, the hypotenuse is 5.']) },
}

function q<T extends Grade8MathUnit9ItemType>(itemType: T, difficulty: Difficulty, prompt: string, answer: string, distractors: string[], parameters: P): Q<T> {
  const d = definitions[itemType]
  return makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, parameters, standard: d.standard, lessonFocus: d.lessonFocus, workedExample: d.workedExample, distractorMode: 'distinct' })
}
function triple(difficulty: Difficulty): P { return pick(triples.slice(0, difficulty === 1 ? 3 : triples.length)) }
export function generateFindHypotenuseQuestion(difficulty: Difficulty): Q<'find-hypotenuse'> { const p = triple(difficulty); return q('find-hypotenuse', difficulty, `A right triangle has legs ${p.a} and ${p.b}. What is the length of the hypotenuse?`, String(p.c), [String(p.a + p.b), String(p.c + 1), String(p.c - 1)], p) }
export function generateFindMissingLegQuestion(difficulty: Difficulty): Q<'find-missing-leg'> { const p = triple(difficulty); return q('find-missing-leg', difficulty, `A right triangle has a hypotenuse of ${p.c} and one leg of ${p.a}. What is the other leg?`, String(p.b), [String(p.c - p.a), String(p.a + p.b), String(p.b + 2)], p) }
export function generateClassifyBySideLengthsQuestion(difficulty: Difficulty): Q<'classify-by-side-lengths'> { const p = triple(difficulty); const mode = pick(['right', 'acute', 'obtuse'] as const); const c = mode === 'right' ? p.c : mode === 'acute' ? p.c - 1 : p.c + 1; return q('classify-by-side-lengths', difficulty, `Classify a triangle with side lengths ${p.a}, ${p.b}, and ${c}.`, mode, [...['right', 'acute', 'obtuse'].filter(x => x !== mode), 'not a triangle'], { ...p, c, mode }) }
export function generateDistanceOnGridQuestion(difficulty: Difficulty): Q<'distance-on-grid'> { const p = triple(difficulty); return q('distance-on-grid', difficulty, `Two points are ${p.a} units apart horizontally and ${p.b} units apart vertically. What is the distance between them?`, String(p.c), [String(p.a + p.b), String(p.c - 2), String(p.c + 3)], p) }
export function generatePythagoreanConverseQuestion(difficulty: Difficulty): Q<'pythagorean-converse'> { const p = triple(difficulty); const yes = ri(0, 1) === 1; const c = yes ? p.c : p.c + pick([-1, 1] as const); return q('pythagorean-converse', difficulty, `Do side lengths ${p.a}, ${p.b}, and ${c} form a right triangle?`, yes ? 'yes' : 'no', [yes ? 'no' : 'yes', 'only if isosceles', 'not enough information'], { ...p, c }) }
export function generateRightTriangleContextQuestion(difficulty: Difficulty): Q<'right-triangle-context'> { const p = triple(difficulty); return q('right-triangle-context', difficulty, `A ladder is ${p.c} feet long and its base is ${p.a} feet from a wall. How high up the wall does it reach?`, `${p.b} feet`, [`${p.a + p.b} feet`, `${p.c - p.a} feet`, `${p.c} feet`], p) }
export function generateIrrationalDistanceEstimateQuestion(difficulty: Difficulty): Q<'irrational-distance-estimate'> { const n = pick([2, 5, 10, 13, 20, 29, 50] as const); const answer = Math.sqrt(n).toFixed(1); return q('irrational-distance-estimate', difficulty, `Estimate √${n} to the nearest tenth.`, answer, [(Number(answer) - .2).toFixed(1), (Number(answer) + .2).toFixed(1), String(Math.round(Math.sqrt(n)))], { a: n, b: 0, c: 0 }) }
export function generateCoordinateDistanceQuestion(difficulty: Difficulty): Q<'coordinate-distance'> { const p = triple(difficulty); const x = ri(-8, 4), y = ri(-8, 4); return q('coordinate-distance', difficulty, `Find the distance between (${x}, ${y}) and (${x + p.a}, ${y + p.b}).`, String(p.c), [String(p.a + p.b), String(p.c + 1), String(p.c - 1)], { ...p, x, y }) }
export function generateChoosePythagoreanTripleQuestion(difficulty: Difficulty): Q<'choose-pythagorean-triple'> { const p = triple(difficulty); return q('choose-pythagorean-triple', difficulty, 'Which set of side lengths is a Pythagorean triple?', `${p.a}, ${p.b}, ${p.c}`, [`${p.a}, ${p.b}, ${p.c + 1}`, `${p.a}, ${p.b + 1}, ${p.c}`, `${p.a + 1}, ${p.b}, ${p.c}`], p) }
export function generateAnalyzePythagoreanErrorQuestion(difficulty: Difficulty): Q<'analyze-pythagorean-error'> { const p = triple(difficulty); return q('analyze-pythagorean-error', difficulty, `A student says ${p.a}² + ${p.b}² = ${p.a + p.b}². Which statement best analyzes the error?`, `The claim is incorrect; ${p.a}² + ${p.b}² = ${p.c}².`, [`The claim is correct; the hypotenuse is ${p.a + p.b}.`, `The legs should be multiplied, so the hypotenuse is ${p.a * p.b}.`, 'The theorem applies only to equilateral triangles.'], p) }
export const GRADE8_MATH_UNIT9_GENERATORS = { 'find-hypotenuse': generateFindHypotenuseQuestion, 'find-missing-leg': generateFindMissingLegQuestion, 'classify-by-side-lengths': generateClassifyBySideLengthsQuestion, 'distance-on-grid': generateDistanceOnGridQuestion, 'pythagorean-converse': generatePythagoreanConverseQuestion, 'right-triangle-context': generateRightTriangleContextQuestion, 'irrational-distance-estimate': generateIrrationalDistanceEstimateQuestion, 'coordinate-distance': generateCoordinateDistanceQuestion, 'choose-pythagorean-triple': generateChoosePythagoreanTripleQuestion, 'analyze-pythagorean-error': generateAnalyzePythagoreanErrorQuestion } satisfies Record<Grade8MathUnit9ItemType, CurriculumGenerator<Grade8MathUnit9Question>>
export function generateGrade8MathUnit9Question<T extends Grade8MathUnit9ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade8MathUnit9Question, { itemType: T }> { return GRADE8_MATH_UNIT9_GENERATORS[itemType](difficulty) as Extract<Grade8MathUnit9Question, { itemType: T }> }
