import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source coverage: Grade 7 Mathematics Unit 10 "Integrated Modeling and Capstone" (days 163-180), 7.RP.3, 7.NS.3, 7.EE.4, 7.G.6, 7.SP.4, MP.4. */
export const GRADE7_MATH_UNIT10_ITEM_TYPES = ['problem-formulation', 'assumptions-and-constraints', 'proportional-and-algebraic-models', 'geometry-and-measurement', 'data-and-uncertainty', 'argument-and-presentation'] as const
export type Grade7MathUnit10ItemType = typeof GRADE7_MATH_UNIT10_ITEM_TYPES[number]
type Params = { a?: number; b?: number; c?: number; solution?: number; values?: number[]; mad?: number; meanA?: number }
type Q<T extends Grade7MathUnit10ItemType> = CurriculumQuestion<T, Params>
export type Grade7MathUnit10Question = { [T in Grade7MathUnit10ItemType]: Q<T> }[Grade7MathUnit10ItemType]
type Def = { standard: '7.RP.3' | '7.NS.3' | '7.EE.4' | '7.G.6' | '7.SP.4' | 'MP.4'; lessonFocus: string; workedExample: CurriculumWorkedExample }
const example = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Identify what the problem is asking and which quantities, assumptions, or constraints matter.', 'Build and solve a model, then check the result against the context.'] })
export const GRADE7_MATH_UNIT10_ITEM_DEFINITIONS = {
  'problem-formulation': { standard: '7.EE.4', lessonFocus: 'problem formulation', workedExample: example('A rental charges a $10 base fee plus $5 per hour, totaling $35. Which equation models this, and how many hours were rented?', '5x + 10 = 35; x = 5') },
  'assumptions-and-constraints': { standard: '7.NS.3', lessonFocus: 'assumptions and constraints', workedExample: example('A diver descends 8 m, then descends 4 m more, then ascends 5 m. What is the diver\'s final position?', '-7') },
  'proportional-and-algebraic-models': { standard: '7.RP.3', lessonFocus: 'proportional and algebraic models', workedExample: example('A model predicts a $80 rate will increase by 25%. What is the new rate?', '$100') },
  'geometry-and-measurement': { standard: '7.G.6', lessonFocus: 'geometry and measurement', workedExample: example('A storage container is 4 by 3 by 2 feet. What is its volume in cubic feet?', '24') },
  'data-and-uncertainty': { standard: '7.SP.4', lessonFocus: 'data and uncertainty', workedExample: example('A data set is 10, 15, 20, 25, 30. The mean is 20. What is the mean absolute deviation?', '6') },
  'argument-and-presentation': { standard: 'MP.4', lessonFocus: 'argument and presentation', workedExample: example('A student claims a 4 by 3 by 2 box has a volume of 9 cubic units. Evaluate the claim.', 'No; the volume is 24 cubic units, not 9.') },
} as const satisfies Record<Grade7MathUnit10ItemType, Def>
const q = (itemType: Grade7MathUnit10ItemType, difficulty: Difficulty, prompt: string, answer: string, parameters: Params, distractors: string[]) => makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, distractorMode: 'distinct', parameters, ...GRADE7_MATH_UNIT10_ITEM_DEFINITIONS[itemType] })
const dollars = (value: number) => `$${value.toFixed(2).replace(/\.00$/, '')}`
export function generateProblemFormulationQuestion(difficulty: Difficulty) { const a = ri(2, difficulty + 5); const x = ri(2, difficulty * 4 + 5); const b = ri(1, difficulty * 5 + 6); const c = a * x + b; const answer = `${a}x + ${b} = ${c}; x = ${x}`; return q('problem-formulation', difficulty, `A rental company charges a $${b} base fee plus $${a} per hour. A customer's total bill was $${c}. Which equation models this situation, and how many hours were rented?`, answer, { a, b, c, solution: x }, [`${a}x + ${b} = ${c}; x = ${x - 1}`, `${a}x - ${b} = ${c}; x = ${x + 1}`, `${a}x + ${b} = ${c}; x = ${x + 1}`, `${b}x + ${a} = ${c}; x = ${x + 2}`]) }
export function generateAssumptionsAndConstraintsQuestion(difficulty: Difficulty) { const descend1 = ri(3, difficulty * 8 + 10); const descend2 = ri(2, difficulty * 6 + 8); const ascend = ri(2, difficulty * 8 + 10); const limit = descend1 + descend2 + ri(5, 20); const answer = -(descend1 + descend2) + ascend; return q('assumptions-and-constraints', difficulty, `A diver starts at the surface (0 m) and descends ${descend1} m, then descends another ${descend2} m, then ascends ${ascend} m. The dive plan assumes a depth limit of ${limit} m below the surface. What is the diver's final position, as a signed number of meters?`, String(answer), { a: descend1, b: descend2, c: ascend, solution: answer }, [String(-(descend1 + descend2) - ascend), String(descend1 + descend2 + ascend), String(descend1 - descend2 + ascend), String(-(descend1 + descend2) + 2 * ascend)]) }
export function generateProportionalAndAlgebraicModelsQuestion(difficulty: Difficulty) { const amount = ri(4, difficulty * 10 + 25) * 20; const percent = pick([5, 10, 20, 25] as const); const increase = pick([true, false] as const); const answer = amount * (increase ? 1 + percent / 100 : 1 - percent / 100); return q('proportional-and-algebraic-models', difficulty, `A model predicts a $${amount} rate will ${increase ? 'increase' : 'decrease'} by ${percent}%. What does the model predict as the new rate?`, dollars(answer), { a: amount, b: percent }, [dollars(amount * (increase ? 1 - percent / 100 : 1 + percent / 100)), dollars(amount * percent / 100), dollars(amount + percent), dollars(amount)]) }
export function generateGeometryAndMeasurementQuestion(difficulty: Difficulty) { const l = ri(2, difficulty * 3 + 5); const w = ri(2, difficulty * 3 + 4); const h = ri(2, difficulty * 3 + 3); const volume = l * w * h; const surfaceArea = 2 * (l * w + l * h + w * h); return q('geometry-and-measurement', difficulty, `A storage container is designed as a rectangular prism ${l} ft long, ${w} ft wide, and ${h} ft high. What is its volume in cubic feet?`, String(volume), { a: l, b: w, c: h, solution: volume }, [String(surfaceArea), String(l * w), String(volume + l), String(volume - h)]) }
export function generateDataAndUncertaintyQuestion(difficulty: Difficulty) { const mean = ri(30, difficulty * 15 + 40); const kMax = Math.max(1, Math.min(difficulty + 2, Math.floor(mean / 10))); const k = ri(1, kMax); const d = 5 * k; const values = [mean - 2 * d, mean - d, mean, mean + d, mean + 2 * d]; const answer = 6 * k; return q('data-and-uncertainty', difficulty, `A data set has the values ${values.join(', ')}. The mean is ${mean}. What is the mean absolute deviation (MAD), a measure of the data's uncertainty or spread?`, String(answer), { values, mad: answer, meanA: mean }, [String(answer + k), String(answer - k), String(2 * d), String(k)]) }
export function generateArgumentAndPresentationQuestion(difficulty: Difficulty) { const l = ri(2, 8); const w = ri(2, 8); const h = ri(2, 8); const correctVolume = l * w * h; const claim = pick([l + w + h, l * w, correctVolume + ri(1, 10)] as const); const answer = `No; the volume is ${correctVolume} cubic units, not ${claim}.`; return q('argument-and-presentation', difficulty, `A student claims a box that is ${l} by ${w} by ${h} units has a volume of ${claim} cubic units. Evaluate the claim.`, answer, { a: l, b: w, c: h, solution: correctVolume }, [`Yes; the volume is ${claim} cubic units.`, `No; the volume is ${claim + 1} cubic units, not ${claim}.`, `No; the volume is ${claim + 2} cubic units, not ${claim}.`, 'Cannot be determined from the given information.']) }
export const GRADE7_MATH_UNIT10_GENERATORS = { 'problem-formulation': generateProblemFormulationQuestion, 'assumptions-and-constraints': generateAssumptionsAndConstraintsQuestion, 'proportional-and-algebraic-models': generateProportionalAndAlgebraicModelsQuestion, 'geometry-and-measurement': generateGeometryAndMeasurementQuestion, 'data-and-uncertainty': generateDataAndUncertaintyQuestion, 'argument-and-presentation': generateArgumentAndPresentationQuestion } satisfies Record<Grade7MathUnit10ItemType, CurriculumGenerator<Grade7MathUnit10Question>>
export function generateGrade7MathUnit10Question<T extends Grade7MathUnit10ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade7MathUnit10Question, { itemType: T }> { return GRADE7_MATH_UNIT10_GENERATORS[itemType](difficulty) as Extract<Grade7MathUnit10Question, { itemType: T }> }
