import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source: Unit 9, Volume and Bivariate Data (8.G.9; 8.SP.1–4). Volumes are exact rational multiples of π. */
export const GRADE8_MATH_UNIT9_ITEM_TYPES = ['cylinder-volume', 'cone-volume', 'sphere-volume', 'compare-solid-volumes', 'identify-scatter-association', 'identify-outlier', 'line-of-fit-prediction', 'interpolation-or-extrapolation', 'two-way-table-relative-frequency', 'correlation-versus-causation'] as const
export type Grade8MathUnit9ItemType = (typeof GRADE8_MATH_UNIT9_ITEM_TYPES)[number]
type P = { r: number; h: number; slope?: number; intercept?: number; x?: number; y?: number; numerator?: number; denominator?: number; association?: 'positive' | 'negative' | 'none' }
type Q<T extends Grade8MathUnit9ItemType> = CurriculumQuestion<T, P>
export type Grade8MathUnit9Question = { [T in Grade8MathUnit9ItemType]: Q<T> }[Grade8MathUnit9ItemType]
const worked = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Identify the quantities and the applicable model.', 'Compute using the stated relationship.', 'Check that the result answers the question.'] })
const d: Record<Grade8MathUnit9ItemType, { standard: string; lessonFocus: string; workedExample: CurriculumWorkedExample }> = {
  'cylinder-volume': { standard: '8.G.9', lessonFocus: 'volume of cylinders cones and spheres', workedExample: worked('Find the volume of a cylinder with radius 3 and height 5.', '45π cubic units') },
  'cone-volume': { standard: '8.G.9', lessonFocus: 'volume of cylinders cones and spheres', workedExample: worked('Find the volume of a cone with radius 3 and height 12.', '36π cubic units') },
  'sphere-volume': { standard: '8.G.9', lessonFocus: 'volume of cylinders cones and spheres', workedExample: worked('Find the volume of a sphere with radius 3.', '36π cubic units') },
  'compare-solid-volumes': { standard: '8.G.9', lessonFocus: 'volume of cylinders cones and spheres', workedExample: worked('A cylinder and cone have the same radius and height. Which has greater volume?', 'the cylinder') },
  'identify-scatter-association': { standard: '8.SP.1', lessonFocus: 'scatter plots', workedExample: worked('As x increases, y generally increases. Identify the association.', 'positive') },
  'identify-outlier': { standard: '8.SP.1', lessonFocus: 'association and outliers', workedExample: worked('Which point far from the overall pattern is an outlier?', '(8, 30)') },
  'line-of-fit-prediction': { standard: '8.SP.2', lessonFocus: 'lines of fit', workedExample: worked('A line of fit is y = 3x + 2. Predict y for x = 4.', '14') },
  'interpolation-or-extrapolation': { standard: '8.SP.2', lessonFocus: 'lines of fit', workedExample: worked('Data use x-values 2 through 10. Predicting at x = 6 is what?', 'interpolation') },
  'two-way-table-relative-frequency': { standard: '8.SP.4', lessonFocus: 'two-way tables', workedExample: worked('18 of 30 students prefer reading. Find the relative frequency.', '3/5') },
  'correlation-versus-causation': { standard: '8.SP.3', lessonFocus: 'correlation versus causation', workedExample: worked('Ice-cream sales and sunburn reports rise together. What can be concluded?', 'They are correlated; this alone does not prove causation.') },
}
function ask<T extends Grade8MathUnit9ItemType>(itemType: T, difficulty: Difficulty, prompt: string, answer: string, distractors: string[], parameters: P): Q<T> { const x=d[itemType]; return makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, parameters, standard:x.standard, lessonFocus:x.lessonFocus, workedExample:x.workedExample, distractorMode:'distinct' }) }
const volume=(n:number)=>`${n}π cubic units`; const dims=(difficulty:Difficulty)=>({ r:pick(difficulty===1?[2,3,4] as const:[2,3,4,5,6] as const), h:ri(1, difficulty===1?4:7)*3 })
export function generateCylinderVolumeQuestion(difficulty:Difficulty):Q<'cylinder-volume'>{const p=dims(difficulty),n=p.r*p.r*p.h;return ask('cylinder-volume',difficulty,`Find the exact volume of a cylinder with radius ${p.r} units and height ${p.h} units. Express your answer as a rational multiple of π.`,volume(n),[volume(n/3),volume(n+p.r),volume(n*2)],p)}
export function generateConeVolumeQuestion(difficulty:Difficulty):Q<'cone-volume'>{const p=dims(difficulty),n=p.r*p.r*p.h/3;return ask('cone-volume',difficulty,`Find the exact volume of a cone with radius ${p.r} units and height ${p.h} units. Express your answer as a rational multiple of π.`,volume(n),[volume(n*3),volume(n+p.r),volume(n/2)],p)}
export function generateSphereVolumeQuestion(difficulty:Difficulty):Q<'sphere-volume'>{const r=pick([3,6,9] as const),n=4*r**3/3;return ask('sphere-volume',difficulty,`Find the exact volume of a sphere with radius ${r} units. Express your answer as a rational multiple of π.`,volume(n),[volume(n/4),volume(n*3/4),volume(n*3)],{r,h:0})}
export function generateCompareSolidVolumesQuestion(difficulty:Difficulty):Q<'compare-solid-volumes'>{const p=dims(difficulty);return ask('compare-solid-volumes',difficulty,`A cylinder and cone each have radius ${p.r} units and height ${p.h} units. Which has the greater volume?`,'the cylinder',['the cone','they have equal volume','not enough information'],p)}
export function generateIdentifyScatterAssociationQuestion(difficulty:Difficulty):Q<'identify-scatter-association'>{const association=pick(['positive','negative','none'] as const),text=association==='positive'?'As x increases, y generally increases.':association==='negative'?'As x increases, y generally decreases.':'As x increases, y shows no consistent change.';return ask('identify-scatter-association',difficulty,`${text} What association does this scatter plot describe?`,association,[...['positive','negative','none'].filter(x=>x!==association),'causation'],{r:0,h:0,association})}
export function generateIdentifyOutlierQuestion(difficulty:Difficulty):Q<'identify-outlier'>{const x=ri(6,12),y=2*x+1+pick([10,12,15] as const),points=[`(${x}, ${2*x+1})`,`(${x+1}, ${2*(x+1)+1})`,`(${x-1}, ${2*(x-1)+1})`,`(${x}, ${y})`];return ask('identify-outlier',difficulty,`Most plotted points follow y = 2x + 1. Of these points, ${points.join(', ')}, which point is an outlier?`,`(${x}, ${y})`,points.filter(point=>point!==`(${x}, ${y})`),{r:0,h:0,x,y})}
export function generateLineOfFitPredictionQuestion(difficulty:Difficulty):Q<'line-of-fit-prediction'>{const slope=ri(1,difficulty===1?5:9),intercept=ri(-5,10),x=ri(2,10),y=slope*x+intercept;return ask('line-of-fit-prediction',difficulty,`A line of fit is y = ${slope}x ${intercept>=0?'+':'-'} ${Math.abs(intercept)}. Predict y when x = ${x}.`,String(y),[String(y+slope+1),String(y-slope-1),String(y+2*slope+1)],{r:0,h:0,slope,intercept,x})}
export function generateInterpolationOrExtrapolationQuestion(difficulty:Difficulty):Q<'interpolation-or-extrapolation'>{const r=ri(1,4),h=r+ri(6,12),inside=ri(0,1)===1,x=inside?ri(r+1,h-1):h+ri(2,8),answer=inside?'interpolation':'extrapolation';return ask('interpolation-or-extrapolation',difficulty,`A data set has x-values from ${r} through ${h}. A prediction is made at x = ${x}. Is this interpolation or extrapolation?`,answer,[answer==='interpolation'?'extrapolation':'interpolation','causation','a census'],{r,h,x})}
export function generateTwoWayTableRelativeFrequencyQuestion(difficulty:Difficulty):Q<'two-way-table-relative-frequency'>{const denominator=pick([20,25,30,40,50] as const),n=pick([1,2,3,4] as const),numerator=n*denominator/5;return ask('two-way-table-relative-frequency',difficulty,`In a survey, ${numerator} of ${denominator} students chose option A. What is the relative frequency for option A?`,`${n}/5`,[`${5-n}/5`,`${numerator}/${denominator}`,`${n+2}/5`],{r:0,h:0,numerator,denominator})}
export function generateCorrelationVersusCausationQuestion(difficulty:Difficulty):Q<'correlation-versus-causation'>{return ask('correlation-versus-causation',difficulty,'Umbrella sales and rainy-day traffic delays are correlated. Which conclusion is justified?','They are correlated; this alone does not prove causation.',['Umbrella sales cause traffic delays.','Traffic delays cause umbrella sales.','There is no relationship at all.'],{r:0,h:0})}
export const GRADE8_MATH_UNIT9_GENERATORS={'cylinder-volume':generateCylinderVolumeQuestion,'cone-volume':generateConeVolumeQuestion,'sphere-volume':generateSphereVolumeQuestion,'compare-solid-volumes':generateCompareSolidVolumesQuestion,'identify-scatter-association':generateIdentifyScatterAssociationQuestion,'identify-outlier':generateIdentifyOutlierQuestion,'line-of-fit-prediction':generateLineOfFitPredictionQuestion,'interpolation-or-extrapolation':generateInterpolationOrExtrapolationQuestion,'two-way-table-relative-frequency':generateTwoWayTableRelativeFrequencyQuestion,'correlation-versus-causation':generateCorrelationVersusCausationQuestion} satisfies Record<Grade8MathUnit9ItemType,CurriculumGenerator<Grade8MathUnit9Question>>
export function generateGrade8MathUnit9Question<T extends Grade8MathUnit9ItemType>(itemType:T,difficulty:Difficulty):Extract<Grade8MathUnit9Question,{itemType:T}>{return GRADE8_MATH_UNIT9_GENERATORS[itemType](difficulty) as Extract<Grade8MathUnit9Question,{itemType:T}>}
