import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source coverage: Grade 7 Mathematics Unit 5 (days 73-90), 7.RP.3 and 7.EE.3. */
export const GRADE7_MATH_UNIT5_ITEM_TYPES = ['percent-increase-decrease', 'discount-markup', 'tax-tip', 'simple-interest', 'percent-error', 'multi-step-percent-problem'] as const
export type Grade7MathUnit5ItemType = typeof GRADE7_MATH_UNIT5_ITEM_TYPES[number]
type Params = { amount: number; percent: number; secondPercent: number; years: number; actual?: number; measured?: number }
type Q<T extends Grade7MathUnit5ItemType> = CurriculumQuestion<T, Params>
export type Grade7MathUnit5Question = { [T in Grade7MathUnit5ItemType]: Q<T> }[Grade7MathUnit5ItemType]
type Def = { standard: '7.RP.3' | '7.EE.3'; lessonFocus: string; workedExample: CurriculumWorkedExample }
const example = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Convert the percent to a decimal or fraction.', 'Apply the percent to the appropriate base amount and state the result with units.'] })
export const GRADE7_MATH_UNIT5_ITEM_DEFINITIONS = {
  'percent-increase-decrease': { standard: '7.RP.3', lessonFocus: 'percent increase and decrease', workedExample: example('Increase $80 by 25%.', '$100') },
  'discount-markup': { standard: '7.RP.3', lessonFocus: 'discounts and markups', workedExample: example('A $60 item is discounted 20%. What is the sale price?', '$48') },
  'tax-tip': { standard: '7.RP.3', lessonFocus: 'tax and tip', workedExample: example('Find a 15% tip on $40.', '$6') },
  'simple-interest': { standard: '7.RP.3', lessonFocus: 'simple interest', workedExample: example('Find simple interest on $200 at 5% for 3 years.', '$30') },
  'percent-error': { standard: '7.EE.3', lessonFocus: 'percent error', workedExample: example('Actual length is 50 cm and measured length is 55 cm. Find percent error.', '10%') },
  'multi-step-percent-problem': { standard: '7.EE.3', lessonFocus: 'multi-step percent problems', workedExample: example('A $100 item is discounted 20%, then taxed 5%. Find the final price.', '$84') },
} as const satisfies Record<Grade7MathUnit5ItemType, Def>
const q = (itemType: Grade7MathUnit5ItemType, difficulty: Difficulty, prompt: string, answer: string, parameters: Params, distractors: string[]) => makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, distractorMode: 'distinct', parameters, ...GRADE7_MATH_UNIT5_ITEM_DEFINITIONS[itemType] })
const facts = (difficulty: Difficulty) => { const percent = pick([5, 10, 20, 25] as const); const amount = ri(4, difficulty * 10 + 25) * 20; return { amount, percent, secondPercent: pick([5, 10] as const), years: ri(2, difficulty + 4) } }
const dollars = (value: number) => `$${value.toFixed(2).replace(/\.00$/, '')}`
export function generatePercentIncreaseDecreaseQuestion(difficulty: Difficulty) { const p = facts(difficulty); const increase = pick([true, false] as const); const answer = p.amount * (increase ? 1 + p.percent / 100 : 1 - p.percent / 100); return q('percent-increase-decrease', difficulty, `${increase ? 'Increase' : 'Decrease'} ${dollars(p.amount)} by ${p.percent}%.`, dollars(answer), p, [dollars(p.amount * (1 + p.percent / 100)), dollars(p.amount * (1 - p.percent / 100)), dollars(p.amount * p.percent / 100), dollars(p.amount + p.percent)]) }
export function generateDiscountMarkupQuestion(difficulty: Difficulty) { const p = facts(difficulty); const markup = pick([true, false] as const); const answer = p.amount * (markup ? 1 + p.percent / 100 : 1 - p.percent / 100); return q('discount-markup', difficulty, `A store ${markup ? 'marks up' : 'discounts'} ${dollars(p.amount)} by ${p.percent}%. What is the new price?`, dollars(answer), p, [dollars(p.amount), dollars(p.amount * p.percent / 100), dollars(p.amount * (markup ? 1 - p.percent / 100 : 1 + p.percent / 100)), dollars(answer + p.percent)]) }
export function generateTaxTipQuestion(difficulty: Difficulty) { const p = facts(difficulty); const tax = pick([true, false] as const); const amount = p.amount / 2; const add = amount * p.percent / 100; const answer = tax ? amount + add : add; return q('tax-tip', difficulty, tax ? `A meal costs ${dollars(amount)} before ${p.percent}% tax. What is the total?` : `A meal costs ${dollars(amount)}. What is a ${p.percent}% tip?`, dollars(answer), { ...p, amount }, [dollars(amount), dollars(add * 2), dollars(amount * (1 - p.percent / 100)), dollars(answer + p.percent)]) }
export function generateSimpleInterestQuestion(difficulty: Difficulty) { const p = facts(difficulty); const answer = p.amount * p.percent / 100 * p.years; return q('simple-interest', difficulty, `Find the simple interest on ${dollars(p.amount)} at ${p.percent}% for ${p.years} years.`, dollars(answer), p, [dollars(p.amount * p.percent / 100), dollars(p.amount * (1 + p.percent / 100) ** p.years - p.amount), dollars(answer + p.amount), dollars(answer + p.percent)]) }
export function generatePercentErrorQuestion(difficulty: Difficulty) { const p = facts(difficulty); const actual = ri(4, difficulty * 8 + 8) * 5; const delta = actual * p.percent / 100; const measured = actual + delta; return q('percent-error', difficulty, `The actual value is ${actual} and the measured value is ${measured}. What is the percent error?`, `${p.percent}%`, { ...p, actual, measured }, [`${p.percent / 2}%`, `${p.percent * 2}%`, `${actual}%`, `${measured}%`]) }
export function generateMultiStepPercentProblemQuestion(difficulty: Difficulty) { const p = facts(difficulty); const afterDiscount = p.amount * (1 - p.percent / 100); const answer = afterDiscount * (1 + p.secondPercent / 100); return q('multi-step-percent-problem', difficulty, `An item costs ${dollars(p.amount)}, is discounted ${p.percent}%, then taxed ${p.secondPercent}%. What is the final price?`, dollars(answer), p, [dollars(afterDiscount), dollars(p.amount * (1 + p.secondPercent / 100)), dollars(p.amount * (1 - (p.percent - p.secondPercent) / 100)), dollars(answer + p.secondPercent)]) }
export const GRADE7_MATH_UNIT5_GENERATORS = { 'percent-increase-decrease': generatePercentIncreaseDecreaseQuestion, 'discount-markup': generateDiscountMarkupQuestion, 'tax-tip': generateTaxTipQuestion, 'simple-interest': generateSimpleInterestQuestion, 'percent-error': generatePercentErrorQuestion, 'multi-step-percent-problem': generateMultiStepPercentProblemQuestion } satisfies Record<Grade7MathUnit5ItemType, CurriculumGenerator<Grade7MathUnit5Question>>
export function generateGrade7MathUnit5Question<T extends Grade7MathUnit5ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade7MathUnit5Question, { itemType: T }> { return GRADE7_MATH_UNIT5_GENERATORS[itemType](difficulty) as Extract<Grade7MathUnit5Question, { itemType: T }> }
