import type { Difficulty } from '../types'
import { pick, ri } from '../genUtils'
import { makeCurriculumQuestion, type CurriculumGenerator, type CurriculumQuestion, type CurriculumWorkedExample } from './generatorCore'

/** Source coverage: Grade 7 Mathematics Unit 5 (days 73-90), 7.RP.3 and 7.EE.3. All money is integer cents. */
export const GRADE7_MATH_UNIT5_ITEM_TYPES = ['percent-increase-decrease', 'discount-markup', 'tax-tip', 'simple-interest', 'percent-error', 'multi-step-percent-problem'] as const
export type Grade7MathUnit5ItemType = typeof GRADE7_MATH_UNIT5_ITEM_TYPES[number]
type Params = { amountCents: number; percent: number; secondPercent: number; years: number; actual?: number; measured?: number; direction?: 'increase' | 'decrease' }
type Q<T extends Grade7MathUnit5ItemType> = CurriculumQuestion<T, Params>
export type Grade7MathUnit5Question = { [T in Grade7MathUnit5ItemType]: Q<T> }[Grade7MathUnit5ItemType]
type Def = { standard: '7.RP.3' | '7.EE.3'; lessonFocus: string; workedExample: CurriculumWorkedExample }
const example = (prompt: string, answer: string): CurriculumWorkedExample => ({ prompt, answer, steps: ['Convert the percent to a fraction with denominator 100.', 'Use integer cents for money and simplify only after the exact calculation.'] })
export const GRADE7_MATH_UNIT5_ITEM_DEFINITIONS = {
  'percent-increase-decrease': { standard: '7.RP.3', lessonFocus: 'percent increase and decrease', workedExample: example('Increase $80 by 25%.', '$100') },
  'discount-markup': { standard: '7.RP.3', lessonFocus: 'discounts and markups', workedExample: example('A $60 item is discounted 20%. What is the sale price?', '$48') },
  'tax-tip': { standard: '7.RP.3', lessonFocus: 'tax and tip', workedExample: example('Find a 15% tip on $40.', '$6') },
  'simple-interest': { standard: '7.RP.3', lessonFocus: 'simple interest', workedExample: example('Find simple interest on $200 at 5% for 3 years.', '$30') },
  'percent-error': { standard: '7.EE.3', lessonFocus: 'percent error', workedExample: example('Actual length is 50 cm and measured length is 55 cm. Find percent error.', '10%') },
  'multi-step-percent-problem': { standard: '7.EE.3', lessonFocus: 'multi-step percent problems', workedExample: example('A $100 item is discounted 20%, then taxed 5%. Find the final price.', '$84') },
} as const satisfies Record<Grade7MathUnit5ItemType, Def>
const q = (itemType: Grade7MathUnit5ItemType, difficulty: Difficulty, prompt: string, answer: string, parameters: Params, distractors: string[]) => makeCurriculumQuestion({ itemType, difficulty, prompt, correctAnswer: answer, distractors, distractorMode: 'distinct', parameters, ...GRADE7_MATH_UNIT5_ITEM_DEFINITIONS[itemType] })
const money = (cents: number) => `$${Math.trunc(cents / 100)}.${String(cents % 100).padStart(2, '0')}`
const percentOf = (cents: number, percent: number) => cents * percent / 100
const facts = (difficulty: Difficulty) => ({ amountCents: ri(4, difficulty * 10 + 25) * 2_000, percent: pick([5, 10, 20, 25] as const), secondPercent: pick([5, 10] as const), years: ri(2, difficulty + 4) })
export function generatePercentIncreaseDecreaseQuestion(difficulty: Difficulty) { const p = facts(difficulty); const direction = pick(['increase', 'decrease'] as const); const answer = p.amountCents + (direction === 'increase' ? 1 : -1) * percentOf(p.amountCents, p.percent); return q('percent-increase-decrease', difficulty, `${direction === 'increase' ? 'Increase' : 'Decrease'} ${money(p.amountCents)} by ${p.percent}%.`, money(answer), { ...p, direction }, [money(p.amountCents), money(percentOf(p.amountCents, p.percent)), money(p.amountCents + (direction === 'increase' ? -1 : 1) * percentOf(p.amountCents, p.percent)), money(answer + 100)]) }
export function generateDiscountMarkupQuestion(difficulty: Difficulty) { const p = facts(difficulty); const direction = pick(['increase', 'decrease'] as const); const answer = p.amountCents + (direction === 'increase' ? 1 : -1) * percentOf(p.amountCents, p.percent); return q('discount-markup', difficulty, `A store ${direction === 'increase' ? 'marks up' : 'discounts'} ${money(p.amountCents)} by ${p.percent}%. What is the new price?`, money(answer), { ...p, direction }, [money(p.amountCents), money(percentOf(p.amountCents, p.percent)), money(p.amountCents + (direction === 'increase' ? -1 : 1) * percentOf(p.amountCents, p.percent)), money(answer + 100)]) }
export function generateTaxTipQuestion(difficulty: Difficulty) { const p = facts(difficulty); const isTax = pick([true, false] as const); const amountCents = p.amountCents / 2; const added = percentOf(amountCents, p.percent); const answer = isTax ? amountCents + added : added; return q('tax-tip', difficulty, isTax ? `A meal costs ${money(amountCents)} before ${p.percent}% tax. What is the total?` : `A meal costs ${money(amountCents)}. What is a ${p.percent}% tip?`, money(answer), { ...p, amountCents }, [money(amountCents), money(added * 2), money(amountCents - added), money(answer + 100)]) }
export function generateSimpleInterestQuestion(difficulty: Difficulty) { const p = facts(difficulty); const answer = percentOf(p.amountCents, p.percent) * p.years; return q('simple-interest', difficulty, `Find the simple interest on ${money(p.amountCents)} at ${p.percent}% for ${p.years} years.`, money(answer), p, [money(percentOf(p.amountCents, p.percent)), money(answer + p.amountCents), money(answer + 100), money(answer + p.percent * 100)]) }
export function generatePercentErrorQuestion(difficulty: Difficulty) { const p = facts(difficulty); const actual = ri(4, difficulty * 8 + 8) * 100; const measured = actual + actual * p.percent / 100; return q('percent-error', difficulty, `The actual value is ${actual} and the measured value is ${measured}. What is the percent error?`, `${p.percent}%`, { ...p, actual, measured }, [`${p.percent / 5}%`, `${p.percent * 2}%`, `${p.percent + 1}%`, `${p.percent + 5}%`]) }
export function generateMultiStepPercentProblemQuestion(difficulty: Difficulty) { const p = facts(difficulty); const afterDiscount = p.amountCents - percentOf(p.amountCents, p.percent); const answer = afterDiscount + percentOf(afterDiscount, p.secondPercent); return q('multi-step-percent-problem', difficulty, `An item costs ${money(p.amountCents)}, is discounted ${p.percent}%, then taxed ${p.secondPercent}%. What is the final price?`, money(answer), p, [money(afterDiscount), money(p.amountCents + percentOf(p.amountCents, p.secondPercent)), money(p.amountCents - percentOf(p.amountCents, p.percent - p.secondPercent)), money(answer + 100)]) }
export const GRADE7_MATH_UNIT5_GENERATORS = { 'percent-increase-decrease': generatePercentIncreaseDecreaseQuestion, 'discount-markup': generateDiscountMarkupQuestion, 'tax-tip': generateTaxTipQuestion, 'simple-interest': generateSimpleInterestQuestion, 'percent-error': generatePercentErrorQuestion, 'multi-step-percent-problem': generateMultiStepPercentProblemQuestion } satisfies Record<Grade7MathUnit5ItemType, CurriculumGenerator<Grade7MathUnit5Question>>
export function generateGrade7MathUnit5Question<T extends Grade7MathUnit5ItemType>(itemType: T, difficulty: Difficulty): Extract<Grade7MathUnit5Question, { itemType: T }> { return GRADE7_MATH_UNIT5_GENERATORS[itemType](difficulty) as Extract<Grade7MathUnit5Question, { itemType: T }> }
