"""Grade 3 English Language Arts — authored course specification.

Source of truth for the Grade 3 ELA year. The build script expands this into
units.json, lessons.jsonl, lesson-sequence.md, assessments.json, course-guide.md
and schedule.csv. Nothing here is derived from the Grade 5 course: the unit
progression, the 18-day unit arc, the daily cadence and every daily focus are
authored for Grade 3.
"""

GRADE = 3
COURSE_ID = "ma-g3-english-language-arts"
COURSE_TITLE = "Grade 3 English Language Arts"
SESSION_MINUTES = "40–55"
WEEKS = 36
DAYS = 180

COURSE_DESCRIPTION = (
    "A third-grade literacy course built for the year learners move from learning to read "
    "toward reading to learn. Foundational decoding and fluency are taught every day beside "
    "literary and informational reading, sentence and paragraph development, grammar, "
    "vocabulary, small-scale research, and speaking and listening with private and no-audio "
    "alternatives. All practice texts are original Manuel Academy passages or clearly "
    "identified public-domain works."
)

CAPSTONE = (
    "A year-end literacy portfolio containing an original narrative, an explanatory piece, an "
    "opinion piece, a research card, and a growth reflection, presented publicly, privately, "
    "in print, or in another accessible form."
)

# The Grade 3 unit arc. Grade 4 uses a different arc; neither is the Grade 5 arc.
ARC = [
    "Launch and baseline",
    "Word work and decoding focus",
    "Explicit model A",
    "Guided practice A",
    "Fluency and rereading practice",
    "Independent application A",
    "Explicit model B",
    "Guided practice B",
    "Shared close reading",
    "Reteach and varied practice",
    "Vocabulary and language study",
    "Writing plan and draft",
    "Writing revise and edit",
    "Talk and listening practice",
    "Skill consolidation and retrieval",
    "Transfer to a new text",
    "Unit assessment",
    "Correction, publication, and reflection",
]

# Daily cadence. Preserves the Manuel Academy welcome / model / guided / independent /
# exit-ticket spine and adds the daily foundational-skills block Grade 3 requires.
CADENCE = [
    ("Welcome and retrieval", "4–6"),
    ("Word work and fluency", "6–10"),
    ("Model or mini-lesson", "8–12"),
    ("Guided practice", "8–12"),
    ("Independent application", "10–15"),
    ("Exit ticket and next step", "3–5"),
]

UNITS = [
    {
        "n": 1,
        "title": "Readers and Writers Begin: Habits, Print, and Sentences",
        "eq": "What do careful readers and writers do every day, and how do I show what a text actually says?",
        "standards": ["3.RF.3", "3.RF.4", "3.RL.1", "3.RI.1", "3.SL.1", "3.SL.6", "3.L.1", "3.L.2", "3.W.10"],
        "topics": [
            "text-based questions and answers",
            "accurate and smooth oral reading",
            "decoding longer words by parts",
            "complete sentences",
            "discussion norms",
            "baseline reading and writing evidence",
        ],
        "performance_task": "Publish a Reader-and-Writer Plan card with three habits, one text-based answer written in complete sentences, and one goal, using school-safe examples only.",
        "anchor_texts": ["g3-text-01", "g3-text-02"],
        "days": [
            ("what strong readers and writers do, and a no-penalty baseline", ["3.RL.1", "3.RI.1", "3.SL.1"]),
            ("hearing syllables and finding known parts inside longer words", ["3.RF.3"]),
            ("asking questions the words on the page can answer", ["3.RL.1", "3.RI.1"]),
            ("answering by pointing to the exact sentence that proves it", ["3.RL.1", "3.RI.1"]),
            ("reading a short passage smoothly and rereading the line that slowed you down", ["3.RF.4"]),
            ("reading a new short passage and recording one question and one proved answer", ["3.RL.1", "3.RF.4"]),
            ("what a complete sentence needs: a naming part and an action part", ["3.L.1"]),
            ("turning a two-word answer into a full sentence that stands alone", ["3.L.1", "3.SL.6"]),
            ("reading one original passage together for who, what, where, and when", ["3.RL.1", "3.RI.1"]),
            ("fixing answers that sound right but do not point to the text", ["3.RL.1", "3.RI.1"]),
            ("capital letters, end marks, and reading a sentence aloud to check it", ["3.L.2", "3.L.1"]),
            ("planning three sentences about one reading habit that helps you", ["3.W.10", "3.L.1"]),
            ("revising for one clear idea and editing every end mark", ["3.W.10", "3.L.2"]),
            ("discussion norms: listen, wait, build on, and disagree kindly", ["3.SL.1", "3.SL.6"]),
            ("retrieving the unit's reading moves and sentence moves together", ["3.RL.1", "3.RI.1", "3.L.1"]),
            ("using the same moves on an unfamiliar informational passage", ["3.RI.1", "3.RF.4"]),
            ("unit evidence: text-based answers written in complete sentences", ["3.RL.1", "3.RI.1", "3.L.1", "3.L.2"]),
            ("correcting one item and publishing the Reader-and-Writer Plan card", ["3.W.10", "3.SL.6"]),
        ],
    },
    {
        "n": 2,
        "title": "Word Builders: Syllables, Prefixes, Suffixes, and Roots",
        "eq": "How do the parts inside a word help me read it and figure out what it means?",
        "standards": ["3.RF.3", "3.RF.4", "3.L.2", "3.L.4", "3.RI.4", "3.SL.4", "3.W.2"],
        "topics": [
            "syllable patterns in multisyllabic words",
            "common prefixes",
            "common suffixes and word endings",
            "roots and word families",
            "irregular high-frequency words",
            "using word parts to predict meaning",
        ],
        "performance_task": "Build a Word-Parts toolkit that decodes and explains ten longer words taken from this year's reading, with a sentence showing each word used correctly.",
        "anchor_texts": ["g3-text-03", "g3-text-04"],
        "days": [
            ("reading longer words aloud and noticing exactly where you slow down", ["3.RF.3", "3.RF.4"]),
            ("syllable patterns and where a longer word can be split", ["3.RF.3"]),
            ("prefixes un-, re-, pre-, and dis- and what each does to meaning", ["3.RF.3", "3.L.4"]),
            ("reading and explaining prefixed words inside real sentences", ["3.RF.3", "3.L.4"]),
            ("rereading a passage until its longer words no longer interrupt you", ["3.RF.4"]),
            ("decoding six new multisyllabic words and checking each meaning", ["3.RF.3", "3.L.4"]),
            ("suffixes -ful, -less, -ly, -ness, and the Latin -ment, -tion, and -able", ["3.RF.3", "3.L.4"]),
            ("adding and removing endings without breaking the base word", ["3.L.2", "3.RF.3"]),
            ("finding word parts at work inside an informational passage", ["3.RI.4", "3.RF.3"]),
            ("words that break the pattern and have to be known on sight", ["3.RF.3"]),
            ("using a known root to predict a meaning, then checking a glossary", ["3.L.4"]),
            ("drafting a toolkit entry that teaches one word to another reader", ["3.W.2", "3.L.4"]),
            ("editing spelling when an ending is added to a base word", ["3.L.2"]),
            ("explaining a word's meaning aloud so a listener can use it correctly", ["3.SL.4"]),
            ("retrieving prefixes, suffixes, roots, and syllable moves together", ["3.RF.3", "3.L.4"]),
            ("decoding unfamiliar words in a new science-style passage", ["3.RF.3", "3.RI.4"]),
            ("unit evidence: decoding, word-part reasoning, and correct use", ["3.RF.3", "3.L.4", "3.L.2"]),
            ("correcting one entry and publishing the Word-Parts toolkit", ["3.W.2", "3.L.4"]),
        ],
    },
    {
        "n": 3,
        "title": "Story Elements: Characters, Problems, and Lessons",
        "eq": "How do a character's actions lead to the lesson a story teaches?",
        "standards": ["3.RL.1", "3.RL.2", "3.RL.3", "3.RL.7", "3.RL.9", "3.RF.4", "3.SL.1", "3.W.10"],
        "topics": [
            "character traits, motivations, and feelings",
            "sequence of events",
            "central message, lesson, or moral",
            "retelling without adding",
            "illustrations and what they contribute",
            "comparing two stories about the same character",
        ],
        "performance_task": "Write a retelling and a lesson statement for one story, each supported by two details taken directly from the text.",
        "anchor_texts": ["g3-text-05", "g3-text-06", "g3-text-17"],
        "days": [
            ("retelling a short story in order without adding anything new", ["3.RL.2"]),
            ("reading character words such as stubborn, uneasy, and determined", ["3.RF.3", "3.L.4"]),
            ("traits, feelings, and motivations are shown through actions", ["3.RL.3"]),
            ("naming a trait and proving it with one action from the text", ["3.RL.3", "3.RL.1"]),
            ("reading dialogue with expression that matches the character", ["3.RF.4"]),
            ("charting one character's actions from the beginning to the end", ["3.RL.3", "3.RL.1"]),
            ("how one action causes the events that follow it", ["3.RL.3"]),
            ("putting cause and effect in order inside a story", ["3.RL.3", "3.RL.2"]),
            ("what an illustration or described figure adds at the moment a character changes", ["3.RL.1", "3.RL.3", "3.RL.7"]),
            ("repairing retellings that include events the story never told", ["3.RL.2"]),
            ("words an author uses to show a feeling without naming it", ["3.RL.4", "3.L.5"]),
            ("planning a retelling that keeps order and leaves out extras", ["3.RL.2", "3.W.10"]),
            ("revising a lesson statement so the text supports it", ["3.RL.2", "3.RL.1"]),
            ("stating a lesson claim aloud and listening for a different claim", ["3.SL.1"]),
            ("retrieving trait, motivation, sequence, and lesson together", ["3.RL.2", "3.RL.3"]),
            ("comparing two stories about the same character by the same author", ["3.RL.9"]),
            ("unit evidence: retelling, lesson statement, and text support", ["3.RL.1", "3.RL.2", "3.RL.3"]),
            ("correcting one claim and publishing the story study", ["3.RL.2", "3.RL.7"]),
        ],
    },
    {
        "n": 4,
        "title": "Reading to Learn: Main Idea and Key Details",
        "eq": "How do I find what an informational text is mostly about and prove it with details?",
        "standards": ["3.RI.1", "3.RI.2", "3.RI.4", "3.RI.7", "3.RF.4", "3.SL.2", "3.W.10"],
        "topics": [
            "main idea of a paragraph and of a whole text",
            "key supporting details",
            "domain vocabulary in context",
            "diagrams, captions, and labels",
            "distinguishing detail from main idea",
            "information gained from media with a text-only alternative",
        ],
        "performance_task": "Produce a one-page main-idea card for an original informational passage with three supporting details and either a labeled diagram or a written description that carries the same information.",
        "anchor_texts": ["g3-text-07", "g3-text-08"],
        "days": [
            ("what an informational text is for, and a no-penalty baseline", ["3.RI.1", "3.RI.2"]),
            ("reading topic words with three or more syllables", ["3.RF.3", "3.RI.4"]),
            ("a paragraph's main idea is what all its sentences share", ["3.RI.2"]),
            ("naming a paragraph's main idea and underlining two details", ["3.RI.2", "3.RI.1"]),
            ("reading an informational paragraph at a pace that keeps meaning", ["3.RF.4"]),
            ("finding the main idea of a new paragraph independently", ["3.RI.2"]),
            ("a whole text's main idea holds all its paragraphs together", ["3.RI.2"]),
            ("choosing the detail that best supports a stated main idea", ["3.RI.1", "3.RI.2"]),
            ("close reading a passage for topic words and what they mean here", ["3.RI.4"]),
            ("sorting out details that are interesting but not supporting", ["3.RI.2", "3.RI.1"]),
            ("reading a diagram, map, or photograph together with the words that explain it", ["3.RI.7", "3.RI.4"]),
            ("planning a main-idea card with three ordered details", ["3.RI.2", "3.W.10"]),
            ("revising so every detail on the card actually supports the idea", ["3.RI.1", "3.W.10"]),
            ("main ideas and supporting details of a text read aloud, with transcript", ["3.SL.2"]),
            ("retrieving main idea, detail, and vocabulary moves together", ["3.RI.2", "3.RI.4"]),
            ("finding the main idea of an unfamiliar passage on a new topic", ["3.RI.2"]),
            ("unit evidence: main idea, supporting details, and word meaning", ["3.RI.1", "3.RI.2", "3.RI.4"]),
            ("correcting one detail and publishing the main-idea card", ["3.RI.7", "3.W.10"]),
        ],
    },
    {
        "n": 5,
        "title": "How Information Texts Are Built: Sequence, Cause, and Comparison",
        "eq": "How does the way a text is organized help me follow the information?",
        "standards": ["3.RI.3", "3.RI.5", "3.RI.7", "3.RI.8", "3.RI.9", "3.L.6", "3.RF.4"],
        "topics": [
            "sequence and chronology",
            "cause and effect",
            "compare and contrast",
            "text features and search tools",
            "connections between sentences and paragraphs",
            "two texts on the same topic",
        ],
        "performance_task": "Make a text-structure map for two passages on one topic showing sequence, cause and effect, and what each text adds that the other does not.",
        "anchor_texts": ["g3-text-09", "g3-text-10"],
        "days": [
            ("noticing how a text moves a reader through its ideas", ["3.RI.3", "3.RI.8"]),
            ("reading signal words such as because, after, and however", ["3.RF.3", "3.L.6"]),
            ("sequence: how a text carries a reader through steps or time", ["3.RI.3", "3.RI.8"]),
            ("mapping a sequence passage and naming its signal words", ["3.RI.3", "3.L.6"]),
            ("reading a procedure aloud accurately enough to follow it", ["3.RF.4"]),
            ("mapping a new sequence passage without prompts", ["3.RI.3"]),
            ("cause and effect: what happened and what it led to", ["3.RI.3", "3.RI.8"]),
            ("separating a cause from an effect that looks like one", ["3.RI.8"]),
            ("close reading how one paragraph connects to the next", ["3.RI.8"]),
            ("repairing structure maps that mix up order and cause", ["3.RI.3", "3.RI.8"]),
            ("the words and text features that help you find and name a connection", ["3.RI.5", "3.L.6"]),
            ("planning a compare-and-contrast map of two passages", ["3.RI.9"]),
            ("revising the map so each column names its evidence", ["3.RI.9", "3.RI.1"]),
            ("explaining a structure to a listener who has not read the text", ["3.SL.4"]),
            ("retrieving sequence, cause, comparison, and features together", ["3.RI.3", "3.RI.5", "3.RI.9"]),
            ("naming how an unfamiliar text connects its ideas, and proving it", ["3.RI.3", "3.RI.8"]),
            ("unit evidence: idea connections, text features, signal words, and comparison", ["3.RI.3", "3.RI.5", "3.RI.8", "3.RI.9"]),
            ("correcting one column and publishing the text-structure map", ["3.RI.7", "3.RI.9"]),
        ],
    },
    {
        "n": 6,
        "title": "Paragraph Power: Informative and Explanatory Writing",
        "eq": "How do I write a paragraph that teaches one idea clearly?",
        "standards": ["3.W.2", "3.W.4", "3.W.5", "3.W.6", "3.RI.2", "3.L.1", "3.L.2", "3.L.3"],
        "topics": [
            "topic sentences",
            "facts, definitions, and details",
            "linking words and phrases",
            "concluding sentences",
            "editing for grammar and spelling",
            "producing and sharing writing with a digital tool",
        ],
        "performance_task": "Publish a two-paragraph explainer with a topic sentence, facts and definitions, linking words, and a closing sentence.",
        "anchor_texts": ["g3-text-11", "g3-text-07"],
        "days": [
            ("what a teaching paragraph does that a list of facts does not", ["3.W.2", "3.RI.2"]),
            ("spelling patterns for the words this unit needs most", ["3.L.2", "3.RF.3"]),
            ("a topic sentence names the one idea the paragraph will teach", ["3.W.2"]),
            ("writing a topic sentence for three given fact sets", ["3.W.2", "3.W.4"]),
            ("reading your own paragraph aloud to hear where it breaks", ["3.RF.4", "3.W.5"]),
            ("drafting one full paragraph on a familiar topic", ["3.W.2", "3.W.4"]),
            ("facts, definitions, and details that develop the topic sentence", ["3.W.2"]),
            ("choosing which two facts belong and which one wanders off", ["3.W.2", "3.W.5"]),
            ("reading a model explainer to see how it is put together", ["3.RI.2", "3.W.2"]),
            ("repairing paragraphs with two ideas mixed into one", ["3.W.2", "3.W.5"]),
            ("linking words: also, another, for example, because, finally", ["3.W.2", "3.L.3"]),
            ("planning a two-paragraph explainer with grouped facts", ["3.W.2", "3.W.4"]),
            ("revising for clarity, then editing subject-verb agreement and spelling", ["3.W.5", "3.L.1", "3.L.2"]),
            ("reading a paragraph aloud and taking one listener question", ["3.SL.4", "3.SL.6"]),
            ("retrieving topic sentence, development, linking, and closing", ["3.W.2", "3.W.4"]),
            ("writing a short explainer on an unfamiliar topic from given facts", ["3.W.2", "3.W.4"]),
            ("unit evidence: an independently written explanatory paragraph pair", ["3.W.2", "3.W.4", "3.L.1", "3.L.2"]),
            ("correcting one paragraph and publishing the explainer", ["3.W.5", "3.W.6"]),
        ],
    },
    {
        "n": 7,
        "title": "Opinion Writing: Reasons That Convince",
        "eq": "How do I state what I think and back it with reasons a reader can follow?",
        "standards": ["3.W.1", "3.W.4", "3.W.5", "3.RI.6", "3.RI.8", "3.SL.4", "3.L.6", "3.L.3"],
        "topics": [
            "stating an opinion clearly",
            "reasons that actually support the opinion",
            "ordering reasons",
            "linking words for opinion writing",
            "the author's point of view and my own",
            "concluding statements",
        ],
        "performance_task": "Write and present an opinion piece with a clear opinion, three ordered reasons, linking words, and a conclusion; presentation may be spoken, read aloud by another person, printed, or private.",
        "anchor_texts": ["g3-text-12", "g3-text-09"],
        "days": [
            ("the difference between a fact, a feeling, and an opinion", ["3.W.1", "3.RI.8"]),
            ("reading opinion words and the endings that change them", ["3.RF.3", "3.L.4"]),
            ("an opinion statement says what you think in one sentence", ["3.W.1"]),
            ("writing an opinion statement three different ways and picking one", ["3.W.1", "3.W.5"]),
            ("reading an opinion paragraph aloud so the position is clear", ["3.RF.4", "3.SL.4"]),
            ("drafting an opinion statement plus one supporting reason", ["3.W.1"]),
            ("a reason answers the question 'why should anyone agree?'", ["3.W.1", "3.RI.8"]),
            ("sorting strong reasons from restatements of the opinion", ["3.W.1", "3.RI.8"]),
            ("close reading to name the author's point of view and say how yours differs", ["3.RI.6"]),
            ("repairing reasons that do not connect to the opinion", ["3.W.1", "3.W.5"]),
            ("linking words for opinion: because, therefore, since, for example", ["3.W.1", "3.L.6", "3.L.3"]),
            ("planning three reasons in the order that convinces best", ["3.W.1", "3.W.4"]),
            ("revising the conclusion so it does more than repeat the opening", ["3.W.1", "3.W.5"]),
            ("presenting an opinion at an understandable pace, or in print", ["3.SL.4"]),
            ("retrieving opinion, reason, order, linking, and conclusion", ["3.W.1", "3.W.4"]),
            ("writing an opinion on a new question about a familiar topic", ["3.W.1"]),
            ("unit evidence: an independently written opinion piece", ["3.W.1", "3.W.4", "3.RI.8"]),
            ("correcting one reason and publishing or privately filing the piece", ["3.W.5", "3.RI.6"]),
        ],
    },
    {
        "n": 8,
        "title": "Poems, Plays, and Words That Mean More",
        "eq": "How do poets and playwrights use sound, shape, and figurative language to make meaning?",
        "standards": ["3.RL.4", "3.RL.5", "3.RL.6", "3.RF.4", "3.L.5", "3.SL.5", "3.W.10"],
        "topics": [
            "stanzas, lines, scenes, and cast lists",
            "rhythm, rhyme, and repeated sound",
            "literal and nonliteral language",
            "imagery and word choice",
            "narrator and character point of view",
            "presenting a reading with a no-audio alternative",
        ],
        "performance_task": "Create a small poem-and-scene set with an author's note explaining two craft choices; the presentation may be printed, silently displayed, recorded, or shared privately with one adult.",
        "anchor_texts": ["g3-text-13", "g3-text-14"],
        "days": [
            ("how a poem and a play look different from a story on the page", ["3.RL.5"]),
            ("hearing rhyme, rhythm, and repeated sounds in words", ["3.RF.3", "3.RL.4"]),
            ("stanzas and lines in poems; scenes and casts in plays", ["3.RL.5"]),
            ("labeling the parts of a poem and the parts of a scene", ["3.RL.5"]),
            ("reading a poem aloud, or silently with a marked rhythm, twice", ["3.RF.4"]),
            ("marking the structure of a new poem independently", ["3.RL.5"]),
            ("literal and nonliteral meaning: when words mean something else", ["3.RL.4", "3.L.5"]),
            ("explaining what a phrase means here and how you can tell", ["3.RL.4", "3.L.5"]),
            ("close reading an original poem for imagery and word choice", ["3.RL.4"]),
            ("repairing readings that take a figure of speech literally", ["3.L.5"]),
            ("shades of meaning between words that seem to be the same", ["3.L.5"]),
            ("planning an original poem or short scene with one craft choice", ["3.W.10", "3.RL.5"]),
            ("revising for sound and image, then editing the layout", ["3.W.10", "3.RL.4"]),
            ("presenting a reading aloud, in print, or through a caption track", ["3.SL.5"]),
            ("retrieving structure, figurative language, and point of view", ["3.RL.4", "3.RL.5", "3.RL.6"]),
            ("comparing your point of view with the narrator's in a new poem", ["3.RL.6"]),
            ("unit evidence: structure, nonliteral meaning, and craft explanation", ["3.RL.4", "3.RL.5", "3.L.5"]),
            ("correcting one note and publishing or privately filing the set", ["3.W.10", "3.SL.5"]),
        ],
    },
    {
        "n": 9,
        "title": "Small Research: Questions, Sources, and Notes",
        "eq": "How do I answer a real question using sources I can name and notes I took myself?",
        "standards": ["3.W.7", "3.W.8", "3.RI.5", "3.RI.9", "3.SL.3", "3.L.4", "3.W.4"],
        "topics": [
            "asking a researchable question",
            "recalling and gathering information",
            "taking notes in your own words",
            "sorting notes into categories",
            "naming a source",
            "two sources on one topic",
        ],
        "performance_task": "Complete a short research card: the question, two named sources, notes written in your own words, the answer, and one thing you still wonder.",
        "anchor_texts": ["g3-text-08", "g3-text-10"],
        "days": [
            ("what makes a question researchable instead of unanswerable", ["3.W.7"]),
            ("reading topic vocabulary you will need for this question", ["3.RF.3", "3.L.4"]),
            ("gathering what you already know before you look anything up", ["3.W.8"]),
            ("turning a broad wondering into one answerable question", ["3.W.7"]),
            ("reading a source passage carefully enough to take notes", ["3.RF.4"]),
            ("locating the part of a source that answers your question", ["3.RI.5", "3.W.8"]),
            ("notes in your own words: why copying is not note-taking", ["3.W.8"]),
            ("shortening a sentence into a note without changing its meaning", ["3.W.8"]),
            ("close reading a second source on the same topic", ["3.RI.9"]),
            ("repairing notes that copied wording or lost the meaning", ["3.W.8"]),
            ("the words a source record needs: who made it, what it is, and where you found it", ["3.W.8", "3.L.6"]),
            ("sorting notes into the categories you were given, then planning the answer", ["3.W.8", "3.W.4"]),
            ("revising the answer so each part traces to a note", ["3.W.7", "3.W.4"]),
            ("asking a speaker a question and answering one about your notes", ["3.SL.3"]),
            ("retrieving question, gather, note, categorize, and cite", ["3.W.7", "3.W.8"]),
            ("running the whole routine on a new question in one session", ["3.W.7", "3.W.8"]),
            ("unit evidence: a research card with sources and own-words notes", ["3.W.7", "3.W.8", "3.RI.9"]),
            ("correcting one note and publishing the research card", ["3.W.8", "3.W.4"]),
        ],
    },
    {
        "n": 10,
        "title": "Narrative Craft and the Year-End Portfolio",
        "eq": "How do I tell a story a reader can follow, and show a year of reading and writing growth?",
        "standards": ["3.W.3", "3.W.4", "3.W.5", "3.W.6", "3.RL.10", "3.RI.10", "3.SL.4", "3.SL.6", "3.L.1", "3.L.3"],
        "topics": [
            "establishing a situation and a narrator or characters",
            "event sequence that unfolds naturally",
            "dialogue and description of feelings",
            "temporal words that signal order",
            "a sense of closure",
            "portfolio selection and reflection",
        ],
        "performance_task": "Publish a year-end portfolio with an original narrative, one explainer, one opinion piece, one research card, and a written reflection on growth.",
        "anchor_texts": ["g3-text-15", "g3-text-16"],
        "days": [
            ("what makes a story easy to follow, and choosing a portfolio piece", ["3.W.3", "3.RL.10"]),
            ("reading and spelling the words your own story needs", ["3.RF.3", "3.L.2"]),
            ("establishing a situation, a narrator, and characters", ["3.W.3"]),
            ("writing an opening that sets up a real problem", ["3.W.3", "3.W.4"]),
            ("reading a draft aloud to hear where a reader would get lost", ["3.RF.4", "3.W.5"]),
            ("drafting the middle events in an order that unfolds naturally", ["3.W.3"]),
            ("dialogue that shows feeling, punctuated with quotation marks and commas", ["3.W.3", "3.L.2", "3.L.3"]),
            ("replacing told feelings with shown actions and words", ["3.W.3", "3.W.5"]),
            ("reading a published narrative for closure and last lines", ["3.RL.10", "3.W.3"]),
            ("repairing sequences that jump, repeat, or stop without closure", ["3.W.3", "3.W.5"]),
            ("temporal words and phrases that keep a reader oriented", ["3.W.3", "3.L.1"]),
            ("planning the portfolio: selection, order, and reflection prompts", ["3.W.4", "3.W.6"]),
            ("revising the narrative, then editing grammar and end punctuation", ["3.W.5", "3.L.1"]),
            ("presenting one portfolio piece aloud, in print, or privately", ["3.SL.4", "3.SL.6"]),
            ("retrieving the year's reading and writing moves in one sitting", ["3.RL.10", "3.RI.10", "3.W.4"]),
            ("reading an unfamiliar grade-level text and responding in writing", ["3.RL.10", "3.RI.10"]),
            ("unit evidence: an independently written narrative and reflection", ["3.W.3", "3.W.4", "3.L.1"]),
            ("correcting one section and publishing the year-end portfolio", ["3.W.5", "3.W.6"]),
        ],
    },
]
