"""Grade 4 English Language Arts — authored course specification.

Independent of both the Grade 3 course in this package and the frozen Grade 5
course in curriculum-content. Grade 4 is built around the genuine Grade 3 to
Grade 4 shifts confirmed against the Michigan K-12 ELA standards document:
theme and summary, analytic text structure, an author's reasons and evidence,
firsthand versus secondhand accounts, evidence drawn from texts (W.4.9, which
does not exist at Grade 3), and a consolidated morphology-driven decoding thread
rather than Grade 3's four discrete phonics sub-skills.
"""

GRADE = 4
COURSE_ID = "ma-g4-english-language-arts"
COURSE_TITLE = "Grade 4 English Language Arts"
SESSION_MINUTES = "45–65"
WEEKS = 36
DAYS = 180

COURSE_DESCRIPTION = (
    "A fourth-grade literacy course organized around evidence. Learners summarize, determine "
    "theme, analyze how informational texts are structured, weigh the reasons and evidence an "
    "author supplies, integrate two sources, and write multi-paragraph explanatory, opinion, "
    "and narrative pieces for a stated audience. A leaner but real foundational thread keeps "
    "morphology-driven decoding and fluency in daily practice. All practice texts are original "
    "Manuel Academy passages or clearly identified public-domain works."
)

CAPSTONE = (
    "A year-end literacy portfolio containing an original narrative, an explanatory piece, an "
    "opinion piece, a research brief with a source list, a two-text "
    "comparison, and a growth reflection, presented publicly, privately, in print, or in "
    "another accessible form."
)

# Grade 4 unit arc. Deliberately different from the Grade 3 arc in this package
# and from the Grade 5 arc in curriculum-content.
ARC = [
    "Launch and diagnostic",
    "Word study and morphology",
    "Concept model A",
    "Guided practice A",
    "Close reading with evidence",
    "Independent application A",
    "Concept model B",
    "Guided practice B",
    "Reteach and varied practice",
    "Craft or structure analysis",
    "Source or research work",
    "Writing plan and draft",
    "Writing revision workshop",
    "Discussion or presentation practice",
    "Transfer challenge",
    "Retrieval and assessment preparation",
    "Unit assessment",
    "Targeted correction, publication, and reflection",
]

CADENCE = [
    ("Welcome and retrieval", "4–6"),
    ("Word study and fluency", "5–8"),
    ("Model or mini-lesson", "8–14"),
    ("Guided practice", "10–15"),
    ("Independent application", "12–20"),
    ("Exit ticket and next step", "3–6"),
]

UNITS = [
    {
        "n": 1,
        "title": "An Evidence Habit: Details, Examples, and Inferences",
        "eq": "What counts as evidence, and how do I show my thinking about a text in writing?",
        "standards": ["4.RL.1", "4.RI.1", "4.RF.3", "4.RF.4", "4.W.4", "4.W.10", "4.SL.1", "4.L.1"],
        "topics": [
            "explicit meaning and inference",
            "referring to details and examples",
            "quoting and paraphrasing accurately",
            "morphology-driven decoding of unfamiliar words",
            "writing for a stated audience",
            "collaborative discussion roles",
        ],
        "performance_task": "Publish an evidence-habits page holding two text-based responses, one literary and one informational, each with quoted or paraphrased support and a self-check.",
        "anchor_texts": ["g4-text-01", "g4-text-02"],
        "days": [
            ("what evidence is, and a no-penalty diagnostic across both text types", ["4.RL.1", "4.RI.1"]),
            ("attacking an unfamiliar multisyllabic word with sound, syllables, and parts", ["4.RF.3"]),
            ("explicit meaning: what the text states outright", ["4.RL.1", "4.RI.1"]),
            ("locating the detail or example that answers a question exactly", ["4.RL.1", "4.RI.1"]),
            ("close reading one passage for stated facts and unstated implications", ["4.RL.1", "4.RF.4"]),
            ("answering two questions on a new passage with cited support", ["4.RI.1", "4.W.4"]),
            ("inference: what the text makes true without saying it", ["4.RL.1", "4.RI.1"]),
            ("separating a supported inference from a guess the text does not carry", ["4.RL.1", "4.RI.1"]),
            ("repairing responses whose evidence does not match the claim", ["4.RI.1", "4.W.4"]),
            ("how quoting and paraphrasing differ, and when each is honest", ["4.W.4", "4.RI.1"]),
            ("recording where a piece of evidence came from inside a passage", ["4.W.8", "4.RI.1"]),
            ("planning a written response for a named audience", ["4.W.4", "4.W.10"]),
            ("revising a response so every claim carries its evidence, then editing for complete sentences", ["4.W.4", "4.W.5", "4.L.1"]),
            ("discussion roles, preparation, and drawing on what you read", ["4.SL.1"]),
            ("using the evidence habit on an unfamiliar pair of passages", ["4.RL.1", "4.RI.1"]),
            ("retrieving explicit meaning, inference, quotation, and paraphrase", ["4.RL.1", "4.RI.1", "4.W.4"]),
            ("unit evidence: cited literary and informational responses", ["4.RL.1", "4.RI.1", "4.W.4", "4.L.1"]),
            ("correcting one response and publishing the evidence-habits page", ["4.W.5", "4.W.10"]),
        ],
    },
    {
        "n": 2,
        "title": "Summary and Theme: Saying What a Story Means",
        "eq": "How is a summary different from a retelling, and how do I state a theme the text supports?",
        "standards": ["4.RL.1", "4.RL.2", "4.RL.10", "4.W.9a", "4.W.4", "4.SL.1", "4.L.4", "4.RF.4"],
        "topics": [
            "objective summary",
            "theme in story, drama, and poem",
            "summary without opinion or retelling",
            "evidence drawn from literature",
            "Greek and Latin roots in unfamiliar words",
            "reading in the grades 4-5 band with scaffolding",
        ],
        "performance_task": "Write an objective summary and a theme statement for one story, each supported by two details drawn directly from the text.",
        "anchor_texts": ["g4-text-03", "g4-text-04"],
        "days": [
            ("summary, retelling, and opinion are three different things", ["4.RL.2"]),
            ("Greek and Latin roots inside this unit's vocabulary", ["4.L.4", "4.RF.3"]),
            ("an objective summary keeps events and leaves out judgment", ["4.RL.2"]),
            ("cutting a retelling down to a summary without losing the spine", ["4.RL.2"]),
            ("close reading a story for the details a summary must keep", ["4.RL.1", "4.RL.2", "4.RF.4"]),
            ("summarizing an unfamiliar story independently", ["4.RL.2"]),
            ("a theme is what the whole text says about something, not its topic", ["4.RL.2"]),
            ("testing a proposed theme against the events of the text", ["4.RL.2", "4.RL.1"]),
            ("repairing themes that are really topics, morals, or opinions", ["4.RL.2"]),
            ("how theme works differently in a poem and in a drama", ["4.RL.2", "4.RL.5"]),
            ("gathering the two strongest details that support a theme", ["4.W.9a", "4.RL.1"]),
            ("planning a summary-and-theme response for a reader who has not read it", ["4.W.4", "4.W.9a"]),
            ("revising so the theme statement is a full sentence the text can carry", ["4.RL.2", "4.W.5"]),
            ("presenting a theme claim and reviewing the key ideas others raised", ["4.SL.1"]),
            ("summarizing and theming a text in the grades 4-5 band, with scaffolding at the hard parts", ["4.RL.10", "4.RL.2"]),
            ("retrieving summary, theme, and literary evidence together", ["4.RL.2", "4.W.9a"]),
            ("unit evidence: objective summary plus supported theme statement", ["4.RL.1", "4.RL.2", "4.W.9a"]),
            ("correcting one statement and publishing the summary-and-theme study", ["4.W.5", "4.RL.2"]),
        ],
    },
    {
        "n": 3,
        "title": "In-Depth Study: Character, Setting, Event, and Point of View",
        "eq": "How do specific details let me describe a character, setting, or event in depth?",
        "standards": ["4.RL.1", "4.RL.3", "4.RL.6", "4.RL.7", "4.RL.9", "4.W.9a", "4.SL.1", "4.L.5"],
        "topics": [
            "describing in depth from specific details",
            "first-person and third-person narration",
            "comparing points of view",
            "text and its visual or oral presentation",
            "similar themes and patterns across cultures",
            "similes and metaphors in context",
        ],
        "performance_task": "Produce an in-depth character, setting, or event study drawing on at least four specific details, one point-of-view observation, and one cross-text pattern.",
        "anchor_texts": ["g4-text-05", "g4-text-06"],
        "days": [
            ("the difference between mentioning a character and describing one in depth", ["4.RL.3"]),
            ("words that name precise emotions and states of being", ["4.L.6"]),
            ("in-depth description is built from a stack of specific details", ["4.RL.3", "4.RL.1"]),
            ("collecting four details that describe one character", ["4.RL.3", "4.RL.1"]),
            ("close reading a setting for the details that make it matter", ["4.RL.3", "4.RL.1", "4.RF.4"]),
            ("writing an in-depth description of an event independently", ["4.RL.3", "4.W.9a"]),
            ("first-person and third-person narration and how each limits what we know", ["4.RL.6"]),
            ("comparing what two narrators can and cannot tell us", ["4.RL.6"]),
            ("repairing descriptions built on impression instead of detail", ["4.RL.3"]),
            ("similes and metaphors an author uses to build a character", ["4.L.5", "4.RL.4"]),
            ("connecting a text to a visual or oral presentation of the same story", ["4.RL.7"]),
            ("planning an in-depth study with a claim and four details", ["4.W.9a", "4.W.4"]),
            ("revising to replace general adjectives with cited detail", ["4.RL.3", "4.W.5"]),
            ("posing and responding to specific questions about another study", ["4.SL.1"]),
            ("comparing similar themes and patterns of events across cultures", ["4.RL.9"]),
            ("retrieving depth, narration, figurative language, and comparison", ["4.RL.3", "4.RL.6", "4.L.5"]),
            ("unit evidence: an in-depth study with cited detail and point of view", ["4.RL.1", "4.RL.3", "4.RL.6"]),
            ("correcting one paragraph and publishing the in-depth study", ["4.W.5", "4.RL.7"]),
        ],
    },
    {
        "n": 4,
        "title": "Informational Main Idea, Summary, and Explanation",
        "eq": "How do I determine a main idea, explain what it rests on, and summarize without opinion?",
        "standards": ["4.RI.1", "4.RI.2", "4.RI.3", "4.RI.4", "4.W.9b", "4.L.4", "4.RF.4", "4.W.4"],
        "topics": [
            "main idea and how key details support it",
            "objective summary of informational text",
            "explaining events, procedures, and ideas",
            "what happened and why it happened",
            "domain-specific vocabulary",
            "evidence drawn from informational text",
        ],
        "performance_task": "Write a main-idea and summary brief for an original informational passage, including an explanation of one process or event the text describes and why it occurs.",
        "anchor_texts": ["g4-text-07", "g4-text-08"],
        "days": [
            ("what a main idea has to account for, and a no-penalty diagnostic", ["4.RI.2"]),
            ("domain vocabulary and the roots that unlock it", ["4.RI.4", "4.L.4", "4.RF.3"]),
            ("a main idea is supported by key details, not merely near them", ["4.RI.2"]),
            ("stating a main idea and naming the three details that carry it", ["4.RI.2", "4.RI.1"]),
            ("close reading for the details a summary of this text must keep", ["4.RI.1", "4.RI.2", "4.RF.4"]),
            ("summarizing an unfamiliar informational passage independently", ["4.RI.2"]),
            ("explaining a process: the steps and why they run in that order", ["4.RI.3"]),
            ("explaining a historical or scientific event: what happened and why", ["4.RI.3"]),
            ("repairing summaries that smuggle in opinion or drop the main idea", ["4.RI.2"]),
            ("how a writer's word choice signals precision in a technical passage", ["4.RI.4", "4.L.6"]),
            ("gathering informational evidence to support an explanation", ["4.W.9b", "4.RI.1"]),
            ("planning a main-idea and summary brief for a stated audience", ["4.W.4", "4.W.9b"]),
            ("revising the explanation so causes and effects are not reversed, and placing prepositional phrases where they belong", ["4.RI.3", "4.W.5", "4.L.1"]),
            ("explaining a process aloud, in writing, or through a labeled sequence", ["4.SL.4"]),
            ("summarizing and explaining an unfamiliar technical passage", ["4.RI.2", "4.RI.3"]),
            ("retrieving main idea, support, summary, and explanation", ["4.RI.2", "4.RI.3", "4.W.9b"]),
            ("unit evidence: main idea, objective summary, and causal explanation", ["4.RI.1", "4.RI.2", "4.RI.3"]),
            ("correcting one explanation and publishing the brief", ["4.W.5", "4.RI.4"]),
        ],
    },
    {
        "n": 5,
        "title": "How Informational Texts Are Structured and Shown",
        "eq": "How do a writer's structure and visual information shape what I understand?",
        "standards": ["4.RI.5", "4.RI.7", "4.RI.4", "4.RI.1", "4.L.6", "4.W.9b", "4.SL.2"],
        "topics": [
            "chronology, comparison, cause and effect, problem and solution",
            "structure of a part versus the whole text",
            "interpreting visual and quantitative information",
            "charts, timelines, diagrams, and tables",
            "paraphrasing a text read aloud",
            "text-only equivalents for every visual",
        ],
        "performance_task": "Build a structure-and-features analysis showing how one passage is organized and how a chart, timeline, or diagram adds to it, including a written description that carries the same information for text-only access.",
        "anchor_texts": ["g4-text-10", "g4-text-08"],
        "days": [
            ("naming the shape of a text instead of only finding facts in it", ["4.RI.5"]),
            ("signal vocabulary that marks each structure", ["4.L.6", "4.RI.4"]),
            ("chronology and problem-and-solution as whole-text structures", ["4.RI.5"]),
            ("naming a passage's overall structure and proving it with signals", ["4.RI.5", "4.RI.1"]),
            ("close reading a passage whose parts use different structures", ["4.RI.5", "4.RI.1", "4.RF.4"]),
            ("describing the structure of an unfamiliar passage independently", ["4.RI.5"]),
            ("comparison and cause-and-effect as whole-text structures", ["4.RI.5"]),
            ("choosing between two plausible structure labels using evidence", ["4.RI.5", "4.RI.1"]),
            ("repairing analyses that name a structure the text does not use", ["4.RI.5"]),
            ("how a chart, timeline, or diagram carries information the prose does not", ["4.RI.7"]),
            ("writing the text-only description that replaces a visual", ["4.RI.7", "4.W.9b"]),
            ("planning a structure-and-features analysis of one passage", ["4.RI.5", "4.RI.7"]),
            ("revising so each structural claim names its evidence, joining ideas with relative pronouns and adverbs", ["4.RI.5", "4.W.5", "4.L.1"]),
            ("paraphrasing a portion of a text read aloud or presented in media", ["4.SL.2"]),
            ("analyzing structure and visuals in an unfamiliar technical text", ["4.RI.5", "4.RI.7"]),
            ("retrieving structure names, signals, and visual interpretation", ["4.RI.5", "4.RI.7"]),
            ("unit evidence: overall structure, signals, and visual interpretation", ["4.RI.5", "4.RI.7", "4.RI.1"]),
            ("correcting one label and publishing the structure analysis", ["4.W.5", "4.RI.7"]),
        ],
    },
    {
        "n": 6,
        "title": "Explanatory Writing: Grouping, Precision, and Development",
        "eq": "How do I group related information and develop it so a reader learns something new?",
        "standards": ["4.W.2", "4.W.4", "4.W.5", "4.W.6", "4.L.1", "4.L.2", "4.L.3", "4.L.6"],
        "topics": [
            "grouping information in paragraphs and sections",
            "facts, definitions, concrete details, quotations, examples",
            "precise language and domain-specific vocabulary",
            "linking ideas within categories",
            "fragments, run-ons, and frequently confused words",
            "producing and publishing with technology",
        ],
        "performance_task": "Publish a three-to-five paragraph explanatory piece with grouped sections, precise domain vocabulary, linking words, a formatting choice, and a conclusion related to the information presented.",
        "anchor_texts": ["g4-text-07", "g4-text-11"],
        "days": [
            ("what separates an explanatory piece from a pile of related facts", ["4.W.2"]),
            ("precise verbs and domain nouns this piece will need", ["4.L.6", "4.W.2"]),
            ("grouping related information into paragraphs and sections", ["4.W.2"]),
            ("sorting a mixed fact set into three defensible groups", ["4.W.2", "4.W.4"]),
            ("close reading a model explanatory text for how it is built", ["4.RI.5", "4.W.2", "4.RF.4"]),
            ("drafting two grouped paragraphs with an introduction", ["4.W.2", "4.W.4"]),
            ("developing a group with facts, definitions, details, and a quotation", ["4.W.2", "4.W.9b"]),
            ("choosing the concrete detail that develops rather than decorates", ["4.W.2", "4.W.5"]),
            ("repairing sections that repeat, wander, or state without developing", ["4.W.2", "4.W.5"]),
            ("precise language: replacing a vague word with the exact one", ["4.W.2", "4.L.3"]),
            ("using headings, a caption, or a list where it genuinely helps", ["4.W.2", "4.W.6"]),
            ("planning the full piece: introduction, sections, and conclusion", ["4.W.2", "4.W.4"]),
            ("revising for development, then editing fragments, run-ons, and confusables", ["4.W.5", "4.L.1", "4.L.2"]),
            ("choosing formal or informal English for this audience", ["4.L.3", "4.SL.6"]),
            ("writing a short explanatory piece on an unfamiliar topic from given sources", ["4.W.2", "4.W.9b"]),
            ("retrieving grouping, development, precision, linking, and conclusion", ["4.W.2", "4.W.4"]),
            ("unit evidence: an independently written multi-paragraph explanatory piece", ["4.W.2", "4.W.4", "4.L.1", "4.L.2"]),
            ("correcting one section and publishing with a typed page", ["4.W.5", "4.W.6"]),
        ],
    },
    {
        "n": 7,
        "title": "Opinion and Argument: Reasons, Evidence, and Fair Reading",
        "eq": "How do I build an opinion on evidence and read someone else's reasons fairly?",
        "standards": ["4.W.1", "4.RI.8", "4.RI.6", "4.W.9b", "4.SL.3", "4.SL.4", "4.L.3", "4.W.4"],
        "topics": [
            "an opinion grouped to support a purpose",
            "reasons supported by facts and details",
            "how an author uses reasons and evidence",
            "firsthand and secondhand accounts",
            "identifying a speaker's reasons and evidence",
            "a conclusion related to the opinion presented",
        ],
        "performance_task": "Write and deliver an opinion piece with a clear position, grouped reasons supported by facts and details from at least two sources; delivery may be spoken, read by another person, printed, or private.",
        "anchor_texts": ["g4-text-12", "g4-text-09"],
        "days": [
            ("an opinion that can be supported versus one that cannot", ["4.W.1"]),
            ("vocabulary that states a position precisely", ["4.L.6", "4.L.3"]),
            ("a reason at Grade 4 must be supported by facts and details", ["4.W.1"]),
            ("attaching two facts to a reason that previously stood alone", ["4.W.1", "4.W.9b"]),
            ("close reading how an author uses reasons and evidence for a point", ["4.RI.8", "4.RI.1", "4.RF.4"]),
            ("evaluating whether one author's evidence actually supports the point", ["4.RI.8"]),
            ("grouping related reasons so the structure supports the purpose", ["4.W.1"]),
            ("ordering grouped reasons and linking them to the opinion", ["4.W.1", "4.L.3"]),
            ("repairing reasons that restate the opinion or cite nothing", ["4.W.1", "4.RI.8"]),
            ("firsthand and secondhand accounts of the same event", ["4.RI.6"]),
            ("drawing evidence from a firsthand and a secondhand source, and recording both", ["4.W.9b", "4.W.8", "4.RI.6"]),
            ("planning the piece: position, grouped reasons, and the evidence behind each", ["4.W.1", "4.W.4"]),
            ("revising the conclusion so it follows from the reasons, using modal auxiliaries precisely", ["4.W.1", "4.W.5", "4.L.1"]),
            ("identifying the reasons and evidence a speaker provides", ["4.SL.3", "4.SL.4"]),
            ("writing an evidence-based opinion on a new question and source pair", ["4.W.1", "4.W.9b"]),
            ("retrieving position, grouped reasons, evidence, and conclusion", ["4.W.1", "4.RI.8"]),
            ("unit evidence: an independently written evidence-based opinion piece", ["4.W.1", "4.W.9b", "4.RI.8"]),
            ("correcting one reason's evidence and publishing or privately filing the piece", ["4.W.5", "4.RI.6"]),
        ],
    },
    {
        "n": 8,
        "title": "Poetry, Drama, and Prose: Structure, Craft, and Figurative Language",
        "eq": "How do the forms of poetry, drama, and prose change the way meaning is made?",
        "standards": ["4.RL.4", "4.RL.5", "4.RL.7", "4.L.5", "4.RF.4", "4.SL.5", "4.W.10", "4.L.3"],
        "topics": [
            "verse, rhythm, meter, cast, stage directions",
            "structural elements of poems and drama",
            "allusions to mythological characters",
            "similes, metaphors, idioms, adages, and proverbs",
            "synonyms and antonyms",
            "presentation with a no-audio alternative",
        ],
        "performance_task": "Create a craft study containing one original poem or dramatic scene and an author's note analyzing its structure, one figurative device, and one allusion, idiom, adage, or proverb; presentation may be silent, printed, recorded, or private.",
        "anchor_texts": ["g4-text-13", "g4-text-14"],
        "days": [
            ("the major differences among poetry, drama, and prose on the page", ["4.RL.5"]),
            ("words built from myth and story, and what they carry with them", ["4.RL.4", "4.L.4", "4.RF.3"]),
            ("structural elements of poetry: verse, rhythm, meter, stanza", ["4.RL.5"]),
            ("labeling the structural elements of a poem and a scene", ["4.RL.5"]),
            ("close reading a poem for how its structure shapes its meaning", ["4.RL.5", "4.RL.4", "4.RF.4"]),
            ("analyzing the structure of an unfamiliar poem or scene independently", ["4.RL.5"]),
            ("allusions: when a word points to a story outside this text", ["4.RL.4"]),
            ("explaining what an allusion adds that a plain word would not", ["4.RL.4", "4.L.5"]),
            ("repairing readings that treat an idiom or metaphor literally", ["4.L.5"]),
            ("similes, metaphors, idioms, adages, and proverbs side by side", ["4.L.5"]),
            ("synonyms and antonyms as tools for precision, not decoration", ["4.L.5", "4.L.3"]),
            ("planning an original poem or scene with one deliberate craft choice", ["4.W.10", "4.RL.5"]),
            ("revising for sound and image, ordering adjectives and punctuating for effect", ["4.W.10", "4.RL.5", "4.L.1", "4.L.3"]),
            ("presenting a reading aloud, in print, or with a caption track", ["4.SL.5"]),
            ("connecting a written scene to a visual or oral presentation of it", ["4.RL.7"]),
            ("retrieving form, structure, allusion, and figurative language", ["4.RL.4", "4.RL.5", "4.L.5"]),
            ("unit evidence: structural analysis and figurative-language explanation", ["4.RL.4", "4.RL.5", "4.L.5"]),
            ("correcting one note and publishing or privately filing the craft study", ["4.W.10", "4.SL.5"]),
        ],
    },
    {
        "n": 9,
        "title": "Research, Sources, and Honest Note-Taking",
        "eq": "How do I investigate a question across sources and record what I found in my own words?",
        "standards": ["4.W.7", "4.W.8", "4.W.9b", "4.RI.9", "4.RI.7", "4.SL.2", "4.SL.3", "4.L.4"],
        "topics": [
            "investigating different aspects of a topic",
            "taking notes and categorizing them",
            "paraphrase versus copying",
            "providing a list of sources",
            "integrating information from two texts",
            "one question the sources raised but did not answer",
        ],
        "performance_task": "Complete a research brief with the question, at least three categorized sources and a source list, paraphrased notes, an integrated answer drawing on two texts, and one question the sources raised that you did not answer.",
        "anchor_texts": ["g4-text-08", "g4-text-10"],
        "days": [
            ("turning a topic into a question with investigable aspects", ["4.W.7"]),
            ("reference tools: dictionary, glossary, and thesaurus for precise meaning", ["4.L.4"]),
            ("choosing which aspects of a topic your project will actually cover", ["4.W.7"]),
            ("splitting one question into three aspects and assigning a source to each", ["4.W.7", "4.W.8"]),
            ("close reading a source for information relevant to one aspect", ["4.W.8", "4.RI.1", "4.RF.4"]),
            ("gathering relevant notes from a new source independently", ["4.W.8"]),
            ("paraphrase: rewriting a source idea without borrowing its wording", ["4.W.8"]),
            ("checking a paraphrase against the original for accuracy and independence", ["4.W.8"]),
            ("repairing notes that copied phrasing or drifted from the source", ["4.W.8"]),
            ("interpreting a chart or table inside a source and noting what it shows", ["4.RI.7"]),
            ("building the source list: who, what, when, and where you found it", ["4.W.8"]),
            ("planning an answer that integrates two texts rather than stacking them", ["4.RI.9", "4.W.9b"]),
            ("revising so every integrated claim traces to a note, punctuating quotations from a text", ["4.W.9b", "4.W.5", "4.L.2"]),
            ("paraphrasing a source read aloud and identifying a speaker's evidence", ["4.SL.2", "4.SL.3"]),
            ("running the full research routine on a new question in one session", ["4.W.7", "4.W.8"]),
            ("retrieving question, aspects, notes, paraphrase, sources, integration", ["4.W.7", "4.W.8", "4.RI.9"]),
            ("unit evidence: a research brief with source list and paraphrased notes", ["4.W.7", "4.W.8", "4.RI.9"]),
            ("correcting one note and publishing the research brief", ["4.W.8", "4.W.9b"]),
        ],
    },
    {
        "n": 10,
        "title": "Narrative Craft, Comparison, and the Year-End Portfolio",
        "eq": "How do I write a narrative a reader can follow, and show a year of growth across genres?",
        "standards": ["4.W.3", "4.W.4", "4.W.5", "4.W.6", "4.RL.9", "4.RL.10", "4.RI.10", "4.SL.4", "4.SL.6", "4.L.1"],
        "topics": [
            "orienting the reader",
            "dialogue and description that develop response",
            "transitional words that manage sequence",
            "concrete words and sensory details",
            "a conclusion that follows from the events",
            "portfolio selection, comparison, and reflection",
        ],
        "performance_task": "Publish a year-end portfolio containing an original narrative, an explanatory piece, an opinion piece, a research brief, a comparison of two texts, and a written growth reflection.",
        "anchor_texts": ["g4-text-15", "g4-text-16"],
        "days": [
            ("what orients a reader in the first paragraph, and portfolio selection", ["4.W.3", "4.RL.10"]),
            ("precise verbs and sensory nouns your own narrative will need", ["4.L.6", "4.W.3"]),
            ("orienting the reader: situation, narrator, and characters", ["4.W.3"]),
            ("drafting an opening that establishes a situation worth following", ["4.W.3", "4.W.4"]),
            ("close reading a published narrative for how its ending is earned", ["4.RL.10", "4.W.3", "4.RF.4"]),
            ("drafting the middle events with a managed sequence", ["4.W.3"]),
            ("dialogue and description that develop a character's response", ["4.W.3"]),
            ("replacing summary of feeling with shown action and speech", ["4.W.3", "4.W.5"]),
            ("repairing narratives that stall, skip, or end without following through", ["4.W.3", "4.W.5"]),
            ("concrete words and sensory details that convey experience precisely", ["4.W.3"]),
            ("comparing similar themes and patterns of events in texts from different cultures", ["4.RL.9"]),
            ("planning the portfolio: selection, order, comparison, and reflection", ["4.W.4", "4.W.6"]),
            ("revising the narrative, then correcting fragments, run-ons, and frequently confused words", ["4.W.5", "4.L.1", "4.L.2"]),
            ("presenting one portfolio piece in an organized way, or privately", ["4.SL.4", "4.SL.6"]),
            ("reading an unfamiliar grades 4-5 band text and responding in writing", ["4.RL.10", "4.RI.10"]),
            ("retrieving the year's reading, writing, research, and language moves", ["4.RL.10", "4.RI.10", "4.W.4"]),
            ("unit evidence: an independently written narrative and growth reflection", ["4.W.3", "4.W.4", "4.L.1"]),
            ("correcting one section and publishing the portfolio with its two-text comparison", ["4.W.5", "4.W.6"]),
        ],
    },
]
