"""Generate the standards alignment table, per-course guides, and the validation
report markdown from the same spec the authoring set is built from, so the prose
cannot drift from the data."""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import course_spec as spec, standards_data
sys.path.insert(0, HERE)
from build_authoring_set import taught_order

PE = {p["code"]: p for p in standards_data.PERFORMANCE_EXPECTATIONS}
COURSE_OF = {}
ORDERED = sorted(spec.COURSES, key=lambda c: c["order"])
UNIT_INDEX = {}
_i = 0
for c in ORDERED:
    for u in c["units"]:
        _i += 1
        UNIT_INDEX[id(u)] = _i
        for s in u["standards"]:
            COURSE_OF.setdefault(s.upper(), []).append((c["title"], u))
TAUGHT_FIRST = taught_order()


def split_spiral(u):
    """Reinforcement looks backwards; a preview looks forwards. Never conflate them."""
    n = UNIT_INDEX[id(u)]
    back, fwd = [], []
    for pe in u["spiral"]:
        first = TAUGHT_FIRST.get(pe)
        (back if first is not None and first <= n else fwd).append(pe)
    return back, fwd

def w(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write(text)

# ---------------------------------------------------------- standards alignment
L = ["# Standards Alignment — Michigan Science Standards, High School",
     "",
     "**Framework:** Michigan Science Standards, November 2015 (`michigan-science-standards-2015`)  ",
     "**Authority status:** `verified` — statements transcribed from the MDE publication  ",
     "**Coverage:** all 71 high school performance expectations, each with a primary owning unit",
     "",
     "Source: Michigan Department of Education, *Michigan K-12 Standards: Science*, November 2015 — ",
     "<https://www.michigan.gov/mde/-/media/Project/Websites/mde/Literacy/Content-Standards/Science_Standards.pdf>",
     "",
     "MDE footnote markers are preserved in the framework data: `*` marks a performance expectation that",
     "integrates traditional science content with engineering; `**` marks one that allows local, regional,",
     "or Michigan-specific contexts.",
     "",
     "This table is generated by `tools/build_docs.py`. Do not hand-edit it.",
     ""]
for grp in ["Physical", "Life", "Earth and Space", "Engineering"]:
    prefix = {"Physical": "HS-PS", "Life": "HS-LS", "Earth and Space": "HS-ESS", "Engineering": "HS-ETS"}[grp]
    L += [f"## {grp} Sciences ({prefix})", "",
          "| PE | MDE topic | Primary course | Unit | Statement |",
          "| --- | --- | --- | --- | --- |"]
    for p in standards_data.PERFORMANCE_EXPECTATIONS:
        if not p["code"].startswith(prefix):
            continue
        owners = COURSE_OF.get(p["code"], [])
        courses = " / ".join(sorted({o[0] for o in owners})) or "**UNCOVERED**"
        units = " / ".join(f"U{o[1]['_n']:02d}" for o in owners)
        note = " *" if "integrates engineering" in p["flags"] else ""
        note += " **" if "allows Michigan or local context" in p["flags"] else ""
        stmt = p["statement"].replace("|", "\\|")
        L += [f"| `{p['code']}`{note} | {p['group']} | {courses} | {units} | {stmt} |"]
    L += [""]
L += ["## Reinforcement and preview (secondary occasions)", "",
      "A unit that touches a performance expectation it does not own is doing one of two different things,",
      "and the package does not conflate them:", "",
      "- **Reinforcement** — the expectation was already taught in or before this unit. This is deliberate",
      "  spiral practice supporting the multi-occasion mastery rule.",
      "- **Preview** — the expectation is taught later in the sequence. The unit builds readiness for it.",
      "  A preview is never called reinforcement, and it is never assessed here.", "",
      "Neither substitutes for the primary coverage above, and neither appears on a unit assessment: an",
      "assessment carries its own unit's primary standards only.", "",
      "| Course | Unit | Reinforces (already taught) | Previews (taught later) |", "| --- | --- | --- | --- |"]
for c in ORDERED:
    for u in c["units"]:
        back, fwd = split_spiral(u)
        if back or fwd:
            L += [f"| {c['title']} | U{u['_n']:02d} {u['title']} | {', '.join(s.upper() for s in back) or '—'} "
                  f"| {', '.join(s.upper() for s in fwd) or '—'} |"]
w(os.path.join(ROOT, "standards-alignment.md"), "\n".join(L) + "\n")

# ---------------------------------------------------------- per-course guides
for c in spec.COURSES:
    G = [f"# {c['title']} — Course Guide", "",
         f"**Course ID:** `{c['course_id']}`  ", f"**Grade:** {c['grade']}  ",
         f"**Credit role:** {c['credit_role']}  ",
         "**Sessions:** 108 (36 weeks × 3 sessions)  ", "**Session length:** 55–75 minutes", "",
         "## Description", "", c["description"], "", "## Capstone", "", c["capstone"], "",
         "## Units", "",
         "| # | Unit | Days | Primary PEs | Performance task |", "| --- | --- | --- | --- | --- |"]
    for u in c["units"]:
        pes = ", ".join(s.upper() for s in u["standards"]) or "practice foundation (no PE claimed or assessed)"
        G += [f"| {u['_n']} | {u['title']} | 12 | {pes} | {u['performance_task']} |"]
    G += ["", "## Anchoring phenomena", "",
          "Every unit opens on an observable phenomenon rather than a definition.", "",
          "| Unit | Phenomenon |", "| --- | --- |"]
    for u in c["units"]:
        G += [f"| {u['_n']} | {u['phenomenon']} |"]
    G += ["", "## Investigations, hazards, and alternative paths", "",
          "Each unit's Day 7 is an investigation, and Day 9 rebuilds the performance task with the same",
          "materials and the same safety set. Every hazard, mitigation, supervision level, safe-order step,",
          "stop condition, and disposal step below is rendered into the learner-visible lesson flow on those",
          "days — none of it lives only in the guardian record. Every investigation has a no-special-equipment",
          "alternative that meets the same learning target: a first-class path, not a consolation.", ""]
    for u in c["units"]:
        i = u["investigation"]
        G += [f"### Unit {u['_n']} — {i['title']}", "",
              f"- **Supervision:** `{i['supervision']}`",
              f"- **Guardian visibility:** `{i['visibility']}`",
              f"- **Materials:** {', '.join(i['materials'])}", "",
              "**Hazards**", "", "| Kind | Hazard | Mitigation |", "| --- | --- | --- |"]
        for k, d, m in i["hazards"]:
            G += [f"| {k} | {d} | {m} |"]
        G += ["", "**Safe order**", ""]
        for n, step in enumerate(i["sequence"], start=1):
            G += [f"{n}. {step}"]
        G += ["", "**Stop conditions**", ""]
        for s in i["stop"]:
            G += [f"- {s}"]
        G += ["", f"**Disposal.** {i['disposal']}", "",
              f"**No-special-equipment alternative.** {i['alternative']}", "",
              f"**Data provenance.** {i['data_source']}", ""]
    w(os.path.join(ROOT, "course-guides", f"{c['course_id']}.md"), "\n".join(G) + "\n")

# ---------------------------------------------------------- validation report md
rp = os.path.join(ROOT, "validation", "validation-report.json")
if os.path.exists(rp):
    r = json.load(open(rp))
    V = [f"# Validation Report — {r['package_id']}", "",
         f"**Schema set:** {r['schema_set_version']}  ",
         f"**Overall:** **{r['overall']}**  ",
         f"**Contract issues from `validateAuthoringSet`:** {len(r['contract_issues'])}  ",
         f"**Mission checks:** {r['counts']['passed']}/{r['counts']['checks']} passed", "",
         "The contract check runs the repository's own validator,",
         "`src/curriculum-authoring/v2/validation.ts`, against this authoring set. The mission checks below",
         "cover requirements that validator does not know about: standards coverage, laboratory safety,",
         "alternative paths, media independence, and data provenance.", "",
         "| Check | Result | Detail |", "| --- | --- | --- |"]
    for c in r["checks"]:
        V += [f"| {c['check']} | {c['result']} | {c['detail']} |"]
    V += ["", "## What a PASS does and does not mean", "",
          "A PASS verifies structural conformance to the 2.0.0 authoring contract, complete and non-duplicated",
          "coverage of all 71 Michigan high school performance expectations, a declared investigation with typed",
          "hazards and an alternative path in every unit, multi-occasion mastery on every lesson, clean student",
          "projections, unique and stable identifiers, and full schedule coverage.", "",
          "It does **not** claim state approval, accreditation, transcript credit, production host integration,",
          "third-party content licensing, or that any individual learner has demonstrated proficiency.", ""]
    w(os.path.join(ROOT, "validation", "validation-report.md"), "\n".join(V) + "\n")

print("docs generated")
