"""Manuel Academy High School Science 9-12 - course design specification.

This module is the hand-authored source of truth for the four-course sequence.
`build_authoring_set.py` expands it into a schema-set 2.0.0 authoring set.

Every unit declares:
  title, essential_question, phenomenon, topics (exactly 6), performance_task,
  standards (primary), reinforces (secondary), investigation.

`investigation` declares the Day 7 laboratory or field work:
  title        - what the learner does
  materials    - household-safe materials only
  hazards      - list of (kind, description, mitigation); kind is one of
                 physical | chemical | online | financial | privacy | emotional
  supervision  - none | nearby-adult | direct-adult
  visibility   - summary | confirmation-required | direct-observation
  stop         - extra stop conditions beyond the global set
  alternative  - REQUIRED no-special-equipment path to the same learning target
  data_source  - where real numbers come from; never fabricated results
"""

BIOLOGY = [
    dict(
        title="Scientific Practice, Measurement, and the Molecules of Life",
        essential_question="What counts as biological evidence, and how do the molecules of life make structure and function inseparable?",
        phenomenon="Two apple slices, one left plain and one coated in lemon juice, brown at very different rates on the same counter.",
        topics=["biological scale and measurement", "uncertainty and repeated trials", "carbon and macromolecule structure",
                "structure-function relationships", "enzymes and reaction conditions", "argument from evidence in biology"],
        performance_task="Plan and run a controlled investigation of one factor affecting an enzyme or browning reaction, then defend the conclusion with your own data, stated uncertainty, and named limitations.",
        standards=["hs-ls1-6"],
        reinforces=["hs-ets1-3"],
        investigation=dict(
            title="Controlled test of enzymatic browning or catalase activity",
            materials=["apple or potato slices", "lemon juice", "cold and room-temperature water",
                       "3% household hydrogen peroxide (optional catalase route)", "timer", "ruler", "notebook"],
            hazards=[("chemical", "3% hydrogen peroxide irritates eyes and can bleach fabric and skin on contact.",
                      "Use the household 3% strength only, keep it in its original bottle, wear eye protection, work over a washable surface, and rinse any splash with water for 15 minutes."),
                     ("physical", "Slicing produce with a kitchen knife risks cuts.",
                      "An adult does all cutting, or the learner uses pre-cut produce; no knife work is required by the lesson.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop if hydrogen peroxide contacts the eyes and begin rinsing immediately.",
                  "Stop if any cut occurs and treat it before continuing."],
            alternative="Run the browning comparison with no chemicals at all: compare apple slices in air, under water, and wrapped, timing colour change against a printed colour scale. This needs only produce, water, and a timer and meets the same target.",
            data_source="Learner-collected timing and colour-scale observations. No result is supplied in advance.",
        ),
    ),
    dict(
        title="DNA, Proteins, and the Information Flow of the Cell",
        essential_question="How does a sequence of four bases end up determining what a cell can actually do?",
        phenomenon="Two people with the same rare condition carry changes in the same gene, but one has mild symptoms and the other severe ones.",
        topics=["DNA structure and base pairing", "replication as information copying", "transcription", "translation and the genetic code",
                "protein folding and function", "mutation and its consequences"],
        performance_task="Build a physical or drawn model tracing one gene from DNA sequence to folded protein to observable function, and state precisely what your model cannot show.",
        standards=["hs-ls1-1"],
        reinforces=["hs-ls3-2"],
        investigation=dict(
            title="DNA extraction from fruit, and modelling sequence to protein",
            materials=["strawberries or banana", "dish soap", "table salt", "water", "coffee filter or fine strainer",
                       "cold rubbing alcohol (isopropyl)", "clear cup", "resealable bag"],
            hazards=[("chemical", "Isopropyl alcohol is flammable and harmful if swallowed or splashed in eyes.",
                      "An adult dispenses and stores the alcohol, keeps it away from any heat or flame, and the learner wears eye protection. Never taste any material."),
                     ("physical", "Glass containers can break and cut.",
                      "Use plastic or unbreakable cups only.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop if alcohol contacts the eyes and rinse for 15 minutes.",
                  "Stop all work if any heat source or flame is present in the room."],
            alternative="Skip extraction entirely: use a printed codon table and a supplied DNA sequence to transcribe and translate by hand, then build the protein from paper or beads. This needs only paper and meets the sequence-to-function target.",
            data_source="Learner's own observation of the extracted material, plus a published codon table. No yield figure is fabricated.",
        ),
    ),
    dict(
        title="Cells, Hierarchical Organization, and Cellular Division",
        essential_question="How do interacting systems at every scale from organelle to organism produce a functioning body?",
        phenomenon="A cut on a finger closes over about a week, but a cut on the cornea can close in a day.",
        topics=["cell theory and cell types", "organelles as interacting subsystems", "tissues, organs, and organ systems",
                "the cell cycle and mitosis", "differentiation and stem cells", "scale and surface-area-to-volume"],
        performance_task="Model the hierarchical organization of one organ system from organelle to organism, showing where cellular division and differentiation act and what each level contributes.",
        standards=["hs-ls1-2", "hs-ls1-4"],
        reinforces=[],
        investigation=dict(
            title="Surface-area-to-volume modelling and observation of dividing cells",
            materials=["modelling clay or potato cubes", "ruler", "food colouring and water (diffusion route)",
                       "microscope and prepared onion-root-tip slide (optional)", "notebook"],
            hazards=[("physical", "Cutting cubes to size uses a knife.",
                      "An adult does all cutting, or the learner uses clay shaped by hand with no cutting tool."),
                     ("physical", "Microscope lamps get warm and slides have sharp edges.",
                      "Handle slides by their edges, let the lamp cool before storage, and treat the microscope step as optional.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if a slide chips or breaks and let an adult clear it."],
            alternative="Do the whole unit with no microscope and no cutting: use published, openly licensed onion-root-tip micrographs to count cells in each mitotic phase, and model surface-area-to-volume with hand-rolled clay cubes measured with a ruler.",
            data_source="Learner's own cube measurements and their own phase counts from either a real slide or a published micrograph.",
        ),
    ),
    dict(
        title="Homeostasis and Feedback Mechanisms",
        essential_question="How do living systems hold conditions steady while the world around them keeps changing?",
        phenomenon="A house thermostat and a lizard on a rock both keep temperature within a range, but only one of them can be reprogrammed.",
        topics=["setpoints and tolerance ranges", "negative feedback loops", "positive feedback loops",
                "feedback failure and disease", "regulation across organ systems", "modelling feedback quantitatively"],
        performance_task="Plan and conduct an investigation using a non-human system that provides evidence a feedback mechanism is maintaining a stable internal condition, then model the loop and identify what would break it.",
        standards=["hs-ls1-3"],
        reinforces=["hs-ets1-1"],
        investigation=dict(
            title="Feedback regulation in a plant or a thermal model system",
            materials=["two similar potted plants", "water", "clear bags", "thermometer", "insulated container",
                       "warm and cool water", "timer", "notebook"],
            hazards=[("physical", "Warm water can scald.",
                      "Keep all water below 50 degrees Celsius, an adult fills the container, and the learner never handles boiling water."),
                     ("emotional", "Health and body topics can be distressing when they touch personal or family medical experience.",
                      "Examples use non-human systems and published cases only; the learner is never asked about their own or a family member's health, and may skip any example without penalty.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if water is hot enough to be uncomfortable to touch.",
                  "Pause and move to the alternative if a health example becomes distressing."],
            alternative="Use a published, openly licensed physiological dataset - for example thermoregulation in a non-human animal - and model the feedback loop from that data. Needs only the dataset and paper.",
            data_source="Learner-collected plant or thermal-model measurements, or a published non-human dataset. NO LEARNER BODY OR HEALTH MEASUREMENT IS REQUESTED ANYWHERE IN THIS UNIT.",
        ),
    ),
    dict(
        title="Photosynthesis, Cellular Respiration, and Energy in Living Systems",
        essential_question="Where does the matter in a tree come from, and where does the energy in your food actually go?",
        phenomenon="A large tree grows tonnes of wood while the soil beneath it barely loses mass.",
        topics=["light energy capture", "photosynthesis as matter and energy transformation", "cellular respiration",
                "aerobic and anaerobic pathways", "conservation of matter in metabolism", "energy accounting in organisms"],
        performance_task="Construct and revise an evidence-based explanation of how matter and energy move through photosynthesis and respiration, using your own data plus a published dataset.",
        standards=["hs-ls1-5", "hs-ls1-7", "hs-ls2-3"],
        reinforces=["hs-ps1-7"],
        investigation=dict(
            title="Evidence of photosynthesis and respiration rates",
            materials=["fresh spinach or elodea", "baking soda", "water", "clear cups", "lamp or window light",
                       "syringe (optional leaf-disk route)", "yeast, sugar, warm water, balloon (respiration route)", "timer"],
            hazards=[("chemical", "Baking soda solution irritates eyes.",
                      "Wear eye protection and rinse any splash with water."),
                     ("physical", "A lamp close to a water container gets hot and mixes electricity with water.",
                      "Keep the lamp at least 30 cm away, never above the water, and plug it in away from any spill zone; an adult positions the lamp.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop immediately if any liquid reaches a lamp, cord, or outlet.",
                  "Stop if a sealed container bulges; never fully seal a fermenting container."],
            alternative="Run the yeast-and-sugar respiration comparison with a loosely fitted balloon and no lamp at all, or analyse a published photosynthesis-rate dataset against light intensity. Both meet the matter-and-energy target with kitchen materials or paper only.",
            data_source="Learner-collected rise times, bubble counts, or balloon circumference, plus a published rate dataset for comparison. No expected value is stated in advance.",
        ),
    ),
    dict(
        title="Ecosystems: Matter Cycling and Energy Flow",
        essential_question="Why does so little of the energy entering an ecosystem reach its top consumers?",
        phenomenon="A hectare of grassland supports thousands of insects, hundreds of mice, and perhaps one hawk.",
        topics=["trophic levels and energy transfer", "food webs and matter flow", "the carbon cycle in ecosystems",
                "nitrogen and nutrient cycling", "decomposition", "quantitative ecosystem models"],
        performance_task="Use mathematical representations of a real ecosystem's energy budget and carbon flows to support a claim about what limits its structure.",
        standards=["hs-ls2-4", "hs-ls2-5"],
        reinforces=["hs-ess2-6", "hs-ls1-5"],
        investigation=dict(
            title="Decomposition rates and a quantified local food web",
            materials=["fallen leaves or fruit scraps", "two containers", "soil", "balance or kitchen scale",
                       "notebook", "published local species list"],
            hazards=[("physical", "Decomposing material grows mould and attracts insects.",
                      "Keep containers outdoors or in a garage, covered and labelled; the learner wears gloves and washes hands after handling, and anyone with a mould or pollen allergy uses the alternative."),
                     ("privacy", "Recording an outdoor location can disclose where the family lives.",
                      "Record habitat type and general conditions only. Never record an address, GPS coordinate, or identifiable landmark.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop and switch to the alternative if anyone in the household has a mould or spore allergy.",
                  "Do not open a container that smells strongly or looks heavily colonised; discard it outdoors unopened."],
            alternative="Skip the decomposition setup: build the energy budget and carbon flow entirely from a published, openly licensed ecosystem dataset and a species list, using arithmetic and a drawn web. Paper only.",
            data_source="Learner-collected mass-loss measurements where run, plus a published ecosystem energy dataset. Trophic efficiency is derived from data, never asserted.",
        ),
    ),
    dict(
        title="Population Dynamics, Carrying Capacity, and Biodiversity",
        essential_question="What actually sets the ceiling on a population, and what makes an ecosystem resilient when conditions change?",
        phenomenon="An introduced species explodes for a decade, crashes, and then settles at a level nobody predicted.",
        topics=["exponential and logistic growth", "carrying capacity and limiting factors", "interspecific interactions",
                "biodiversity measurement", "ecosystem resilience and disturbance", "group behaviour and survival"],
        performance_task="Use mathematical and computational representations of real population data to explain and revise a claim about carrying capacity, biodiversity, or the survival value of group behaviour.",
        standards=["hs-ls2-1", "hs-ls2-2", "hs-ls2-6", "hs-ls2-8"],
        reinforces=["hs-ets1-4"],
        investigation=dict(
            title="Modelling population growth from a published long-term dataset",
            materials=["published population dataset", "spreadsheet or graph paper", "calculator", "notebook",
                       "dried beans or counters (physical sampling model)"],
            hazards=[("privacy", "Online dataset searching can expose the learner to tracking or to accounts.",
                      "An adult supplies the dataset file or the exact source; no account creation, sign-in, or purchase is required."),
                     ("physical", "Small counters are a choking hazard around young children.",
                      "Keep counters away from younger siblings and count them back into the container at the end.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if a website asks for an account, payment, or personal information."],
            alternative="Run a mark-and-recapture sampling model with two colours of dried beans in a bag to estimate an unknown population, then compare the estimate to the true count. Kitchen materials and arithmetic only.",
            data_source="A published long-term population dataset the family retrieves, plus the learner's own sampling counts. Growth constants are fitted by the learner, not supplied.",
        ),
    ),
    dict(
        title="Inheritance and Variation of Traits",
        essential_question="Where does heritable variation come from, and what can probability actually predict about it?",
        phenomenon="Two siblings share both parents and about half their DNA, yet differ in almost every visible trait.",
        topics=["chromosomes and gene loci", "meiosis and recombination", "sources of genetic variation",
                "probability and Punnett models", "polygenic and environmental effects", "distribution of expressed traits"],
        performance_task="Make and defend an evidence-based claim about the source of a heritable variation, using statistics and probability, and state where a simple inheritance model stops working.",
        standards=["hs-ls3-1", "hs-ls3-2", "hs-ls3-3"],
        reinforces=["hs-ls1-1"],
        investigation=dict(
            title="Statistical distribution of a trait in a non-human population",
            materials=["dried beans, seeds, or leaves from one plant species (30+ specimens)", "ruler", "graph paper",
                       "coins or dice for probability modelling", "notebook"],
            hazards=[("privacy", "Family trait or pedigree work can expose genetic and health information about relatives who never consented.",
                      "This unit uses NON-HUMAN specimens and fictional pedigrees only. The learner is never asked to record family traits, family medical history, ancestry, or any relative's data."),
                     ("emotional", "Heredity topics can touch on disability, adoption, or family history painfully.",
                      "All examples are fictional or non-human; the learner may decline any example without penalty and no personal disclosure is ever requested.")],
            supervision="none",
            visibility="summary",
            stop=["Stop and use fictional data if any prompt seems to ask for real family information; it should not."],
            alternative="Use a supplied fictional pedigree and a coin-flip meiosis model on paper to generate the trait distribution. No specimens needed.",
            data_source="Learner's own measurements of non-human specimens and their own coin or dice trials. Distributions are built from those trials, never pre-filled.",
        ),
    ),
    dict(
        title="Natural Selection, Evolution, and Biodiversity Engineering",
        essential_question="What lines of evidence support common ancestry, and how should we design a response when human activity threatens biodiversity?",
        phenomenon="Antibiotic-resistant bacteria appear in hospitals within a few years of a new drug's release.",
        topics=["multiple lines of evidence for common ancestry", "the four factors driving natural selection",
                "statistics of advantageous traits", "adaptation of populations", "environmental change and extinction",
                "engineering solutions for biodiversity"],
        performance_task="Complete a biodiversity engineering capstone: define criteria and constraints for a real conservation problem, model a solution, test it by simulation, evaluate trade-offs, and defend the revision history.",
        standards=["hs-ls4-1", "hs-ls4-2", "hs-ls4-3", "hs-ls4-4", "hs-ls4-5", "hs-ls4-6", "hs-ls2-7",
                   "hs-ets1-1", "hs-ets1-2", "hs-ets1-3"],
        reinforces=["hs-ls3-3"],
        investigation=dict(
            title="Selection simulation and a conservation design test",
            materials=["two or three colours of dried beans or paper dots", "patterned cloth or paper background",
                       "timer", "graph paper", "published conservation case study"],
            hazards=[("physical", "Timed grabbing games can knock over nearby objects.",
                      "Clear the work surface first and keep the play area away from edges and breakables."),
                     ("emotional", "Extinction and habitat loss can be genuinely upsetting.",
                      "Frame the unit around designed responses and documented recoveries; the learner may pause or choose a different case at any point.")],
            supervision="none",
            visibility="summary",
            stop=["Pause if the extinction content becomes distressing and resume with a recovery case study."],
            alternative="Run the selection simulation entirely on paper with dice determining survival probability by trait, then analyse a published conservation case study. No materials beyond paper and one die.",
            data_source="Learner's own predation-simulation counts across generations and a published conservation case study. Allele-frequency change is computed by the learner from their own trials.",
        ),
    ),
]

CHEMISTRY = [
    dict(
        title="Matter, Measurement, and Laboratory Practice",
        essential_question="How do chemists decide what a measurement actually tells them, and how do we work safely with matter at home?",
        phenomenon="Two people measure the same spoon of salt and get masses that differ by more than the salt they think they added.",
        topics=["physical and chemical properties", "measurement, precision, and significant figures", "uncertainty and repeated trials",
                "density and derived quantities", "separation of mixtures", "chemical safety and hazard reading"],
        performance_task="Determine the density of an unknown solid or solution from your own repeated measurements, report it with an honest uncertainty, and justify every digit you kept.",
        standards=[],
        reinforces=["hs-ets1-3"],
        investigation=dict(
            title="Density determination with repeated trials and stated uncertainty",
            materials=["kitchen scale reading to 1 g or better", "measuring cup or graduated container", "water",
                       "salt or sugar", "small solid objects", "notebook"],
            hazards=[("physical", "Spilled water makes floors slippery and can reach electrical outlets.",
                      "Work over a tray on a low surface away from outlets, and wipe spills immediately."),
                     ("chemical", "Household substances must never be combined experimentally.",
                      "This unit uses water, salt, and sugar only. Never mix cleaning products; bleach with ammonia or acid releases toxic gas. This prohibition is not disableable.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop all work if any cleaning product is brought to the work area.",
                  "Stop if liquid approaches an outlet, cord, or the scale's battery compartment."],
            alternative="Determine density from a supplied set of published mass and volume measurements, computing uncertainty by hand. Paper and calculator only.",
            data_source="Learner's own repeated mass and volume trials. Accepted reference densities are looked up for comparison only, after the learner reports their own value.",
        ),
    ),
    dict(
        title="Atomic Structure and the Periodic Table as a Model",
        essential_question="Why does the periodic table predict how an element will behave before anyone tests it?",
        phenomenon="Sodium and potassium sit in the same column and react with water in strikingly similar ways, while argon beside them does nothing at all.",
        topics=["subatomic structure and isotopes", "electron arrangement and energy levels", "valence electrons",
                "periodic trends in atomic radius and ionization", "reactivity patterns by group", "the periodic table as a predictive model"],
        performance_task="Use the periodic table as a model to predict relative properties of unfamiliar elements from outer-electron patterns, then check your predictions against published data and account for every miss.",
        standards=["hs-ps1-1"],
        reinforces=[],
        investigation=dict(
            title="Flame-colour patterns and periodic trend analysis from published data",
            materials=["published periodic-trend dataset", "graph paper or spreadsheet", "calculator",
                       "salt substitute (potassium chloride) and table salt (optional flame route, adult-run)"],
            hazards=[("physical", "Any flame test involves open flame and burn risk.",
                      "The flame route is OPTIONAL and is performed only by an adult, outdoors or over a sink, with hair tied back, sleeves secured, and water within reach. The learner observes from at least one metre and never holds a flame."),
                     ("chemical", "Heated metal salts produce fumes.",
                      "Work outdoors or with strong ventilation, use pinches of material only, and never heat an unknown substance.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop the flame route immediately if anything other than the intended sample ignites.",
                  "Skip the flame route entirely if the household has no safe outdoor space or if anyone present has a respiratory condition."],
            alternative="Do the entire unit from published data: graph atomic radius, ionization energy, and electronegativity across periods and down groups, and use published emission-spectrum images to identify elements. No flame, no chemicals, paper only. This is the DEFAULT path.",
            data_source="Published periodic-property data the family retrieves, plus the learner's own graphs and predictions. No flame-test outcome is stated before observation.",
        ),
    ),
    dict(
        title="Bonding, Structure, and the Properties of Designed Materials",
        essential_question="How does what happens between particles explain what a material does in your hand?",
        phenomenon="Candle wax, table salt, and copper wire all look solid, but only one conducts, only one shatters, and only one melts in a warm room.",
        topics=["ionic, covalent, and metallic bonding", "intermolecular forces", "bulk properties as evidence of particle forces",
                "conductivity, melting point, and solubility", "polymers and designed materials", "communicating technical information"],
        performance_task="Plan and conduct an investigation comparing bulk properties of several substances to infer the relative strength of forces between their particles, then communicate why molecular-level structure matters for one designed material.",
        standards=["hs-ps1-3", "hs-ps2-6"],
        reinforces=["hs-ets1-2"],
        investigation=dict(
            title="Inferring particle forces from solubility, conductivity, and melting behaviour",
            materials=["table salt", "sugar", "cooking oil", "water", "rubbing alcohol", "clear cups",
                       "9V battery with leads and a small LED (conductivity route)", "warm water", "spoons"],
            hazards=[("chemical", "Rubbing alcohol is flammable, its vapour is heavier than air, and it is harmful if swallowed.",
                      "An adult dispenses and stores it, nothing is ever tasted, and the alcohol step is run FIRST and finished before any battery is brought out."),
                     ("chemical", "A shorting battery is itself an ignition source near alcohol vapour.",
                      "Never run the alcohol step and the battery step at the same time or on the same surface. Close and put away the alcohol, then ventilate the area, before the battery leaves its packaging."),
                     ("physical", "Battery testing risks a short circuit that heats the leads.",
                      "Use a 9V battery only - NEVER mains electricity. Include the LED in the circuit, keep leads apart when not testing, and disconnect between tests. An adult builds the circuit."),
                     ("physical", "Warm water can scald.",
                      "Keep water below 50 degrees Celsius and let an adult pour.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop if battery leads or the battery itself become warm.",
                  "Stop all work if a flame, heat source, or battery is present while alcohol is open.",
                  "Never connect anything in this lesson to a wall outlet."],
            alternative="Compare only salt, sugar, and oil in water at room temperature - solubility and mixing behaviour alone - and use published melting-point and conductivity tables for the rest. No battery, no alcohol, no heat, and therefore no ignition risk at all. Choose this path if the two hazardous steps cannot be reliably separated in time and space.",
            data_source="Learner's own solubility and conductivity observations plus published melting-point tables. Rankings are inferred by the learner from what they observe.",
        ),
    ),
    dict(
        title="Chemical Reactions and Electron Rearrangement",
        essential_question="What is actually happening to electrons when one substance turns into another?",
        phenomenon="Steel wool left damp in air grows warm and gains mass, while the same wool kept dry does not change.",
        topics=["evidence of chemical change", "reaction types and patterns", "outermost electron states in reactions",
                "oxidation and reduction basics", "predicting products from periodic trends", "writing and revising explanations"],
        performance_task="Construct and revise an explanation for the outcome of a reaction you ran, grounded in outer-electron states and periodic trends rather than memorised rules.",
        standards=["hs-ps1-2"],
        reinforces=["hs-ps1-1"],
        investigation=dict(
            title="Oxidation of steel wool and acid-base reactions with a natural indicator",
            materials=["plain steel wool (no soap)", "vinegar", "baking soda", "red cabbage", "hot water from the tap",
                       "clear cups", "kitchen scale", "resealable bags"],
            hazards=[("chemical", "Vinegar is a mild acid that stings eyes and open cuts.",
                      "Wear eye protection, work over a tray, and rinse splashes with water."),
                     ("chemical", "Combining household chemicals other than those listed can generate toxic gas.",
                      "Use ONLY vinegar, baking soda, and cabbage indicator. Never add bleach, ammonia, drain cleaner, or any cleaning product. This prohibition is not disableable."),
                     ("physical", "Steel wool fibres cut skin and can ignite if they contact a battery or flame.",
                      "Wear gloves, keep steel wool far from all batteries and heat sources, and dispose of it in a sealed bag.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop immediately if any cleaning product is brought near the work area.",
                  "Stop if steel wool warms noticeably while dry or contacts any battery.",
                  "Stop if a sealed bag inflates; open it outdoors and away from faces."],
            alternative="Run the cabbage-indicator colour scale with vinegar and baking soda only - no steel wool - and analyse published mass-change data for the rusting reaction. Kitchen materials only.",
            data_source="Learner's own mass measurements before and after oxidation, and their own indicator colour observations. Published data is used only for comparison.",
        ),
    ),
    dict(
        title="Conservation of Mass and Quantitative Reasoning in Reactions",
        essential_question="If atoms are never created or destroyed, why does a reaction so often look like mass disappeared?",
        phenomenon="Baking soda and vinegar in an open cup lose mass as they fizz; the same reaction in a sealed bag does not.",
        topics=["conservation of atoms and mass", "balancing equations as bookkeeping", "the mole as a counting unit",
                "molar mass and formula mass", "limiting reactants", "mathematical representations of reactions"],
        performance_task="Use your own mass measurements from open and closed systems to support the claim that atoms and mass are conserved, and explain the open-system loss quantitatively.",
        standards=["hs-ps1-7"],
        reinforces=["hs-ps1-2"],
        investigation=dict(
            title="Open versus closed system mass accounting",
            materials=["baking soda", "vinegar", "resealable freezer bags", "clear cups", "kitchen scale reading to 1 g or better",
                       "tray", "notebook"],
            hazards=[("chemical", "Vinegar stings eyes; the reaction produces carbon dioxide.",
                      "Wear eye protection and work in a ventilated room. Carbon dioxide is not toxic at these quantities but the bag must never be sealed rigid."),
                     ("physical", "A sealed bag can burst and spray liquid.",
                      "Use no more than a teaspoon of baking soda, leave the bag partly unsealed or seal loosely, keep it on a tray at arm's length, and point it away from all faces.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop and release pressure if a bag becomes taut.",
                  "Stop if liquid contacts the eyes and rinse for 15 minutes."],
            alternative="Do the mass accounting from a supplied table of published open- and closed-system masses, balancing the equation and computing expected gas mass by hand. Paper and calculator only.",
            data_source="Learner's own before-and-after masses in both systems. The mass of gas lost is derived by the learner; no expected number is supplied first.",
        ),
    ),
    dict(
        title="Energy in Chemical Systems",
        essential_question="Why do some reactions warm their surroundings and others chill them, when both are just rearranging bonds?",
        phenomenon="One instant cold pack and one hand warmer are both sealed pouches you squeeze, and they do opposite things.",
        topics=["bond breaking and bond making", "exothermic and endothermic processes", "total bond energy changes",
                "thermal energy transfer and equilibration", "computational energy models", "the second law in everyday systems"],
        performance_task="Develop a model showing that energy release or absorption depends on total bond energy change, and build a computational energy account for a system you measured.",
        standards=["hs-ps1-4"],
        reinforces=["hs-ps3-1", "hs-ps3-2", "hs-ps3-4"],
        investigation=dict(
            title="Measuring temperature change in dissolution and reaction",
            materials=["baking soda", "vinegar", "Epsom salt", "calcium chloride ice-melt or road salt (optional)",
                       "water", "thermometer", "insulated cup", "kitchen scale", "timer"],
            hazards=[("chemical", "Calcium chloride releases substantial heat when dissolving and can burn skin and eyes.",
                      "This route is OPTIONAL. If used, an adult handles the solid, the learner wears eye protection and gloves, quantities stay under one teaspoon, and the solution is never touched while warm."),
                     ("physical", "Solutions can become hot enough to burn.",
                      "Use an insulated cup on a tray, measure with the thermometer rather than by hand, and stop if the solution exceeds 50 degrees Celsius.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop if any solution exceeds 50 degrees Celsius.",
                  "Stop if calcium chloride contacts skin and rinse thoroughly for 15 minutes.",
                  "Skip the calcium chloride route entirely if eye protection and gloves are not available."],
            alternative="Use Epsom salt and baking soda with vinegar only - both mild - to observe cooling and mild warming, or work entirely from a published table of dissolution enthalpies and bond energies. Kitchen materials or paper.",
            data_source="Learner's own temperature-versus-time measurements, plus published bond-energy tables for the model. No temperature change is predicted numerically before measurement.",
        ),
    ),
    dict(
        title="Reaction Rates and the Conditions That Change Them",
        essential_question="What has to be true at the particle level for a reaction to go faster?",
        phenomenon="A glow stick snapped in ice water stays bright far longer than an identical one in warm water.",
        topics=["collision model of reactions", "temperature and reaction rate", "concentration and reaction rate",
                "surface area and mixing", "catalysts", "explaining rate with scientific principles"],
        performance_task="Apply the collision model and your own rate data to explain how temperature and concentration change reaction rate, and identify the variable your design failed to control.",
        standards=["hs-ps1-5"],
        reinforces=["hs-ls1-6"],
        investigation=dict(
            title="Rate of an effervescent or enzymatic reaction under varied conditions",
            materials=["effervescent tablets or baking soda", "vinegar at several dilutions", "cold, room-temperature, and warm water",
                       "clear cups", "timer", "thermometer", "notebook"],
            hazards=[("chemical", "Vinegar and effervescent tablets irritate eyes.",
                      "Wear eye protection, work over a tray, and rinse splashes with water."),
                     ("physical", "Warm water can scald and glass can break with thermal shock.",
                      "Keep water below 50 degrees Celsius, use plastic or unbreakable cups only, and let an adult pour warm water.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop if water is hot enough to be uncomfortable to touch.",
                  "Never seal a container during an effervescent reaction."],
            alternative="Vary only surface area and concentration at room temperature - whole versus crushed tablet, full-strength versus diluted vinegar - eliminating all heating. Or analyse a published rate-versus-temperature dataset. Kitchen materials or paper.",
            data_source="Learner-timed reaction completions across their own conditions. Rate relationships are inferred from the learner's plotted data.",
        ),
    ),
    dict(
        title="Equilibrium and the Design of Chemical Systems",
        essential_question="How can a reaction be running hard in both directions and still look like nothing is happening?",
        phenomenon="A sealed bottle of fizzy water looks perfectly still until the cap comes off.",
        topics=["reversible reactions", "dynamic equilibrium", "stress and system response",
                "shifting equilibrium by changing conditions", "yield and industrial trade-offs", "refining a chemical system design"],
        performance_task="Refine the design of a chemical system by specifying a condition change that would increase product at equilibrium, and defend the change with evidence and stated trade-offs.",
        standards=["hs-ps1-6"],
        reinforces=["hs-ets1-3"],
        investigation=dict(
            title="Shifting a visible equilibrium with a natural indicator",
            materials=["red cabbage indicator", "vinegar", "baking soda solution", "carbonated water",
                       "clear cups", "droppers", "warm and cool water baths", "notebook"],
            hazards=[("chemical", "Acidic and basic solutions sting eyes and irritate skin.",
                      "Wear eye protection, work over a tray, use small volumes with droppers, and rinse any splash with water for 15 minutes."),
                     ("chemical", "Household chemical mixing beyond the listed materials can produce toxic gas.",
                      "Use ONLY cabbage indicator, vinegar, baking soda, and carbonated water. Never introduce a cleaning product. This prohibition is not disableable.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop if any solution contacts the eyes and rinse for 15 minutes.",
                  "Stop all work if a cleaning product enters the work area."],
            alternative="Observe the carbon-dioxide equilibrium in carbonated water alone - sealed versus open, cool versus warm - with no indicator chemistry, or reason from a published equilibrium dataset. Kitchen materials or paper.",
            data_source="Learner's own colour and effervescence observations across conditions. Direction of shift is concluded by the learner from what they see.",
        ),
    ),
    dict(
        title="The Nucleus, Nuclear Energy, and a Chemistry Engineering Capstone",
        essential_question="What changes when the nucleus itself is rearranged, and how should a society weigh the trade-offs?",
        phenomenon="A smoke detector contains a radioactive source, runs for a decade, and is safe to hold - while a comparable mass of the same isotope in another form would not be.",
        topics=["nuclear composition and isotopes", "radioactive decay and half-life", "fission",
                "fusion", "mass-energy and nuclear energy scale", "criteria, constraints, and trade-offs in chemical engineering"],
        performance_task="Complete a chemistry engineering capstone: analyse a real materials or energy challenge, model a chemical solution including nuclear or energy trade-offs, evaluate it against prioritised criteria, and defend the revisions.",
        standards=["hs-ps1-8", "hs-ets1-1", "hs-ets1-2", "hs-ets1-3"],
        reinforces=["hs-ps1-4"],
        investigation=dict(
            title="Half-life modelling and a materials trade-off analysis",
            materials=["100 coins or dice", "container", "graph paper or spreadsheet", "calculator",
                       "published decay dataset", "published materials-property data"],
            hazards=[("physical", "Large numbers of small counters spread and can be a choking hazard.",
                      "Work in a shallow tray, keep counters away from young children, and count them back at the end."),
                     ("emotional", "Nuclear topics can raise anxiety about weapons or accidents.",
                      "Content stays on decay physics, energy scale, and engineering trade-offs; the learner may pause or redirect to the materials strand at any point.")],
            supervision="none",
            visibility="summary",
            stop=["Pause if nuclear content becomes distressing and continue with the materials trade-off strand.",
                  "NO RADIOACTIVE SOURCE OF ANY KIND IS USED OR ACQUIRED IN THIS UNIT."],
            alternative="Model half-life with a single die and tally marks on paper instead of 100 coins, then complete the trade-off analysis from published materials data. Paper only.",
            data_source="Learner's own coin- or dice-decay trials plotted against the exponential model, plus published decay and materials data. No radiation measurement is taken.",
        ),
    ),
]

PHYSICS = [
    dict(
        title="Motion, Measurement, and Quantitative Reasoning",
        essential_question="How do we describe motion precisely enough that someone else can check us?",
        phenomenon="A ball rolled down a ramp covers far more distance in its third second than its first, even though nothing pushes it.",
        topics=["position, displacement, and reference frames", "velocity and acceleration", "motion graphs and their slopes",
                "uniform acceleration relationships", "measurement uncertainty in motion", "vectors and components"],
        performance_task="Measure a real accelerating motion, produce position, velocity, and acceleration representations from your own data, and report the acceleration with an honest uncertainty.",
        standards=[],
        reinforces=["hs-ps2-1"],
        investigation=dict(
            title="Timing accelerated motion on a ramp",
            materials=["board or stiff cardboard for a ramp", "ball or toy car", "measuring tape", "stopwatch or phone timer",
                       "books to set ramp height", "masking tape", "notebook"],
            hazards=[("physical", "A ball leaving a ramp can trip someone or strike an object.",
                      "Set the ramp so the run ends against a soft barrier, clear the floor path, keep the ramp low, and keep pets and young children out of the area.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if the ball repeatedly leaves the intended path.",
                  "Stop if anyone enters the run area."],
            alternative="Analyse a published motion dataset or a frame-numbered motion diagram supplied on paper, extracting velocity and acceleration by hand. No ramp, no timing, paper only.",
            data_source="Learner's own repeated timing trials over measured distances. Acceleration is computed from the learner's data, never supplied.",
        ),
    ),
    dict(
        title="Forces and Newton's Second Law",
        essential_question="What exactly is the relationship among net force, mass, and acceleration - and how would you know?",
        phenomenon="A loaded wagon and an empty one, pulled with what feels like the same effort, reach very different speeds.",
        topics=["free-body diagrams", "net force", "Newton's second law as a mathematical relationship",
                "mass versus weight", "friction and normal forces", "analysing force data"],
        performance_task="Analyse your own data to support or challenge the claim that net force, mass, and acceleration follow Newton's second law, and account for the friction your model ignored.",
        standards=["hs-ps2-1"],
        reinforces=[],
        investigation=dict(
            title="Varying mass and force on a rolling cart",
            materials=["toy car or cart", "string", "pulley or smooth table edge", "small weights or coins",
                       "measuring tape", "timer", "kitchen scale", "notebook"],
            hazards=[("physical", "Falling weights can land on feet or break flooring.",
                      "Keep masses small, place a cushion or towel below the drop zone, keep feet clear, and never stand under the hanging mass."),
                     ("physical", "String under tension can snap back.",
                      "Use light loads only, inspect the string before each run, and keep faces away from the string line.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if the string frays or the pulley slips.",
                  "Stop if anyone's feet are in the drop zone."],
            alternative="Use a published force-mass-acceleration dataset and a supplied set of free-body diagrams; derive the relationship graphically. Paper and calculator only.",
            data_source="Learner's own timing and mass measurements across conditions. The proportionality is fitted by the learner from their own plotted data.",
        ),
    ),
    dict(
        title="Momentum, Collisions, and Protective Design",
        essential_question="What is conserved in a collision, and how do we use that to keep people safe?",
        phenomenon="An egg dropped onto a folded towel survives a fall that shatters it on bare tile.",
        topics=["momentum as mass times velocity", "conservation of momentum", "impulse and contact time",
                "elastic and inelastic collisions", "collision analysis from data", "engineering a protective device"],
        performance_task="Design, test, and refine a device that minimises the force on an object during a collision, and use momentum and impulse reasoning plus your own trial data to justify each revision.",
        standards=["hs-ps2-2", "hs-ps2-3"],
        reinforces=["hs-ets1-2", "hs-ets1-3"],
        investigation=dict(
            title="Impact-protection design and collision trials",
            materials=["raw eggs or a small fragile object", "padding materials from the household", "measuring tape",
                       "tray or tarp for the landing zone", "toy cars for the collision strand", "notebook"],
            hazards=[("physical", "Dropping objects from height risks falls and impacts.",
                      "Drop from standing height at most, never from a ladder, chair, or window. The learner stands clear of the landing zone."),
                     ("physical", "Raw egg is a salmonella exposure and a slip hazard.",
                      "Contain every drop in a tray or tarp, wear gloves or wash hands thoroughly after each trial, disinfect the area, and never eat or drink in the work area.")],
            supervision="nearby-adult",
            visibility="confirmation-required",
            stop=["Stop if anyone climbs on furniture to increase drop height.",
                  "Stop and clean thoroughly if raw egg contacts skin, and wash hands before touching anything else."],
            alternative="Use a sealed water balloon, a small beanbag, or a marshmallow instead of an egg - no biological hazard, no cleanup - or run the collision strand with toy cars only and analyse published crash-test data for the protective design. ",
            data_source="Learner's own survival counts, drop heights, and cart velocities. Impulse comparisons come from the learner's own trials.",
        ),
    ),
    dict(
        title="Gravitation and Electrostatic Forces",
        essential_question="Why do gravity and the electric force follow the same mathematical shape while behaving so differently?",
        phenomenon="A charged balloon lifts hair against the pull of the entire Earth.",
        topics=["Newton's law of gravitation", "Coulomb's law", "inverse-square relationships",
                "comparing gravitational and electrostatic strength", "field lines as representations", "predicting forces mathematically"],
        performance_task="Use mathematical representations of Newton's law of gravitation and Coulomb's law to predict and compare forces in real situations, and explain why one dominates at each scale.",
        standards=["hs-ps2-4"],
        reinforces=["hs-ess1-4"],
        investigation=dict(
            title="Electrostatic force behaviour and inverse-square modelling",
            materials=["balloons", "wool or hair", "small paper pieces", "thread", "ruler",
                       "flashlight and paper (light-intensity inverse-square route)", "notebook"],
            hazards=[("physical", "Balloons can pop suddenly and are a choking hazard for young children.",
                      "Keep balloon fragments away from young children, and anyone with a latex allergy uses the light-intensity route instead."),
                     ("physical", "Static discharge is startling though harmless at this scale.",
                      "Keep all static work away from electronics and never perform static work near a computer or a fuel source.")],
            supervision="none",
            visibility="summary",
            stop=["Stop static work near any electronic device.",
                  "Switch to the light route if anyone present has a latex allergy."],
            alternative="Demonstrate the inverse-square relationship with a flashlight and a ruler, measuring illuminated area against distance, then apply the same mathematics to gravitation and Coulomb's law using published masses and charges. Household items and paper.",
            data_source="Learner's own separation-versus-effect observations and their own calculations from published masses, charges, and distances.",
        ),
    ),
    dict(
        title="Energy: Modelling, Accounting, and Conservation",
        essential_question="If energy is always conserved, why does everything eventually stop?",
        phenomenon="A bouncing ball returns to a lower height every bounce, yet nothing about it looks like it is losing anything.",
        topics=["kinetic and potential energy", "energy as a system-level account", "computational energy models",
                "energy at macroscopic and particle scales", "energy transfer and dissipation", "building and checking an energy budget"],
        performance_task="Create a computational model that calculates the energy change of one component of a system from the changes in the others, and test it against a system you measured.",
        standards=["hs-ps3-1", "hs-ps3-2"],
        reinforces=["hs-ps1-4"],
        investigation=dict(
            title="Energy accounting for a bouncing ball or a pendulum",
            materials=["bouncy ball or pendulum bob on string", "measuring tape", "timer", "kitchen scale",
                       "spreadsheet or graph paper", "notebook"],
            hazards=[("physical", "A swinging pendulum or bouncing ball can strike a person or object.",
                      "Clear a radius larger than the string length, keep the bob light, swing at small angles, and keep faces and screens out of the swing plane.")],
            supervision="none",
            visibility="summary",
            stop=["Stop if the bob or ball leaves the cleared area.",
                  "Stop if the string shows any sign of fraying."],
            alternative="Build the energy budget from a supplied table of published bounce heights or pendulum periods, computing the model by hand. Paper and calculator only.",
            data_source="Learner's own height, mass, and time measurements. Energy losses are computed by the learner from their own numbers.",
        ),
    ),
    dict(
        title="Thermal Energy and the Second Law",
        essential_question="Why does energy spread out on its own, and never gather itself back up?",
        phenomenon="A metal spoon and a wooden spoon left in the same room feel like different temperatures to the hand.",
        topics=["temperature versus thermal energy", "conduction, convection, and radiation", "thermal equilibrium",
                "specific heat capacity", "the second law of thermodynamics", "investigating energy distribution"],
        performance_task="Plan and conduct an investigation providing evidence that combining components at different temperatures in a closed system produces a more uniform energy distribution.",
        standards=["hs-ps3-4"],
        reinforces=["hs-ps1-4", "hs-ess2-4"],
        investigation=dict(
            title="Thermal equilibration in an insulated system",
            materials=["insulated cups or a thermos", "thermometer", "warm and cool water", "kitchen scale",
                       "timer", "notebook", "assorted materials for the insulation strand"],
            hazards=[("physical", "Hot water scalds, and the risk rises with temperature.",
                      "Keep all water below 50 degrees Celsius. An adult measures and pours every warm sample. The learner never carries an open container of warm water."),
                     ("physical", "Thermometers can break; mercury thermometers must never be used.",
                      "Use a digital or alcohol thermometer only. If any thermometer breaks, an adult clears it.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop if water exceeds 50 degrees Celsius.",
                  "Stop and let an adult clear any broken thermometer.",
                  "Never use a mercury thermometer for any part of this unit."],
            alternative="Use a published cooling-curve dataset, or run the whole investigation at room temperature versus refrigerator temperature - no heating at all. Both meet the equilibration target.",
            data_source="Learner-recorded temperature-versus-time series for their own system. Final equilibrium temperature is measured, then compared with the learner's own prediction.",
        ),
    ),
    dict(
        title="Fields, Electromagnetism, and Induction",
        essential_question="How can a moving magnet create a current in a wire it never touches?",
        phenomenon="A bicycle light with no battery glows brighter the faster the wheel turns.",
        topics=["electric and magnetic fields", "current and magnetic field production", "electromagnetic induction",
                "field models of interaction at a distance", "energy changes in field interactions", "investigating induction"],
        performance_task="Plan and conduct an investigation providing evidence that a current produces a magnetic field and that a changing magnetic field produces a current, and model the energy change involved.",
        standards=["hs-ps2-5", "hs-ps3-5"],
        reinforces=["hs-ps2-4"],
        investigation=dict(
            title="Electromagnet construction and induction with a coil and magnet",
            materials=["insulated copper wire", "iron nail", "D-cell or AA battery with holder", "compass",
                       "strong magnet", "coil of many wire turns", "sensitive multimeter or LED", "paper clips"],
            hazards=[("physical", "A wire connected directly across a battery heats rapidly and can burn skin or start a fire.",
                      "Always include the nail or coil as resistance, use a single 1.5 V cell - NEVER mains electricity and never a lithium or button cell - connect only for a few seconds at a time, and disconnect between trials. An adult supervises every connection."),
                     ("physical", "Strong neodymium magnets pinch skin severely and destroy electronics and cards.",
                      "Handle magnets one at a time, keep them well away from phones, laptops, bank cards, and any medical device such as a pacemaker, and store them separated.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop immediately and disconnect if the wire, battery, or nail becomes warm.",
                  "Stop if a magnet approaches any electronic device or anyone with an implanted medical device.",
                  "Never connect any part of this investigation to a wall outlet."],
            alternative="Map a magnetic field with a compass and a permanent magnet only - no battery, no circuit - and study induction from published data or a supplied diagram sequence. Compass and paper only.",
            data_source="Learner's own compass deflections, paper-clip counts, and meter or LED observations across conditions.",
        ),
    ),
    dict(
        title="Waves and Their Mathematics",
        essential_question="What stays the same and what changes when a wave crosses into a new material?",
        phenomenon="A straw in a glass of water looks broken at the surface, and the break shifts as you move your head.",
        topics=["wave properties and terminology", "the frequency-wavelength-speed relationship", "waves in different media",
                "reflection, refraction, and diffraction", "wave and particle models of light", "evaluating competing models"],
        performance_task="Use mathematical representations to support a claim about frequency, wavelength, and speed in different media, and evaluate when a wave model or a particle model of light serves better.",
        standards=["hs-ps4-1", "hs-ps4-3"],
        reinforces=["hs-ps4-4"],
        investigation=dict(
            title="Wave speed in a spring and light behaviour at boundaries",
            materials=["long spring or rope", "measuring tape", "timer", "shallow tray of water",
                       "flashlight or LED", "CD or DVD as a diffraction grating", "clear container", "notebook"],
            hazards=[("physical", "A stretched spring released under tension snaps back hard and can injure eyes.",
                      "Two people hold the ends, never stretch beyond about twice the resting length, keep faces away from the line of the spring, and release tension slowly and deliberately."),
                     ("physical", "Bright light sources can damage vision.",
                      "Use a flashlight or LED only. NO LASER of any kind is used in this unit. Never look directly into any light source or point one at another person.")],
            supervision="nearby-adult",
            visibility="confirmation-required",
            stop=["Stop if the spring is stretched near its limit or if anyone is in its recoil path.",
                  "Stop if any light source is pointed toward a face.",
                  "Do not substitute a laser pointer for the flashlight under any circumstances."],
            alternative="Measure wave speed on a rope on the floor - no tension, no recoil - and observe diffraction with a CD held under a household lamp. Or work from published wave-speed tables and a supplied refraction diagram. No spring, no bright source.",
            data_source="Learner-timed pulse round trips over measured lengths and their own boundary observations. Wave speed is computed from the learner's own data.",
        ),
    ),
    dict(
        title="Electromagnetic Radiation, Information, and a Physics Engineering Capstone",
        essential_question="How do we send information reliably using something we cannot see?",
        phenomenon="A phone in a metal box loses signal completely, while the same phone behind a wooden door does not.",
        topics=["the electromagnetic spectrum", "absorption of radiation by matter", "digital versus analog information",
                "evaluating published claims about radiation", "wave-based technologies", "energy conversion device design"],
        performance_task="Complete a physics engineering capstone: design, build, and refine a device that converts one form of energy into another or transmits information, and communicate how wave principles and evidence justify the design.",
        standards=["hs-ps4-2", "hs-ps4-4", "hs-ps4-5", "hs-ps3-3", "hs-ets1-1", "hs-ets1-2", "hs-ets1-3"],
        reinforces=["hs-ps4-1"],
        investigation=dict(
            title="Signal transmission, shielding, and an energy-conversion device build",
            materials=["small radio or phone", "aluminium foil", "cardboard boxes", "assorted household materials",
                       "small motor or LED", "battery", "published claim article about radiation", "notebook"],
            hazards=[("physical", "Building a device involves cutting and small parts.",
                      "An adult performs all cutting with sharp tools, the learner uses blunt scissors or pre-cut parts, and small parts stay away from young children."),
                     ("physical", "Battery-powered builds can short and heat.",
                      "Single 1.5 V cells only - never mains electricity, never a lithium or button cell. Disconnect between tests and stop if anything warms."),
                     ("online", "Evaluating published radiation claims means reading sources of uncertain quality.",
                      "An adult approves each source in advance. No account creation, sign-in, purchase, or personal information is required, and the learner never contacts a site owner.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop if any component becomes warm.",
                  "Stop if a source requests an account, payment, or personal information.",
                  "Never connect any build to a wall outlet."],
            alternative="Run the shielding test with a radio and household materials only - no build - and complete the capstone as a documented paper design with a modelled energy budget rather than a physical device.",
            data_source="Learner's own signal-strength observations across shielding materials and their own device performance trials. Published claims are evaluated, never restated as findings.",
        ),
    ),
]

EARTH_SPACE = [
    dict(
        title="Earth and Space Systems, Scale, and Data Practice",
        essential_question="How do we reason honestly about systems too large, too slow, or too far away to experiment on?",
        phenomenon="Two published graphs of the same climate record look like they tell opposite stories, purely because of their axes.",
        topics=["systems and system models", "spatial and temporal scale", "proxy data and indirect evidence",
                "uncertainty in geoscience data", "reading and building graphs honestly", "distinguishing correlation and causation"],
        performance_task="Take one published geoscience or astronomical dataset, build an honest representation of it, and document every choice that could mislead a reader.",
        standards=[],
        reinforces=["hs-ess3-5"],
        investigation=dict(
            title="Scale modelling and critical analysis of published representations",
            materials=["published geoscience dataset", "graph paper or spreadsheet", "measuring tape", "string",
                       "calculator", "notebook"],
            hazards=[("online", "Locating datasets online can expose the learner to tracking or account prompts.",
                      "An adult supplies the dataset file or exact source. No account creation, sign-in, or purchase is required."),
                     ("physical", "Building a large scale model outdoors involves walking measured distances.",
                      "Stay on the property or in a park away from roads and water, with an adult aware of the route.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if a site requests an account, payment, or personal information.",
                  "Stop outdoor work near any road, water body, or unstable ground."],
            alternative="Do the scale model on paper at desk scale rather than walking it outdoors, and analyse a printed dataset supplied by the adult. Paper only.",
            data_source="Published datasets the family retrieves plus the learner's own graphs and scale calculations.",
        ),
    ),
    dict(
        title="The Sun, Stars, and the Origin of the Elements",
        essential_question="Where did the atoms in your body actually come from?",
        phenomenon="The sun has been radiating enormous power for billions of years without burning out or collapsing.",
        topics=["nuclear fusion in stellar cores", "the sun's energy budget and lifespan", "stellar life cycles",
                "nucleosynthesis and element formation", "spectra as compositional evidence", "communicating stellar science"],
        performance_task="Develop an evidence-based model of the sun's life span and energy source, and communicate how stars across their life cycle produce the elements in ordinary matter.",
        standards=["hs-ess1-1", "hs-ess1-3"],
        reinforces=["hs-ps1-8", "hs-ps3-1"],
        investigation=dict(
            title="Solar energy measurement and spectral element identification",
            materials=["thermometer", "dark container of water", "timer", "measuring cup",
                       "CD or diffraction grating", "published stellar spectra", "notebook"],
            hazards=[("physical", "Looking at the sun causes permanent eye damage.",
                      "NEVER look at the sun directly, through any lens, grating, CD, camera, or filter. All solar work is done by measuring warming water in shade-versus-sun, with the learner's back to the sun."),
                     ("physical", "Working outdoors in sun risks heat and sunburn.",
                      "Limit exposure, wear a hat and sunscreen, keep drinking water available, and work in the cooler part of the day.")],
            supervision="direct-adult",
            visibility="confirmation-required",
            stop=["Stop instantly if anyone looks toward the sun through any optical device.",
                  "Stop and move indoors at any sign of overheating."],
            alternative="Skip all outdoor solar work: compute the sun's power output and lifetime from published solar-constant and mass data, and identify elements from published stellar spectra images. Paper and calculator only. This is the DEFAULT path.",
            data_source="Published solar constant, solar mass, and stellar spectra, plus the learner's own warming measurements if the outdoor route is used. Fusion rates are computed by the learner.",
        ),
    ),
    dict(
        title="Cosmology and the Evidence for the Big Bang",
        essential_question="What observations force the conclusion that the universe has a history?",
        phenomenon="Nearly every distant galaxy's light is shifted toward red, and the farther away it is, the more shifted it is.",
        topics=["light spectra and redshift", "motion of distant galaxies", "Hubble's relationship",
                "cosmic microwave background", "composition of matter in the universe", "constructing an explanation from multiple evidence lines"],
        performance_task="Construct an explanation of the Big Bang theory from astronomical evidence, weighing how each independent line of evidence constrains the model.",
        standards=["hs-ess1-2"],
        reinforces=["hs-ess1-3"],
        investigation=dict(
            title="Expansion modelling and analysis of published redshift data",
            materials=["balloon and marker, or elastic band and ruler", "published galaxy redshift and distance dataset",
                       "graph paper or spreadsheet", "calculator", "notebook"],
            hazards=[("physical", "Balloons pop and are a choking hazard for young children.",
                      "Keep fragments away from young children; anyone with a latex allergy uses the elastic-band model."),
                     ("emotional", "Cosmological scale and deep time can be unsettling for some learners.",
                      "Pace the content, keep the focus on evidence and reasoning, and allow the learner to pause at any point.")],
            supervision="none",
            visibility="summary",
            stop=["Switch to the elastic-band model if anyone present has a latex allergy.",
                  "Pause if the scale content becomes distressing."],
            alternative="Model expansion with dots drawn on an elastic band stretched along a ruler, then fit published redshift-distance data by hand. No balloon, paper and ruler only.",
            data_source="Published galaxy redshift and distance measurements the family retrieves. The learner fits the relationship themselves; no expansion rate is supplied.",
        ),
    ),
    dict(
        title="Orbital Motion and the Solar System",
        essential_question="Why do orbits keep their shape, and what would it take to change one?",
        phenomenon="A comet spends decades far from the sun and then whips through the inner solar system in weeks.",
        topics=["gravitational orbits", "Kepler's relationships", "orbital period and radius",
                "elliptical orbits and orbital energy", "computational prediction of orbits", "solar system architecture"],
        performance_task="Use mathematical or computational representations to predict the motion of orbiting bodies, and test your predictions against published orbital data.",
        standards=["hs-ess1-4"],
        reinforces=["hs-ps2-4", "hs-ets1-4"],
        investigation=dict(
            title="Orbital prediction from published solar system data",
            materials=["published orbital dataset for planets or moons", "spreadsheet or graph paper", "calculator",
                       "string, pins, and cardboard for ellipse construction", "notebook"],
            hazards=[("physical", "Pins used to draw ellipses can prick or be stepped on.",
                      "Push pins into a cardboard backing on a table, count them out and back in, and keep them away from young children and off the floor.")],
            supervision="none",
            visibility="summary",
            stop=["Stop and account for every pin before leaving the work area."],
            alternative="Construct ellipses with a compass and ruler rather than pins and string, and complete all orbital prediction arithmetically from the published dataset. Paper only.",
            data_source="Published planetary and satellite orbital periods and radii. The learner derives and tests the period-radius relationship from that data.",
        ),
    ),
    dict(
        title="Plate Tectonics and the History of Earth",
        essential_question="How can rock that formed at the bottom of an ocean end up on a mountaintop?",
        phenomenon="Identical fossil species appear on coastlines now separated by an entire ocean.",
        topics=["evidence for plate motion", "seafloor age and magnetic striping", "convection in Earth's interior",
                "continental and oceanic crust formation", "radiometric dating and Earth's age", "reconstructing geologic history"],
        performance_task="Evaluate multiple lines of evidence for past and current crustal movement, and construct an account of Earth's formation and early history from ancient materials and planetary surfaces.",
        standards=["hs-ess1-5", "hs-ess1-6", "hs-ess2-1", "hs-ess2-3"],
        reinforces=["hs-ps1-8"],
        investigation=dict(
            title="Seafloor age mapping and a convection model",
            materials=["published seafloor age and crustal age datasets", "coloured pencils", "graph paper",
                       "clear heatproof container", "warm water, cool water, food colouring (convection route)", "notebook"],
            hazards=[("physical", "Warm water used for the convection model can scald, and glass can crack from thermal shock.",
                      "Keep water below 50 degrees Celsius, use a plastic or heatproof container, and let an adult pour."),
                     ("physical", "Food colouring stains surfaces and clothing.",
                      "Work over a tray with old clothing or an apron.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if water is uncomfortable to touch.",
                  "Stop if a container shows any crack."],
            alternative="Do the convection strand from a published thermal-convection diagram sequence and complete the seafloor age mapping with coloured pencils on a printed map. No water, paper only.",
            data_source="Published seafloor age, radiometric age, and fossil distribution data. Spreading rates are calculated by the learner from the map.",
        ),
    ),
    dict(
        title="Surface Processes, Water, and Earth System Feedbacks",
        essential_question="How does one change to Earth's surface end up changing systems far away from it?",
        phenomenon="Removing vegetation from a hillside changes the temperature, the water table, and the air quality of a valley kilometres downstream.",
        topics=["weathering and erosion", "the special properties of water", "surface water and groundwater systems",
                "feedbacks between Earth systems", "human alteration of surface processes", "investigating water and Earth materials"],
        performance_task="Plan and conduct an investigation of water's properties and their effects on Earth materials, then analyse geoscience data to claim that one surface change creates feedbacks in other systems.",
        standards=["hs-ess2-2", "hs-ess2-5"],
        reinforces=["hs-ess2-1"],
        investigation=dict(
            title="Erosion, infiltration, and water property testing",
            materials=["soil, sand, and gravel", "trays or baking pans", "water", "measuring cup", "timer",
                       "ice", "thermometer", "published watershed dataset", "notebook"],
            hazards=[("physical", "Soil and outdoor materials carry bacteria and sharp fragments.",
                      "Wear gloves, keep hands away from the face, wash thoroughly afterwards, and never use soil from an area treated with pesticide or near a roadway."),
                     ("physical", "Water and soil together make surfaces slippery.",
                      "Work outdoors or over a large tray, and clean spills immediately."),
                     ("privacy", "Photographing or logging a field site can reveal where the family lives.",
                      "Record substrate type, slope, and conditions only. No address, GPS coordinate, or identifiable landmark is recorded, and no photograph is required.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if soil source is unknown or possibly contaminated.",
                  "Stop outdoor work near any road, steep bank, or water body."],
            alternative="Compare infiltration through sand, gravel, and packed soil in three cups on a tray indoors, or work entirely from a published watershed dataset. Kitchen materials or paper.",
            data_source="Learner's own infiltration times, sediment transport observations, and temperature readings, plus a published watershed dataset for comparison.",
        ),
    ),
    dict(
        title="Climate, Energy Flow, and the Carbon Cycle",
        essential_question="What determines Earth's temperature, and how confident can a forecast honestly be?",
        phenomenon="Two cities at the same latitude have average winter temperatures nearly twenty degrees apart.",
        topics=["energy flow into and out of Earth systems", "the greenhouse effect", "the global carbon cycle",
                "climate versus weather", "climate models and their uncertainty", "evidence-based forecasting"],
        performance_task="Use a model of Earth's energy flows and a quantitative carbon-cycle model to make an evidence-based forecast of climate change, with the forecast's uncertainty stated explicitly.",
        standards=["hs-ess2-4", "hs-ess2-6", "hs-ess3-5"],
        reinforces=["hs-ps3-4", "hs-ls2-5"],
        investigation=dict(
            title="Energy balance modelling and carbon cycle quantification",
            materials=["two identical containers", "thermometer", "clear covering", "lamp or sunlight",
                       "published climate and carbon flux datasets", "spreadsheet or graph paper", "notebook"],
            hazards=[("physical", "A lamp used as a light source gets hot and must stay away from water.",
                      "Keep the lamp at least 30 cm from containers, never above water, and let an adult position it. Allow it to cool before moving."),
                     ("emotional", "Climate content can produce genuine anxiety about the future.",
                      "Pair every impact with documented response options and human agency, keep the framing on evidence and design, and let the learner pause or redirect at any time.")],
            supervision="nearby-adult",
            visibility="summary",
            stop=["Stop if any liquid approaches the lamp or its cord.",
                  "Pause and move to the response-and-design strand if the content becomes distressing."],
            alternative="Run the energy-balance comparison in sunlight rather than under a lamp, or skip the physical model entirely and build the energy budget and carbon-cycle quantification from published flux data. Paper and calculator only.",
            data_source="Published climate records, carbon flux estimates, and model outputs the family retrieves, plus the learner's own container temperature series. Forecasts are the learner's own, with stated uncertainty.",
        ),
    ),
    dict(
        title="Coevolution of Earth and Life, Resources, and Natural Hazards",
        essential_question="How have Earth and life reshaped each other, and how does that history set where people can live?",
        phenomenon="Earth's atmosphere contains abundant oxygen, which is chemically reactive and should not persist without something continuously producing it.",
        topics=["the Great Oxidation Event and atmospheric change", "coevolution of the geosphere and biosphere",
                "distribution of natural resources", "natural hazards and their causes", "resource availability and human settlement",
                "constructing arguments from geologic and biological evidence"],
        performance_task="Construct an evidence-based argument about the coevolution of Earth's systems and life, and explain how resource distribution, hazards, and climate change have driven human activity.",
        standards=["hs-ess2-7", "hs-ess3-1"],
        reinforces=["hs-ls4-5", "hs-ls2-6"],
        investigation=dict(
            title="Atmospheric change evidence and a regional resource and hazard analysis",
            materials=["published atmospheric composition and banded-iron-formation data", "published hazard and resource maps",
                       "graph paper", "notebook"],
            hazards=[("privacy", "Mapping local hazards and resources can disclose where the family lives.",
                      "Analyse a region at county scale or larger, or a region the family does not live in. Never record a home address or precise location."),
                     ("emotional", "Natural hazard content can be frightening, especially after a local event.",
                      "Keep the framing on preparation, mitigation, and documented responses; the learner may choose a different region at any point.")],
            supervision="none",
            visibility="summary",
            stop=["Stop if the analysis begins to require the family's precise location.",
                  "Switch regions if hazard content becomes distressing."],
            alternative="Use a supplied printed regional case study rather than searching sources, and complete the argument on paper. No online work required.",
            data_source="Published atmospheric, geologic, resource, and hazard data. The argument and its evidence weighting are the learner's own.",
        ),
    ),
    dict(
        title="Sustainability Engineering and the Grade 12 Capstone",
        essential_question="Given real constraints and real trade-offs, what should actually be done?",
        phenomenon="Two counties facing the same water shortage adopt opposite policies, and both can cite evidence.",
        topics=["criteria, constraints, and prioritisation", "cost-benefit analysis of energy and mineral resources",
                "computational simulation of coupled systems", "refining technological solutions", "sustainability and human population",
                "defending a design under uncertainty"],
        performance_task="Complete the Grade 12 capstone: analyse a global challenge, build a computational simulation of coupled Earth and human systems, evaluate competing solutions on prioritised criteria and trade-offs, refine your solution, and defend it with stated limitations.",
        standards=["hs-ess3-2", "hs-ess3-3", "hs-ess3-4", "hs-ess3-6",
                   "hs-ets1-1", "hs-ets1-2", "hs-ets1-3", "hs-ets1-4"],
        reinforces=["hs-ls2-7", "hs-ess3-1"],
        investigation=dict(
            title="Computational simulation of a coupled resource and sustainability system",
            materials=["spreadsheet or simple programming environment", "published resource, energy, and population datasets",
                       "graph paper", "calculator", "notebook"],
            hazards=[("online", "Building a simulation may involve downloading tools or datasets.",
                      "An adult approves and installs any software and supplies every dataset. No account creation, sign-in, purchase, or personal information is required."),
                     ("emotional", "Sustainability and population content can provoke anxiety or touch on contested politics.",
                      "Keep the work on evidence, explicit criteria, and transparent trade-offs; represent competing positions fairly and let the learner choose the challenge they analyse.")],
            supervision="nearby-adult",
            visibility="confirmation-required",
            stop=["Stop if any tool or site requests an account, payment, or personal information.",
                  "Pause and reselect a challenge if the content becomes distressing."],
            alternative="Build the simulation as an iterated spreadsheet or as a hand-computed table over time steps on paper. No programming environment and no downloads required.",
            data_source="Published resource, energy, and population datasets. All simulation outputs are generated by the learner's own model and reported as model output, never as observed fact.",
        ),
    ),
]

COURSES = [
    dict(course_id="ma-hs9-biology", grade=9, order=1, title="Biology",
         credit_role="Statutory named credit under MCL 380.1278b(1)(b)",
         description=(
             "A first high school laboratory science building directly on the Grade 8 middle-school band. "
             "The course develops molecular and cellular biology from foundations, then raises the Grade 8 heredity, "
             "natural selection, and ecosystem strands to the high school performance-expectation band. Biology is the "
             "credit Michigan names explicitly in MCL 380.1278b(1)(b), so it is placed in Grade 9 and banked first. "
             "Every investigation is household-safe, every investigation has a no-special-equipment alternative, and no "
             "activity anywhere in the course measures the learner's own body or health."),
         capstone=("A biodiversity engineering defense: define criteria and constraints for a real conservation problem, "
                   "model and simulate a solution, evaluate trade-offs, and defend the revision history with stated limitations."),
         units=BIOLOGY),
    dict(course_id="ma-hs10-chemistry", grade=10, order=2, title="Chemistry",
         credit_role="Satisfies the chemistry-or-physics credit by name under MCL 380.1278b(1)(b)",
         description=(
             "A household-safe laboratory chemistry course covering the full HS-PS1 band from measurement and atomic "
             "structure through bonding, reactions, stoichiometry, energy, kinetics, equilibrium, and nuclear change. "
             "Because the course is named Chemistry, it satisfies the second statutory credit directly and no department "
             "determination of benchmark equivalency is required. No investigation uses concentrated acids or bases, "
             "compressed gases, a fume hood, or any chemical needing institutional disposal, and the prohibition on "
             "mixing household cleaning products is stated in every unit and cannot be disabled."),
         capstone=("A chemistry engineering defense: analyse a materials or energy challenge, model a chemical solution "
                   "with its energy and nuclear trade-offs, evaluate against prioritised criteria, and defend the revisions."),
         units=CHEMISTRY),
    dict(course_id="ma-hs11-physics", grade=11, order=3, title="Physics",
         credit_role="Third science credit",
         description=(
             "A quantitative laboratory physics course covering forces, momentum, gravitation and electrostatics, energy, "
             "thermal physics, fields and induction, waves, and electromagnetic radiation. Placed in Grade 11 so it follows "
             "Algebra I and Geometry and runs alongside Algebra II - a Manuel Academy sequencing decision, not a state "
             "requirement. All electrical work uses single low-voltage cells; mains electricity and lasers are excluded "
             "from the course entirely."),
         capstone=("A physics engineering defense: design, build, and refine an energy-conversion or information-transmission "
                   "device, and justify it with wave and energy principles plus the learner's own trial data."),
         units=PHYSICS),
    dict(course_id="ma-hs12-earth-space-environmental", grade=12, order=4,
         title="Earth, Space, and Environmental Systems",
         credit_role="Encouraged fourth credit; statute names Earth science, astronomy, environmental science, and geology",
         description=(
             "An integrated synthesis course covering the full HS-ESS1, HS-ESS2, and HS-ESS3 bands - the 19 performance "
             "expectations most often left uncovered by a three-year disciplinary sequence. Placed last because it genuinely "
             "depends on the other three: stellar nucleosynthesis needs Chemistry's atomic model, the carbon cycle needs "
             "Biology's photosynthesis and respiration, and climate modelling needs all three plus quantitative reasoning. "
             "The course is data-intensive and low-hazard; most investigations use published datasets the family retrieves, "
             "and the sun is never observed directly by any means."),
         capstone=("The Grade 12 capstone: analyse a global challenge, build a computational simulation of coupled Earth and "
                   "human systems, evaluate competing solutions on prioritised criteria and trade-offs, refine, and defend "
                   "with stated limitations."),
         units=EARTH_SPACE),
]

# Attach 1-based unit numbers so generated docs can reference units stably.
for _course in COURSES:
    for _i, _unit in enumerate(_course["units"], start=1):
        _unit["_n"] = _i
