"""Michigan Science Standards (November 2015) - high school performance expectations.

Source: Michigan Department of Education, "Michigan K-12 Standards: Science", November 2015.
https://www.michigan.gov/mde/-/media/Project/Websites/mde/Literacy/Content-Standards/Science_Standards.pdf

Statement text is transcribed from that document. Topic groupings ("group") are the headings the
document itself uses. Flags record the document's own footnote markers:
  "integrates engineering"          = * Integrates traditional science content with engineering.
  "allows Michigan or local context" = ** Allow for local, regional, or Michigan specific contexts.

This file is generated data, not prose to edit by hand. All 71 high school performance
expectations are present; the build refuses to run if that count changes.
"""

PERFORMANCE_EXPECTATIONS = [
    dict(code="HS-PS1-1", group="Structure and Properties of Matter", flags=[],
         statement="Use the periodic table as a model to predict the relative properties of elements based on the patterns of electrons in the outermost energy level of atoms."),
    dict(code="HS-PS1-2", group="Chemical Reactions", flags=[],
         statement="Construct and revise an explanation for the outcome of a simple chemical reaction based on the outermost electron states of atoms, trends in the periodic table, and knowledge of the patterns of chemical properties."),
    dict(code="HS-PS1-3", group="Structure and Properties of Matter", flags=[],
         statement="Plan and conduct an investigation to gather evidence to compare the structure of substances at the bulk scale to infer the strength of electrical forces between particles."),
    dict(code="HS-PS1-4", group="Chemical Reactions", flags=[],
         statement="Develop a model to illustrate that the release or absorption of energy from a chemical reaction system depends upon the changes in total bond energy."),
    dict(code="HS-PS1-5", group="Chemical Reactions", flags=[],
         statement="Apply scientific principles and evidence to provide an explanation about the effects of changing the temperature or concentration of the reacting particles on the rate at which a reaction occurs."),
    dict(code="HS-PS1-6", group="Chemical Reactions", flags=["integrates engineering"],
         statement="Refine the design of a chemical system by specifying a change in conditions that would produce increased amounts of products at equilibrium."),
    dict(code="HS-PS1-7", group="Chemical Reactions", flags=[],
         statement="Use mathematical representations to support the claim that atoms, and therefore mass, are conserved during a chemical reaction."),
    dict(code="HS-PS1-8", group="Structure and Properties of Matter", flags=[],
         statement="Develop models to illustrate the changes in the composition of the nucleus of the atom and the energy released during the processes of fission, fusion, and radioactive decay."),
    dict(code="HS-PS2-1", group="Forces and Interactions", flags=[],
         statement="Analyze data to support the claim that Newton’s second law of motion describes the mathematical relationship among the net force on a macroscopic object, its mass, and its acceleration."),
    dict(code="HS-PS2-2", group="Forces and Interactions", flags=[],
         statement="Use mathematical representations to support the claim that the total momentum of a system of objects is conserved when there is no net force on the system."),
    dict(code="HS-PS2-3", group="Forces and Interactions", flags=["integrates engineering"],
         statement="Apply scientific and engineering ideas to design, evaluate, and refine a device that minimizes the force on a macroscopic object during a collision."),
    dict(code="HS-PS2-4", group="Forces and Interactions", flags=[],
         statement="Use mathematical representations of Newton’s Law of Gravitation and Coulomb’s Law to describe and predict the gravitational and electrostatic forces between objects."),
    dict(code="HS-PS2-5", group="Forces and Interactions", flags=[],
         statement="Plan and conduct an investigation to provide evidence that an electric current can produce a magnetic field and that a changing magnetic field can produce an electric current."),
    dict(code="HS-PS2-6", group="Structure and Properties of Matter", flags=["integrates engineering"],
         statement="Communicate scientific and technical information about why the molecular-level structure is important in the functioning of designed materials."),
    dict(code="HS-PS3-1", group="Energy", flags=[],
         statement="Create a computational model to calculate the change in the energy of one component in a system when the change in energy of the other component(s) and energy flows in and out of the system are known."),
    dict(code="HS-PS3-2", group="Energy", flags=[],
         statement="Develop and use models to illustrate that energy at the macroscopic scale can be accounted for as a combination of energy associated with the motions of particles (objects) and energy associated with the relative position of particles (objects)."),
    dict(code="HS-PS3-3", group="Energy", flags=["integrates engineering"],
         statement="Design, build, and refine a device that works within given constraints to convert one form of energy into another form of energy."),
    dict(code="HS-PS3-4", group="Energy", flags=[],
         statement="Plan and conduct an investigation to provide evidence that the transfer of thermal energy when two components of different temperature are combined within a closed system results in a more uniform energy distribution among the components in the system (second law of thermodynamics)."),
    dict(code="HS-PS3-5", group="Energy", flags=[],
         statement="Develop and use a model of two objects interacting through electric or magnetic fields to illustrate the forces between objects and the changes in energy of the objects due to the interaction."),
    dict(code="HS-PS4-1", group="Waves and Electromagnetic Radiation", flags=[],
         statement="Use mathematical representations to support a claim regarding relationships among the frequency, wavelength, and speed of waves traveling in various media."),
    dict(code="HS-PS4-2", group="Waves and Electromagnetic Radiation", flags=[],
         statement="Evaluate questions about the advantages of using a digital transmission and storage of information."),
    dict(code="HS-PS4-3", group="Waves and Electromagnetic Radiation", flags=[],
         statement="Evaluate the claims, evidence, and reasoning behind the idea that electromagnetic radiation can be described either by a wave model or a particle model, and that for some situations one model is more useful than the other."),
    dict(code="HS-PS4-4", group="Waves and Electromagnetic Radiation", flags=[],
         statement="Evaluate the validity and reliability of claims in published materials of the effects that different frequencies of electromagnetic radiation have when absorbed by matter."),
    dict(code="HS-PS4-5", group="Waves and Electromagnetic Radiation", flags=["integrates engineering"],
         statement="Communicate technical information about how some technological devices use the principles of wave behavior and wave interactions with matter to transmit and capture information and energy."),
    dict(code="HS-LS1-1", group="Structure and Function", flags=[],
         statement="Construct an explanation based on evidence for how the structure of DNA determines the structure of proteins which carry out the essential functions of life through systems of specialized cells."),
    dict(code="HS-LS1-2", group="Structure and Function", flags=[],
         statement="Develop and use a model to illustrate the hierarchical organization of interacting systems that provide specific functions within multicellular organisms."),
    dict(code="HS-LS1-3", group="Structure and Function", flags=[],
         statement="Plan and conduct an investigation to provide evidence that feedback mechanisms maintain homeostasis."),
    dict(code="HS-LS1-4", group="Inheritance and Variation of Traits", flags=[],
         statement="Use a model to illustrate the role of cellular division (mitosis) and differentiation in producing and maintaining complex organisms."),
    dict(code="HS-LS1-5", group="Energy", flags=[],
         statement="Use a model to illustrate how photosynthesis transforms light energy into stored chemical energy."),
    dict(code="HS-LS1-6", group="Energy", flags=[],
         statement="Construct and revise an explanation based on evidence for how carbon, hydrogen, and oxygen from sugar molecules may combine with other elements to form amino acids and/or other large carbon-based molecules."),
    dict(code="HS-LS1-7", group="Energy", flags=[],
         statement="Use a model to illustrate that cellular respiration is a chemical process whereby the bonds of food molecules and oxygen molecules are broken and the bonds in new compounds are formed resulting in a net transfer of energy."),
    dict(code="HS-LS2-1", group="Interdependent Relationships in Ecosystems", flags=[],
         statement="Use mathematical and/or computational representations to support explanations of factors that affect carrying capacity of ecosystems at different scales."),
    dict(code="HS-LS2-2", group="Interdependent Relationships in Ecosystems", flags=[],
         statement="Use mathematical representations to support and revise explanations based on evidence about factors affecting biodiversity and populations in ecosystems of different scales."),
    dict(code="HS-LS2-3", group="Energy", flags=[],
         statement="Construct and revise an explanation based on evidence for the cycling of matter and flow of energy in aerobic and anaerobic conditions."),
    dict(code="HS-LS2-4", group="Energy", flags=["allows Michigan or local context"],
         statement="Use mathematical representations to support claims for the cycling of matter and flow of energy among organisms in an ecosystem."),
    dict(code="HS-LS2-5", group="Energy", flags=["allows Michigan or local context"],
         statement="Develop a model to illustrate the role of photosynthesis and cellular respiration in the cycling of carbon among the biosphere, atmosphere, hydrosphere, and geosphere."),
    dict(code="HS-LS2-6", group="Interdependent Relationships in Ecosystems", flags=["allows Michigan or local context"],
         statement="Evaluate the claims, evidence, and reasoning that the complex interactions in ecosystems maintain relatively consistent numbers and types of organisms in stable conditions, but changing conditions may result in a new ecosystem."),
    dict(code="HS-LS2-7", group="Interdependent Relationships in Ecosystems", flags=["integrates engineering", "allows Michigan or local context"],
         statement="Design, evaluate, and refine a solution for reducing the impacts of human activities on the environment and biodiversity."),
    dict(code="HS-LS2-8", group="Interdependent Relationships in Ecosystems", flags=[],
         statement="Evaluate the evidence for the role of group behavior on individual and species’ chances to survive and reproduce."),
    dict(code="HS-LS3-1", group="Inheritance and Variation of Traits", flags=[],
         statement="Ask questions to clarify relationships about the role of DNA and chromosomes in coding the instructions for characteristic traits passed from parents to offspring."),
    dict(code="HS-LS3-2", group="Inheritance and Variation of Traits", flags=[],
         statement="Make and defend a claim based on evidence that inheritable genetic variations may result from: (1) new genetic combinations through meiosis, (2) viable errors occurring during replication, and/or (3) mutations caused by environmental factors."),
    dict(code="HS-LS3-3", group="Inheritance and Variation of Traits", flags=[],
         statement="Apply concepts of statistics and probability to explain the variation and distribution of expressed traits in a population."),
    dict(code="HS-LS4-1", group="Natural Selection and Evolution", flags=[],
         statement="Communicate scientific information that common ancestry and biological evolution are supported by multiple lines of empirical evidence."),
    dict(code="HS-LS4-2", group="Natural Selection and Evolution", flags=[],
         statement="Construct an explanation based on evidence that the process of evolution primarily results from four factors: (1) the potential for a species to increase in number, (2) the heritable genetic variation of individuals in a species due to mutation and sexual reproduction, (3) competition for limited resources, and (4) the proliferation of those organisms that are better able to survive and reproduce in the environment."),
    dict(code="HS-LS4-3", group="Natural Selection and Evolution", flags=[],
         statement="Apply concepts of statistics and probability to support explanations that organisms with an advantageous heritable trait tend to increase in proportion to organisms lacking this trait."),
    dict(code="HS-LS4-4", group="Natural Selection and Evolution", flags=[],
         statement="Construct an explanation based on evidence for how natural selection leads to adaptation of populations."),
    dict(code="HS-LS4-5", group="Natural Selection and Evolution", flags=[],
         statement="Evaluate the evidence supporting claims that changes in environmental conditions may result in: (1) increases in the number of individuals of some species, (2) the emergence of new species over time, and (3) the extinction of other species."),
    dict(code="HS-LS4-6", group="Interdependent Relationships in Ecosystems", flags=["allows Michigan or local context"],
         statement="Create or revise a simulation to test a solution to mitigate adverse impacts of human activity on biodiversity."),
    dict(code="HS-ESS1-1", group="Space Systems", flags=[],
         statement="Develop a model based on evidence to illustrate the life span of the sun and the role of nuclear fusion in the sun’s core to release energy that eventually reaches Earth in the form of radiation."),
    dict(code="HS-ESS1-2", group="Space Systems", flags=[],
         statement="Construct an explanation of the Big Bang theory based on astronomical evidence of light spectra, motion of distant galaxies, and composition of matter in the universe."),
    dict(code="HS-ESS1-3", group="Space Systems", flags=[],
         statement="Communicate scientific ideas about the way stars, over their life cycle, produce elements."),
    dict(code="HS-ESS1-4", group="Space Systems", flags=[],
         statement="Use mathematical or computational representations to predict the motion of orbiting objects in the solar system."),
    dict(code="HS-ESS1-5", group="History of Earth", flags=[],
         statement="Evaluate evidence of the past and current movements of continental and oceanic crust and the theory of plate tectonics to explain the ages of crustal rocks."),
    dict(code="HS-ESS1-6", group="History of Earth", flags=[],
         statement="Apply scientific reasoning and evidence from ancient Earth materials, meteorites, and other planetary surfaces to construct an account of Earth’s formation and early history."),
    dict(code="HS-ESS2-1", group="History of Earth", flags=[],
         statement="Develop a model to illustrate how Earth’s internal and surface processes operate at different spatial and temporal scales to form continental and ocean-floor features."),
    dict(code="HS-ESS2-2", group="Earth's Systems", flags=[],
         statement="Analyze geoscience data to make the claim that one change to Earth’s surface can create feedbacks that cause changes to other Earth systems."),
    dict(code="HS-ESS2-3", group="Earth's Systems", flags=[],
         statement="Develop a model based on evidence of Earth’s interior to describe the cycling of matter by thermal convection."),
    dict(code="HS-ESS2-4", group="Weather and Climate", flags=[],
         statement="Use a model to describe how variations in the flow of energy into and out of Earth’s systems result in changes in climate."),
    dict(code="HS-ESS2-5", group="Earth's Systems", flags=["allows Michigan or local context"],
         statement="Plan and conduct an investigation of the properties of water and its effects on Earth materials and surface processes."),
    dict(code="HS-ESS2-6", group="Earth's Systems", flags=[],
         statement="Develop a quantitative model to describe the cycling of carbon among the hydrosphere, atmosphere, geosphere, and biosphere."),
    dict(code="HS-ESS2-7", group="Earth's Systems", flags=[],
         statement="Construct an argument based on evidence about the simultaneous coevolution of Earth’s systems and life on Earth."),
    dict(code="HS-ESS3-1", group="Human Sustainability", flags=[],
         statement="Construct an explanation based on evidence for how the availability of natural resources, occurrence of natural hazards, and changes in climate have influenced human activity."),
    dict(code="HS-ESS3-2", group="Human Sustainability", flags=["integrates engineering", "allows Michigan or local context"],
         statement="Evaluate competing design solutions for developing, managing, and utilizing energy and mineral resources based on cost-benefit ratios."),
    dict(code="HS-ESS3-3", group="Human Sustainability", flags=["allows Michigan or local context"],
         statement="Create a computational simulation to illustrate the relationships among management of natural resources, the sustainability of human populations, and biodiversity."),
    dict(code="HS-ESS3-4", group="Human Sustainability", flags=["integrates engineering"],
         statement="Evaluate or refine a technological solution that reduces impacts of human activities on natural systems."),
    dict(code="HS-ESS3-5", group="Weather and Climate", flags=["allows Michigan or local context"],
         statement="Analyze geoscience data and the results from global climate models to make an evidence-based forecast of the current rate of global or regional climate change and associated future impacts to Earth systems."),
    dict(code="HS-ESS3-6", group="Human Sustainability", flags=[],
         statement="Use a computational representation to illustrate the relationships among Earth systems and how those relationships are being modified due to human activity."),
    dict(code="HS-ETS1-1", group="Engineering Design", flags=[],
         statement="Analyze a major global challenge to specify qualitative and quantitative criteria and constraints for solutions that account for societal needs and wants."),
    dict(code="HS-ETS1-2", group="Engineering Design", flags=[],
         statement="Design a solution to a complex real-world problem by breaking it down into smaller, more manageable problems that can be solved through engineering."),
    dict(code="HS-ETS1-3", group="Engineering Design", flags=[],
         statement="Evaluate a solution to a complex real-world problem based on prioritized criteria and trade-offs that account for a range of constraints, including cost, safety, reliability, and aesthetics, as well as possible social, cultural, and environmental impacts."),
    dict(code="HS-ETS1-4", group="Engineering Design", flags=[],
         statement="Use a computer simulation to model the impact of proposed solutions to a complex real-world problem with numerous criteria and constraints on interactions within and between systems relevant to the problem."),
]


def build_framework(framework_id: str, schema_set_version: str) -> dict:
    """Return the standard_framework entity for the authoring set."""
    if len(PERFORMANCE_EXPECTATIONS) != 71:
        raise SystemExit(
            f"expected 71 Michigan high school performance expectations, found {len(PERFORMANCE_EXPECTATIONS)}"
        )
    standards = []
    for pe in PERFORMANCE_EXPECTATIONS:
        note = ""
        if pe["flags"]:
            note = "  [MDE footnote: " + "; ".join(pe["flags"]) + "]"
        standards.append({
            "standard_id": pe["code"].lower(),
            "code": pe["code"],
            "label": pe["group"][:240] or pe["code"],
            "description": (pe["statement"] + note)[:12000],
        })
    return {
        "schema_set_version": schema_set_version,
        "framework_id": framework_id,
        "name": "Michigan Science Standards, high school performance expectations",
        "jurisdiction": "Michigan",
        "framework_version": "November 2015",
        "authority_status": "verified",
        "standards": standards,
    }
