// Generated by tooling/build-registry.sh — do not edit by hand.
import type { LessonSpec } from './types.ts'
import { g09u01 } from './specs/g09u01.ts'
import { g09u02 } from './specs/g09u02.ts'
import { g09u03 } from './specs/g09u03.ts'
import { g09u04 } from './specs/g09u04.ts'
import { g09u05 } from './specs/g09u05.ts'
import { g09u06 } from './specs/g09u06.ts'
import { g09u07 } from './specs/g09u07.ts'
import { g10u01 } from './specs/g10u01.ts'

export const ALL_SPECS: readonly LessonSpec[] = [
  ...g09u01,
  ...g09u02,
  ...g09u03,
  ...g09u04,
  ...g09u05,
  ...g09u06,
  ...g09u07,
  ...g10u01,
]
