// Generated by tooling/build-registry.sh — do not edit by hand.
import type { LessonSpec } from './types.ts'
import { g09u01 } from './specs/g09u01.ts'

export const ALL_SPECS: readonly LessonSpec[] = [
  ...g09u01,
]
