// Generated by tooling/build-registry.sh — do not edit by hand.
import type { LessonSpec } from './types.ts'
import { g09u01 } from './specs/g09u01.ts'
import { g09u02 } from './specs/g09u02.ts'
import { g09u03 } from './specs/g09u03.ts'

export const ALL_SPECS: readonly LessonSpec[] = [
  ...g09u01,
  ...g09u02,
  ...g09u03,
]
