// Generated by tooling/build-registry.sh — do not edit by hand.
import type { LessonSpec } from './types.ts'
import { g11u01 } from './specs/g11u01.ts'
import { g11u02 } from './specs/g11u02.ts'
import { g11u03 } from './specs/g11u03.ts'
import { g11u04 } from './specs/g11u04.ts'
import { g11u05 } from './specs/g11u05.ts'
import { g11u06 } from './specs/g11u06.ts'
import { g11u07 } from './specs/g11u07.ts'

export const ALL_SPECS: readonly LessonSpec[] = [
  ...g11u01,
  ...g11u02,
  ...g11u03,
  ...g11u04,
  ...g11u05,
  ...g11u06,
  ...g11u07,
]
