// Generated by tooling/build-registry.sh — do not edit by hand.
import type { LessonSpec } from './types.ts'
import { g10u03 } from './specs/g10u03.ts'
import { g10u04 } from './specs/g10u04.ts'
import { g10u05 } from './specs/g10u05.ts'
import { g10u06 } from './specs/g10u06.ts'
import { g10u07 } from './specs/g10u07.ts'

export const ALL_SPECS: readonly LessonSpec[] = [
  ...g10u03,
  ...g10u04,
  ...g10u05,
  ...g10u06,
  ...g10u07,
]
