export const HOSTED_SYNC_R2_SCENARIOS = Object.freeze([
  'fresh Device A signs in and hydrates household',
  'Device A starts real-shaped Study state and syncs',
  'fresh Device B signs into the same household',
  'Device B hydrates exact student assignment lesson and progress',
  'Device B resumes exactly where Device A stopped',
  'Device A goes offline and advances',
  'Device A reconnects and uploads',
  'Device B refreshes and receives the update',
  'both devices modify the same Study document from the same base',
  'stale write is rejected and reconciled safely',
  'normal completion propagates',
  'completed lesson never regresses',
  'Ready-for-Life learner finish remains pending',
  'parent attestation propagates across devices',
  'student device cannot self-attest',
  'social dynamic-source attachment propagates',
  'pending-source device cannot start early',
  'safety hold is created and received across devices',
  'offline stale device cannot clear or bypass a hold after reconnect',
  'parent clear propagates',
  'two siblings remain isolated',
  'wrong household is forbidden',
  'auth expiration is handled as auth and not safety',
  'duplicate network retry is idempotent',
  'temporary server outage preserves local progress',
  'device clock skew does not decide truth',
  'logout clears ephemeral authorization',
  'no PIN Tutor transcript or restricted answer authority reaches the server',
  'first link uploads the current learner-ready aggregate exactly once',
  'repeated first link is idempotent',
  'pending and scored learner response records propagate',
  'pending and certified assessment attempt records propagate',
] as const)
