// G34-M5 — Grade 3/4 Health course data.
//
// Standards anchors follow the Michigan Health Education Standards Guidelines
// 2025 (State Board approved 2025-11-13), which reorganize health education
// into six Practices across the grade bands K-2, 3-5, 6-8, 9-12. Grades 3 and 4
// both sit inside the 3-5 band, so the two courses share the band's anchors and
// differ by depth, not by standard.
//
// Each topic carries its own teaching content: `key_points` are the facts and
// rules the session actually teaches, and `scenario` is a fictional worked
// situation for guided practice. Topic order is deliberate — the highest-stakes
// topic in each unit sits at index 1, which the six-day arc maps to the
// explicit-model session.

export const PRACTICE = {
  1: 'Michigan Health Practice 1: Self-Awareness and Analyzing Influences',
  2: 'Michigan Health Practice 2: Social Awareness, Relationship, and Communication Skills',
  3: 'Michigan Health Practice 3: Information and Resource Seeking',
  4: 'Michigan Health Practice 4: Decision Making and Problem Solving',
  5: 'Michigan Health Practice 5: Self-Management and Goal Setting',
  6: 'Michigan Health Practice 6: Advocacy and Health Promotion',
}

const topic = (name) => `Michigan Health Topic (Grades 3-5): ${name}`

export const COURSES = [
  {
    grade: 3,
    courseId: 'ma-g3-health',
    title: 'Grade 3 Health',
    description:
      'A non-shaming, age-appropriate Grade 3 health course built on the Michigan Health Education Standards Guidelines 2025 Grades 3-5 band. It teaches everyday wellness routines, feelings and coping skills, respectful relationships and personal-safety rules, home and outdoor safety including how to call for emergency help, and how to find information worth trusting. No body measurement, calorie counting, dieting, private medical disclosure, or learner body photo is ever required.',
    capstone:
      'A private-safe personal health and safety toolkit: daily routines, a calm-down menu, a guardian-held trusted-adult contact card, and a guardian-reviewed home safety plan. No body measurement, photograph, or private disclosure is required.',
    units: [
      {
        title: 'Healthy Bodies, Healthy Routines',
        standards: [PRACTICE[5], PRACTICE[3], topic('Personal Health and Wellness')],
        essentialQuestion: 'How do everyday routines keep my body well and stop germs from spreading?',
        performanceTask: 'Build a personal daily health routine card with morning, daytime, and bedtime steps, and explain what each step protects. No body measurement is used.',
        materials: ['index cards or paper for a routine card', 'soap and water for a handwashing demonstration'],
        homeConnection: 'With a guardian, choose one routine step from the card to try this week and talk about what made it easier or harder.',
        adapted: 'Any routine step may be described, drawn, sequenced with picture cards, or demonstrated by an adult instead of written. A step a learner cannot do independently is planned as an adult-supported step, which counts fully.',
        guardian: {
          equipment: 'Household hygiene items only (soap, toothbrush, sunscreen). No specialized equipment.',
          environment: 'Indoor home or classroom setting.',
          movement_hazards: 'None expected.',
          food_or_allergy_note: 'Check soap, sanitizer, sunscreen, and toothpaste against any known skin or ingredient allergy before use.',
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'daily hygiene routines', key_points: ['A routine is a set of steps you do in the same order, so you do not have to remember each one separately.', 'Morning usually includes washing face and hands, brushing teeth, and dressing for the weather.', 'Evening usually includes washing, brushing teeth, and getting to bed at a steady time.', 'Routines work better when they are attached to something that already happens, like brushing right after breakfast.'], scenario: 'Sam keeps forgetting to brush in the morning because the family leaves in a rush. Where in Sam\'s morning could brushing be attached so it is harder to forget?' },
          { name: 'handwashing and how germs spread', key_points: ['Germs are far too small to see, and hands look clean even when they carry them.', 'Germs move by touch, by coughs and sneezes, and by shared surfaces like door handles and tablets.', 'Wash with soap and water for about 20 seconds: palms, backs of hands, between fingers, thumbs, and under nails.', 'Always wash before eating or helping with food, and after the toilet, blowing your nose, touching animals, or coming inside.', 'Cough and sneeze into your elbow, not your hand, so your hands stay clean for touching things.'], scenario: 'Mia pets a neighbor\'s dog on the walk home, then goes straight to the snack cupboard. What should she do first, and what could happen if she skips it?' },
          { name: 'dental care', key_points: ['Brush twice a day for about two minutes with a pea-sized amount of fluoride toothpaste.', 'Brush every surface: outsides, insides, and the chewing tops, plus gently along the gum line.', 'Sugary drinks sipped slowly over a long time give germs more time to harm teeth than the same drink finished quickly.', 'Adult teeth grow in around this age and do not get replaced, so caring for them matters.'], scenario: 'Theo brushes hard and fast for 20 seconds and his gums hurt afterwards. Name two things he could change.' },
          { name: 'sleep and rest', key_points: ['Children this age generally need somewhere around 9 to 12 hours of sleep a night.', 'Sleep is when the body grows, repairs, and files away what you learned that day.', 'Screens close to bedtime make it harder to fall asleep because bright light tells the brain it is still daytime.', 'A steady bedtime and a wind-down routine help more than trying to catch up at the weekend.'], scenario: 'Ana feels grumpy and cannot concentrate by mid-morning most days. What sleep questions would help work out why?' },
          { name: 'sun and skin care', key_points: ['Skin can burn on cloudy days and in winter, not just in summer sun.', 'Sunscreen goes on before going outside and needs putting on again after swimming or a long time outdoors.', 'Shade, a hat, and covering clothes protect as well as sunscreen does.', 'Sunburn is an injury to the skin, and it hurts for days after the sun has gone.'], scenario: 'A family plans a cloudy afternoon at a lake. Someone says sunscreen is not needed because there is no sun. What would you tell them?' },
          { name: 'resting and recovering when sick', key_points: ['Rest, fluids, and time are what most everyday illnesses need.', 'Staying home when sick protects other people, and is not something to feel guilty about.', 'Only a trusted adult gives medicine — never a child, a sibling, or a friend.', 'Tell an adult about symptoms that get worse, will not stop, or make it hard to breathe.'], scenario: 'Jo has a sore throat and a temperature but does not want to miss a school trip. What is the healthy choice here, and who decides?' },
        ],
      },
      {
        title: 'Food, Water, and Moving My Body',
        standards: [PRACTICE[1], PRACTICE[5], topic('Balanced Eating and Physical Activity')],
        essentialQuestion: 'How do food, water, and movement give my body energy for the things I want to do?',
        performanceTask: 'Design flexible fuel-and-move plans for three different kinds of days, including a safe plan for sharing food with someone who has an allergy. No calories, weights, diets, body-size targets, or good-and-bad food labels are used.',
        materials: ['paper or a digital planner for day plans', 'optional clean, empty food packages'],
        homeConnection: 'With a guardian, look at what the household already keeps for quick snacks and talk about which ones travel well.',
        adapted: 'Plans may use pictures, cut-outs, dictation, or spoken description. Learners with food allergies, medical diets, religious or cultural food practices, or limited food access plan with the foods actually available to them, and the adult may substitute any example.',
        guardian: {
          equipment: 'Optional clean, empty food packaging. No cooking with heat is required.',
          environment: 'Kitchen or table setting with an adult present for any food handling.',
          movement_hazards: 'Active-play examples only; the learner chooses intensity and may sit or rest at any point.',
          food_or_allergy_note: 'Guardian confirms every food example, tasting, and handling against household allergies, intolerances, and dietary practices. No tasting is required to complete any lesson.',
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'variety across food groups', key_points: ['Different foods do different jobs, so eating a range works better than eating a lot of one thing.', 'A useful pattern is some fruit or vegetables, some grains, some protein, and some dairy or an alternative.', 'Foods are not good or bad; foods that are mostly for enjoyment simply fit alongside the rest.', 'What a family eats depends on culture, budget, and what is available, and all of those are valid.'], scenario: 'Two lunches both contain four items. What questions would help you tell whether each one gives a range of foods, without calling either lunch bad?' },
          { name: 'food allergies and safe sharing', key_points: ['A food allergy is the body reacting to a food as if it were dangerous, and it can be serious very fast.', 'Common ones include peanuts, tree nuts, milk, eggs, wheat, soy, fish, shellfish, and sesame.', 'Never share or swap food with someone who has an allergy unless a trusted adult has checked it.', 'Signs to get an adult for immediately: swelling of the face or lips, a rash, trouble breathing, or vomiting after eating.', 'Wash hands after eating an allergen so it is not left on shared surfaces.'], scenario: 'Rae offers half a peanut-butter sandwich to a classmate who says "I think I am allergic to nuts." What is the right move, and who needs to know?' },
          { name: 'hunger and fullness signals', key_points: ['The body sends signals: a rumbling or empty stomach, low energy, or trouble concentrating.', 'Fullness arrives slowly, so eating at a steady pace helps you notice it.', 'Being hungry between meals is normal and is what snacks are for.', 'Different days need different amounts, and that is expected, not a problem to fix.'], scenario: 'Kai finishes lunch quickly and still feels hungry, then feels uncomfortably full ten minutes later. What might explain that?' },
          { name: 'drinking water through the day', key_points: ['Water is what the body uses for almost everything, and it is lost through sweat and breathing.', 'Thirst, a dry mouth, a headache, or dark yellow urine can all mean it is time to drink.', 'You need more when it is hot and when you have been active.', 'Water is the everyday drink; sugary drinks are occasional.'], scenario: 'After an hour of outdoor play on a hot day, Nico has a headache and has not had a drink. What should happen next?' },
          { name: 'everyday movement and active play', key_points: ['Children this age benefit from around an hour of activity a day, and it does not have to happen all at once.', 'Movement that counts includes walking, cycling, dancing, chores, and free play, not only sport.', 'Activity you enjoy is the activity you keep doing.', 'Movement helps mood and sleep as well as the body.'], scenario: 'Someone says they "did no exercise" on a day when they walked to school, helped carry groceries, and danced in the kitchen. What would you point out?' },
          { name: 'kitchen and food safety basics', key_points: ['Wash hands before and after handling food.', 'Keep raw meat separate from food that will not be cooked, and wash anything it touched.', 'Cold food belongs in the fridge; food left out for hours is not safe to eat.', 'Ask an adult before using knives, the stovetop, the oven, or anything hot.'], scenario: 'A cutting board was used for raw chicken and is about to be used for cutting apples. What has to happen first, and why?' },
        ],
      },
      {
        title: 'Feelings, Calm, and Asking for Help',
        standards: [PRACTICE[1], PRACTICE[2], topic('Mental and Emotional Health')],
        essentialQuestion: 'How can I notice what I feel and choose a helpful next step?',
        performanceTask: 'Create a personal calm-down menu, and with a guardian make a trusted-adult contact card the family keeps. The contact card stays with the guardian and is never graded, collected, or stored by the course.',
        materials: ['paper or cards for a calm-down menu', 'a card the guardian keeps for trusted-adult contacts'],
        homeConnection: 'With a guardian, agree on one calm-down option that is allowed at home and one that is allowed away from home.',
        adapted: 'Calming tools may be movement-based, still, sensory, verbal, or silent, and each learner picks tools their body and setting allow. Any scenario may be answered by pointing, choosing from options, drawing, or speaking.',
        guardian: {
          equipment: 'None.',
          environment: 'Quiet indoor space with a break space available.',
          movement_hazards: 'None expected.',
          food_or_allergy_note: null,
          guardian_confirmation_required: false,
        },
        topics: [
          { name: 'naming feelings', key_points: ['Naming a feeling accurately makes it easier to handle than calling everything "fine" or "bad".', 'Useful words include frustrated, disappointed, nervous, embarrassed, lonely, excited, and proud.', 'Feelings come in sizes: a little annoyed is not the same as furious.', 'All feelings are allowed. What you do with a feeling is the part you choose.'], scenario: 'Ellis snaps at a friend after losing a game. What might Ellis actually be feeling underneath, and what word fits best?' },
          { name: 'telling a trusted adult', key_points: ['A trusted adult is someone who keeps you safe, listens, and takes action — often a parent, caregiver, teacher, coach, school nurse, or relative.', 'It helps to have more than one, including one outside your home.', 'Tell an adult when someone is hurt or unsafe, when something feels wrong, or when a problem is too big to solve alone.', 'If the first adult does not help, keep telling until someone does. That is not being a nuisance.', 'Telling to keep someone safe is never the same as tattling to get someone in trouble.'], scenario: 'Priya told one adult that something at the park worried her and was told "do not worry about it." She still feels worried. What should Priya do?' },
          { name: 'where feelings show up in the body', key_points: ['Strong feelings often show up physically: a fast heartbeat, a tight chest, hot cheeks, a churning stomach, or tense shoulders.', 'These signals are early warnings that can be noticed before a feeling gets big.', 'Bodies differ, so signals are personal and no one signal is the correct one.', 'Noticing a signal early gives you more choices about what to do next.'], scenario: 'Before reading aloud, Devi\'s hands shake and her stomach churns. What is her body telling her, and what could she do with that information?' },
          { name: 'calming and coping tools', key_points: ['Slow breathing out for longer than you breathe in settles the body down.', 'Moving, stretching, drinking water, or stepping outside can all help.', 'Grounding works: name things you can see, hear, and touch right now.', 'Different tools suit different feelings and places, so having a menu beats having one trick.'], scenario: 'A calming tool that works at home is not allowed in the middle of a lesson. What else could work in that setting?' },
          { name: 'kindness and empathy', key_points: ['Empathy is imagining how a situation feels from where someone else is standing.', 'You can be kind to someone without agreeing with them.', 'Small actions count: including someone, noticing effort, checking in after a hard day.', 'Kindness towards yourself matters too, especially after a mistake.'], scenario: 'A classmate gets an answer wrong and goes quiet. What could you do that helps without drawing more attention to them?' },
          { name: 'big problems and small problems', key_points: ['Small problems can usually be solved by you, or by waiting, or with a small amount of help.', 'Big problems involve someone being hurt, unsafe, or scared, and always need an adult.', 'Sorting the size of a problem helps you pick the right response instead of panicking or ignoring it.', 'If you are not sure which size it is, treat it as big and ask an adult.'], scenario: 'Sort these: a lost pencil; a friend who will not share; someone being threatened. Which need an adult, and which do not?' },
        ],
      },
      {
        title: 'Friends, Boundaries, and Speaking Up',
        standards: [PRACTICE[2], PRACTICE[6], topic('Healthy Relationships')],
        essentialQuestion: 'How do respectful words and clear boundaries keep me and my friendships safe?',
        performanceTask: 'Practice and write short scripts for asking permission, saying no, and getting help, using fictional situations only.',
        materials: ['paper or cards for scripts'],
        homeConnection: 'With a guardian, agree on the family rule for secrets and who is always safe to tell.',
        adapted: 'Scripts may be spoken, signed, typed, drawn as a comic, or acted with figures or puppets. Role-play is optional and may always be replaced by describing what a character should say.',
        guardian: {
          equipment: 'None.',
          environment: 'Indoor setting.',
          movement_hazards: 'None expected.',
          food_or_allergy_note: 'None. This unit covers personal-safety rules; guardians may wish to preview it.',
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'listening and taking turns', key_points: ['Listening means letting someone finish, not planning your reply while they talk.', 'Checking back — "so you mean..." — proves you understood.', 'Taking turns applies to talking as well as to games.', 'Interrupting is sometimes necessary, for example when someone is in danger.'], scenario: 'Two friends both want to describe their weekend and keep talking over each other. Suggest a rule that would fix it.' },
          { name: 'personal body boundaries and unsafe touch', key_points: ['Your body belongs to you, and you may decide who hugs, tickles, or touches you — including relatives.', 'The parts covered by a swimsuit are private. Use correct names for them; correct names make it possible to be understood and believed.', 'No one should look at, touch, photograph, or ask to see your private parts, except a doctor or nurse checking your health with your guardian present, or a caregiver helping you stay clean when you need help.', 'You may say no to any touch, even from someone you know and like, and even if you said yes before.', 'If someone breaks this rule it is never your fault, no matter what they said, gave you, or promised.', 'Tell a trusted adult right away, and keep telling until someone helps.'], scenario: 'An older cousin keeps tickling Jordan after Jordan says stop, and says "you love it really." Is Jordan allowed to say no? What exactly could Jordan say, and who should Jordan tell?' },
          { name: 'asking for and giving permission', key_points: ['Ask before you touch someone, take their things, or share something about them.', 'Permission has to be freely given; pestering someone until they give in is not permission.', 'A yes can be taken back at any time.', 'When someone says no to you, the respectful answer is to stop and not to argue.'], scenario: 'Ben wants a hug from a friend who steps back. What should Ben do, and what should he not do?' },
          { name: 'secrets, surprises, and telling', key_points: ['A surprise is happy and gets told soon, like a birthday present.', 'A secret you are told to keep forever, especially about touching or about your body, is not safe and should be told.', 'Adults who ask a child to keep a secret from their guardian are breaking a rule, even if they are known and liked.', 'Threats and bribes are warning signs, not reasons to stay quiet.', 'Telling is always the right thing to do, even when someone says you will be in trouble for it.'], scenario: 'Someone gives Alex a present and says "this is our secret, do not tell your mom." What kind of secret is that, and what should Alex do?' },
          { name: 'making and repairing friendships', key_points: ['Friendships need shared time, shared interest, and being reliable.', 'Disagreements are normal and do not have to end a friendship.', 'A real repair names what you did, says sorry for that specific thing, and changes something.', '"Sorry you feel that way" is not an apology.'], scenario: 'Rowan broke a promise to a friend. Write what a real apology from Rowan would sound like.' },
          { name: 'teasing, bullying, and reporting', key_points: ['Bullying is deliberate, repeated, and aimed at someone who is finding it hard to stop it.', 'It can be physical, spoken, social such as deliberate exclusion, or online.', 'A bystander who tells an adult, includes the person afterwards, or refuses to join in changes the outcome.', 'Reporting bullying is telling to keep someone safe; it is not tattling.'], scenario: 'The same group leaves one classmate out of every game and laughs when they walk past. Is this bullying? What can a bystander do?' },
        ],
      },
      {
        title: 'Staying Safe at Home, Outside, and Online',
        standards: [PRACTICE[4], PRACTICE[3], topic('Safety and Injury Prevention')],
        essentialQuestion: 'How do I spot a hazard early and choose the safest next step?',
        performanceTask: 'Make a household and outdoor safety plan with hazard checks, safe steps, an escape route, and who to contact. A guardian reviews and confirms the plan.',
        materials: ['paper or a printed checklist for a home safety walk', 'a properly fitted helmet if wheels are discussed'],
        homeConnection: 'With a guardian, walk the home fire escape route and agree the outside meeting place.',
        adapted: 'A safety walk may be done by an adult with the learner directing from a seated position, by spoken description with no photographs taken, or entirely through a floor-plan drawing. No learner is required to reach, lift, or test any hazard.',
        guardian: {
          equipment: 'Helmet and protective gear only if the learner uses wheels; smoke alarm and emergency contact list for review by the adult.',
          environment: 'Home interior and, if chosen, a guardian-supervised outdoor area. Water and fire content is taught as discussion and planning only.',
          movement_hazards: 'A home safety walk involves moving through the home; an adult accompanies the learner. No learner tests, touches, or operates a hazard, alarm, appliance, water source, or flame.',
          food_or_allergy_note: 'Kitchen safety discussion may reference household foods; no tasting or cooking is required.',
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'home and kitchen safety', key_points: ['Common home hazards: wet floors, trailing cables, cluttered stairs, hot drinks, and unlocked cupboards with chemicals.', 'Hot pan handles turn inwards so they cannot be knocked.', 'Never put water on a pan fire and never carry a burning pan.', 'Ask an adult before using anything hot, sharp, or electrical.'], scenario: 'Walk through a kitchen where a kettle cable trails over the edge, a pan handle sticks out, and cleaning bottles sit under an open sink. Name each hazard and one fix.' },
          { name: 'emergency help and calling 911', key_points: ['In the United States, call 911 for a real emergency: a fire, someone badly hurt, someone who cannot breathe, or a crime happening now.', 'Say what happened, where you are including the full address, and your name. Do not hang up until told to.', 'Learn your home address and a guardian\'s phone number by heart, and know where the phone is.', 'Calling 911 as a joke is never safe, because it takes help away from someone who needs it.', 'Non-emergencies — a scraped knee, a lost pet, a broken window — go to a trusted adult, not to 911.'], scenario: 'A neighbor has fallen and cannot get up or reach a phone. Is this a 911 call? Say out loud exactly what you would tell the operator.' },
          { name: 'wheels, helmets, and street safety', key_points: ['A helmet sits level, two fingers above the eyebrows, with the strap snug under the chin.', 'A helmet that has taken a hard knock is replaced, even if it looks fine.', 'Cross at crosswalks, stop at the curb, look both ways, and make eye contact with drivers.', 'Headphones and phones make it harder to notice traffic.'], scenario: 'A helmet slides back off the forehead and the strap is loose. What needs adjusting before riding?' },
          { name: 'water safety', key_points: ['Never swim alone, and only swim where an adult is watching.', 'Open water is different from a pool: cold, currents, and hidden depth make it far less predictable.', 'If someone is in trouble in water, do not go in after them — shout for an adult, and reach or throw something that floats.', 'Wear a life jacket on boats and in open water, whatever your swimming ability.'], scenario: 'A friend has waded out too far in a lake and is struggling. You are a strong swimmer. What do you actually do first?' },
          { name: 'fire safety', key_points: ['Working smoke alarms give the warning; adults test them and change batteries.', 'If a smoke alarm sounds, get out, stay out, and call for help from outside.', 'Crawl low under smoke, because the cleanest air is near the floor.', 'Feel a closed door with the back of your hand before opening it; if it is hot, use another way out.', 'If clothing catches fire: stop, drop, and roll. Agree a meeting place outside in advance.'], scenario: 'The alarm sounds at night and the bedroom door handle feels hot. What is the safe sequence of actions?' },
          { name: 'device and online safety basics', key_points: ['Personal information — full name, address, school, phone number, passwords — stays private online.', 'People online are not always who they say they are.', 'Anything sent can be saved and shared onwards, even if it seems to disappear.', 'If something online is scary, mean, or asks you to keep a secret, tell a trusted adult right away. Telling is always the right thing to do, and it is the adult\'s job to help.'], scenario: 'Someone in a game chat tells Sam they are also nine, asks which school Sam goes to, and asks Sam to keep it a secret from Sam\'s parents. What is wrong here, and what should Sam do?' },
        ],
      },
      {
        title: 'Good Information and Healthy Choices',
        standards: [PRACTICE[3], PRACTICE[4], PRACTICE[6], topic('Substance Use and Misuse'), topic('Community and Environmental Health')],
        essentialQuestion: 'How do I find information I can trust and use it to make a healthy choice?',
        performanceTask: 'Create a short health advocacy message for family or community, supported by one adult-checked reliable source.',
        materials: ['one adult-approved reliable health source', 'paper or a digital tool for an advocacy message'],
        homeConnection: 'With a guardian, find out where medicines are stored in your home and why they are kept there.',
        adapted: 'The advocacy message may be a poster, a spoken message, a letter, an audio note, a slide, or a described plan. No public posting, publication, or performance is required.',
        guardian: {
          equipment: 'Medicine and household-product containers are viewed with an adult only, and are never opened, handled, or tasted by the learner.',
          environment: 'Indoor setting; supervised internet use if an online source is chosen.',
          movement_hazards: 'None expected.',
          food_or_allergy_note: null,
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'trusted adults and health helpers', key_points: ['Health helpers include doctors, nurses, dentists, pharmacists, school nurses, and paramedics.', 'Different helpers do different jobs, so knowing who to ask saves time.', 'It is fine to ask a health helper questions about your own body and care.', 'A trusted adult usually helps you reach the right helper.'], scenario: 'Who would you ask about a tooth that hurts when you drink something cold, and who would you ask about a cut that will not stop bleeding?' },
          { name: 'medicine and household product safety', key_points: ['Medicine is given by a trusted adult only — never taken by yourself and never shared with anyone.', 'Medicine that helps one person can seriously harm another, even at the same age.', 'Vitamins and candy can look alike; if you are not certain what something is, do not put it in your mouth.', 'Cleaning products, vapes, alcohol, and garden chemicals are not for children and are stored away for that reason.', 'If someone has swallowed something they should not have, tell an adult immediately — speed matters.'], scenario: 'A younger sibling finds a bottle of colored pills on a low shelf and says they look like candy. What do you do, in what order?' },
          { name: 'reliable information and advertising', key_points: ['Ads are made to sell something, so they show the best case, not the whole picture.', 'Reliable health information usually comes from health organizations, hospitals, and health professionals.', 'Warning signs: miracle claims, "doctors hate this", pressure to buy now, and no author.', 'Checking a claim in a second place is the simplest way to test it.'], scenario: 'A video says one drink "boosts your immune system instantly" and links to a store. List two reasons to be suspicious.' },
          { name: 'saying no and getting away', key_points: ['A refusal works better when it is short, clear, and repeated: "No thanks." "I said no."', 'You do not owe anyone an explanation for a no.', 'Having an exit ready — leaving, going to an adult, phoning home — matters as much as the words.', 'Real friends accept a no; pressure to do something unsafe is a signal about them, not about you.'], scenario: 'An older child offers Sasha a vape and says everyone does it. Write what Sasha says, and what Sasha does next.' },
          { name: 'simple decision steps', key_points: ['Stop and name the actual choice.', 'List the options, including the ones nobody mentioned.', 'Think through what likely happens after each, for you and for others.', 'Choose, act, and afterwards ask whether it worked.', 'If the choice involves safety, add an adult to the process.'], scenario: 'Friends want to take a shortcut across a construction site. Walk through the steps out loud and say what you decide.' },
          { name: 'caring for our shared community', key_points: ['Community health means the conditions everyone shares: clean water, clean air, safe places to play.', 'Litter, waste, and pollution affect other people and animals, not only the person dropping it.', 'Children can genuinely change things by asking, writing, organizing, and setting an example.', 'Advocacy means speaking up for something better, with a reason behind it.'], scenario: 'A local park has broken glass near the play area. Who could you tell, and what would make the message more likely to work?' },
        ],
      },
    ],
  },
  {
    grade: 4,
    courseId: 'ma-g4-health',
    title: 'Grade 4 Health',
    description:
      'A non-shaming, age-appropriate Grade 4 health course built on the Michigan Health Education Standards Guidelines 2025 Grades 3-5 band. It deepens Grade 3 by moving from naming healthy habits to planning, deciding, refusing, and advocating: body systems and disease prevention, balanced eating and media literacy about bodies, emotional regulation and stress, assertive communication and consent, injury response and digital safety, and goal setting with source-checked advocacy. No body measurement, calorie counting, dieting, weight-loss goal, private medical disclosure, mental-health diagnosis, or learner body photo is ever required.',
    capstone:
      'A private-safe personal health portfolio: a prevention routine, a coping toolkit, communication and refusal scripts, a guardian-reviewed safety and emergency plan, and one source-supported advocacy piece. No body measurement, photograph, or private disclosure is required.',
    units: [
      {
        title: 'How My Body Works and Stays Well',
        standards: [PRACTICE[3], PRACTICE[5], topic('Personal Health and Wellness')],
        essentialQuestion: 'How do my body systems and my daily habits work together to keep me well?',
        performanceTask: 'Design a prevention routine that explains what each step protects, why it works, and when adult or professional help is needed.',
        materials: ['a simple body-systems diagram or model', 'paper or a digital tool for a prevention routine'],
        homeConnection: 'With a guardian, find out where the household keeps its first-aid supplies and the doctor or clinic contact details.',
        adapted: 'Diagrams may be replaced with text descriptions, tactile models, or spoken explanation. Any routine step a learner cannot perform independently is planned as an adult-supported step, which counts fully.',
        guardian: {
          equipment: 'Household hygiene items only. No medical device, thermometer reading, or body measurement is used.',
          environment: 'Indoor home or classroom setting.',
          movement_hazards: 'None expected.',
          food_or_allergy_note: 'Check soap, sanitizer, and dental products against any known allergy before use.',
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'body systems working together', key_points: ['Systems cooperate: the respiratory system takes in oxygen, the circulatory system carries it, and muscles use it.', 'The digestive system breaks food into fuel the blood can deliver.', 'The skeleton supports and protects; the skin is the first barrier against germs.', 'Because systems are connected, a habit like sleep or hydration affects several at once.'], scenario: 'Running upstairs leaves you breathing hard with a fast heartbeat. Which systems are responding, and why do both change together?' },
          { name: 'germs and how illness spreads', key_points: ['Bacteria and viruses are different: antibiotics work on bacteria and do nothing to viruses.', 'Germs spread by droplets from coughs and sneezes, by direct contact, by contaminated surfaces, and through food and water.', 'Someone can pass on an illness before they feel ill themselves.', 'Breaking one link in the chain — washing, covering, staying home, cleaning surfaces — stops the spread.'], scenario: 'One person in a class has a stomach bug on Monday and six do by Friday. Trace the likely routes and name the two changes that would help most.' },
          { name: 'handwashing and respiratory etiquette', key_points: ['Soap works by breaking up the outer layer of many germs, which is why scrubbing beats a quick rinse.', 'Twenty seconds, covering palms, backs, between fingers, thumbs, and nails.', 'Sanitizer is a stand-in when soap is unavailable, and does not work well on visibly dirty hands.', 'Cough or sneeze into your elbow or a tissue, throw the tissue away, then wash.'], scenario: 'Someone rinses their hands with water for three seconds and says they washed. Explain, using how soap works, why that is not enough.' },
          { name: 'dental and skin care', key_points: ['Brush twice daily for two minutes with fluoride toothpaste, and clean between teeth.', 'Plaque is a bacterial film; left alone it causes decay and gum disease.', 'Skin needs washing, sun protection, and clean cuts covered to keep germs out.', 'Adult teeth are permanent, so damage now lasts.'], scenario: 'A friend brushes once a day and never cleans between their teeth, and their gums bleed. Explain what is likely happening and what to change.' },
          { name: 'sleep quality and routines', key_points: ['Around 9 to 12 hours a night is typical at this age.', 'Sleep consolidates memory and learning, and supports mood, growth, and immunity.', 'Blue light and stimulating content near bedtime delay falling asleep.', 'A consistent schedule works better than catching up at weekends.'], scenario: 'Someone sleeps five hours on school nights and twelve on Saturday, and still feels tired. Explain why the weekend does not fix it.' },
          { name: 'checkups and staying well', key_points: ['Routine checkups find problems early, before they are felt.', 'Vaccines teach the immune system to recognize a germ safely in advance, which protects the person and people who cannot be vaccinated.', 'Bring questions to appointments; you are allowed to ask about your own body.', 'Medical decisions are made by guardians and health professionals, not by children or by the internet.'], scenario: 'A friend says checkups are pointless when you feel fine. Give two reasons that is not right.' },
        ],
      },
      {
        title: 'Balanced Eating, Hydration, and Active Living',
        standards: [PRACTICE[1], PRACTICE[5], topic('Balanced Eating and Physical Activity')],
        essentialQuestion: 'How can I plan food, water, and movement in a way that fits my body, my day, and my family?',
        performanceTask: 'Build a week of flexible meal, snack, hydration, and movement options with substitutions for allergies, preferences, culture, and budget. No calorie counting, dieting, weight goal, or body measurement is used.',
        materials: ['clean, empty food packages or printed sample labels', 'paper or a digital planner'],
        homeConnection: 'With a guardian, look at one food label from the cupboard and find the ingredients list and any allergen warning.',
        adapted: 'Planning may use pictures, dictation, sorting cards, or a spoken walkthrough. Learners with allergies, medical diets, religious or cultural food practices, or limited food access plan with the foods actually available to them, and any example may be substituted.',
        guardian: {
          equipment: 'Clean, empty food packaging or printed labels. No cooking with heat is required.',
          environment: 'Kitchen or table setting with an adult present for any food handling.',
          movement_hazards: 'Active-living examples only; the learner chooses intensity and may rest at any point.',
          food_or_allergy_note: 'Guardian confirms every food example, label, and any handling against household allergies, intolerances, medical diets, and dietary practices. No tasting is required to complete any lesson.',
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'what different foods do for the body', key_points: ['Carbohydrates are the body\'s main everyday fuel, including for the brain.', 'Protein builds and repairs muscle, skin, and blood.', 'Fats support the brain and help absorb some vitamins; the body needs them.', 'Fruit and vegetables supply vitamins, minerals, and fiber that keep digestion working.', 'No single food does everything, which is why range matters more than any one item.'], scenario: 'A lunch is bread, butter, cheese, and an apple. Which jobs are covered? What could be added without calling the lunch bad?' },
          { name: 'food allergies and cross-contact safety', key_points: ['An allergy is an immune reaction; an intolerance is a digestive one, and allergies can be life-threatening.', 'Cross-contact is when a trace transfers by a shared knife, board, toaster, or unwashed hand — a trace is enough.', 'Labels must flag major allergens; "may contain" means a real risk.', 'Signs needing an adult immediately: swelling of lips, face or throat, widespread rash, wheezing, or difficulty breathing.', 'Never talk someone into eating something they have said they cannot eat.'], scenario: 'A peanut-butter knife was rinsed and used for jam on a friend\'s sandwich. The friend is allergic to peanuts. Is that safe? Explain what should have happened.' },
          { name: 'media messages about food and bodies', key_points: ['Ads, influencers, and filters present altered images, not real bodies.', 'Bodies genuinely differ in size and shape, and healthy comes in many of them.', 'Claims that a food is "clean", "guilt-free", or "bad" are marketing, not nutrition.', 'Content that makes you feel worse about your body is worth unfollowing; talk to a trusted adult if it keeps happening.'], scenario: 'A post promises a snack that will "fix your body in two weeks" and shows a before-and-after photo. Name three reasons to distrust it.' },
          { name: 'building balanced meals and snacks', key_points: ['A workable pattern: half the plate fruit and vegetables, a quarter grains, a quarter protein, plus dairy or an alternative.', 'Pairing carbohydrate with protein tends to keep energy steadier than carbohydrate alone.', 'Snacks are a normal part of the day at this age.', 'Plans have to survive real life: budget, time, and what is actually in the house.'], scenario: 'Redesign a snack of crackers alone so it lasts longer through an afternoon, using only cupboard staples.' },
          { name: 'hydration through the day', key_points: ['Water carries nutrients, controls temperature, and cushions joints.', 'Pale straw-colored urine suggests you are drinking enough; dark yellow suggests not.', 'Needs rise with heat, illness, and activity.', 'Sugary and caffeinated drinks are not everyday hydration.'], scenario: 'Someone drinks only at meals, plays sport at midday in summer, and gets afternoon headaches. Suggest a plan.' },
          { name: 'reading a simple food label', key_points: ['Ingredients are listed by weight, so the first few make up most of the product.', 'The allergen information is usually emphasized in bold or a separate statement.', 'Serving size matters: the numbers on the label describe one serving, not the whole pack.', 'A label describes what is in a food; it does not tell you whether the food is allowed or forbidden.'], scenario: 'On one label sugar is the second ingredient and the pack holds four servings. What does that tell you, and what does it not tell you?' },
        ],
      },
      {
        title: 'Emotional Health and Managing Stress',
        standards: [PRACTICE[1], PRACTICE[2], topic('Mental and Emotional Health')],
        essentialQuestion: 'How can I manage strong feelings and know when to reach for support?',
        performanceTask: 'Build a coping-strategy toolkit matched to different fictional stress scenarios, plus a help-seeking plan. Private reflection is never required to be shared or stored.',
        materials: ['cards or paper for a coping toolkit', 'optional timer for a calming practice'],
        homeConnection: 'With a guardian, agree one signal you can use at home that means "I need a few minutes".',
        adapted: 'Coping strategies may be movement-based, still, sensory, verbal, or silent, and each learner selects strategies their body and setting allow. Scenario responses may be pointed to, chosen from options, drawn, spoken, or written.',
        guardian: {
          equipment: 'None.',
          environment: 'Quiet indoor space with a break space available.',
          movement_hazards: 'None expected.',
          food_or_allergy_note: null,
          guardian_confirmation_required: false,
        },
        topics: [
          { name: 'emotion vocabulary and intensity', key_points: ['Precise words give better options: disappointed, overwhelmed, resentful, anxious, relieved, content.', 'Intensity matters — irritated, angry, and furious call for different responses.', 'Two feelings can be present at once, such as excited and nervous.', 'Naming a feeling accurately tends to reduce its intensity.'], scenario: 'Someone says only "I am fine" while slamming doors. Offer three more accurate words and say what each would suggest doing.' },
          { name: 'help-seeking and trusted supports', key_points: ['Reaching out is a skill, not a weakness or a failure.', 'Build a support list: guardians, a relative, a teacher, a coach, a school counsellor or nurse.', 'Get help promptly when a feeling stops you eating, sleeping, or going out, when it lasts for weeks, or when anyone talks about harming themselves.', 'If someone mentions hurting themselves, tell a trusted adult immediately — that is never a secret to keep.', 'If the first adult does not respond, keep telling until someone acts.'], scenario: 'A friend says they feel hopeless and asks you to promise not to tell. What do you do, and what do you say to your friend?' },
          { name: 'stress signals and triggers', key_points: ['Stress shows up in the body — headaches, stomach aches, tight muscles, disturbed sleep.', 'It shows up in behavior too — snapping, avoiding, rushing, or going quiet.', 'A trigger is the situation that sets it off; noticing patterns lets you plan ahead.', 'Some stress before a challenge is normal and can help you focus.'], scenario: 'Every Sunday evening one learner gets a stomach ache that clears by Monday afternoon. What might the trigger be, and how could you check?' },
          { name: 'change, loss, and difficult feelings', key_points: ['Moving, a family change, or the death of a person or pet all bring grief, and grief is not an illness.', 'Grief arrives in waves rather than in tidy stages, and there is no correct schedule.', 'Routines, talking, and remembering all help; so does being allowed to feel bad for a while.', 'A trusted adult should know when a hard feeling is not easing.'], scenario: 'A classmate\'s dog died two weeks ago and they were laughing yesterday but tearful today. Is that normal? What could a friend say?' },
          { name: 'coping and regulation strategies', key_points: ['Slow breathing with a longer out-breath lowers the body\'s alarm response.', 'Grounding by naming what you can see, hear, and touch brings attention back to the present.', 'Movement, water, daylight, and sleep are underrated regulators.', 'Match the strategy to the setting — some work in a classroom, some only at home.', 'Strategies work better when practiced before you need them.'], scenario: 'Build a toolkit for someone who gets overwhelmed in noisy places and cannot leave the room. What actually fits that constraint?' },
          { name: 'self-talk and mindset', key_points: ['Self-talk is the running commentary in your head, and it can be checked for accuracy.', '"I cannot do this" becomes "I cannot do this yet", which describes the situation more truthfully.', 'Mistakes are information about the method, not verdicts about the person.', 'Speak to yourself the way you would speak to a friend in the same position.'], scenario: 'After a hard test someone thinks "I am useless at math." Rewrite that thought so it is both kinder and more accurate.' },
        ],
      },
      {
        title: 'Relationships, Boundaries, and Conflict Repair',
        standards: [PRACTICE[2], PRACTICE[6], topic('Healthy Relationships')],
        essentialQuestion: 'How do I speak up for myself, respect others, and repair a relationship after conflict?',
        performanceTask: 'Write and rehearse assertive communication and conflict-repair scripts for fictional situations, including a bystander response plan.',
        materials: ['paper or a digital tool for scripts'],
        homeConnection: 'With a guardian, review who is on your list of adults you could tell if something felt wrong.',
        adapted: 'Scripts may be spoken, signed, typed, drawn as a comic, or acted with figures. Role-play is optional and may always be replaced by describing what a character should say and why.',
        guardian: {
          equipment: 'None.',
          environment: 'Indoor setting.',
          movement_hazards: 'None expected.',
          food_or_allergy_note: 'None. This unit covers personal-safety and consent rules; guardians may wish to preview it.',
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'assertive, respectful communication', key_points: ['Passive gives in, aggressive attacks, assertive states your need and respects theirs.', 'A clear frame: "When ___ happens, I feel ___, and I would like ___."', 'Tone, volume, and body language carry as much as the words.', 'Being assertive does not guarantee you get what you want; it makes being understood far more likely.'], scenario: 'A friend keeps borrowing things without asking. Write a passive, an aggressive, and an assertive version, and say why the third is better.' },
          { name: 'body autonomy, consent, and unsafe requests', key_points: ['Your body belongs to you; you decide about hugs, tickling, and touch, including with family.', 'The parts covered by a swimsuit are private. Use correct anatomical names — they make you easier to understand and to believe.', 'No one should touch, look at, photograph, or ask to see your private parts, except a doctor or nurse checking your health with your guardian present, or a caregiver helping you when you need help.', 'Unsafe requests most often come from someone already known and trusted, not from a stranger — so the rule applies to everyone.', 'Bribes, threats, and "this is our secret" are warning signs.', 'If it happens it is never your fault, whatever you did, accepted, or agreed to earlier. Tell a trusted adult and keep telling until someone helps.'], scenario: 'An adult a family knows well asks Sam to sit on their lap and keep it "just between us." Name every warning sign, and say exactly what Sam should do.' },
          { name: 'listening and perspective-taking', key_points: ['Active listening: face the person, let them finish, then summarize before replying.', 'Two people can experience the same event differently and both be reporting honestly.', 'Asking a genuine question beats assuming a motive.', 'Understanding someone is not the same as agreeing with them.'], scenario: 'Two friends give opposite accounts of an argument. How would you find out more without deciding who is lying?' },
          { name: 'conflict resolution and repair', key_points: ['Cool down first — nothing useful gets settled mid-anger.', 'State the problem as a behavior, not as a character flaw.', 'Look for a solution both can live with, not for a winner.', 'A real repair names the specific action, apologizes for it, and changes something afterwards.'], scenario: 'Two friends both think the other started it and neither will speak. Write the first three steps towards repair.' },
          { name: 'bullying and cyberbullying response', key_points: ['Bullying is deliberate, repeated, and directed at someone struggling to stop it.', 'Cyberbullying follows people home, spreads fast, and leaves a record.', 'Keep the evidence, do not retaliate, block and report, and tell a trusted adult.', 'Bystanders shift outcomes by refusing to join in, supporting the person afterwards, and reporting.'], scenario: 'A group chat is sharing an unkind edited photo of a classmate. List what you do, in order, and what you do not do.' },
          { name: 'inclusion and respect for differences', key_points: ['People differ in ability, culture, language, faith, family shape, and interests.', 'Exclusion can be quiet — never being picked, never being asked — and still does harm.', 'Inclusion often means changing the activity rather than asking the person to cope.', 'Asking someone what would help beats guessing on their behalf.'], scenario: 'A game needs fast running and one classmate uses a wheelchair. Redesign the game so they are genuinely playing, not just present.' },
        ],
      },
      {
        title: 'Safety, Injury Prevention, and Digital Life',
        standards: [PRACTICE[4], PRACTICE[3], topic('Safety and Injury Prevention'), topic('Substance Use and Misuse')],
        essentialQuestion: 'How do I prevent harm and respond well when something goes wrong?',
        performanceTask: 'Create a safety and refusal plan covering an activity, an online situation, and an emergency, reviewed and confirmed by a guardian.',
        materials: ['a basic first-aid kit for inspection with an adult', 'a properly fitted helmet or protective gear if relevant'],
        homeConnection: 'With a guardian, check that everyone in the household knows the home address and one emergency contact number by heart.',
        adapted: 'First-aid content is taught as recognition and when-to-get-help, not as independent treatment. Any hands-on step may be observed, described, or demonstrated by the adult instead of performed by the learner.',
        guardian: {
          equipment: 'First-aid kit inspected with an adult; helmet or protective gear if the learner uses wheels or sport equipment.',
          environment: 'Indoor setting, plus a guardian-supervised outdoor area if chosen. Water and fire content is planning and discussion only.',
          movement_hazards: 'No learner performs first aid on another person, tests a hazard, or enters water as part of this unit. Gear fitting is adult-supervised.',
          food_or_allergy_note: 'If the first-aid kit is reviewed, check adhesive, latex, and antiseptic contents against known allergies.',
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'injury prevention and protective gear', key_points: ['Most injuries at this age are predictable and preventable: falls, collisions, and road incidents.', 'A helmet sits level, two fingers above the eyebrows, snug strap, and is replaced after a hard impact.', 'Gear only works when it fits and is actually worn.', 'Checking the surface, the equipment, and the space first prevents more injuries than reacting well afterwards.'], scenario: 'Before skating at a new park, list the checks you would do on gear, surface, and surroundings.' },
          { name: 'emergency response and calling for help', key_points: ['Call 911 in the United States for fire, serious injury, someone not breathing, or a crime in progress.', 'Give what happened, the full address, and your name; stay on the line until told otherwise.', 'Check the scene is safe before approaching — do not become a second person who needs help.', 'Know your address and a guardian\'s number by heart; a locked phone can still call emergency services.', 'Prank calls take help away from someone who genuinely needs it.'], scenario: 'You find an adult collapsed and unresponsive at home and you are alone. Give the exact sequence, including what you say on the call.' },
          { name: 'medicines, household chemicals, and substance safety', key_points: ['Medicine is given by a trusted adult only, at the right dose, and is never shared.', 'Prescription medicine belongs to one named person; taking someone else\'s is dangerous.', 'Alcohol, nicotine, vapes, and other drugs affect a developing brain more than an adult one.', 'Vapes are not harmless water vapor; most contain nicotine, which is addictive.', 'Never taste or sniff an unlabeled substance. If someone has swallowed something, tell an adult at once — speed matters.'], scenario: 'An older student says vaping is "just flavored air" and offers one. Give two accurate facts in reply and say what you do next.' },
          { name: 'basic first aid and when to get an adult', key_points: ['Small cut: wash with clean water, apply gentle pressure, cover.', 'Burn: cool under running water for around 20 minutes, then get an adult. Never use ice, butter, or cream.', 'Nosebleed: sit up, lean forward, pinch the soft part of the nose.', 'Always get an adult for head injuries, bleeding that will not stop, breathing trouble, a suspected broken bone, or any loss of consciousness.', 'Your job is to recognize and fetch help, not to treat someone yourself.'], scenario: 'A friend falls, hits their head, and seems dazed and confused. What do you do, and what do you not do?' },
          { name: 'online privacy and personal information', key_points: ['Personal data — full name, address, school, birthday, phone, location, passwords — stays private.', 'Photos can carry location data and can be copied and re-shared beyond your control.', 'Privacy settings help but never make something truly private.', 'A digital footprint lasts; assume anything posted could be seen by a guardian or a future school.'], scenario: 'A quiz app asks for your birthday, school, and first pet\'s name to "find your spirit animal." What is actually being collected, and why does it matter?' },
          { name: 'recognizing unsafe requests and refusing', key_points: ['Warning signs: secrecy, flattery, gifts, urgency, isolating you, or asking you to break a family rule.', 'Online grooming often begins friendly and moves slowly towards secrets and images.', 'A refusal is short and repeated; you do not owe an explanation, and you may simply leave or log off.', 'No one is allowed to ask for a photo of your body, and you never have to send one; the answer is always no, and you always tell a trusted adult.', 'Telling is always the right thing to do, and none of it is your fault, even if you already replied or already agreed.'], scenario: 'Someone met in a game says they are 11, sends a gift code, asks for a photo, and says not to tell. Identify every warning sign and give the full response.' },
        ],
      },
      {
        title: 'Decisions, Goals, and Health Advocacy',
        standards: [PRACTICE[4], PRACTICE[5], PRACTICE[6], PRACTICE[1], topic('Community and Environmental Health')],
        essentialQuestion: 'How do I make a sound decision, set a goal I can reach, and advocate for health beyond myself?',
        performanceTask: 'Set a private-safe personal health goal with a plan and a progress check, and produce an advocacy piece supported by a reliable source. Goals may not target body weight, body size, or appearance.',
        materials: ['two or more adult-approved health sources for comparison', 'paper or a digital tool for a goal plan and advocacy piece'],
        homeConnection: 'With a guardian, pick one household health habit worth improving and talk about what would make it stick.',
        adapted: 'Goal tracking may be a checklist, a spoken check-in, a drawing, or an adult-recorded note. The advocacy piece may be a poster, letter, slide, spoken message, or described plan. No public posting, publication, or performance is required.',
        guardian: {
          equipment: 'None beyond writing or digital tools.',
          environment: 'Indoor setting; supervised internet use when sources are compared online.',
          movement_hazards: 'None expected.',
          food_or_allergy_note: null,
          guardian_confirmation_required: true,
        },
        topics: [
          { name: 'a step-by-step decision process', key_points: ['Name the decision precisely, because a vague question gets a vague answer.', 'List options, including ones nobody has suggested.', 'Weigh likely consequences for you and for others, short term and longer term.', 'Decide, act, then review whether it worked — reviewing is what improves the next decision.', 'Safety decisions always include a trusted adult.'], scenario: 'Friends want to bike along a busy road with no bike lane to reach a park faster. Work the process and justify your decision.' },
          { name: 'checking sources and spotting misinformation', key_points: ['Ask who wrote it, when, and what they gain if you believe it.', 'Prefer health organizations, hospitals, and qualified professionals over anonymous posts.', 'Cross-check a claim in at least two independent places.', 'Warning signs: miracle cures, "what doctors will not tell you", urgency, and a product attached to the claim.', 'Sponsored content is an ad even when it looks like advice.'], scenario: 'Two pages disagree about whether a supplement helps children concentrate. One sells it. Describe how you decide what to believe.' },
          { name: 'influences from peers, family, and media', key_points: ['Influence is often invisible: placement, repetition, and who is shown using a product.', 'Peer influence can push either way, towards risk or towards good habits.', 'Family habits shape defaults such as meals, bedtime, and activity.', 'Noticing an influence is what gives you the option to choose differently.'], scenario: 'A learner suddenly wants a drink they have never tried. Trace three possible influences and say how you would test which was strongest.' },
          { name: 'setting and tracking a personal health goal', key_points: ['A workable goal is specific, realistic, and has a visible first step.', '"Drink water with each meal" beats "be healthier", because you can tell whether you did it.', 'Track the action, not your body — never weight, size, or appearance.', 'Expect to miss some days; a plan that survives a missed day is a better plan.'], scenario: 'Turn "get fitter" into a goal a nine-year-old could actually start tomorrow and check on Friday.' },
          { name: 'community health helpers and access', key_points: ['Community health includes clinics, school nurses, pharmacists, dentists, libraries, and food programmes.', 'Access is not equal: cost, transport, language, and disability all get in the way.', 'Knowing what exists locally is itself a health skill.', 'Helping someone reach a service is a genuine form of advocacy.'], scenario: 'A family new to the area does not know where to get a child\'s vaccination. Who could help, and how would you find out?' },
          { name: 'advocating for a healthier community', key_points: ['Advocacy is speaking up for a change with a reason and an audience in mind.', 'A strong message states the problem, gives evidence, and makes one clear ask.', 'Direct it at someone who can actually act — a school, a city council, a store.', 'Children\'s advocacy works, especially when it is specific and polite.'], scenario: 'Your park has no shade and no water fountain. Draft the one clear ask, name who receives it, and give the evidence you would include.' },
        ],
      },
    ],
  },
]
