export const MAXIMUM_PROVIDER_POLICY_REQUIREMENTS = 64;
export const MAXIMUM_ALLOWED_RETENTION_CLASSES = 3;
export const MAXIMUM_TRUSTED_PROVIDER_PROFILES = 64;
export const MAXIMUM_APPROVED_PROVIDER_REGIONS = 32;
