"""Grade 3 Mathematics authored blueprint (Manuel Academy, full-family-grade34).

Authored from the Grade 3 Michigan mathematics domains (3.OA, 3.NBT, 3.NF,
3.MD, 3.G) plus the Standards for Mathematical Practice. This is original
Grade 3 sequencing, not a reduction of the Grade 5 course.

Each unit is 18 instructional days. Ten units = 180 days = 36 weeks at 5
days/week. `days` entries are (focus, standards) and follow the fixed
instructional arc defined in arc.py.
"""

GRADE = 3

UNITS = [
  {
    "n": 1,
    "title": "Mathematical Habits, Place Value, and Rounding",
    "eq": "How do we make sense of an unfamiliar problem, and how does place value help us round, add, and subtract within 1,000?",
    "task": "Build a Number Sense Toolkit poster: for each strategy, show a worked example, a model, and a check for reasonableness.",
    "topics": ["problem-solving routines", "place-value structure to 1,000", "rounding to the nearest ten and hundred",
               "addition within 1,000", "subtraction within 1,000", "estimation and reasonableness"],
    "vocabulary": ["digit", "place value", "expanded form", "round", "estimate", "regroup", "sum", "difference", "number line", "reasonable"],
    "representations": ["base-ten blocks or paper place-value strips", "open number line", "place-value chart", "expanded form", "written algorithm"],
    "prerequisites": ["reading and writing three-digit numbers", "addition and subtraction within 100"],
    "fluency": "Add and subtract within 1,000 using place-value strategies and algorithms.",
    "misconceptions": [
      {"pattern": "Rounds using the wrong digit (looks at the leftmost digit instead of the digit to the right of the target place).",
       "probe": "Round 476 to the nearest ten. Which digit decides, and why?",
       "repair": "Locate the number between two consecutive tens on an open number line and name the closer end before applying any rule."},
      {"pattern": "Rounds correctly but drops place value, writing 350 rounded to the nearest hundred as 4 rather than 400.",
       "probe": "You rounded 350 and wrote 4. What does the 4 stand for?",
       "repair": "Say the rounded value aloud in place-value words, then write it in expanded form."},
      {"pattern": "Subtracts the smaller digit from the larger in each column regardless of position.",
       "probe": "For 502 - 138, what happens in the ones place, and is that allowed?",
       "repair": "Model the minuend with base-ten materials and physically trade before recording the written step."},
      {"pattern": "Regroups across a zero incorrectly, treating the zero as nothing to trade.",
       "probe": "In 400 - 176, there are no tens to trade. What can you trade first?",
       "repair": "Trade one hundred for ten tens first, record it, then trade one ten for ten ones."},
      {"pattern": "Treats an estimate as a wrong answer because it does not match the exact sum.",
       "probe": "Your estimate was 700 and the exact answer is 683. Is the estimate wrong?",
       "repair": "Name the purpose of the estimate (checking reasonableness) separately from the purpose of the exact calculation."}
    ],
    "day_misconceptions": [2, 0, 0, 0, 1, 1, 3, 3, 3, 2, 3, 4, 4, 4, 0, 0, 0, 4],
    "topic_standards": {
      "problem-solving routines": ["MP.1", "MP.3"],
      "place-value structure to 1,000": ["3.NBT.1", "MP.7"],
      "rounding to the nearest ten and hundred": ["3.NBT.1"],
      "addition within 1,000": ["3.NBT.2"],
      "subtraction within 1,000": ["3.NBT.2"],
      "estimation and reasonableness": ["3.NBT.1", "MP.3"],
    },
    "connection_prompt": "Explain how rounding helps you decide whether an addition or subtraction answer within 1,000 is reasonable.",
    "assessment_error_stem": "A learner rounded 476 to the nearest ten and wrote 400.",
    "days": [
      ("making sense of unfamiliar problems", "MP.1 MP.3"),
      ("the place-value structure of three-digit numbers", "3.NBT.1 MP.6 MP.7"),
      ("locating three-digit numbers on an open number line", "3.NBT.1 MP.6"),
      ("rounding to the nearest ten", "3.NBT.1"),
      ("rounding to the nearest hundred", "3.NBT.1"),
      ("addition within 1,000 by decomposing place values", "3.NBT.2 MP.6"),
      ("addition with regrouping across place values", "3.NBT.2"),
      ("regrouping errors in written addition", "3.NBT.2 MP.3"),
      ("addition within 1,000", "3.NBT.2"),
      ("subtraction within 1,000 by decomposing place values", "3.NBT.2"),
      ("subtraction with regrouping across zeros", "3.NBT.2 MP.1"),
      ("choosing between an exact answer and an estimate", "3.NBT.1 3.NBT.2 MP.3"),
      ("the Number Sense Toolkit", "3.NBT.1 3.NBT.2 MP.1"),
      ("worked examples with reasonableness checks", "3.NBT.1 3.NBT.2 MP.3"),
      ("place value, rounding, addition, and subtraction", "3.NBT.1 3.NBT.2"),
      ("rounding and computation within 1,000", "3.NBT.1 3.NBT.2 MP.3 MP.6"),
      ("rounding and regrouping", "3.NBT.1 3.NBT.2"),
      ("estimating and checking in everyday situations", "3.NBT.1 MP.1 MP.4")
    ]
  },
  {
    "n": 2,
    "title": "Meanings of Multiplication and Division",
    "eq": "What do multiplication and division actually mean, and how does each one undo the other?",
    "task": "Curate an Equal Groups Museum: each exhibit pairs a model, a story problem, and the matching multiplication and division equations.",
    "topics": ["multiplication as equal groups", "arrays and area", "division as equal sharing",
               "division as equal measuring", "word problems within 100", "multiplication and division as inverses"],
    "vocabulary": ["factor", "product", "quotient", "divisor", "dividend", "equal groups", "array", "row", "column", "unknown factor"],
    "representations": ["counters in equal groups", "arrays on grid paper", "equal-jumps number line", "bar model", "equation with a symbol for the unknown"],
    "prerequisites": ["skip counting by 2s, 5s, and 10s", "repeated addition", "equal sharing with concrete objects"],
    "fluency": "Interpret products and quotients within 100 and match them to models and contexts.",
    "misconceptions": [
      {"pattern": "Swaps the number of groups with the size of each group when writing an equation from a context.",
       "probe": "Four bags hold six marbles each. In 4 x 6, which number is the group size?",
       "repair": "Label the model out loud - 'groups' and 'in each group' - before writing the equation."},
      {"pattern": "Treats division as always meaning 'how many in each group', missing measurement division.",
       "probe": "You have 24 markers and put 6 in each cup. What is unknown here - the group size or the number of groups?",
       "repair": "Sort story problems into 'sharing' and 'measuring' piles and model each with counters."},
      {"pattern": "Reads an array by counting every square individually rather than using rows and columns.",
       "probe": "Can you find the total without counting each square?",
       "repair": "Cover all but one row, name the row size, then count rows."},
      {"pattern": "Believes multiplication always makes a number bigger and division always makes it smaller, then applies the wrong operation.",
       "probe": "Does 1 x 7 make 7 bigger? Does 7 divided by 1 make it smaller?",
       "repair": "Test the claim against models involving 1 and 0 before generalizing."},
      {"pattern": "Solves an unknown-factor problem by guessing rather than using a related known fact.",
       "probe": "For 8 x ? = 32, which multiplication fact family helps?",
       "repair": "Write the fact family for the two known numbers and read off the missing factor."}
    ],
    "day_misconceptions": [0, 0, 2, 0, 0, 1, 1, 0, 2, 3, 4, 4, 0, 2, 3, 0, 1, 3],
    "topic_standards": {
      "multiplication as equal groups": ["3.OA.1"],
      "arrays and area": ["3.OA.1"],
      "division as equal sharing": ["3.OA.2"],
      "division as equal measuring": ["3.OA.2"],
      "word problems within 100": ["3.OA.3"],
      "multiplication and division as inverses": ["3.OA.5", "3.OA.6"],
    },
    "connection_prompt": "Explain how multiplication and division describe the same equal-groups situation from two directions.",
    "assessment_error_stem": "The problem says four bags hold six marbles each. A learner wrote 4 x 6 = 24 and said there are six bags of four marbles.",
    "days": [
      ("noticing equal groups in everyday situations", "3.OA.1 MP.1"),
      ("multiplication as a count of equal groups", "3.OA.1"),
      ("arrays, rows, and columns as multiplication models", "3.OA.1 MP.6"),
      ("writing multiplication equations from models", "3.OA.1"),
      ("interpreting products in context", "3.OA.1 3.OA.3"),
      ("division as sharing a total into equal groups", "3.OA.2"),
      ("division as measuring out groups of a known size", "3.OA.2"),
      ("group-size versus group-count errors", "3.OA.1 3.OA.2 MP.3"),
      ("equal-group models", "3.OA.1 3.OA.2"),
      ("solving multiplication and division word problems within 100", "3.OA.2 3.OA.3"),
      ("unknown-factor problems and fact families", "3.OA.4 3.OA.6"),
      ("multiplication and division as inverse operations", "3.OA.5 3.OA.6"),
      ("the Equal Groups Museum", "3.OA.1 3.OA.2 MP.4"),
      ("exhibits with matched models and equations", "3.OA.1 3.OA.2 3.OA.3"),
      ("operation meanings and relationships", "3.OA.1 3.OA.2 3.OA.6"),
      ("meanings of multiplication and division", "3.OA.1 3.OA.2 3.OA.3 3.OA.6"),
      ("operation meaning", "3.OA.1 3.OA.2 3.OA.3"),
      ("choosing an operation for a new situation", "3.OA.3 MP.1 MP.4")
    ]
  },
  {
    "n": 3,
    "title": "Multiplication and Division Fluency Within 100",
    "eq": "How do properties and facts we already know help us multiply and divide within 100 accurately and efficiently?",
    "task": "Design a fact-strategy deck: each card shows a fact, the strategy that unlocks it, a model, and a way to check.",
    "topics": ["doubling strategies", "fives and tens from place value", "the commutative property",
               "the distributive property", "division from related multiplication", "multiplying by multiples of ten"],
    "vocabulary": ["strategy", "commutative property", "associative property", "distributive property", "double", "half", "multiple of ten", "fact family", "known fact", "derived fact"],
    "representations": ["arrays split into two parts", "number line with equal jumps", "fact-family triangles", "area models on grid paper", "strategy cards"],
    "prerequisites": ["meanings of multiplication and division", "skip counting", "arrays"],
    "fluency": "Multiply and divide within 100, knowing from memory all products of two one-digit numbers by the end of the unit sequence.",
    "misconceptions": [
      {"pattern": "Skip-counts to a near miss and lands one group off (for example 6 x 7 = 48).",
       "probe": "How many sevens did you count? Show them.",
       "repair": "Track each group physically or with tally marks, then verify with a derived fact such as 5 x 7 plus 7."},
      {"pattern": "Does not use commutativity, so treats 3 x 8 and 8 x 3 as two unrelated facts to memorize.",
       "probe": "Turn the array a quarter turn. What changed, and what stayed the same?",
       "repair": "Rotate a physical array and record both equations for the same picture."},
      {"pattern": "Breaks a factor apart but forgets to add the second partial product.",
       "probe": "You split 7 into 5 and 2. Where did the 2 groups go?",
       "repair": "Shade both regions of the split array in different colors and label each partial product before adding."},
      {"pattern": "Writes a division fact with the dividend and divisor reversed.",
       "probe": "In 42 divided by 6, which number is the whole amount you started with?",
       "repair": "State the total first in words, then place it in the equation."},
      {"pattern": "Multiplies by a multiple of ten by appending a zero without understanding the place-value shift.",
       "probe": "Why does 4 x 30 give 120? Where did the ten come from?",
       "repair": "Model 4 x 3 tens with base-ten materials and name the result in tens before writing it."}
    ],
    "day_misconceptions": [0, 0, 0, 1, 0, 2, 2, 0, 0, 3, 4, 3, 1, 2, 1, 0, 0, 1],
    "topic_standards": {
      "doubling strategies": ["3.OA.7", "3.OA.5"],
      "fives and tens from place value": ["3.OA.5", "3.OA.7"],
      "the commutative property": ["3.OA.5"],
      "the distributive property": ["3.OA.5", "MP.7"],
      "division from related multiplication": ["3.OA.6"],
      "multiplying by multiples of ten": ["3.NBT.3"],
    },
    "connection_prompt": "Explain how knowing one multiplication fact helps you find both a related multiplication fact and a related division fact.",
    "assessment_error_stem": "A learner skip-counted by sevens to find 6 x 7 and wrote 48.",
    "days": [
      ("what it means for a fact to be known rather than counted", "3.OA.7 MP.1"),
      ("doubling and the twos, fours, and eights chain", "3.OA.5 3.OA.7"),
      ("fives and tens from place-value patterns", "3.OA.5 3.OA.7"),
      ("using the commutative property to halve the fact load", "3.OA.5"),
      ("deriving threes and sixes from known facts", "3.OA.5 3.OA.7"),
      ("the distributive property: breaking a factor apart", "3.OA.5 MP.7"),
      ("sevens and nines using break-apart strategies", "3.OA.5 3.OA.7"),
      ("near-miss and skip-counting errors", "3.OA.7 MP.3"),
      ("mixed products within 100", "3.OA.7"),
      ("solving unknown-factor equations", "3.OA.4 3.OA.6"),
      ("multiplying one-digit numbers by multiples of ten", "3.NBT.3 3.OA.5"),
      ("division facts derived from related multiplication", "3.OA.6 3.OA.7"),
      ("the fact-strategy deck", "3.OA.5 3.OA.7 MP.4"),
      ("strategy cards with models and checks", "3.OA.5 3.OA.7"),
      ("choosing an efficient strategy", "3.OA.5 3.OA.7 3.NBT.3"),
      ("fluency, strategy, and explanation", "3.OA.4 3.OA.5 3.OA.6 3.OA.7 3.NBT.3"),
      ("unsecured facts", "3.OA.6 3.OA.7"),
      ("accuracy and flexibility without speed pressure", "3.OA.7 MP.6")
    ]
  },
  {
    "n": 4,
    "title": "Properties, Patterns, and Two-Step Problems",
    "eq": "How do we solve problems that hide a second step, and how can patterns help us predict and check?",
    "task": "Write and publish a two-step event problem set; each problem needs a model, an equation with a letter for the unknown, and a reasonableness check.",
    "topics": ["two-step word problems", "equations with a letter for the unknown", "order of operations in context",
               "estimation to check reasonableness", "patterns in the addition and multiplication tables", "explaining patterns with properties"],
    "vocabulary": ["two-step problem", "unknown", "variable letter", "expression", "equation", "pattern", "row", "column", "even", "odd", "reasonable"],
    "representations": ["bar models with two stages", "equations with a letter", "estimation number line", "addition table", "multiplication table"],
    "prerequisites": ["fact fluency within 100", "one-step word problems", "rounding to the nearest ten"],
    "fluency": "Solve two-step word problems using the four operations and assess reasonableness with mental math and estimation.",
    "misconceptions": [
      {"pattern": "Answers only the first step and stops before the question is actually answered.",
       "probe": "Read the question again. Does your number answer that question?",
       "repair": "Underline the question, then check each recorded step against it before finishing."},
      {"pattern": "Adds every number that appears in the problem regardless of what the situation describes.",
       "probe": "What is happening in this story - joining, separating, grouping, or sharing?",
       "repair": "Draw the situation as a bar model before choosing any operation."},
      {"pattern": "Ignores grouping and computes strictly left to right in a two-operation expression.",
       "probe": "In 3 + 4 x 2, which part describes the groups?",
       "repair": "Bracket the multiplication in the model first, then record the expression to match."},
      {"pattern": "Treats a letter for the unknown as a label for an object rather than a number.",
       "probe": "In 5 x b = 45, does b stand for a bag or for a number?",
       "repair": "Say the sentence in words with 'some number' in place of the letter."},
      {"pattern": "Describes a table pattern by appearance only ('it goes up') without an arithmetic explanation.",
       "probe": "Why does every product in this column end in 0 or 5?",
       "repair": "Connect the pattern to the property or place-value fact that causes it."}
    ],
    "day_misconceptions": [0, 1, 3, 2, 2, 1, 0, 0, 0, 1, 4, 4, 3, 3, 0, 0, 0, 1],
    "topic_standards": {
      "two-step word problems": ["3.OA.8"],
      "equations with a letter for the unknown": ["3.OA.8"],
      "order of operations in context": ["3.OA.8", "MP.6"],
      "estimation to check reasonableness": ["3.OA.8", "MP.3"],
      "patterns in the addition and multiplication tables": ["3.OA.9"],
      "explaining patterns with properties": ["3.OA.5", "3.OA.9"],
    },
    "connection_prompt": "Explain how a pattern in the multiplication table can help you check the answer to a two-step problem.",
    "assessment_error_stem": "A problem asks how much money is left after buying 3 notebooks that cost $4 each, starting from $20. A learner wrote 3 x 4 = 12 and answered $12.",
    "days": [
      ("recognizing problems that hide a second step", "3.OA.8 MP.1"),
      ("representing two-step problems with bar models", "3.OA.8"),
      ("writing equations with a letter for the unknown quantity", "3.OA.8"),
      ("order of operations inside two-step situations", "3.OA.8 MP.6"),
      ("two-step problems combining addition and multiplication", "3.OA.8"),
      ("estimation and mental strategies to test reasonableness", "3.OA.8 MP.3"),
      ("two-step problems combining subtraction and division", "3.OA.8"),
      ("stopped-at-step-one errors", "3.OA.8 MP.3"),
      ("facts embedded in multi-step work", "3.OA.7 3.OA.8"),
      ("two-step problems across all four operations", "3.OA.8"),
      ("patterns in the addition and multiplication tables", "3.OA.9"),
      ("explaining patterns using properties and multiples of ten", "3.OA.5 3.OA.9 3.NBT.3"),
      ("the two-step event problem set", "3.OA.8 MP.4"),
      ("problems with models, equations, and checks", "3.OA.8 3.OA.9"),
      ("multi-step reasoning and pattern explanation", "3.OA.8 3.OA.9"),
      ("two-step problems and pattern reasoning", "3.OA.5 3.OA.8 3.OA.9 3.NBT.3"),
      ("multi-step reasoning", "3.OA.8 3.OA.9"),
      ("two-step reasoning in daily planning", "3.OA.8 MP.1 MP.4")
    ]
  },
  {
    "n": 5,
    "title": "Understanding Fractions as Numbers",
    "eq": "What is a fraction, and how do we place one on the number line?",
    "task": "Build a fraction number-line gallery showing unit fractions and non-unit fractions, each with visible evidence that the parts are equal.",
    "topics": ["equal partitioning", "unit fractions", "building fractions from unit fractions",
               "the number line as a length model", "locating fractions on the number line", "identifying the whole"],
    "vocabulary": ["fraction", "numerator", "denominator", "unit fraction", "equal parts", "whole", "partition", "interval", "number line", "point"],
    "representations": ["folded paper strips", "area models partitioned equally", "fraction bars", "number line with marked intervals", "fraction notation"],
    "prerequisites": ["partitioning shapes into halves, thirds, and fourths", "equal sharing", "reading a number line with whole numbers"],
    "fluency": "Name, draw, and locate unit fractions and non-unit fractions with denominators 2, 3, 4, 6, and 8.",
    "misconceptions": [
      {"pattern": "Partitions a shape into the right number of parts without making the parts equal.",
       "probe": "Are these four parts the same size? How could you prove it?",
       "repair": "Cut out and overlay the parts, or fold the strip, before naming the fraction."},
      {"pattern": "Reads a larger denominator as a larger fraction because the number is bigger.",
       "probe": "Which is more of the same pizza - one of eight slices, or one of three slices?",
       "repair": "Compare the physical size of one part as the number of parts increases."},
      {"pattern": "Counts tick marks instead of intervals when locating a fraction on a number line.",
       "probe": "How many equal jumps from 0 to this point?",
       "repair": "Trace and count the jumps between marks, not the marks themselves."},
      {"pattern": "Names a fraction without identifying the whole it refers to.",
       "probe": "One half of what? Show me the whole.",
       "repair": "Outline the whole first and label it before naming any part."},
      {"pattern": "Treats a fraction as two separate whole numbers rather than one number.",
       "probe": "Where does three fourths sit on this number line - is it one place or two?",
       "repair": "Locate the single point on the number line and say its one name."}
    ],
    "day_misconceptions": [0, 0, 1, 4, 0, 2, 2, 2, 1, 2, 3, 3, 0, 0, 4, 1, 0, 3],
    "topic_standards": {
      "equal partitioning": ["3.G.2", "3.NF.1"],
      "unit fractions": ["3.NF.1"],
      "building fractions from unit fractions": ["3.NF.1"],
      "the number line as a length model": ["3.NF.2"],
      "locating fractions on the number line": ["3.NF.2"],
      "identifying the whole": ["3.NF.1", "MP.6"],
    },
    "connection_prompt": "Explain how partitioning a shape into equal parts and marking a fraction on a number line show the same idea.",
    "assessment_error_stem": "A learner cut a rectangle into 4 parts of clearly different sizes, then labeled the largest part 1/4.",
    "days": [
      ("fair shares and what makes parts equal", "3.NF.1 MP.1"),
      ("partitioning shapes into equal parts", "3.G.2 3.NF.1"),
      ("unit fractions as one part of an equally partitioned whole", "3.NF.1"),
      ("non-unit fractions from unit fractions", "3.NF.1"),
      ("naming fractions from area models", "3.NF.1 3.G.2"),
      ("the number line as a length model for fractions", "3.NF.2"),
      ("locating unit fractions on the number line", "3.NF.2"),
      ("tick-mark counting errors", "3.NF.2 MP.3"),
      ("naming and drawing unit fractions", "3.NF.1"),
      ("locating non-unit fractions on the number line", "3.NF.2"),
      ("fractions of a whole in measurement and sharing contexts", "3.NF.1 3.G.2"),
      ("why the whole must always be identified", "3.NF.1 MP.6"),
      ("the fraction number-line gallery", "3.NF.1 3.NF.2 MP.4"),
      ("gallery entries with equal-partition evidence", "3.NF.1 3.NF.2"),
      ("a fraction is a number", "3.NF.1 3.NF.2"),
      ("fractions as numbers", "3.NF.1 3.NF.2 3.G.2"),
      ("partitioning and placement", "3.NF.1 3.NF.2"),
      ("fractions in measurement and sharing", "3.NF.2 MP.4")
    ]
  }
]

UNITS += [
  {
    "n": 6,
    "title": "Equivalent Fractions and Comparison",
    "eq": "When are two fractions the same number, and how can we compare fractions we cannot simply count?",
    "task": "Create a Same Size, Different Name proof set: each claim is backed by a model and a written justification.",
    "topics": ["equivalence on the number line", "equivalence with area models", "generating equivalent fractions",
               "whole numbers as fractions", "comparing with the same numerator", "comparing with the same denominator"],
    "vocabulary": ["equivalent", "equal", "compare", "greater than", "less than", "same whole", "justify", "numerator", "denominator", "whole number as a fraction"],
    "representations": ["stacked fraction bars", "parallel number lines", "area models with the same whole", "fraction notation", "comparison statements with symbols"],
    "prerequisites": ["unit fractions", "locating fractions on a number line", "equal partitioning"],
    "fluency": "Recognize and generate simple equivalent fractions and compare fractions with the same numerator or the same denominator (denominators 2, 3, 4, 6, and 8).",
    "misconceptions": [
      {"pattern": "Compares fractions drawn on wholes of different sizes and concludes the larger picture is the larger fraction.",
       "probe": "Are these two wholes the same size? Can we compare fairly if they are not?",
       "repair": "Redraw both fractions on identical wholes before comparing."},
      {"pattern": "Assumes a bigger denominator always means a bigger fraction.",
       "probe": "Compare one third and one sixth on the same bar. Which part is larger?",
       "repair": "Hold the numerator fixed and watch the part shrink as the denominator grows."},
      {"pattern": "Generates 'equivalent' fractions by adding the same number to numerator and denominator.",
       "probe": "You changed one half to two thirds by adding one to each. Are those the same amount on the bar?",
       "repair": "Test the claim on a model; then re-partition each part to see what equivalence actually does."},
      {"pattern": "Does not recognize that a whole number can be written as a fraction.",
       "probe": "How many fourths make one whole? How would you write that?",
       "repair": "Partition several wholes into four equal parts each and count all the fourths."},
      {"pattern": "Compares two fractions by looking only at numerators or only at denominators.",
       "probe": "Which is greater, three eighths or five eighths? What did you compare?",
       "repair": "Model both fractions on the same whole and compare the shaded amounts directly. In Grade 3, compare only fractions that share a numerator or share a denominator."}
    ],
    "day_misconceptions": [2, 2, 0, 2, 2, 3, 3, 0, 1, 1, 4, 4, 2, 0, 1, 4, 4, 2],
    "topic_standards": {
      "equivalence on the number line": ["3.NF.2", "3.NF.3"],
      "equivalence with area models": ["3.NF.3", "3.G.2"],
      "generating equivalent fractions": ["3.NF.3"],
      "whole numbers as fractions": ["3.NF.3"],
      "comparing with the same numerator": ["3.NF.3"],
      "comparing with the same denominator": ["3.NF.3"],
    },
    "connection_prompt": "Explain how two fractions can name the same amount even though their numerators and denominators are different numbers.",
    "assessment_error_stem": "A learner wrote 1/2 = 2/3, explaining that they added one to the top and one to the bottom.",
    "days": [
      ("two names for the same amount", "3.NF.3 MP.1"),
      ("equivalence seen on the number line", "3.NF.2 3.NF.3"),
      ("equivalence seen with area models", "3.NF.3 3.G.2"),
      ("generating simple equivalent fractions", "3.NF.3"),
      ("recognizing equivalent fractions in models and notation", "3.NF.3"),
      ("whole numbers written as fractions", "3.NF.3"),
      ("fractions equal to whole numbers", "3.NF.3"),
      ("different-whole comparison errors", "3.NF.3 MP.3"),
      ("unit fractions and equivalence", "3.NF.1 3.NF.3"),
      ("comparing fractions with the same numerator", "3.NF.3"),
      ("comparing fractions with the same denominator", "3.NF.3"),
      ("justifying a comparison with a model and a symbol", "3.NF.3 MP.3"),
      ("the Same Size, Different Name proof set", "3.NF.3 MP.4"),
      ("proofs with models and written justifications", "3.NF.3"),
      ("equivalence and comparison", "3.NF.1 3.NF.3"),
      ("equivalence and comparison", "3.NF.1 3.NF.2 3.NF.3"),
      ("comparison reasoning", "3.NF.3"),
      ("recognizing the same amount written different ways", "3.NF.3 MP.4")
    ]
  },
  {
    "n": 7,
    "title": "Measurement: Time, Liquid Volume, and Mass",
    "eq": "How do we measure time, liquid volume, and mass, and how do we know a measurement is reasonable?",
    "task": "Design a day plan and a Measure It station guide with estimates, chosen units, and elapsed-time reasoning.",
    "topics": ["telling time to the minute", "elapsed time on a number line", "time interval problems",
               "liquid volume in liters", "mass in grams and kilograms", "estimating with benchmarks"],
    "vocabulary": ["minute", "hour", "elapsed time", "interval", "liquid volume", "liter", "mass", "gram", "kilogram", "estimate", "benchmark"],
    "representations": ["analog and digital clock faces", "elapsed-time number line", "labeled containers", "balance scale", "benchmark reference objects"],
    "prerequisites": ["telling time to the nearest five minutes", "addition and subtraction within 100", "one-step word problems"],
    "fluency": "Tell and write time to the nearest minute and solve one-step problems involving time intervals, liquid volume, and mass.",
    "misconceptions": [
      {"pattern": "Computes elapsed time by subtracting clock digits as if they were base-ten numbers.",
       "probe": "From 2:45 to 3:20, does 3:20 minus 2:45 equal 0:75?",
       "repair": "Jump forward on an elapsed-time number line in friendly chunks to the next hour, then onward."},
      {"pattern": "Confuses mass units with volume units and reports a drink in grams or a rock in liters.",
       "probe": "Does this measure how heavy it is, or how much space the liquid fills?",
       "repair": "Sort objects into 'we weigh this' and 'we pour this' before selecting a unit."},
      {"pattern": "Gives an estimate with no benchmark, producing an unreasonable value.",
       "probe": "Is a full water bottle closer to 1 liter or 20 liters? What do you know that is about 1 liter?",
       "repair": "Anchor every estimate to a known benchmark object before answering."},
      {"pattern": "Reads only the hour hand position and misnames the hour when the minute hand is past the half hour.",
       "probe": "The hour hand is between 4 and 5. Which hour has already started?",
       "repair": "Name the hour that has begun, then read minutes separately."},
      {"pattern": "Adds the numbers in a measurement problem without attending to the unit.",
       "probe": "You added 3 and 250. What unit is each one in?",
       "repair": "Write the unit next to every number before computing."}
    ],
    "day_misconceptions": [1, 3, 0, 0, 0, 2, 1, 1, 2, 4, 2, 4, 2, 0, 1, 0, 0, 2],
    "topic_standards": {
      "telling time to the minute": ["3.MD.1"],
      "elapsed time on a number line": ["3.MD.1"],
      "time interval problems": ["3.MD.1"],
      "liquid volume in liters": ["3.MD.2", "MP.5"],
      "mass in grams and kilograms": ["3.MD.2"],
      "estimating with benchmarks": ["3.MD.2", "MP.6"],
    },
    "connection_prompt": "Explain how choosing a different unit changes the number you write down without changing the amount you measured.",
    "assessment_error_stem": "A learner found the time from 2:45 to 3:20 by writing 3:20 - 2:45 = 0:75 and answered 75 minutes.",
    "days": [
      ("what we measure and why the unit matters", "3.MD.1 3.MD.2 MP.6"),
      ("telling and writing time to the nearest minute", "3.MD.1"),
      ("elapsed time on a number line", "3.MD.1"),
      ("adding and subtracting time intervals", "3.MD.1"),
      ("elapsed-time problems in real contexts", "3.MD.1"),
      ("measuring and estimating liquid volume in liters", "3.MD.2 MP.5"),
      ("measuring and estimating mass in grams and kilograms", "3.MD.2"),
      ("unit-confusion and unreasonable-estimate errors", "3.MD.2 MP.3"),
      ("time and unit benchmarks", "3.MD.1 3.MD.2"),
      ("one-step problems involving liquid volume and mass", "3.MD.2"),
      ("choosing a unit and estimating before measuring", "3.MD.2 MP.6"),
      ("measurement problems solved by multiplication and division", "3.MD.2 3.OA.3"),
      ("the day plan and Measure It station guide", "3.MD.1 3.MD.2 MP.4"),
      ("the guide with estimates, units, and elapsed-time reasoning", "3.MD.1 3.MD.2"),
      ("measurement reasoning", "3.MD.1 3.MD.2"),
      ("time, liquid volume, and mass", "3.MD.1 3.MD.2"),
      ("elapsed time and units", "3.MD.1 3.MD.2"),
      ("measuring safely with an adult at home", "3.MD.2 MP.4")
    ]
  },
  {
    "n": 8,
    "title": "Data: Scaled Graphs and Measurement Line Plots",
    "eq": "How do we represent data honestly, and what questions can a graph actually answer?",
    "task": "Run a small de-identified survey or measurement study and publish a scaled bar graph, a line plot, and a written interpretation.",
    "topics": ["scaled picture graphs", "scaled bar graphs", "one- and two-step graph questions",
               "measuring to the half and quarter inch", "line plots", "choosing a representation"],
    "vocabulary": ["data", "category", "scale", "key", "axis", "bar graph", "picture graph", "line plot", "half inch", "quarter inch", "interpret"],
    "representations": ["picture graph with a key", "scaled bar graph", "ruler marked in halves and fourths", "line plot", "written interpretation"],
    "prerequisites": ["counting by 2s, 5s, and 10s", "measuring to the nearest inch", "two-step word problems"],
    "fluency": "Draw and read scaled bar and picture graphs and build line plots from measurement data in halves and fourths of an inch.",
    "misconceptions": [
      {"pattern": "Reads a scaled graph as if each unit on the axis were one item.",
       "probe": "What does one square on this axis stand for?",
       "repair": "Read the scale aloud and label a few gridlines with their values before answering."},
      {"pattern": "Answers a 'how many more' question by reading only the taller bar.",
       "probe": "How many more - is that one bar, or the difference between two?",
       "repair": "Mark both values, then subtract, showing the difference on the graph."},
      {"pattern": "Places a measurement at the nearest whole number on a line plot when it falls at a half or quarter mark.",
       "probe": "Your object measured between 3 and 4 inches. Which mark is closest?",
       "repair": "Count the quarter-inch marks between whole numbers before placing the point."},
      {"pattern": "Draws bars of unequal width or with inconsistent spacing, distorting the comparison.",
       "probe": "Do these bars start from the same line and use the same width?",
       "repair": "Use grid paper and a shared baseline for every bar."},
      {"pattern": "Claims a graph proves something it does not show, such as a cause.",
       "probe": "Does this graph tell us why, or only how many?",
       "repair": "Restate the claim so it only says what the data actually shows."}
    ],
    "day_misconceptions": [4, 0, 0, 1, 3, 2, 2, 0, 0, 2, 1, 4, 4, 3, 1, 0, 0, 4],
    "topic_standards": {
      "scaled picture graphs": ["3.MD.3"],
      "scaled bar graphs": ["3.MD.3"],
      "one- and two-step graph questions": ["3.MD.3", "3.OA.8"],
      "measuring to the half and quarter inch": ["3.MD.4", "MP.5"],
      "line plots": ["3.MD.4"],
      "choosing a representation": ["3.MD.3", "3.MD.4", "MP.4"],
    },
    "connection_prompt": "Explain how the scale on a bar graph and the marks on a line plot each change what the display can tell you.",
    "assessment_error_stem": "On a bar graph where each square stands for 5 books, a learner read a bar that is 4 squares tall and answered 4 books.",
    "days": [
      ("questions a graph can and cannot answer", "3.MD.3 MP.3"),
      ("picture graphs with a scaled key", "3.MD.3"),
      ("drawing and reading scaled bar graphs", "3.MD.3"),
      ("one- and two-step questions from a graph", "3.MD.3 3.OA.8"),
      ("a scaled bar graph from a data set", "3.MD.3"),
      ("measuring lengths to the nearest half and quarter inch", "3.MD.4 MP.5"),
      ("a line plot from measurement data", "3.MD.4"),
      ("misleading-scale and axis errors", "3.MD.3 MP.3"),
      ("reading scaled graphs", "3.MD.3"),
      ("interpreting a line plot", "3.MD.4"),
      ("comparing categories with two-step questions", "3.MD.3 3.OA.8"),
      ("choosing a representation that fits the question", "3.MD.3 3.MD.4 MP.4"),
      ("a de-identified survey or measurement study", "3.MD.3 3.MD.4 MP.4"),
      ("the graph, line plot, and interpretation", "3.MD.3 3.MD.4"),
      ("representing and interpreting data", "3.MD.3 3.MD.4"),
      ("scaled graphs and line plots", "3.MD.3 3.MD.4"),
      ("scale and interpretation", "3.MD.3 3.MD.4"),
      ("judging whether a real graph is honest", "3.MD.3 MP.3")
    ]
  },
  {
    "n": 9,
    "title": "Area and the Distributive Property",
    "eq": "What is area, and why can a rectangle be broken apart without changing how much it covers?",
    "task": "Design a floor plan for a small space and justify every area calculation two different ways.",
    "topics": ["area as covering", "unit squares", "measuring area by tiling",
               "area as multiplication of side lengths", "breaking rectangles apart", "rectilinear figures"],
    "vocabulary": ["area", "unit square", "square unit", "tile", "gap", "overlap", "side length", "decompose", "distributive property", "rectilinear"],
    "representations": ["square tiles", "grid paper", "labeled rectangles", "split arrays with two partial products", "decomposed rectilinear figures"],
    "prerequisites": ["arrays", "multiplication within 100", "measuring side lengths"],
    "fluency": "Find the area of rectangles by tiling and by multiplying side lengths, and decompose rectilinear figures into rectangles.",
    "misconceptions": [
      {"pattern": "Confuses area with perimeter and adds side lengths when asked for area.",
       "probe": "Are you measuring the space inside or the distance around?",
       "repair": "Trace the boundary in one color and shade the interior in another before choosing an operation."},
      {"pattern": "Tiles with gaps or overlaps and still reports the tile count as the area.",
       "probe": "Do your tiles cover every part exactly once?",
       "repair": "Rebuild the covering with physical tiles and check for gaps and overlaps."},
      {"pattern": "Reports area in linear units rather than square units.",
       "probe": "You wrote 12 centimeters. Are we counting lengths or squares?",
       "repair": "Name one unit square aloud, then label the result in square units."},
      {"pattern": "Splits a rectangle for the distributive property but multiplies the split parts together instead of adding the partial areas.",
       "probe": "You found two areas. Should they be joined or combined by multiplying?",
       "repair": "Shade both regions and physically push them together to see that areas add."},
      {"pattern": "Decomposes a rectilinear figure into overlapping rectangles and double-counts a region.",
       "probe": "Is any part of this figure inside two of your rectangles?",
       "repair": "Outline each rectangle in a different color to check that none overlap."}
    ],
    "day_misconceptions": [1, 2, 1, 2, 1, 0, 2, 0, 2, 0, 3, 4, 0, 3, 4, 0, 0, 2],
    "topic_standards": {
      "area as covering": ["3.MD.5"],
      "unit squares": ["3.MD.5"],
      "measuring area by tiling": ["3.MD.6"],
      "area as multiplication of side lengths": ["3.MD.7"],
      "breaking rectangles apart": ["3.MD.7", "3.OA.5", "MP.7"],
      "rectilinear figures": ["3.MD.7"],
    },
    "connection_prompt": "Explain how breaking a rectangle into two smaller rectangles shows why you can multiply one side by a sum of two numbers.",
    "assessment_error_stem": "A learner found the area of a rectangle with sides 6 cm and 4 cm by writing 6 + 4 + 6 + 4 = 20 and answered 20 square centimeters.",
    "days": [
      ("covering a surface without gaps or overlaps", "3.MD.5 MP.1"),
      ("unit squares and area as a count of squares", "3.MD.5"),
      ("measuring area by tiling", "3.MD.6"),
      ("counting unit squares in standard square units", "3.MD.6"),
      ("finding area from a tiled figure", "3.MD.5 3.MD.6"),
      ("area as the product of side lengths", "3.MD.7"),
      ("connecting tiling to the area formula", "3.MD.7"),
      ("area-versus-perimeter confusion", "3.MD.7 MP.3"),
      ("products read as areas", "3.MD.7 3.OA.7"),
      ("area of rectangles in real contexts", "3.MD.7"),
      ("breaking a rectangle apart to show the distributive property", "3.MD.7 3.OA.5 MP.7"),
      ("area of combined rectilinear figures", "3.MD.7"),
      ("the floor plan design", "3.MD.7 MP.4"),
      ("the plan with every area justified two ways", "3.MD.7"),
      ("area concepts, tiling, and formulas", "3.MD.5 3.MD.6 3.MD.7"),
      ("area and the distributive property", "3.MD.5 3.MD.6 3.MD.7"),
      ("area reasoning", "3.MD.7"),
      ("area in the spaces around us", "3.MD.7 MP.4")
    ]
  },
  {
    "n": 10,
    "title": "Perimeter, Geometry, and Integrated Capstone",
    "eq": "How do shape, perimeter, and area work together when we design something real?",
    "task": "Capstone: design a small garden, room, or play space using perimeter, area, shape categories, and fractional partitioning, with a written justification of every decision.",
    "topics": ["perimeter of polygons", "unknown side lengths", "same perimeter with different area",
               "quadrilateral categories", "shared attributes", "partitioning shapes into equal areas"],
    "vocabulary": ["perimeter", "polygon", "quadrilateral", "rhombus", "rectangle", "square", "attribute", "category", "equal area", "unit fraction"],
    "representations": ["grid paper outlines", "labeled polygons", "shape sorting by attribute", "partitioned shapes", "scaled design plan"],
    "prerequisites": ["area of rectangles", "addition within 1,000", "unit fractions", "shape names"],
    "fluency": "Solve perimeter problems for polygons, including finding an unknown side length, and classify quadrilaterals by attribute.",
    "misconceptions": [
      {"pattern": "Adds only the two labeled side lengths of a rectangle and reports that as the perimeter.",
       "probe": "How many sides does this rectangle have? Did every side get counted?",
       "repair": "Trace the full boundary with a finger, labeling each side before adding."},
      {"pattern": "Assumes shapes with the same perimeter must have the same area.",
       "probe": "Build two different rectangles with perimeter 12. Do they cover the same amount?",
       "repair": "Construct several rectangles with a fixed perimeter and tabulate their areas."},
      {"pattern": "Classifies a square as not a rectangle because it 'looks different'.",
       "probe": "Does a square have four sides and four square corners, the way a rectangle does?",
       "repair": "Check each defining attribute against the category definition rather than the overall look."},
      {"pattern": "Rotates a shape and treats it as a different shape.",
       "probe": "Did turning it change any side length or angle?",
       "repair": "Physically rotate a cut-out and re-check the attributes."},
      {"pattern": "Partitions a shape into the right number of parts without equal areas and names them unit fractions.",
       "probe": "Do these four parts cover the same amount of space?",
       "repair": "Verify equal area by tiling or by overlaying the parts before naming the fraction."}
    ],
    "day_misconceptions": [0, 0, 0, 1, 1, 2, 2, 3, 0, 4, 1, 4, 1, 2, 3, 2, 0, 4],
    "topic_standards": {
      "perimeter of polygons": ["3.MD.8"],
      "unknown side lengths": ["3.MD.8"],
      "same perimeter with different area": ["3.MD.8"],
      "quadrilateral categories": ["3.G.1"],
      "shared attributes": ["3.G.1"],
      "partitioning shapes into equal areas": ["3.G.2", "3.NF.1"],
    },
    "connection_prompt": "Explain how two shapes can have the same perimeter but cover different amounts of space.",
    "assessment_error_stem": "A learner found the perimeter of a rectangle labeled 8 cm and 3 cm by writing 8 + 3 = 11 cm.",
    "days": [
      ("distance around compared with space inside", "3.MD.8 MP.1"),
      ("finding the perimeter of polygons", "3.MD.8"),
      ("finding an unknown side length from a known perimeter", "3.MD.8"),
      ("same perimeter, different area", "3.MD.8"),
      ("same area, different perimeter", "3.MD.8"),
      ("categories of quadrilaterals and their attributes", "3.G.1"),
      ("attributes shared across shape categories", "3.G.1"),
      ("classification-by-appearance errors", "3.G.1 MP.3"),
      ("perimeter, area, and shape names", "3.MD.8 3.G.1"),
      ("partitioning shapes into parts with equal areas", "3.G.2 3.NF.1"),
      ("design constraints that involve both perimeter and area", "3.MD.7 3.MD.8"),
      ("connecting geometry, fractions, and measurement", "3.G.2 3.NF.1 3.MD.7"),
      ("the capstone design", "3.MD.7 3.MD.8 MP.4"),
      ("the capstone design", "3.MD.8 3.MD.7 3.G.1"),
      ("the mathematical justifications in the capstone design", "3.MD.8 3.G.1 MP.3"),
      ("perimeter, geometry, and partitioning", "3.MD.8 3.G.1 3.G.2"),
      ("perimeter and classification", "3.MD.8 3.G.1"),
      ("perimeter, area, and shape classification in the completed design", "3.G.1 3.MD.8 MP.4")
    ]
  }
]
