"""Grade 4 Mathematics authored blueprint (Manuel Academy, full-family-grade34).

Authored from the Grade 4 Michigan mathematics domains (4.OA, 4.NBT, 4.NF,
4.MD, 4.G) plus the Standards for Mathematical Practice. Original Grade 4
sequencing; it is not a reduction of the Grade 5 course and shares no lesson
content with it.

Verified domain scope honored throughout: base-ten work is limited to whole
numbers less than or equal to 1,000,000, and fraction denominators are limited
to 2, 3, 4, 5, 6, 8, 10, 12, and 100.

Each unit is 18 instructional days. Ten units = 180 days = 36 weeks.
"""

GRADE = 4

UNITS = [
  {
    "n": 1,
    "title": "Mathematical Habits and Place Value to One Million",
    "eq": "How does the base-ten structure let us read, compare, and round whole numbers of any size up to one million?",
    "task": "Build a Ten Times Bigger explainer showing place-value relationships with models, comparisons, and a rounding decision made for a stated purpose.",
    "topics": ["problem-solving routines", "ten-times place-value relationships", "reading and writing multi-digit numbers",
               "comparing multi-digit numbers", "rounding to any place", "estimation and reasonableness"],
    "vocabulary": ["place value", "period", "standard form", "word form", "expanded form", "compare", "round", "estimate", "digit", "ten times"],
    "representations": ["place-value chart with periods", "base-ten reasoning in words", "expanded form", "open number line for rounding", "comparison statements with symbols"],
    "prerequisites": ["place value to 1,000", "rounding to the nearest ten and hundred", "reading three-digit numbers"],
    "fluency": "Read, write, compare, and round multi-digit whole numbers through the hundred thousands.",
    "misconceptions": [
      {"pattern": "Compares multi-digit numbers by counting digits or by the largest single digit anywhere in the number.",
       "probe": "Which is greater, 4,318 or 4,905? Which place actually decides?",
       "repair": "Align both numbers in a place-value chart and compare left to right, stopping at the first place that differs."},
      {"pattern": "Writes expanded form using digits rather than place values, such as 3 + 4 + 7 for 347.",
       "probe": "What is the value of the 3 in 347?",
       "repair": "Say each digit's value aloud in place-value words before recording the expanded form."},
      {"pattern": "Rounds to the wrong place because the target place was not identified first.",
       "probe": "Round 46,271 to the nearest thousand. Which digit is in the thousands place?",
       "repair": "Underline the target place, then look only at the digit immediately to its right."},
      {"pattern": "States the ten-times relationship backwards, saying a digit is ten times the place to its left.",
       "probe": "Is the hundreds place ten times the tens place, or the other way around?",
       "repair": "Move one place left on a place-value chart and confirm the value multiplies by ten."},
      {"pattern": "Drops a zero placeholder when writing a number from its word name.",
       "probe": "Write forty thousand six. How many digits should that have?",
       "repair": "Write the place-value chart headings first and fill every place, including empty ones."}
    ],
    "day_misconceptions": [0, 3, 4, 4, 1, 0, 0, 0, 1, 2, 2, 2, 3, 1, 0, 2, 0, 4],
    "topic_standards": {
      "problem-solving routines": ["MP.1", "MP.3"],
      "ten-times place-value relationships": ["4.NBT.1", "MP.7"],
      "reading and writing multi-digit numbers": ["4.NBT.2"],
      "comparing multi-digit numbers": ["4.NBT.2"],
      "rounding to any place": ["4.NBT.3"],
      "estimation and reasonableness": ["4.NBT.3", "MP.3"],
    },
    "connection_prompt": "Explain how the ten-times relationship between neighboring places makes both comparing and rounding multi-digit numbers possible.",
    "assessment_error_stem": "A learner compared 4,318 and 985 and wrote 985 > 4,318, explaining that 9 is the biggest digit.",
    "days": [
      ("making sense of large numbers and unfamiliar problems", "MP.1 MP.3"),
      ("a digit represents ten times what it represents to its right", "4.NBT.1 MP.7"),
      ("place value through the hundred thousands and beyond", "4.NBT.1 4.NBT.2"),
      ("reading and writing multi-digit numbers in three forms", "4.NBT.2"),
      ("expanded form and number names", "4.NBT.1 4.NBT.2"),
      ("comparing multi-digit numbers using place value", "4.NBT.2"),
      ("recording comparisons with greater than, equal to, and less than", "4.NBT.2 MP.6"),
      ("digit-count comparison errors", "4.NBT.2 MP.3"),
      ("place value and comparison", "4.NBT.1 4.NBT.2"),
      ("rounding multi-digit whole numbers to any place", "4.NBT.3"),
      ("choosing a rounding place to fit a purpose", "4.NBT.3 MP.3"),
      ("estimation as a tool for judging reasonableness", "4.NBT.3 MP.1"),
      ("the Ten Times Bigger explainer", "4.NBT.1 4.NBT.2 MP.4"),
      ("the explainer with models and comparisons", "4.NBT.1 4.NBT.2 4.NBT.3"),
      ("place value, comparison, and rounding", "4.NBT.1 4.NBT.2 4.NBT.3"),
      ("multi-digit place value and rounding", "4.NBT.1 4.NBT.2 4.NBT.3"),
      ("comparison and rounding", "4.NBT.2 4.NBT.3"),
      ("reading large numbers encountered in the world", "4.NBT.3 MP.4")
    ]
  },
  {
    "n": 2,
    "title": "Multi-Digit Addition and Subtraction",
    "eq": "Why does the standard algorithm work, and how do we know an answer is reasonable before we check it?",
    "task": "Audit a set of worked addition and subtraction problems, find and explain every error, and publish a correction guide.",
    "topics": ["the standard addition algorithm", "why regrouping preserves value", "the standard subtraction algorithm",
               "subtraction across zeros", "multistep problems with a letter for the unknown", "reasonableness through rounding"],
    "vocabulary": ["standard algorithm", "regroup", "compose", "decompose", "addend", "sum", "minuend", "subtrahend", "difference", "unknown", "reasonable"],
    "representations": ["place-value chart", "expanded-form recording", "standard algorithm", "bar model for comparison", "rounding number line"],
    "prerequisites": ["addition and subtraction within 1,000", "place value to one million", "rounding to any place"],
    "fluency": "Fluently add and subtract multi-digit whole numbers using the standard algorithm.",
    "misconceptions": [
      {"pattern": "Misaligns place values when writing numbers with different digit counts in a column.",
       "probe": "Which places are lined up in your setup? Where does the ones place sit in each number?",
       "repair": "Rewrite both numbers on a place-value grid so every column holds one place."},
      {"pattern": "Regroups in addition but forgets to add the carried value into the next column.",
       "probe": "You wrote a small 1 above the tens. Did it get added?",
       "repair": "Say the regrouped amount aloud as the first addend of the next column."},
      {"pattern": "Subtracts the smaller digit from the larger in each column regardless of position.",
       "probe": "In this column, which number is on top? Is that what we are subtracting from?",
       "repair": "Model the top number with place-value materials and trade before recording."},
      {"pattern": "Cannot regroup across a zero and either stops or skips the column.",
       "probe": "There are no tens to trade. What is the next larger place you could trade from?",
       "repair": "Trade one hundred for ten tens first, record it, then trade one ten for ten ones."},
      {"pattern": "Accepts an answer without checking, missing an error an estimate would have caught.",
       "probe": "Roughly, about how big should this answer be?",
       "repair": "Round both numbers and compare the estimate with the exact answer before finalizing."}
    ],
    "day_misconceptions": [0, 1, 1, 1, 0, 2, 3, 0, 2, 4, 4, 2, 0, 3, 4, 2, 3, 4],
    "topic_standards": {
      "the standard addition algorithm": ["4.NBT.4"],
      "why regrouping preserves value": ["4.NBT.1", "4.NBT.4"],
      "the standard subtraction algorithm": ["4.NBT.4"],
      "subtraction across zeros": ["4.NBT.4"],
      "multistep problems with a letter for the unknown": ["4.OA.3"],
      "reasonableness through rounding": ["4.NBT.3", "4.OA.3"],
    },
    "connection_prompt": "Explain how rounding gives you a way to tell whether the answer produced by the standard algorithm is reasonable.",
    "assessment_error_stem": "A learner added 3,472 + 596 by lining up the leftmost digits of each number and answered 9,432.",
    "days": [
      ("what the standard algorithm records about place value", "4.NBT.4 MP.1"),
      ("multi-digit addition with regrouping across places", "4.NBT.4"),
      ("why regrouping preserves the value of a number", "4.NBT.1 4.NBT.4"),
      ("fluent multi-digit addition", "4.NBT.4"),
      ("addition inside multistep contexts", "4.NBT.4 4.OA.3"),
      ("multi-digit subtraction with regrouping", "4.NBT.4"),
      ("subtraction across zeros", "4.NBT.4"),
      ("alignment and regrouping errors", "4.NBT.4 MP.3"),
      ("mixed addition and subtraction", "4.NBT.4"),
      ("multistep problems using a letter for the unknown quantity", "4.OA.3"),
      ("assessing reasonableness with rounding and estimation", "4.OA.3 4.NBT.3"),
      ("comparison and difference situations in context", "4.OA.3 4.NBT.4"),
      ("the error-audit correction guide", "4.NBT.4 MP.3"),
      ("corrections with place-value explanations", "4.NBT.4 4.OA.3"),
      ("algorithm, reasoning, and reasonableness", "4.NBT.4 4.OA.3"),
      ("multi-digit addition and subtraction", "4.NBT.3 4.NBT.4 4.OA.3"),
      ("regrouping", "4.NBT.4 4.OA.3"),
      ("checking a total before trusting it", "4.OA.3 MP.4")
    ]
  },
  {
    "n": 3,
    "title": "Multiplicative Comparison, Factors, Multiples, and Patterns",
    "eq": "What does times as many mean, and what do factors, multiples, and rule-based patterns reveal about numbers?",
    "task": "Build a Number Portrait set: for each chosen number show its factor pairs, several multiples, its prime or composite status, and a comparison story.",
    "topics": ["multiplicative comparison statements", "equations for comparison", "additive versus multiplicative comparison",
               "factor pairs within 100", "multiples and divisibility", "prime and composite numbers",
               "number patterns generated from a rule"],
    "vocabulary": ["times as many", "factor", "factor pair", "multiple", "product", "prime", "composite", "divisible", "additive comparison", "multiplicative comparison"],
    "representations": ["comparison bar models", "arrays showing factor pairs", "factor rainbows", "multiplication table", "number portraits"],
    "prerequisites": ["multiplication and division within 100", "arrays", "meanings of the operations"],
    "fluency": "Find all factor pairs for whole numbers 1 to 100 and determine whether a number is prime or composite.",
    "misconceptions": [
      {"pattern": "Reads 'three times as many' as 'three more than'.",
       "probe": "If Ann has 4 and Ben has three times as many, does Ben have 7 or 12?",
       "repair": "Draw Ann's bar, then copy it three times for Ben, before writing any equation."},
      {"pattern": "Finds some factor pairs but stops before all are found, with no system.",
       "probe": "How do you know you have found every pair?",
       "repair": "Test divisors in order from 1 upward and stop when the pair values meet or cross."},
      {"pattern": "Confuses factors with multiples, listing 12, 24, 36 as factors of 12.",
       "probe": "Do these numbers divide 12, or does 12 divide them?",
       "repair": "State the definition each way and sort a mixed list into two labeled columns."},
      {"pattern": "Calls every odd number prime.",
       "probe": "Is 9 prime? What are its factor pairs?",
       "repair": "Test each candidate against small divisors rather than relying on parity."},
      {"pattern": "Treats 1 as prime.",
       "probe": "How many different factors does 1 have?",
       "repair": "Apply the definition, which requires exactly two distinct factors."},
      {"pattern": "Continues a rule-based pattern correctly but cannot name a feature of the pattern that the rule never stated.",
       "probe": "Your rule is add 3 starting at 1. Look at your terms. What do you notice about odd and even?",
       "repair": "Extend the pattern several more terms, then describe one property, such as alternating odd and even, that the rule itself did not mention."}
    ],
    "day_misconceptions": [0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 5, 3, 2, 4, 3, 0, 2, 0],
    "topic_standards": {
      "multiplicative comparison statements": ["4.OA.1"],
      "equations for comparison": ["4.OA.1"],
      "additive versus multiplicative comparison": ["4.OA.2"],
      "factor pairs within 100": ["4.OA.4"],
      "multiples and divisibility": ["4.OA.4"],
      "prime and composite numbers": ["4.OA.4"],
      "number patterns generated from a rule": ["4.OA.5"],
    },
    "connection_prompt": "Explain how the factor pairs of a number decide whether it is prime or composite, and how a rule-generated pattern can show a feature the rule never mentioned.",
    "assessment_error_stem": "Ann has 4 stickers and Ben has three times as many. A learner answered that Ben has 7 stickers.",
    "days": [
      ("more than compared with times as many", "4.OA.1 MP.1"),
      ("interpreting a multiplication equation as a comparison", "4.OA.1"),
      ("writing equations for multiplicative comparisons", "4.OA.1"),
      ("comparison word problems solved with models", "4.OA.2"),
      ("distinguishing additive from multiplicative comparison", "4.OA.2 MP.3"),
      ("finding factor pairs for whole numbers within 100", "4.OA.4"),
      ("finding all factor pairs systematically", "4.OA.4"),
      ("missed-factor and misread-comparison errors", "4.OA.2 4.OA.4 MP.3"),
      ("facts and factor pairs", "4.OA.4"),
      ("recognizing multiples and reasoning about divisibility", "4.OA.4"),
      ("generating a number pattern from a rule and describing a feature the rule does not state", "4.OA.5"),
      ("prime and composite numbers", "4.OA.4"),
      ("the Number Portrait set", "4.OA.4 MP.4"),
      ("portraits with factor pairs, multiples, and stories", "4.OA.1 4.OA.4"),
      ("comparison, factors, and multiples", "4.OA.1 4.OA.2 4.OA.4"),
      ("comparison, factors, and multiples", "4.OA.1 4.OA.2 4.OA.4"),
      ("comparison and factoring", "4.OA.2 4.OA.4"),
      ("describing real relationships as times as many", "4.OA.1 MP.4")
    ]
  },
  {
    "n": 4,
    "title": "Multi-Digit Multiplication with Area Models and Partial Products",
    "eq": "How do area models and place value explain what happens when we multiply larger numbers?",
    "task": "Plan a supply order for a class or family event; justify every product with a model and an estimate before committing to it.",
    "topics": ["multiplying by multiples of ten", "area models", "partial products",
               "four digits by one digit", "two digits by two digits", "estimating products"],
    "vocabulary": ["factor", "product", "partial product", "area model", "multiple of ten", "place-value strategy", "estimate", "decompose", "row", "column"],
    "representations": ["open area models", "partial-product recording", "place-value decomposition", "rounding for estimation", "labeled rectangle diagrams"],
    "prerequisites": ["multiplication facts within 100", "place value to one million", "the distributive property"],
    "fluency": "Multiply a whole number of up to four digits by a one-digit number, and multiply two two-digit numbers, using place-value strategies.",
    "misconceptions": [
      {"pattern": "Multiplies by a multiple of ten by appending a zero without understanding the place-value shift.",
       "probe": "Why does 6 x 40 give 240? Where did the ten come from?",
       "repair": "Model 6 x 4 tens and name the product in tens before writing it in standard form."},
      {"pattern": "Finds only two of the four partial products when multiplying two two-digit numbers.",
       "probe": "Your area model has four regions. How many products did you write?",
       "repair": "Label all four regions of the area model and check each one off as it is computed."},
      {"pattern": "Records a partial product in the wrong place-value column.",
       "probe": "This partial product came from tens times tens. What place should it start in?",
       "repair": "Write the place value of each partial product beside it before adding."},
      {"pattern": "Forgets to add the partial products after computing them.",
       "probe": "You have three numbers written. What is the final step?",
       "repair": "Draw the addition line as part of the setup, not after."},
      {"pattern": "Accepts an unreasonable product because no estimate was made first.",
       "probe": "About how large should 38 x 52 be? Compare that with your answer.",
       "repair": "Round both factors and compute the estimate before the exact product."}
    ],
    "day_misconceptions": [0, 0, 2, 3, 2, 1, 1, 2, 0, 3, 4, 4, 4, 1, 3, 1, 2, 4],
    "topic_standards": {
      "multiplying by multiples of ten": ["4.NBT.1", "4.NBT.5"],
      "area models": ["4.NBT.5", "MP.7"],
      "partial products": ["4.NBT.5"],
      "four digits by one digit": ["4.NBT.5"],
      "two digits by two digits": ["4.NBT.5"],
      "estimating products": ["4.NBT.5", "4.OA.3", "MP.3"],
    },
    "connection_prompt": "Explain how an area model and a written set of partial products record the same multiplication in two different ways.",
    "assessment_error_stem": "A learner multiplied 38 x 52 by writing 3 x 5 = 15 and 8 x 2 = 16, and answered 1,516.",
    "days": [
      ("multiplying beyond the basic facts", "4.NBT.5 MP.1"),
      ("multiplying by multiples of ten", "4.NBT.1 4.NBT.5"),
      ("area models for two digits by one digit", "4.NBT.5 MP.7"),
      ("recording partial products", "4.NBT.5"),
      ("multiplying up to four digits by one digit", "4.NBT.5"),
      ("area models for two digits by two digits", "4.NBT.5"),
      ("partial products with two two-digit factors", "4.NBT.5"),
      ("place-value slips in partial products", "4.NBT.5 MP.3"),
      ("facts and multiples of ten", "4.NBT.5"),
      ("multiplication inside multistep problems", "4.OA.3"),
      ("multiplicative comparison with larger numbers", "4.OA.2"),
      ("estimating products to check reasonableness", "4.NBT.5 4.OA.3 MP.3"),
      ("the supply order", "4.NBT.5 MP.4"),
      ("the order with models and estimates", "4.NBT.5 4.OA.3"),
      ("models, partial products, and estimation", "4.NBT.5 4.OA.2 4.OA.3"),
      ("multi-digit multiplication", "4.NBT.5 4.OA.2 4.OA.3"),
      ("partial products and place-value alignment", "4.NBT.5 4.OA.3"),
      ("scaling a plan up with multiplication", "4.NBT.5 MP.4")
    ]
  },
  {
    "n": 5,
    "title": "Division with Remainders",
    "eq": "What does a remainder mean, and how does the situation decide what to do with it?",
    "task": "Design a fair-distribution plan for a real situation and explain in writing why the remainder was handled the way it was.",
    "topics": ["division as an unknown factor", "area and array models for division", "partial quotients",
               "four digits by one digit", "interpreting remainders", "checking quotients"],
    "vocabulary": ["dividend", "divisor", "quotient", "remainder", "partial quotient", "share", "group", "interpret", "check", "estimate"],
    "representations": ["area models for division", "partial-quotient recording", "arrays", "bar models for sharing", "multiplication check"],
    "prerequisites": ["multiplication facts and multi-digit multiplication", "place value", "meanings of division"],
    "fluency": "Find whole-number quotients and remainders with up to four-digit dividends and one-digit divisors.",
    "misconceptions": [
      {"pattern": "Ignores the remainder and reports only the whole-number quotient regardless of context.",
       "probe": "There are 3 left over. In this story, do they disappear?",
       "repair": "Reread the question and decide what the leftover amount means for the situation."},
      {"pattern": "Always rounds the quotient up, or always drops the remainder, without reading the context.",
       "probe": "Do we need enough buses for everyone, or how many full boxes we can fill?",
       "repair": "Sort remainder problems into drop-it, round-up, and report-what-is-left-over categories."},
      {"pattern": "Omits a zero in the quotient when a place cannot be divided.",
       "probe": "How many hundreds are in your quotient? Did that place get a digit?",
       "repair": "Record a digit for every place in the dividend, including zeros."},
      {"pattern": "Writes a remainder that is larger than the divisor.",
       "probe": "Your remainder is 7 and the divisor is 5. Could another group be made?",
       "repair": "Check that the remainder is always less than the divisor before finishing."},
      {"pattern": "Does not verify the quotient, missing an error multiplication would have caught.",
       "probe": "Multiply your quotient by the divisor and add the remainder. What should you get?",
       "repair": "Make the multiplication check a required final step."}
    ],
    "day_misconceptions": [0, 3, 3, 2, 2, 0, 1, 2, 3, 1, 4, 4, 1, 0, 0, 1, 2, 1],
    "topic_standards": {
      "division as an unknown factor": ["4.NBT.6"],
      "area and array models for division": ["4.NBT.6"],
      "partial quotients": ["4.NBT.6"],
      "four digits by one digit": ["4.NBT.6"],
      "interpreting remainders": ["4.OA.3"],
      "checking quotients": ["4.NBT.6", "MP.3"],
    },
    "connection_prompt": "Explain how multiplying the quotient by the divisor checks a division, and why the remainder has to be added back in.",
    "assessment_error_stem": "A learner divided 43 cookies among 5 friends, answered 8 remainder 3, and then said each friend gets 8 cookies and the 3 left over do not matter.",
    "days": [
      ("sharing that does not come out even", "4.NBT.6 MP.1"),
      ("division as an unknown-factor problem with place value", "4.NBT.6"),
      ("area and array models for division", "4.NBT.6"),
      ("recording partial quotients", "4.NBT.6"),
      ("dividing up to four digits by a one-digit divisor", "4.NBT.6"),
      ("interpreting remainders in context", "4.OA.3"),
      ("remainder decisions: drop it, round up, or report what is left over", "4.OA.3"),
      ("ignored-remainder and missing-zero errors", "4.NBT.6 MP.3"),
      ("division facts and multiples", "4.NBT.6"),
      ("multistep problems that involve division", "4.OA.3"),
      ("checking a quotient by multiplying", "4.NBT.6 MP.3"),
      ("estimating to predict the size of a quotient", "4.NBT.6 4.OA.3"),
      ("the fair-distribution plan", "4.OA.3 MP.4"),
      ("the plan with a written remainder justification", "4.NBT.6 4.OA.3"),
      ("division strategy and remainder interpretation", "4.NBT.6 4.OA.3"),
      ("division and remainders", "4.NBT.6 4.OA.3"),
      ("quotients and remainders", "4.NBT.6 4.OA.3"),
      ("fair sharing decisions in real situations", "4.OA.3 MP.4")
    ]
  }
]

UNITS += [
  {
    "n": 6,
    "title": "Fraction Equivalence and Comparison",
    "eq": "Why does multiplying the numerator and the denominator by the same number leave a fraction unchanged?",
    "task": "Create an equivalence proof wall where every claim is backed by a visual model and a written argument.",
    "topics": ["equivalence by further partitioning", "why a/b equals (n x a)/(n x b)", "generating equivalent fractions",
               "common denominators", "benchmark fractions", "justifying comparisons"],
    "vocabulary": ["equivalent fraction", "numerator", "denominator", "common denominator", "common numerator", "benchmark", "simplify", "same whole", "justify", "compare"],
    "representations": ["area models re-partitioned", "parallel number lines", "fraction strips", "symbolic generation of equivalents", "comparison statements"],
    "prerequisites": ["fractions as numbers", "unit fractions", "comparing fractions with like denominators or like numerators"],
    "fluency": "Generate equivalent fractions and compare two fractions with different numerators and denominators (denominators 2, 3, 4, 5, 6, 8, 10, 12, and 100).",
    "misconceptions": [
      {"pattern": "Generates equivalents by adding the same number to numerator and denominator.",
       "probe": "You turned two thirds into three fourths by adding one to each. Do the models match?",
       "repair": "Re-partition the model and count the new parts to see that equivalence multiplies rather than adds."},
      {"pattern": "Compares fractions by comparing numerators alone or denominators alone.",
       "probe": "Which is greater, two thirds or five sixths? What exactly did you compare?",
       "repair": "Rewrite both with a common denominator, or compare each to the benchmark one half."},
      {"pattern": "Compares fractions that refer to different wholes and reports a result anyway.",
       "probe": "Half of a small pizza and half of a large pizza - are those the same amount?",
       "repair": "State the whole for each fraction before any comparison is allowed."},
      {"pattern": "Believes a fraction with a larger denominator is always smaller, even when numerators differ.",
       "probe": "Is five sixths smaller than one half because six is larger than two?",
       "repair": "Check both fractions against the benchmark one half before generalizing."},
      {"pattern": "Simplifies by dividing only the numerator.",
       "probe": "You halved the top. What has to happen to the bottom?",
       "repair": "Apply the same operation to both parts and verify with a model."}
    ],
    "day_misconceptions": [0, 0, 0, 0, 4, 4, 1, 1, 3, 3, 2, 1, 0, 2, 3, 1, 1, 2],
    "topic_standards": {
      "equivalence by further partitioning": ["4.NF.1"],
      "why a/b equals (n x a)/(n x b)": ["4.NF.1"],
      "generating equivalent fractions": ["4.NF.1"],
      "common denominators": ["4.NF.1", "4.NF.2"],
      "benchmark fractions": ["4.NF.2"],
      "justifying comparisons": ["4.NF.2", "MP.3"],
    },
    "connection_prompt": "Explain how generating an equivalent fraction is what makes it possible to compare two fractions with unlike denominators.",
    "assessment_error_stem": "A learner wrote 2/3 = 3/4, explaining that they added one to the top and one to the bottom.",
    "days": [
      ("the same amount written with a different name", "4.NF.1 MP.1"),
      ("equivalence produced by partitioning a model further", "4.NF.1"),
      ("why a/b equals n times a over n times b", "4.NF.1"),
      ("generating equivalent fractions", "4.NF.1"),
      ("recognizing equivalence across models and notation", "4.NF.1"),
      ("rewriting fractions with a common denominator", "4.NF.1"),
      ("comparing fractions using a common denominator", "4.NF.2"),
      ("numerator-only comparison errors", "4.NF.2 MP.3"),
      ("equivalence and benchmarks", "4.NF.1 4.NF.2"),
      ("comparing fractions using benchmark values", "4.NF.2"),
      ("comparing only when fractions refer to the same whole", "4.NF.2 MP.6"),
      ("justifying comparisons visually and symbolically", "4.NF.1 4.NF.2 MP.3"),
      ("the equivalence proof wall", "4.NF.1 MP.4"),
      ("claims with models and written arguments", "4.NF.1 4.NF.2"),
      ("equivalence and comparison", "4.NF.1 4.NF.2"),
      ("fraction equivalence and comparison", "4.NF.1 4.NF.2"),
      ("comparison strategy", "4.NF.1 4.NF.2"),
      ("recognizing equivalent amounts in real settings", "4.NF.2 MP.4")
    ]
  },
  {
    "n": 7,
    "title": "Adding, Subtracting, and Multiplying Fractions",
    "eq": "How is adding fractions simply counting unit fractions, and what happens when a fraction is multiplied by a whole number?",
    "task": "Build a recipe or measurement plan that combines fractional amounts and then scales the whole plan by a whole number.",
    "topics": ["decomposing into unit fractions", "adding and subtracting like denominators", "mixed numbers",
               "word problems with fractions", "multiplying a fraction by a whole number", "fractions in measurement"],
    "vocabulary": ["unit fraction", "decompose", "mixed number", "improper fraction", "like denominator", "sum", "difference", "multiple", "scale", "same whole"],
    "representations": ["fraction strips", "number lines with unit-fraction jumps", "area models", "mixed-number diagrams", "repeated-addition equations"],
    "prerequisites": ["fraction equivalence", "unit fractions", "multiplication facts"],
    "fluency": "Add and subtract fractions and mixed numbers with like denominators, and multiply a fraction by a whole number.",
    "misconceptions": [
      {"pattern": "Adds denominators as well as numerators, reporting one fourth plus two fourths as three eighths.",
       "probe": "You are counting fourths. Does the size of each piece change when you count more of them?",
       "repair": "Count unit fractions aloud on a strip; the denominator names the piece size and does not change."},
      {"pattern": "Converts a mixed number to an improper fraction by adding the whole number to the numerator.",
       "probe": "How many fourths are in 2 whole units alone?",
       "repair": "Partition each whole into four equal parts and count all the fourths before adding the extra ones."},
      {"pattern": "Subtracts mixed numbers without regrouping when the fractional part is too small.",
       "probe": "You need to take five sixths from two sixths. What can you trade?",
       "repair": "Trade one whole for six sixths first, then subtract."},
      {"pattern": "Multiplies a fraction by a whole number by multiplying both the numerator and the denominator.",
       "probe": "Three groups of two fifths - does the piece size change, or only how many pieces?",
       "repair": "Model repeated addition and observe that only the count of unit fractions grows."},
      {"pattern": "Decomposes a fraction in only one way and assumes it is the only decomposition.",
       "probe": "Can three fourths be broken apart differently and still be three fourths?",
       "repair": "List several decompositions and verify each sums to the original."}
    ],
    "day_misconceptions": [0, 4, 0, 1, 2, 0, 3, 0, 4, 3, 2, 3, 4, 1, 0, 3, 1, 3],
    "topic_standards": {
      "decomposing into unit fractions": ["4.NF.3"],
      "adding and subtracting like denominators": ["4.NF.3"],
      "mixed numbers": ["4.NF.3"],
      "word problems with fractions": ["4.NF.3"],
      "multiplying a fraction by a whole number": ["4.NF.4"],
      "fractions in measurement": ["4.NF.4", "4.MD.2"],
    },
    "connection_prompt": "Explain how adding fractions with like denominators and multiplying a fraction by a whole number are both just counting unit fractions.",
    "assessment_error_stem": "A learner added 1/4 + 2/4 and answered 3/8.",
    "days": [
      ("a fraction as a count of unit fractions", "4.NF.3 MP.1"),
      ("decomposing a fraction into a sum of unit fractions", "4.NF.3"),
      ("adding and subtracting fractions with like denominators", "4.NF.3"),
      ("mixed numbers and fractions greater than one", "4.NF.3"),
      ("adding and subtracting mixed numbers with like denominators", "4.NF.3"),
      ("word problems adding and subtracting like-denominator fractions", "4.NF.3"),
      ("multiplying a fraction by a whole number as repeated addition", "4.NF.4"),
      ("added-denominator errors", "4.NF.3 MP.3"),
      ("unit-fraction decomposition", "4.NF.3"),
      ("solving word problems that multiply a fraction by a whole number", "4.NF.4"),
      ("fraction operations inside measurement contexts", "4.NF.4 4.MD.2"),
      ("connecting repeated addition to n times a over b", "4.NF.4 MP.3"),
      ("the recipe or measurement plan", "4.NF.3 4.NF.4 MP.4"),
      ("the plan with combined and scaled amounts", "4.NF.3 4.NF.4"),
      ("fraction operations", "4.NF.3 4.NF.4"),
      ("fraction addition, subtraction, and multiplication", "4.NF.3 4.NF.4"),
      ("fraction operations", "4.NF.3 4.NF.4"),
      ("scaling a fractional plan for more people", "4.NF.4 MP.4")
    ]
  },
  {
    "n": 8,
    "title": "Decimal Notation and Fraction-Decimal Connections",
    "eq": "How can tenths and hundredths be written as both fractions and decimals, and how do we compare them?",
    "task": "Create a money-and-measurement conversion board linking fractions, decimals, models, and comparisons for the same amounts.",
    "topics": ["tenths and hundredths as fractions", "adding tenths and hundredths", "decimal notation",
               "decimals on the number line", "decimals in money and measurement", "comparing decimals"],
    "vocabulary": ["tenth", "hundredth", "decimal point", "decimal notation", "equivalent", "compare", "money notation", "place value", "same whole", "order"],
    "representations": ["tenths and hundredths grids", "number lines partitioned in tenths and hundredths", "money amounts", "place-value chart with decimals", "comparison statements"],
    "prerequisites": ["fraction equivalence", "place value", "comparing fractions"],
    "fluency": "Write fractions with denominators 10 and 100 in decimal notation and compare two decimals to hundredths.",
    "misconceptions": [
      {"pattern": "Compares decimals by digit count, concluding 0.25 is greater than 0.5.",
       "probe": "Shade both on hundredths grids. Which covers more?",
       "repair": "Rewrite both with the same number of decimal places and compare place by place."},
      {"pattern": "Reads 0.7 as seven hundredths rather than seven tenths.",
       "probe": "How many parts is the whole cut into when there is one digit after the point?",
       "repair": "Name the place aloud from a place-value chart before reading the value."},
      {"pattern": "Adds tenths to hundredths without rewriting to a common denominator.",
       "probe": "Can you add three tenths and four hundredths directly? What are the piece sizes?",
       "repair": "Rewrite tenths as hundredths, then add like units."},
      {"pattern": "Treats the decimal point as separating two independent whole numbers.",
       "probe": "Is 3.7 the same as three and seven, or three and seven tenths?",
       "repair": "Locate the value on a number line between consecutive whole numbers."},
      {"pattern": "Compares decimals attached to different wholes and reports a result anyway.",
       "probe": "Half of one dollar and half of one meter - are those the same amount?",
       "repair": "Identify the whole for each value before comparing."}
    ],
    "day_misconceptions": [1, 1, 2, 1, 3, 3, 0, 0, 1, 0, 2, 4, 1, 2, 3, 0, 0, 4],
    "topic_standards": {
      "tenths and hundredths as fractions": ["4.NF.5"],
      "adding tenths and hundredths": ["4.NF.5"],
      "decimal notation": ["4.NF.6"],
      "decimals on the number line": ["4.NF.6"],
      "decimals in money and measurement": ["4.NF.6", "4.MD.2"],
      "comparing decimals": ["4.NF.7"],
    },
    "connection_prompt": "Explain how a fraction with denominator 100 and a decimal written to hundredths describe the same amount.",
    "assessment_error_stem": "A learner compared 0.25 and 0.5 and wrote 0.25 > 0.5, explaining that 25 is greater than 5.",
    "days": [
      ("two ways to write the same amount", "4.NF.6 MP.1"),
      ("tenths and hundredths written as fractions", "4.NF.5"),
      ("adding tenths and hundredths by rewriting to a common unit", "4.NF.5"),
      ("writing fractions with denominator 10 or 100 in decimal notation", "4.NF.6"),
      ("locating decimals on a number line", "4.NF.6"),
      ("decimals in money and measurement contexts", "4.NF.6 4.MD.2"),
      ("comparing decimals to hundredths", "4.NF.7"),
      ("digit-count decimal comparison errors", "4.NF.7 MP.3"),
      ("fraction and decimal equivalents", "4.NF.6"),
      ("comparing and ordering decimals", "4.NF.7"),
      ("money problems involving decimals", "4.MD.2 4.NF.5 4.NF.6"),
      ("why a comparison requires the same whole", "4.NF.7 MP.6"),
      ("the conversion board", "4.NF.6 MP.4"),
      ("the board with fractions, decimals, models, and comparisons", "4.NF.5 4.NF.6 4.NF.7"),
      ("fraction and decimal connections", "4.NF.5 4.NF.6 4.NF.7"),
      ("decimal notation and comparison", "4.NF.5 4.NF.6 4.NF.7"),
      ("decimal comparison", "4.NF.6 4.NF.7"),
      ("reading decimals on price tags and measuring tools", "4.NF.6 MP.4")
    ]
  },
  {
    "n": 9,
    "title": "Measurement, Conversion, and Data",
    "eq": "How do we convert between units, apply area and perimeter formulas, and represent measurement data precisely?",
    "task": "Measure a real space and a set of objects; publish a conversion table, an area and perimeter analysis, and a line plot in fractions of an inch.",
    "topics": ["relative sizes of metric units", "relative sizes of customary units", "two-column conversion tables",
               "measurement word problems", "area and perimeter formulas", "line plots with fractional measurements"],
    "vocabulary": ["convert", "unit", "kilometer", "meter", "centimeter", "kilogram", "gram", "pound", "ounce", "perimeter", "area", "formula", "line plot"],
    "representations": ["two-column conversion tables", "labeled rectangles", "measuring tools marked in fractions", "line plots with halves, quarters, and eighths", "measurement diagrams"],
    "prerequisites": ["multiplication and division", "fraction operations", "area and perimeter of rectangles from Grade 3"],
    "fluency": "Convert measurements from a larger unit to a smaller unit within one system, and apply area and perimeter formulas for rectangles.",
    "misconceptions": [
      {"pattern": "Converts in the wrong direction, dividing when the new unit is smaller.",
       "probe": "Meters to centimeters - are the pieces getting smaller? Should the number get bigger or smaller?",
       "repair": "Predict whether the number grows or shrinks before computing, then check."},
      {"pattern": "Mixes units within a single calculation without converting first.",
       "probe": "You added 2 meters and 40 centimeters and wrote 42. What unit is that?",
       "repair": "Convert everything to a single unit before operating."},
      {"pattern": "Substitutes into the area formula when the problem asks for perimeter, or the reverse.",
       "probe": "Are you finding the space covered or the distance around?",
       "repair": "Restate the question in words, then choose the matching formula."},
      {"pattern": "Cannot find an unknown side length from a given area or perimeter.",
       "probe": "If the area is 48 and one side is 6, what multiplication fact helps?",
       "repair": "Write the formula with the unknown shown, then solve it as an unknown-factor problem."},
      {"pattern": "Places fractional measurements at whole-number marks on a line plot.",
       "probe": "Your object measured three and one eighth inches. Which mark is that?",
       "repair": "Count the eighth-inch marks between whole numbers before plotting."}
    ],
    "day_misconceptions": [0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 4, 3, 4, 2, 3, 2, 0, 1],
    "topic_standards": {
      "relative sizes of metric units": ["4.MD.1", "MP.5"],
      "relative sizes of customary units": ["4.MD.1"],
      "two-column conversion tables": ["4.MD.1"],
      "measurement word problems": ["4.MD.2"],
      "area and perimeter formulas": ["4.MD.3"],
      "line plots with fractional measurements": ["4.MD.4"],
    },
    "connection_prompt": "Explain why measurements have to be converted to a common unit before an area or perimeter formula can be applied to them.",
    "assessment_error_stem": "A learner converted 3 meters to centimeters and answered 0.03 centimeters.",
    "days": [
      ("why the size of a unit changes the number", "4.MD.1 MP.1"),
      ("relative sizes of metric units", "4.MD.1 MP.5"),
      ("relative sizes of customary units", "4.MD.1"),
      ("two-column conversion tables", "4.MD.1"),
      ("converting from a larger unit to a smaller unit", "4.MD.1"),
      ("measurement word problems including money and time", "4.MD.2"),
      ("measurement problems involving fractions and decimals", "4.MD.2"),
      ("wrong-direction conversion errors", "4.MD.1 MP.3"),
      ("unit benchmarks and conversions", "4.MD.1"),
      ("applying area and perimeter formulas for rectangles", "4.MD.3"),
      ("line plots with halves, quarters, and eighths of an inch", "4.MD.4"),
      ("finding an unknown side length from area or perimeter", "4.MD.3"),
      ("the measurement study", "4.MD.1 4.MD.4 MP.4"),
      ("the conversion table, area analysis, and line plot", "4.MD.1 4.MD.3 4.MD.4"),
      ("conversion, formulas, and measurement data", "4.MD.1 4.MD.2 4.MD.3 4.MD.4"),
      ("measurement, conversion, and data", "4.MD.1 4.MD.2 4.MD.3 4.MD.4"),
      ("conversion and formulas", "4.MD.1 4.MD.3"),
      ("measuring and converting for a real task", "4.MD.2 MP.4")
    ]
  },
  {
    "n": 10,
    "title": "Angles, Geometry, and Integrated Capstone",
    "eq": "How do lines, angles, and symmetry describe the shapes we design and build?",
    "task": "Capstone: design a symmetric plan for a garden, room, banner, or game board using measured angles, classified shapes, and a generated pattern, with a full written justification.",
    "topics": ["angles as fractions of a circle", "measuring angles with a protractor", "additive angle measure",
               "points, lines, rays, and angle types", "classifying two-dimensional figures", "symmetry and generated patterns"],
    "vocabulary": ["ray", "vertex", "degree", "protractor", "acute", "obtuse", "right", "parallel", "perpendicular", "line of symmetry", "rule", "pattern"],
    "representations": ["circles partitioned into degrees", "protractor diagrams", "angle decomposition diagrams", "shape classification charts", "symmetry folds"],
    "prerequisites": ["quadrilateral categories from Grade 3", "measurement", "addition and subtraction"],
    "fluency": "Measure and sketch angles in whole-number degrees, classify two-dimensional figures, and identify lines of symmetry.",
    "misconceptions": [
      {"pattern": "Reads the wrong protractor scale, reporting 130 degrees for a 50-degree angle.",
       "probe": "Is this angle smaller or larger than a right angle? Does your number agree?",
       "repair": "Classify the angle as acute or obtuse first, then choose the scale that matches."},
      {"pattern": "Judges angle size by the drawn length of the rays rather than the opening.",
       "probe": "If the rays were longer, would the opening change?",
       "repair": "Extend the rays and re-measure to confirm the measure is unchanged."},
      {"pattern": "Does not align the protractor vertex and baseline with the angle.",
       "probe": "Where is the center mark of the protractor sitting?",
       "repair": "Place the vertex on the center mark and one ray on the zero line before reading."},
      {"pattern": "Assumes any fold that halves the area is a line of symmetry.",
       "probe": "When you fold here, do the two halves match exactly?",
       "repair": "Physically fold and check that every point maps onto a matching point."},
      {"pattern": "Continues a pattern correctly but cannot state a feature that follows from the rule.",
       "probe": "Your rule adds 3 each time. What do you notice about whether the terms are odd or even?",
       "repair": "Extend the pattern several terms and describe a property the rule did not state explicitly."}
    ],
    "day_misconceptions": [1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 2, 3, 3, 2, 4, 0, 2, 4],
    "topic_standards": {
      "angles as fractions of a circle": ["4.MD.5"],
      "measuring angles with a protractor": ["4.MD.6", "MP.5"],
      "additive angle measure": ["4.MD.7"],
      "points, lines, rays, and angle types": ["4.G.1"],
      "classifying two-dimensional figures": ["4.G.2"],
      "symmetry and generated patterns": ["4.G.3", "4.OA.5"],
    },
    "connection_prompt": "Explain how angle measure and line symmetry each describe something about a shape that side lengths alone cannot.",
    "assessment_error_stem": "A learner measured an angle that is clearly smaller than a right angle and reported 130 degrees.",
    "days": [
      ("what an angle actually measures", "4.MD.5 MP.1"),
      ("angles as fractions of a circular turn", "4.MD.5"),
      ("measuring angles with a protractor", "4.MD.6 MP.5"),
      ("sketching angles of a specified measure", "4.MD.6"),
      ("measuring and drawing angles accurately", "4.MD.5 4.MD.6"),
      ("angle measure as additive and unknown-angle problems", "4.MD.7"),
      ("solving for an unknown angle in a diagram", "4.MD.7"),
      ("protractor scale-reading errors", "4.MD.6 MP.3"),
      ("angle types and measures", "4.MD.5 4.MD.6"),
      ("points, lines, segments, rays, and angle types in figures", "4.G.1"),
      ("solving unknown-angle problems inside classified figures", "4.MD.7 4.G.2"),
      ("lines of symmetry and patterns generated from a rule", "4.G.3 4.OA.5"),
      ("the capstone design", "4.G.2 4.G.3 MP.4"),
      ("the capstone design", "4.MD.6 4.MD.7 4.G.1 4.G.2"),
      ("the mathematical justifications in the capstone design", "4.G.2 4.G.3 MP.3"),
      ("angles, geometry, and symmetry", "4.MD.5 4.MD.6 4.MD.7 4.G.1 4.G.2 4.G.3"),
      ("angle and classification work", "4.MD.6 4.MD.7 4.G.2"),
      ("symmetry and rule-based patterns in the completed design", "4.OA.5 4.G.3 MP.4")
    ]
  }
]
