// GENERATED by ./generate.node.ts from the frozen curriculum release. Do not edit.
//
// Every specifier below is a static string, which is what lets Vite split each
// course's lessons into its own chunk and keep them out of the initial bundle.
// A glob or a computed specifier would forfeit that, so this stays explicit.
import type { GeneratedLessonRow } from './rows'

export type CourseLessonLoader = () => Promise<{ default: readonly GeneratedLessonRow[] }>

export const COURSE_LESSON_LOADERS: Readonly<Record<string, CourseLessonLoader>> = {
  "ma-g5-arts-and-music": () => import('./generated/courses/ma-g5-arts-and-music'),
  "ma-g5-english-language-arts": () => import('./generated/courses/ma-g5-english-language-arts'),
  "ma-g5-financial-literacy": () => import('./generated/courses/ma-g5-financial-literacy'),
  "ma-g5-health": () => import('./generated/courses/ma-g5-health'),
  "ma-g5-mathematics": () => import('./generated/courses/ma-g5-mathematics'),
  "ma-g5-physical-education": () => import('./generated/courses/ma-g5-physical-education'),
  "ma-g5-ready-for-life": () => import('./generated/courses/ma-g5-ready-for-life'),
  "ma-g5-science": () => import('./generated/courses/ma-g5-science'),
  "ma-g5-social-studies": () => import('./generated/courses/ma-g5-social-studies'),
  "ma-g5-technology": () => import('./generated/courses/ma-g5-technology'),
  "ma-g7-arts-and-music": () => import('./generated/courses/ma-g7-arts-and-music'),
  "ma-g7-english-language-arts": () => import('./generated/courses/ma-g7-english-language-arts'),
  "ma-g7-financial-literacy": () => import('./generated/courses/ma-g7-financial-literacy'),
  "ma-g7-health": () => import('./generated/courses/ma-g7-health'),
  "ma-g7-mathematics": () => import('./generated/courses/ma-g7-mathematics'),
  "ma-g7-physical-education": () => import('./generated/courses/ma-g7-physical-education'),
  "ma-g7-ready-for-life": () => import('./generated/courses/ma-g7-ready-for-life'),
  "ma-g7-science": () => import('./generated/courses/ma-g7-science'),
  "ma-g7-social-studies": () => import('./generated/courses/ma-g7-social-studies'),
  "ma-g7-technology": () => import('./generated/courses/ma-g7-technology'),
  "ma-g8-arts-and-music": () => import('./generated/courses/ma-g8-arts-and-music'),
  "ma-g8-english-language-arts": () => import('./generated/courses/ma-g8-english-language-arts'),
  "ma-g8-financial-literacy": () => import('./generated/courses/ma-g8-financial-literacy'),
  "ma-g8-health": () => import('./generated/courses/ma-g8-health'),
  "ma-g8-mathematics": () => import('./generated/courses/ma-g8-mathematics'),
  "ma-g8-physical-education": () => import('./generated/courses/ma-g8-physical-education'),
  "ma-g8-ready-for-life": () => import('./generated/courses/ma-g8-ready-for-life'),
  "ma-g8-science": () => import('./generated/courses/ma-g8-science'),
  "ma-g8-social-studies": () => import('./generated/courses/ma-g8-social-studies'),
  "ma-g8-technology": () => import('./generated/courses/ma-g8-technology'),
}
