#!/usr/bin/env python3
"""Render source-projection.json as SOURCE-PROJECTION.md. Generated; do not edit."""
import json
import os
from collections import Counter, OrderedDict

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJ = os.path.join(HERE, "source-projection.json")
OUT = os.path.join(HERE, "SOURCE-PROJECTION.md")


def main():
    p = json.load(open(PROJ, encoding="utf-8"))
    by_course = OrderedDict()
    for row in p["lessons"]:
        by_course.setdefault(row["courseId"], []).append(row)

    lines = ["# Social Studies source projection -- release admission",
             "",
             "Generated by `tools/build-projection.py`. Do not edit by hand.",
             "",
             "| Class | Lessons | Meaning |", "|---|---:|---|"]
    for name, meaning in p["classes"].items():
        lines.append("| `%s` | %d | %s |" % (name, p["totals"].get(name, 0), meaning))
    lines += ["",
              "Admissible: **%d** | Blocked: **%d** | No claim made: **%d**"
              % (p["admissibleCount"], p["blockedCount"], p["unclaimedCount"]),
              "",
              "What the dynamic validator checks: %s" % p["whatTheDynamicValidatorChecks"],
              "",
              "## By course", "",
              "| Course | STATIC_VERIFIED_SOURCE | DYNAMIC_SOURCE_REQUIRED | UNRESOLVED | NOT_ASSESSED |",
              "|---|---:|---:|---:|---:|"]
    for course, rows in by_course.items():
        c = Counter(r["sourceClass"] for r in rows)
        lines.append("| %s | %d | %d | %d | %d |" % (
            course, c["STATIC_VERIFIED_SOURCE"], c["DYNAMIC_SOURCE_REQUIRED"],
            c["UNRESOLVED"], c["NOT_ASSESSED_BY_SOURCE_REGISTRY"]))

    lines += ["", "## Lessons this lane resolved or holds", ""]
    lines += ["| Lesson | Class | State | Admissible | Anchors / blocker |", "|---|---|---|---|---|"]
    for row in p["lessons"]:
        if row.get("resolvedBy") != "social-studies-dynamic":
            continue
        blocker = ", ".join(row["anchorSourceKeys"]) or "; ".join(row["admissionBlockedBy"])
        lines.append("| `%s` | %s | %s | %s | %s |" % (
            row["lessonRef"], row["sourceClass"], row.get("dynamicState", "--"),
            "yes" if row["admissible"] else "no", blocker))

    lines += ["", "## Static unit checks", ""]
    for ref, found in p["unitFindings"].items():
        lines.append("- `%s` -- usable anchors: %s; typologically assigned: %s; problems: %s; "
                     "supporting-source problems: %s"
                     % (ref, ", ".join(found["usableAnchors"]) or "none",
                        ", ".join(found["typologicalAnchors"]) or "none",
                        "; ".join(found["problems"]) or "none",
                        "; ".join(found["supportingSourceProblems"]) or "none"))
    lines.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(lines))
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
