# -*- coding: utf-8 -*-
"""Unit blueprints for Manuel Academy High School ELA, English 9-12.

Each course is 10 units x 18 lessons = 180 instructional days (36 weeks x 5).
Standards codes resolve against ../standards/michigan-ela-9-12-standards.json.
"""

COURSES = [
  {
    "grade": 9, "slug": "english-9", "band": "9-10",
    "title": "English 9: Foundations of Analysis, Argument, and Academic Writing",
    "description": "A first high-school English course that converts Grade 8 literacy habits into high-school analytical practice: strong and thorough evidence, complex character and structural analysis, formal argument with fairly developed counterclaims, explanatory synthesis, and the first sustained research writing with formal citation.",
    "band_expectation": "Grade 9 works inside the grades 9-10 text complexity band with scaffolding as needed at the high end of the range (9-10.RL.10, 9-10.RI.10, first sentence).",
    "capstone": "A curated analytical portfolio and a formally defended selection, with a documented revision history and a private defense option.",
    "units": [
      ("Close Reading and Strong, Thorough Evidence",
       ["9-10.RL.1","9-10.RI.1","9-10.SL.1","9-10.W.9","9-10.L.6"],
       ["strong and thorough textual evidence","explicit statement versus supported inference","high-school annotation systems","discussion preparation and evidence logs","academic vocabulary acquisition","evidence sufficiency review"],
       "Build an evidence-and-inference casebook on an unfamiliar text and defend two contested readings in seminar."),
      ("Complex Characters and Narrative Structure",
       ["9-10.RL.3","9-10.RL.5","9-10.RL.2","9-10.W.3","9-10.L.3"],
       ["characters with multiple or conflicting motivations","character development across a whole text","parallel plots and ordered events","pacing, flashback, and manipulated time","theme emergence and refinement","narrative craft in original writing"],
       "Write an original narrative that uses parallel plotting or manipulated time, plus a craft commentary explaining the structural choice."),
      ("Word Choice, Tone, and Cumulative Meaning",
       ["9-10.RL.4","9-10.RI.4","9-10.L.4","9-10.L.5","9-10.SL.6"],
       ["cumulative impact of specific word choices","connotative and figurative meaning","technical meaning in informational text","euphemism, oxymoron, and figures of speech","nuance among words with similar denotations","register and command of formal English"],
       "Produce a diction-and-tone study comparing two passages, then rewrite one passage for a deliberately changed tone."),
      ("Central Ideas and Explanatory Synthesis",
       ["9-10.RI.2","9-10.RI.3","9-10.RI.5","9-10.W.2","9-10.W.4"],
       ["central idea emergence and refinement","the order in which points are made","how sentences and paragraphs refine claims","objective summary at high-school length","formatting and graphics that aid comprehension","precise language and domain-specific vocabulary"],
       "Write a formal explanatory article with headings and one graphic that genuinely clarifies a complex idea."),
      ("Argument, Counterclaim, and Valid Reasoning",
       ["9-10.W.1","9-10.RI.8","9-10.SL.3","9-10.L.1","9-10.W.5"],
       ["precise claims distinguished from opposing claims","counterclaim strengths and limitations","valid reasoning versus sufficient evidence","false statements and fallacious reasoning","cohesion across major sections","formal style and objective tone"],
       "Write a formal argument that develops a counterclaim fairly, then defend it in a structured evidence exchange."),
      ("Sustained Inquiry and Source Usefulness",
       ["9-10.W.7","9-10.W.8","9-10.RI.7","9-10.SL.2","9-10.L.3"],
       ["self-generated research questions","narrowing or broadening an inquiry","advanced search strategies","assessing a source's usefulness to the question","selective integration that maintains flow","standard citation format and plagiarism avoidance"],
       "Produce a source-usefulness report: for one research question, rank every source by how well it actually answers that question, with formal style-manual citations."),
      ("Rhetoric, Fallacy, and the Audited Argument",
       ["9-10.RI.6","9-10.RI.7","9-10.SL.2","9-10.SL.3","9-10.RL.7"],
       ["author point of view and purpose","rhetoric used to advance a purpose","valid reasoning versus relevant and sufficient evidence","false statements in a public argument","named fallacies and how to test for them","which details a second medium emphasizes or omits"],
       "Audit a public argument for false statements and named fallacies, then produce a corrected version that survives the same audit."),
      ("Named Grammatical Structures and Style-Manual Conformance",
       ["9-10.L.1","9-10.L.2","9-10.L.3","9-10.W.5","9-10.L.6"],
       ["parallel structure","participial, absolute, and other phrase types","independent, relative, and adverbial clauses","semicolons and conjunctive adverbs","colons introducing lists and quotations","editing to a style manual"],
       "Bring a full draft into conformance with a named style manual, documenting every phrase- and clause-level change by its grammatical category."),
      ("World Literature and Cultural Perspective",
       ["9-10.RL.6","9-10.RL.9","9-10.RL.2","9-10.W.9","9-10.SL.1"],
       ["point of view from outside the United States","wide reading of world literature","how an author transforms source material","theme across cultural contexts","comparative thesis construction","evidence-based collegial seminar"],
       "Write and present a comparative analysis of a world-literature text and a later work that transforms it."),
      ("Sustained Writing, Portfolio, and Presentation",
       ["9-10.W.10","9-10.W.6","9-10.RL.10","9-10.RI.10","9-10.SL.4","9-10.SL.5"],
       ["writing routinely over extended and short time frames","technology for producing and updating writing","independent reading in the 9-10 band","portfolio curation and selection rationale","clear, concise, logical presentation","strategic and accessible digital media"],
       "Publish a curated portfolio and formally defend one piece against questions about its evidence, revision history, and source use."),
    ],
  },
  {
    "grade": 10, "slug": "english-10", "band": "9-10",
    "title": "English 10: Independent Analysis, Rhetoric, and Sustained Research",
    "description": "A second high-school English course that moves the same 9-10 band from supported to independent performance: unaided evidence selection at the high end of the band, analysis of authorial structure, seminal U.S. documents and their rhetoric, sustained multi-source research, and publication-quality explanatory and argumentative writing.",
    "band_expectation": "Grade 10 works at the high end of the grades 9-10 text complexity band independently and proficiently (9-10.RL.10, 9-10.RI.10, second sentence).",
    "capstone": "A published portfolio and a defended self-directed analytical piece for a named audience.",
    "units": [
      ("Independent Evidence and Analytical Precision",
       ["9-10.RL.1","9-10.RI.1","9-10.RL.2","9-10.W.9","9-10.SL.1"],
       ["unaided selection of strong and thorough evidence","competing defensible readings","theme refinement across a whole text","evidence sufficiency without prompting","annotation without a provided template","seminar leadership and collegial rules"],
       "Lead an evidence seminar on a self-selected band-level text and submit an analytical evidence dossier."),
      ("Authorial Structure and Calculated Effect",
       ["9-10.RL.5","9-10.RL.3","9-10.RI.5","9-10.W.3","9-10.L.3"],
       ["structuring a text and ordering events","manipulating time for mystery, tension, or surprise","character interaction that advances plot or theme","claims refined by sections or chapters","narrative technique under a formal constraint","syntax and style choices for meaning"],
       "Compose a structurally experimental narrative and a rigorous analysis of the effects its structure produces."),
      ("Rhetoric and Seminal U.S. Documents",
       ["9-10.RI.9","9-10.RI.6","9-10.RI.8","9-10.SL.3","9-10.W.9"],
       ["seminal U.S. documents of historical and literary significance","how documents address related themes and concepts","author purpose advanced through rhetoric","validity of reasoning and sufficiency of evidence","fallacious reasoning in public texts","drawing written evidence from documentary sources"],
       "Analyze two seminal U.S. documents that address a shared theme and evaluate the rhetoric each uses."),
      ("Advanced Explanatory Writing",
       ["9-10.W.2","9-10.RI.2","9-10.RI.3","9-10.RI.4","9-10.W.4"],
       ["organizing complex ideas to make connections and distinctions","central idea shaped and refined by detail","how an author unfolds an analysis","figurative, connotative, and technical meaning","appropriate and varied transitions","development, organization, and style fit to audience"],
       "Produce a publication-quality explanatory piece that integrates multimedia and precise domain vocabulary."),
      ("Sustained Argument and Audience Analysis",
       ["9-10.W.1","9-10.RI.8","9-10.SL.4","9-10.W.5","9-10.L.1"],
       ["organization that clarifies claim and counterclaim relationships","anticipating audience knowledge level and concerns","strengths and limitations of both sides","concluding sections that follow from the argument","revision focused on what is most significant","clause and phrase variety in formal writing"],
       "Write a sustained argument for a defined external audience and deliver it as a logically ordered formal presentation."),
      ("Sustained Research and Source Synthesis",
       ["9-10.W.7","9-10.W.8","9-10.RI.7","9-10.SL.2","9-10.L.3"],
       ["designing a sustained inquiry","multiple authoritative print and digital sources","advanced searches used effectively","synthesizing multiple sources on one subject","integrating information to maintain flow of ideas","conforming to a style manual"],
       "Complete a sustained multi-source research paper with a defensible synthesis and complete citations."),
      ("Two Mediums, One Subject",
       ["9-10.RL.7","9-10.RI.7","9-10.SL.5","9-10.SL.2","9-10.RL.4"],
       ["a subject or key scene in two artistic mediums","what is emphasized or absent in each treatment","accounts of a subject told in different mediums","strategic use of digital media in presentation","credibility and accuracy across formats","word choice that evokes time, place, and tone"],
       "Build a comparative medium study and present the findings with strategic, accessible digital media."),
      ("Style, Conventions, and the Style Manual",
       ["9-10.L.1","9-10.L.2","9-10.L.3","9-10.L.4","9-10.W.5"],
       ["parallel structure sustained across long passages","phrase and clause variety for interest and meaning","semicolon and colon control","conforming work to a style manual","word-change patterns and parts of speech","verifying a preliminary determination of meaning"],
       "Produce a style-manual-conformant edited manuscript with a documented editorial rationale for each change."),
      ("Source Transformation and Literary Lineage",
       ["9-10.RL.9","9-10.RL.6","9-10.RL.2","9-10.W.9","9-10.SL.1"],
       ["how an author draws on and transforms source material","point of view or cultural experience from outside the U.S.","theme development across adaptations","mapping a literary lineage","comparative claims grounded in evidence","propelling conversation toward larger ideas"],
       "Trace one story's transformation across sources and argue what each version's changes accomplish."),
      ("Independent Reading, Publication, and Defense",
       ["9-10.RL.10","9-10.RI.10","9-10.W.6","9-10.W.10","9-10.SL.4","9-10.SL.5"],
       ["independent proficiency at the high end of the band","routine writing over extended time frames","technology-supported publication and updating","a portfolio that argues for its own selections","presentation listeners can follow","accessible media with captions and transcripts"],
       "Publish a portfolio and defend a self-directed analytical piece to a named audience."),
    ],
  },
  {
    "grade": 11, "slug": "english-11", "band": "11-12",
    "title": "English 11: American Literature, Public Argument, and Complex Synthesis",
    "description": "A junior course that enters the 11-12 band: texts that leave matters uncertain, two or more interacting themes, foundational and nineteenth-century American literature, the reasoning of seminal U.S. texts including legal reasoning, synthesis across sources that disagree, and argument that establishes the significance of its own claims.",
    "band_expectation": "Grade 11 works inside the grades 11-CCR text complexity band with scaffolding as needed at the high end of the range (11-12.RL.10, 11-12.RI.10, first sentence).",
    "capstone": "A published argument portfolio and a defended sustained argument tested against substantive objections.",
    "units": [
      ("Uncertainty, Ambiguity, and Rigorous Evidence",
       ["11-12.RL.1","11-12.RI.1","11-12.RL.2","11-12.RI.2","11-12.W.9","11-12.SL.1"],
       ["determining where a text leaves matters uncertain","two or more themes interacting and building","evidence that supports a complex account","interpretive restraint under ambiguity","civil, democratic discussion practice","preparation and research before seminar"],
       "Produce an interpretive brief that argues from a text's deliberate uncertainties rather than around them."),
      ("American Foundations: Colonial Through Early Republic",
       ["11-12.RL.9","11-12.RI.9","11-12.RI.6","11-12.W.9","11-12.SL.1"],
       ["eighteenth-century foundational works of American literature","The Declaration of Independence and the Preamble","the Bill of Rights and period documents","themes, purposes, and rhetorical features","two texts from one period on a shared topic","synthesizing claims made on all sides"],
       "Analyze how two foundational U.S. texts from one period treat a shared theme, purpose, and rhetorical problem."),
      ("Legal Reasoning and Public Advocacy",
       ["11-12.RI.8","11-12.RI.5","11-12.RI.4","11-12.RI.3","11-12.SL.3","11-12.W.1"],
       ["application of constitutional principles","majority opinions and dissents","premises and purposes in works of public advocacy","how an author refines a key term over a text","whether a structure makes points convincing","a speaker's stance, premises, and links among ideas"],
       "Evaluate the reasoning of a seminal U.S. text and write a formal assessment of how its argument is built."),
      ("Author's Craft: Developing and Relating Elements",
       ["11-12.RL.3","11-12.RL.5","11-12.RL.4","11-12.W.3","11-12.L.3"],
       ["where a story is set and how action is ordered","how characters are introduced and developed","structural choice and aesthetic impact","language that is fresh, engaging, or beautiful","building toward a particular tone and outcome","varying syntax for effect"],
       "Write a narrative built on one deliberate structural choice and analyze the aesthetic impact it produces."),
      ("Nineteenth-Century American Literature and Dissent",
       ["11-12.RL.9","11-12.RL.2","11-12.RI.9","11-12.RL.6","11-12.W.9"],
       ["nineteenth-century foundational works","themes that interact to produce a complex account","Lincoln's Second Inaugural and period documents","satire, sarcasm, irony, and understatement","literary dissent and national argument","comparative analysis across a period"],
       "Argue how a nineteenth-century literary text and a public document engage the same national question."),
      ("Complex Synthesis and Multi-Source Research",
       ["11-12.W.7","11-12.W.8","11-12.RI.7","11-12.W.2","11-12.W.4","11-12.SL.2","11-12.L.3"],
       ["sustained research from a self-generated question","strengths and limitations of each source","avoiding overreliance on any one source","integrating multiple formats to solve a problem","noting discrepancies among the data","conforming to a discipline's style manual"],
       "Complete a synthesis research paper that resolves, or explicitly bounds, discrepancies among conflicting sources."),
      ("Rhetorical Power and Effective Style",
       ["11-12.RI.6","11-12.RI.5","11-12.SL.3","11-12.SL.4","11-12.SL.5","11-12.SL.6","11-12.RL.7"],
       ["rhetoric that is particularly effective","how style and content create power or persuasiveness","evaluating the effectiveness of a structure","assessing stance, word choice, and tone","multiple interpretations of a drama or poem","conveying a clear and distinct perspective"],
       "Analyze a rhetorically powerful text and deliver an evidence-based evaluation that states a clear stance."),
      ("Contested Usage and the Sentence",
       ["11-12.L.1","11-12.L.2","11-12.L.3","11-12.L.4","11-12.L.5","11-12.L.6"],
       ["usage as convention that changes and is contested","resolving contested usage with cited references","hyphenation conventions","syntax varied for effect in complex texts","word-change patterns and etymology","hyperbole, paradox, and nuance"],
       "Produce a usage-and-syntax casebook that resolves contested questions using cited reference works."),
      ("Early Twentieth-Century Works and Interpretation",
       ["11-12.RL.9","11-12.RL.7","11-12.RL.6","11-12.RL.4","11-12.SL.1"],
       ["early-twentieth-century foundational works","multiple interpretations of one dramatic work","what is directly stated versus what is meant","words with multiple meanings in literary language","at least one Shakespeare play and one American dramatist","resolving contradictions in discussion"],
       "Compare interpretations of one dramatic work and argue which reading the text itself best supports."),
      ("Complex Argument Portfolio and Defense",
       ["11-12.W.1","11-12.W.5","11-12.W.6","11-12.W.10","11-12.RL.10","11-12.RI.10","11-12.SL.4"],
       ["precise, knowledgeable claims and their significance","logically sequencing claims and counterclaims","audience values and possible biases","publishing in response to ongoing feedback","routine writing over extended time frames","addressing alternative or opposing perspectives"],
       "Publish an argument portfolio and defend one sustained argument against substantive, prepared objections."),
    ],
  },
  {
    "grade": 12, "slug": "english-12", "band": "11-12",
    "title": "English 12: Postsecondary Reading, Research, and Rhetoric",
    "description": "A senior course built around independent scholarly work rather than guided practice. Students design their own research questions, evaluate sources by warranted credibility, adjudicate genuine disagreements, write to discipline conventions, and defend an independent research project. The course targets the transition to postsecondary reading and writing loads.",
    "band_expectation": "Grade 12 works at the high end of the grades 11-CCR text complexity band independently and proficiently (11-12.RL.10, 11-12.RI.10, second sentence).",
    "capstone": "An independent senior research project, publicly or privately defended, with a complete auditable source trail.",
    "units": [
      ("Independent Scholarly Reading",
       ["11-12.RL.10","11-12.RI.10","11-12.RL.1","11-12.RI.1","11-12.L.4"],
       ["independence at the high end of the 11-CCR band","protocols for dense and unfamiliar text","evidence where a text leaves matters uncertain","academic vocabulary met without instruction","annotation designed for scholarly reuse","self-monitoring and repairing comprehension"],
       "Complete an independent close-reading dossier on a demanding text using a protocol the student designs."),
      ("The Research Question and the Source Landscape",
       ["11-12.W.7","11-12.W.8","11-12.RI.7","11-12.SL.2","11-12.RI.3"],
       ["framing a genuinely researchable question","narrowing or broadening a sustained inquiry","mapping an authoritative source landscape","strengths and limitations for task and purpose","how ideas and events interact across a text","noting discrepancies before drafting"],
       "Design a researchable question and produce an annotated source landscape with an explicit scope rationale."),
      ("Evaluating Evidence, Method, and Credibility",
       ["11-12.RI.8","11-12.RI.5","11-12.RI.4","11-12.SL.3","11-12.W.8","11-12.RI.6"],
       ["reasoning in seminal and specialized texts","whether a structure makes points clear and convincing","stance, premises, and links among ideas","source limitations relative to the question","avoiding overreliance on any one source","expertise, interest, and warranted credibility"],
       "Produce a source-evaluation report that ranks contested sources by warranted credibility and says why."),
      ("Disciplinary Writing and the Style Manual",
       ["11-12.W.2","11-12.L.3","11-12.W.4","11-12.L.2","11-12.L.1"],
       ["organizing so each element builds a unified whole","conventions of the discipline being written in","hyphenation, mechanics, and correct spelling","resolving complex or contested usage","varying syntax for effect with cited guidance","metaphor, simile, and analogy to manage complexity"],
       "Write a discipline-conformant explanatory paper and document every style-manual decision it required."),
      ("Sustained Academic Argument",
       ["11-12.W.1","11-12.RI.8","11-12.W.5","11-12.SL.4","11-12.L.3"],
       ["establishing the significance of a claim","logically sequencing claims, counterclaims, and evidence","audience knowledge, values, and possible biases","supplying the most relevant evidence for each side","varied syntax that creates cohesion","addressing alternative or opposing perspectives"],
       "Write a sustained academic argument that establishes its own significance and answers the strongest objection to it."),
      ("Rhetoric, Power, and Public Language",
       ["11-12.RI.6","11-12.RI.9","11-12.SL.3","11-12.RL.6","11-12.SL.4"],
       ["rhetoric in texts where it is particularly effective","style and content contributing to power or beauty","rhetorical features of foundational U.S. documents","satire, irony, and understatement in public language","assessing points of emphasis and tone","conveying a clear and distinct perspective"],
       "Deliver a rhetorical analysis of a public text and defend a specific claim about how its language does its work."),
      ("Literary Interpretation at Scale",
       ["11-12.RL.2","11-12.RL.3","11-12.RL.4","11-12.RL.5","11-12.RL.7","11-12.L.5","11-12.W.9"],
       ["themes that interact to produce a complex account","the author's development and relation of elements","structure, overall meaning, and aesthetic impact","multiple interpretations of one work","Shakespeare and an American dramatist","drawing evidence for a scholarly literary claim"],
       "Produce a scholarly literary analysis that defends one interpretation against credible competing readings."),
      ("Synthesis Across Contradictory Sources",
       ["11-12.W.7","11-12.RI.7","11-12.RI.2","11-12.SL.2","11-12.SL.1","11-12.W.8","11-12.RI.3"],
       ["synthesis when authoritative sources disagree","discrepancies among data and accounts","integrating diverse formats to make a decision","selective integration that maintains flow","stating the limits of a synthesis","how specific ideas interact and develop"],
       "Write a synthesis that adjudicates a genuine scholarly or civic disagreement and states the limits of its conclusion."),
      ("Professional and Civic Communication",
       ["11-12.SL.4","11-12.SL.5","11-12.SL.6","11-12.W.6","11-12.W.2"],
       ["a range of formal and informal tasks","addressing alternative or opposing perspectives","strategic, accessible digital media","command of formal English when appropriate","publishing in response to ongoing feedback","explanation matched to audience knowledge"],
       "Produce a professional communication set and present it with accessible media and a private presentation option."),
      ("Senior Capstone: Independent Research and Defense",
       ["11-12.W.7","11-12.W.8","11-12.W.10","11-12.W.1","11-12.RL.10","11-12.RI.10","11-12.SL.4","11-12.L.6"],
       ["independent sustained research start to finish","an auditable source trail others can re-walk","routine writing over extended time frames","defending reasoning against prepared objections","publication ethics and attribution","postsecondary reading and writing transition"],
       "Complete and defend an independent senior research project supported by a full auditable source trail."),
    ],
  },
]


# ---------------------------------------------------------------------------
# Unit -> assigned texts. Without this the courses cannot be taught: a family
# opening day 1 must be told what to read. Gated (rights_required) works are
# deliberately never assigned; their public-domain substitutes are.
# ---------------------------------------------------------------------------

UNIT_TEXTS = {
  "english-9": {
    1: ["ma-hs-ela-t-901", "ma-hs-ela-t-905"],
    2: ["ma-hs-ela-t-902", "ma-hs-ela-t-907"],
    3: ["ma-hs-ela-t-908", "ma-hs-ela-t-911"],
    4: ["ma-hs-ela-t-904", "ma-hs-ela-t-910"],
    5: ["ma-hs-ela-t-903", "ma-hs-ela-t-910"],
    6: ["ma-hs-ela-t-903", "ma-hs-ela-t-904"],
    7: ["ma-hs-ela-t-906", "ma-hs-ela-t-911"],
    8: ["ma-hs-ela-t-901", "ma-hs-ela-t-904"],
    9: ["ma-hs-ela-t-909", "ma-hs-ela-t-906"],
    10: ["ma-hs-ela-t-905", "ma-hs-ela-t-910"],
  },
  "english-10": {
    1: ["ma-hs-ela-t-1001", "ma-hs-ela-t-1008"],
    2: ["ma-hs-ela-t-1001", "ma-hs-ela-t-1008"],
    3: ["ma-hs-ela-t-1005", "ma-hs-ela-t-1006", "ma-hs-ela-t-1007"],
    4: ["ma-hs-ela-t-1004", "ma-hs-ela-t-1002"],
    5: ["ma-hs-ela-t-1003", "ma-hs-ela-t-1006"],
    6: ["ma-hs-ela-t-1002", "ma-hs-ela-t-1004"],
    7: ["ma-hs-ela-t-1010", "ma-hs-ela-t-1012", "ma-hs-ela-t-1011"],
    8: ["ma-hs-ela-t-1003", "ma-hs-ela-t-1004"],
    9: ["ma-hs-ela-t-1012", "ma-hs-ela-t-1007"],
    10: ["ma-hs-ela-t-1008", "ma-hs-ela-t-1005"],
  },
  "english-11": {
    1: ["ma-hs-ela-t-1101", "ma-hs-ela-t-1108"],
    2: ["ma-hs-ela-t-1113", "ma-hs-ela-t-1106", "ma-hs-ela-t-1104"],
    3: ["ma-hs-ela-t-1102", "ma-hs-ela-t-1104"],
    4: ["ma-hs-ela-t-1110", "ma-hs-ela-t-1109"],
    5: ["ma-hs-ela-t-1105", "ma-hs-ela-t-1107", "ma-hs-ela-t-1108"],
    6: ["ma-hs-ela-t-1103", "ma-hs-ela-t-1104"],
    7: ["ma-hs-ela-t-1105", "ma-hs-ela-t-1110"],
    8: ["ma-hs-ela-t-1109", "ma-hs-ela-t-1102"],
    9: ["ma-hs-ela-t-1111", "ma-hs-ela-t-1112", "ma-hs-ela-t-1110"],
    10: ["ma-hs-ela-t-1103", "ma-hs-ela-t-1111"],
  },
  "english-12": {
    1: ["ma-hs-ela-t-1211", "ma-hs-ela-t-1210"],
    2: ["ma-hs-ela-t-1201", "ma-hs-ela-t-1202"],
    3: ["ma-hs-ela-t-1202", "ma-hs-ela-t-1205"],
    4: ["ma-hs-ela-t-1204", "ma-hs-ela-t-1210"],
    5: ["ma-hs-ela-t-1203", "ma-hs-ela-t-1207"],
    6: ["ma-hs-ela-t-1212", "ma-hs-ela-t-1206", "ma-hs-ela-t-1205"],
    7: ["ma-hs-ela-t-1208", "ma-hs-ela-t-1209"],
    8: ["ma-hs-ela-t-1202", "ma-hs-ela-t-1203"],
    9: ["ma-hs-ela-t-1201", "ma-hs-ela-t-1204"],
    10: ["ma-hs-ela-t-1201", "ma-hs-ela-t-1203"],
  },
}

# Standards that name a required *kind* of text. The validator asserts that the
# unit carrying the code actually assigns a text meeting it, so the alignment is
# instantiated rather than merely claimed.
TEXT_ANCHORS = [
  ("english-10", 3, "9-10.RI.9", ["ma-hs-ela-t-1005", "ma-hs-ela-t-1007"],
   "seminal U.S. documents of historical and literary significance"),
  ("english-9", 9, "9-10.RL.6", ["ma-hs-ela-t-909"],
   "a work of literature from outside the United States"),
  ("english-10", 7, "9-10.RL.7", ["ma-hs-ela-t-1010", "ma-hs-ela-t-1012"],
   "one subject represented in two different artistic mediums"),
  ("english-11", 2, "11-12.RI.9", ["ma-hs-ela-t-1113", "ma-hs-ela-t-1106"],
   "foundational U.S. documents of historical and literary significance"),
  ("english-11", 9, "11-12.RL.7", ["ma-hs-ela-t-1110", "ma-hs-ela-t-1112"],
   "at least one play by Shakespeare and one play by an American dramatist"),
  ("english-12", 7, "11-12.RL.7", ["ma-hs-ela-t-1208", "ma-hs-ela-t-1209"],
   "at least one play by Shakespeare and one play by an American dramatist"),
  ("english-11", 5, "11-12.RL.9", ["ma-hs-ela-t-1107", "ma-hs-ela-t-1108"],
   "nineteenth-century foundational works of American literature"),
]
