"""Build package-alone learner inputs for every Science lesson.

The pinned curriculum sources establish sequence, objectives, safety, and H4
authority.  They do not, however, always ship the case, evidence, model, or
dataset a learner needs to do the stated work.  This module adds that production
layer without changing any source record or source lineage.

Reference-evidence lessons use the accepted topic relationships as readable
instructional information, then give the learner a specific claim and a closed
set of evidence to evaluate.  Investigation lessons additionally provide an
executable document investigation (K-8) or retain the H4 physical procedure and
ship a deterministic, equal-credit model dataset (High School).

Model datasets are labelled as model output, state their rule or equation, and
never pretend to be observed or published measurements.  They use systems and
conditions different from the physical route, so they do not disclose the
physical investigation's result before evidence collection.
"""

from __future__ import annotations

from typing import Any


CONTENT_VERSION = "2.0.0"


def _dataset(
    title: str,
    columns: list[str],
    rows: list[list[Any]],
    model: str,
    task: str,
) -> dict:
    return {
        "kind": "MODEL_OUTPUT",
        "title": title,
        "columns": columns,
        "rows": rows,
        "provenance": (
            "Manuel Academy deterministic instructional simulation. Values are model output, "
            "not observations, measurements, or a prediction for the hands-on route."
        ),
        "model_rule": model,
        "task": task,
        "independent_from_physical_route": True,
    }


# One complete alternative input per distinct H4 investigation.  The values are
# intentionally compact enough to calculate by hand and are generated by the
# stated rule.  Nothing here changes or replaces the H4 primary procedure.
HS_ALTERNATIVE_DATA: dict[tuple[str, int], dict] = {
    ("ma-hs9-biology", 1): _dataset(
        "Modelled enzyme activity in four sealed samples",
        ["Sample", "Temperature (°C)", "pH", "Modelled product after 10 min (units)"],
        [["A", 10, 7, 12], ["B", 22, 7, 25], ["C", 35, 7, 38], ["D", 35, 4, 9]],
        "For pH 7, product units are a piecewise classroom model that rise from 12 at 10 °C to 38 at 35 °C; changing pH from 7 to 4 multiplies the 35 °C output by 9/38.",
        "Graph modelled product against temperature for A-C, compare C with D, and separate what this model shows from what an experiment would still have to test.",
    ),
    ("ma-hs9-biology", 2): _dataset(
        "DNA transcription and translation case",
        ["Item", "Supplied model input"],
        [["DNA template", "TAC GGA CTT ACT"], ["mRNA pairing", "A-U, T-A, C-G, G-C"], ["AUG", "Met/start"], ["CCU", "Pro"], ["GAA", "Glu"], ["UGA", "Stop"]],
        "Apply the supplied complementary-pairing rules, read mRNA from left to right in triplets, and use only the four-entry codon key shown.",
        "Transcribe the template, translate it with the supplied key, draw the resulting amino-acid chain, and explain how one changed DNA base could change or preserve the chain.",
    ),
    ("ma-hs9-biology", 3): _dataset(
        "Modelled cell-cycle field counts and cube geometry",
        ["Field or cube", "Input 1", "Input 2", "Input 3"],
        [["Microscope field 1", "Interphase 42", "Mitosis 8", "Total 50"], ["Field 2", "Interphase 45", "Mitosis 5", "Total 50"], ["Field 3", "Interphase 40", "Mitosis 10", "Total 50"], ["Cube A", "side 1 cm", "surface area 6 cm²", "volume 1 cm³"], ["Cube B", "side 2 cm", "surface area 24 cm²", "volume 8 cm³"], ["Cube C", "side 3 cm", "surface area 54 cm²", "volume 27 cm³"]],
        "Field counts are fixed simulation inputs. Cube surface area is 6s² and volume is s³.",
        "Compute the mitotic fraction for each field and surface-area-to-volume ratio for each cube; use both patterns to evaluate limits on cell size and cell-cycle claims.",
    ),
    ("ma-hs9-biology", 4): _dataset(
        "Non-human thermoregulation feedback model",
        ["Minute", "Air temperature (°C)", "Body-model temperature (°C)", "Cooling response (0-3)"],
        [[0, 22, 38.0, 0], [5, 30, 38.3, 1], [10, 34, 38.6, 2], [15, 34, 38.5, 2], [20, 30, 38.2, 1], [25, 22, 38.0, 0]],
        "A fictional ectotherm-control simulation increases a cooling-response index when model temperature exceeds 38.2 °C; the response removes 0.15 °C per index per step.",
        "Plot model temperature and response through time, identify the stimulus-response loop, and state why the table cannot be used as a learner health measurement.",
    ),
    ("ma-hs9-biology", 5): _dataset(
        "Photosynthesis-rate model across light levels",
        ["Light (arbitrary units)", "CO₂ level (relative)", "Modelled O₂ rate (units/min)"],
        [[0, 1.0, 0.0], [20, 1.0, 3.3], [50, 1.0, 6.7], [100, 1.0, 10.0], [200, 1.0, 13.3], [200, 0.5, 8.0]],
        "At relative CO₂ 1.0, rate = 20L/(100+L). The final row applies a 0.60 CO₂ limitation factor.",
        "Graph rate against light, calculate the gain from each light increase, and use the last two rows to distinguish light limitation from carbon-dioxide limitation.",
    ),
    ("ma-hs9-biology", 6): _dataset(
        "Ecosystem energy-transfer model",
        ["Trophic level", "Modelled available energy (kJ)", "Biomass carbon (kg)"],
        [["Producers", 50000, 1200], ["Primary consumers", 6000, 180], ["Secondary consumers", 720, 28], ["Tertiary consumers", 86.4, 4.5]],
        "Each trophic level receives 12% of the previous level's modelled energy. Biomass carbon is a separate supplied model state, not calculated from energy.",
        "Calculate each transfer efficiency, draw a food-energy pyramid, and explain where the untransferred energy goes without claiming that energy is destroyed.",
    ),
    ("ma-hs9-biology", 7): _dataset(
        "Population-growth comparison",
        ["Time step", "Population X", "Population Y"],
        [[0, 20, 20], [1, 30, 29], [2, 45, 40], [3, 68, 52], [4, 101, 61], [5, 152, 67], [6, 228, 70]],
        "X is rounded 1.5-fold growth. Y follows rounded logistic growth N(next)=N+0.5N(1-N/75).",
        "Graph both populations, identify which rule is exponential and which is density-limited, and use differences between successive values as evidence.",
    ),
    ("ma-hs9-biology", 8): _dataset(
        "Fictional inheritance and meiosis model",
        ["Offspring", "Parent 1 allele", "Parent 2 allele", "Genotype"],
        [[1, "A", "A", "AA"], [2, "A", "a", "Aa"], [3, "a", "A", "Aa"], [4, "a", "a", "aa"], [5, "A", "a", "Aa"], [6, "a", "A", "Aa"], [7, "A", "A", "AA"], [8, "a", "a", "aa"]],
        "Each heterozygous fictional parent contributes A or a according to a fixed simulated coin sequence. A is dominant in this model only.",
        "Tally genotype and phenotype frequencies, compare them with a 1:2:1 expectation without treating eight trials as proof, and explain how meiosis creates variation.",
    ),
    ("ma-hs9-biology", 9): _dataset(
        "Selection model with two fictional traits",
        ["Generation", "Trait L count", "Trait D count", "Environment state"],
        [[0, 50, 50, "mixed"], [1, 56, 44, "light"], [2, 64, 36, "light"], [3, 60, 40, "mixed"], [4, 51, 49, "dark"], [5, 42, 58, "dark"]],
        "Counts come from a deterministic survival-reproduction simulation in which the matching trait has survival weight 1.2 and the other 0.8; each generation is rescaled to 100.",
        "Graph trait frequency, connect changes to the environment state, and explain why the model supports selection on populations rather than individuals changing because they need to.",
    ),
    ("ma-hs10-chemistry", 1): _dataset(
        "Mass-volume density model for three unknown solids",
        ["Solid", "Trial", "Mass (g)", "Volume (mL)"],
        [["A", 1, 27.1, 10.0], ["A", 2, 40.4, 15.0], ["A", 3, 54.2, 20.0], ["B", 1, 18.0, 10.0], ["B", 2, 27.3, 15.0], ["B", 3, 35.8, 20.0]],
        "The simulator uses density 2.70 g/mL for A and 1.80 g/mL for B, then adds fixed instrument deviations of at most 0.3 g.",
        "Calculate every density, mean density, range, and percent spread; decide which measurements are consistent with one material and justify the precision you report.",
    ),
    ("ma-hs10-chemistry", 2): _dataset(
        "Atomic-property and emission-line model",
        ["Element model", "Atomic number", "Radius (pm)", "Ionization energy (kJ/mol)", "Emission lines (nm)"],
        [["P", 3, 152, 520, "671, 610"], ["Q", 4, 112, 900, "468, 527"], ["R", 5, 85, 801, "412, 448"], ["S", 11, 186, 496, "589, 590"]],
        "Values are a simplified instructional table patterned on periodic relationships; element letters are masked so identification must use the supplied evidence rather than recall.",
        "Graph radius and ionization energy against atomic number, describe the within-period pattern and the reset, then match an unknown spectrum containing 589 and 590 nm.",
    ),
    ("ma-hs10-chemistry", 3): _dataset(
        "Bonding-property comparison model",
        ["Material", "Water mixing", "Solid conductivity", "Solution conductivity", "Melting category"],
        [["M", "dissolves", "low", "high", "high"], ["N", "dissolves", "low", "low", "low"], ["O", "does not mix", "low", "not applicable", "low"], ["P", "does not dissolve", "high", "not applicable", "high"]],
        "The four masked materials instantiate idealized ionic, molecular-polar, molecular-nonpolar, and metallic property patterns.",
        "Classify each material's most likely bonding type, cite at least two independent properties for each classification, and identify one limitation of inferring structure from bulk properties.",
    ),
    ("ma-hs10-chemistry", 4): _dataset(
        "Open oxidation and indicator evidence model",
        ["Case", "Initial mass (g)", "Final mass (g)", "Gas observed", "Indicator before/after"],
        [["1", 5.00, 5.72, "none", "no change"], ["2", 20.00, 19.45, "yes", "blue to pink"], ["3", 12.00, 12.00, "none", "liquid to solid"], ["4", 10.00, 10.00, "yes", "no change"]],
        "Each row is a distinct closed or open classroom model case; mass, gas, indicator, and state evidence are independent inputs, not a universal reaction rule.",
        "For each case, decide whether the evidence supports chemical change, physical change, or is insufficient; explain why no single sign is conclusive by itself.",
    ),
    ("ma-hs10-chemistry", 5): _dataset(
        "Open- and closed-system mass accounting",
        ["System", "Reactants before (g)", "Container before (g)", "System after (g)", "Gas retained?"],
        [["Open A", 12.40, 8.00, 19.35, "no"], ["Open B", 12.40, 8.00, 19.29, "no"], ["Closed A", 12.40, 10.50, 22.88, "yes"], ["Closed B", 12.40, 10.50, 22.91, "yes"]],
        "The closed-system model conserves 22.90 g with ±0.02 g scale deviation; the open model releases simulated gas mass plus the same scale deviation.",
        "Compute each before-after difference, estimate gas mass for the open trials, and explain why system boundary—not disappearance of atoms—changes the measured total.",
    ),
    ("ma-hs10-chemistry", 6): _dataset(
        "Bond-energy account for reactions not used in the physical route",
        ["Process", "Bonds broken (kJ/mol)", "Bonds formed (kJ/mol)", "ΔH model = broken - formed"],
        [["R1", 920, 1080, "calculate"], ["R2", 1250, 1130, "calculate"], ["R3", 760, 760, "calculate"], ["R4", 1440, 1595, "calculate"]],
        "For this model only, ΔH = total energy assigned to broken bonds minus total energy assigned to formed bonds. These processes are not the household trials in the H4 route.",
        "Calculate each ΔH, classify the modelled energy transfer from the sign, and compare the model with its assumptions. Do not use these values to predict the household temperature trials.",
    ),
    ("ma-hs10-chemistry", 7): _dataset(
        "Reaction-rate collision model",
        ["Condition", "Temperature (°C)", "Relative concentration", "Surface factor", "Modelled completion time (s)"],
        [["A", 20, 1.0, 1, 120], ["B", 30, 1.0, 1, 60], ["C", 20, 0.5, 1, 240], ["D", 20, 1.0, 2, 60], ["E", 30, 0.5, 2, 60]],
        "Base time is 120 s; each +10 °C or doubling of surface factor halves time, while halving concentration doubles it.",
        "Compare matched pairs to isolate one variable, convert time to relative rate 1/time, and explain the patterns with collision frequency and effective collisions.",
    ),
    ("ma-hs10-chemistry", 8): _dataset(
        "Reversible-system equilibrium model",
        ["Step", "Condition change", "A particles", "B particles", "Total"],
        [[0, "initial", 70, 30, 100], [1, "none", 60, 40, 100], [2, "none", 55, 45, 100], [3, "add 20 A", 75, 45, 120], [4, "re-equilibrate", 66, 54, 120], [5, "re-equilibrate", 62, 58, 120]],
        "At each equilibrium step, 20% of A converts to B and 30% of B converts to A, rounded to whole particles; step 3 adds A before conversion resumes.",
        "Calculate forward and reverse changes at two steps, identify dynamic equilibrium, and explain the response to added A without claiming that either reaction stops.",
    ),
    ("ma-hs10-chemistry", 9): _dataset(
        "Half-life die-decay model",
        ["Generation", "Unchanged nuclei", "Changed nuclei this generation"],
        [[0, 64, 0], [1, 33, 31], [2, 17, 16], [3, 9, 8], [4, 4, 5], [5, 2, 2], [6, 1, 1]],
        "A deterministic classroom decay model removes approximately half of the remaining counters per generation; deviations alternate around exact halves.",
        "Graph unchanged nuclei on linear and semilog axes, estimate half-life in generations, and explain why an individual nucleus is not assigned a known decay time.",
    ),
    ("ma-hs11-physics", 1): _dataset(
        "Frame-numbered motion model",
        ["Time (s)", "Position in ground frame (m)", "Position in cart frame (m)"],
        [[0, 0.0, 0.0], [1, 1.2, 0.7], [2, 2.8, 1.8], [3, 4.8, 3.3], [4, 7.2, 5.2], [5, 10.0, 7.5]],
        "Ground-frame position is 0.2t²+1.0t; the cart frame moves at 0.5 m/s, so x(cart)=x(ground)-0.5t.",
        "Compute interval velocities and changes in velocity in both frames, state the sign convention, and explain which quantities change with reference frame.",
    ),
    ("ma-hs11-physics", 2): _dataset(
        "Force-mass-acceleration model",
        ["Trial", "Net force (N)", "Mass (kg)", "Acceleration (m/s²)"],
        [[1, 2, 1, 2.0], [2, 4, 1, 4.0], [3, 6, 1, 6.0], [4, 4, 2, 2.0], [5, 4, 4, 1.0], [6, 8, 4, 2.0]],
        "Acceleration is generated exactly by a=Fnet/m for an idealized frictionless model.",
        "Graph acceleration against force for constant mass and against inverse mass for constant force; draw a free-body diagram for each comparison and identify the source of every force.",
    ),
    ("ma-hs11-physics", 3): _dataset(
        "One-dimensional collision model",
        ["Trial", "m1 (kg)", "v1 before (m/s)", "m2 (kg)", "v2 before (m/s)", "shared v after (m/s)"],
        [[1, 1.0, 3.0, 1.0, 0.0, 1.5], [2, 2.0, 3.0, 1.0, 0.0, 2.0], [3, 1.0, 2.0, 1.0, -1.0, 0.5], [4, 0.5, 4.0, 1.5, 0.0, 1.0]],
        "For a perfectly inelastic one-dimensional model, shared velocity is (m1v1+m2v2)/(m1+m2).",
        "Verify momentum before and after, calculate kinetic energy before and after, and distinguish conservation of momentum from conservation of kinetic energy.",
    ),
    ("ma-hs11-physics", 4): _dataset(
        "Work-energy spring-launch model",
        ["Compression (m)", "Spring constant (N/m)", "Mass (kg)", "Modelled speed (m/s)"],
        [[0.05, 40, 0.20, 0.71], [0.10, 40, 0.20, 1.41], [0.15, 40, 0.20, 2.12], [0.10, 40, 0.40, 1.00], [0.10, 80, 0.20, 2.00]],
        "Ideal model: 0.5kx²=0.5mv², with no friction; speeds are rounded to two decimals.",
        "Check each speed from the energy equation, graph speed against compression, and explain how the no-friction assumption limits transfer to a real launcher.",
    ),
    ("ma-hs11-physics", 5): _dataset(
        "Low-voltage circuit model",
        ["Circuit", "Voltage (V)", "Resistance (Ω)", "Current (A)", "Power (W)"],
        [["A", 1.5, 10, 0.15, 0.225], ["B", 3.0, 10, 0.30, 0.900], ["C", 3.0, 20, 0.15, 0.450], ["D", 4.5, 15, 0.30, 1.350]],
        "Ideal resistor model: I=V/R and P=VI. Values are model output for a battery circuit, never mains electricity.",
        "Verify current and power, compare matched circuits, and draw energy-transfer and charge-flow representations without claiming charge is used up.",
    ),
    ("ma-hs11-physics", 6): _dataset(
        "Wave relationship model",
        ["Wave", "Frequency (Hz)", "Wavelength (m)", "Amplitude (cm)", "Speed (m/s)"],
        [["A", 2, 3.0, 1, 6.0], ["B", 3, 2.0, 1, 6.0], ["C", 4, 1.5, 2, 6.0], ["D", 6, 1.0, 3, 6.0], ["E", 3, 4.0, 1, 12.0]],
        "Wave speed is v=fλ. A-D share one medium; E represents a second medium. Relative energy is proportional to amplitude squared.",
        "Verify speeds, compare wavelength and frequency within one medium, calculate relative energy, and explain which variable changes when the medium changes.",
    ),
    ("ma-hs11-physics", 7): _dataset(
        "Thermal energy-transfer model",
        ["Object", "Mass (kg)", "Specific heat (J/kg°C)", "Initial °C", "Final °C"],
        [["Water A", 0.20, 4180, 20, 25], ["Water B", 0.40, 4180, 20, 22.5], ["Metal A", 0.20, 900, 20, 43.2], ["Metal B", 0.40, 900, 20, 31.6]],
        "Each object receives 4180 J in an isolated model; ΔT=Q/(mc), rounded to one decimal where needed.",
        "Recalculate every final temperature, compare effects of mass and specific heat, and identify why a real transfer would not be perfectly isolated.",
    ),
    ("ma-hs11-physics", 8): _dataset(
        "Thin-lens ray model",
        ["Case", "Focal length (cm)", "Object distance (cm)", "Image distance (cm)", "Magnification"],
        [["A", 10, 30, 15.0, -0.50], ["B", 10, 20, 20.0, -1.00], ["C", 10, 15, 30.0, -2.00], ["D", 10, 8, -40.0, 5.00]],
        "Ideal thin lens: 1/f=1/do+1/di and magnification=-di/do. Negative image distance denotes a virtual image.",
        "Verify image distance and magnification, draw principal rays for two cases, and distinguish real from virtual images using both calculation and diagram.",
    ),
    ("ma-hs11-physics", 9): _dataset(
        "Energy-conversion device model",
        ["Design", "Input energy (J)", "Useful output (J)", "Time (s)", "Material score /5"],
        [["A", 1000, 420, 20, 5], ["B", 1000, 510, 30, 4], ["C", 1200, 660, 25, 3], ["D", 800, 400, 18, 2]],
        "Efficiency=useful output/input; useful power=useful output/time. Material score is an independent design constraint where 5 is best.",
        "Calculate efficiency and power, choose a design under two stated criteria, and defend the trade-off without claiming any design creates energy.",
    ),
    ("ma-hs12-earth-space-environmental", 1): _dataset(
        "Earth-system stock-and-flow model",
        ["Year", "Atmosphere carbon (units)", "Ocean uptake", "Land uptake", "Human input"],
        [[0, 800, 2, 3, 9], [1, 804, 2, 3, 9], [2, 808, 2, 3, 10], [3, 813, 3, 3, 10], [4, 817, 3, 4, 10]],
        "Atmosphere(next)=atmosphere+human input-ocean uptake-land uptake. Units are model units, not observed gigatonnes.",
        "Verify each stock change, draw the system boundary and flows, and identify how moving one flow outside the boundary changes the accounting but not the modeled Earth system.",
    ),
    ("ma-hs12-earth-space-environmental", 2): _dataset(
        "Main-sequence star model",
        ["Star", "Mass (Sun=1)", "Luminosity (Sun=1)", "Core temperature index", "Lifetime index"],
        [["A", 0.5, 0.06, 0.7, 8.3], ["B", 1.0, 1.00, 1.0, 1.0], ["C", 2.0, 11.3, 1.4, 0.18], ["D", 4.0, 128.0, 2.0, 0.03]],
        "Instructional scaling: luminosity=M^3.5 and lifetime=M/luminosity; core-temperature index=square root of mass.",
        "Verify the model outputs, graph luminosity against mass on log axes, and explain why greater fuel supply does not give a massive star a longer main-sequence lifetime in this model.",
    ),
    ("ma-hs12-earth-space-environmental", 3): _dataset(
        "Seismic arrival-time location model",
        ["Station", "P arrival (s)", "S arrival (s)", "S-P (s)", "Model distance (km)"],
        [["North", 12.0, 21.0, 9.0, 72], ["East", 15.0, 27.0, 12.0, 96], ["South", 10.0, 16.0, 6.0, 48], ["West", 13.0, 23.5, 10.5, 84]],
        "For this simplified model, epicentral distance=8 km times the S-P interval.",
        "Calculate every distance, triangulate the epicenter on the supplied coordinate grid you draw, and state what the simplified constant-speed model omits.",
    ),
    ("ma-hs12-earth-space-environmental", 4): _dataset(
        "Weathering-rate model",
        ["Site", "Rainfall index", "Temperature index", "Rock resistance", "Model weathering score"],
        [["A", 2, 2, 1, 4.0], ["B", 4, 2, 1, 8.0], ["C", 4, 3, 2, 6.0], ["D", 1, 4, 1, 4.0], ["E", 3, 3, 3, 3.0]],
        "Weathering score=(rainfall index × temperature index)/rock resistance.",
        "Verify scores, isolate each variable with matched comparisons, and explain why this index is a model rather than a direct rate in physical units.",
    ),
    ("ma-hs12-earth-space-environmental", 5): _dataset(
        "Groundwater infiltration model",
        ["Column", "Grain model", "Water added (mL)", "Water through in 5 min (mL)", "Turbidity index"],
        [["A", "coarse", 100, 82, 1], ["B", "medium", 100, 61, 2], ["C", "fine", 100, 28, 5], ["D", "mixed", 100, 48, 3]],
        "A deterministic pore-flow simulation assigns larger connected pore spaces more five-minute flow; turbidity is a separate 1-5 model index.",
        "Calculate retained water, rank permeability, and use both flow and turbidity to evaluate a claim about groundwater filtration without assuming faster flow always means cleaner water.",
    ),
    ("ma-hs12-earth-space-environmental", 6): _dataset(
        "Watershed runoff model",
        ["Watershed", "Rain (mm)", "Impervious cover (%)", "Peak runoff (model units)", "Sediment (model units)"],
        [["A", 20, 10, 7, 12], ["B", 20, 40, 13, 18], ["C", 20, 70, 19, 24], ["D", 40, 10, 14, 25], ["E", 40, 70, 38, 49]],
        "Peak runoff=rainfall×(0.25+0.01×impervious percentage), rounded; sediment is a fixed coupled-model output.",
        "Graph peak runoff against impervious cover for equal rain, compare rainfall effects, and propose one watershed intervention with a measurable criterion.",
    ),
    ("ma-hs12-earth-space-environmental", 7): _dataset(
        "Planetary energy-budget model",
        ["Scenario", "Incoming (W/m²)", "Reflected", "Absorbed", "Outgoing", "Net"],
        [["A", 340, 100, "calculate", 240, "calculate"], ["B", 340, 110, "calculate", 230, "calculate"], ["C", 340, 90, "calculate", 245, "calculate"], ["D", 350, 100, "calculate", 240, "calculate"]],
        "Absorbed=incoming-reflected; net=absorbed-outgoing. Positive net adds energy to the modeled system and negative net removes it.",
        "Complete the table, compare albedo and outgoing-energy changes, and state why the sign of net energy is not itself a forecast of exact future temperature.",
    ),
    ("ma-hs12-earth-space-environmental", 8): _dataset(
        "Regional environmental decision case",
        ["Option", "Flood-risk reduction /5", "Habitat /5", "Cost /5 (5=lowest)", "Displacement risk /5 (5=lowest)"],
        [["Wetland restoration", 4, 5, 3, 5], ["Concrete barrier", 5, 1, 2, 2], ["Managed retreat", 5, 4, 1, 1], ["Drain expansion", 3, 2, 4, 4]],
        "Scores are a fictional county-scale decision model. No real address, family, or identifiable community is represented.",
        "Set and justify weights before calculating a score, test how one changed weight affects the recommendation, and address the strongest evidence against the chosen option.",
    ),
    ("ma-hs12-earth-space-environmental", 9): _dataset(
        "Resource-population simulation",
        ["Step", "Population", "Resource stock", "Renewal", "Use per person"],
        [[0, 100, 1000, 120, 1.0], [1, 110, 1020, 120, 1.0], [2, 121, 1030, 120, 1.0], [3, 133, 1029, 120, 1.0], [4, 146, 1016, 120, 1.0], [5, 161, 990, 120, 1.0]],
        "Population(next)=round(1.10×population); stock(next)=stock+renewal-population×use per person, using the current step population.",
        "Verify each transition, extend three steps, test one policy change, and defend a design while stating assumptions, uncertainty, and the result that would change the recommendation.",
    ),
}


PHASE_TASKS = {
    "Launch and diagnostic": "Write an initial explanation, then mark which evidence item would most strongly change it.",
    "Concept model A": "Build a labelled model that includes every accepted relationship in the science brief and test it against the case claim.",
    "Concept model B": "Build a second representation of the same evidence and identify one feature the first model hid.",
    "Guided practice A": "Use E1 with E2 first; then add E3 and revise any conclusion that no longer fits.",
    "Guided practice B": "Sort all evidence as supports, challenges, or does not decide, and justify every placement.",
    "Independent application A": "Evaluate the case claim independently using at least two evidence codes and one stated limitation.",
    "Investigation or close reading": "Carry out the document investigation in the stated order and record the evidence tally before writing a conclusion.",
    "Investigation": "Choose the H4 physical route or the supplied model-data route, complete that route, and answer from the evidence you actually collected or calculated.",
    "Reteach and varied practice": "Correct the candidate claim, explain the exact evidence that makes the correction necessary, and create one fresh example.",
    "Performance task build": "Use the supplied record to build a claim-evidence-reasoning product that another reader can check line by line.",
    "Synthesis and review": "Connect at least three evidence items, state the boundary of the conclusion, and answer the unit question.",
    "Unit assessment": "Without copying the brief, evaluate the candidate claim, interpret the evidence table, and apply the idea to a new example you create.",
    "Correction and reflection": "Locate one weakness in an earlier response, revise it with a named evidence code, and state what the revision fixes.",
}


def _reference_rows(authority: dict) -> list[dict[str, str]]:
    relationships = list(authority.get("relationships", []))
    facts = list(authority.get("fixed_facts", []))
    rows: list[dict[str, str]] = []
    source_items = facts + relationships
    for index, statement in enumerate(source_items[:4], start=1):
        # The adult content key remains a distinct, adult-facing authority.
        # Lowercasing the first alphabetic character turns the learner copy
        # into a readable brief fragment without reproducing the key verbatim.
        learner_statement = statement
        for position, character in enumerate(learner_statement):
            if character.isalpha():
                learner_statement = (
                    learner_statement[:position]
                    + character.lower()
                    + learner_statement[position + 1 :]
                )
                break
        rows.append(
            {
                "evidence_id": f"E{index}",
                "type": "established science reference",
                "information": f"Science brief: {learner_statement}",
            }
        )
    return rows


def _candidate_claim(authority: dict, focus: str) -> str:
    errors = authority.get("disqualifying_errors", [])
    if errors:
        claim = errors[0].rstrip(".")
        if claim.lower().startswith("claiming "):
            claim = claim[len("claiming ") :]
        for position, character in enumerate(claim):
            if character.isalpha():
                claim = claim[:position] + character.lower() + claim[position + 1 :]
                break
        return f"A case report presents this as acceptable science: “{claim}.”"
    return f"The evidence supplied here is enough to make an unlimited claim about {focus}."


def _document_investigation(lesson: dict, evidence_rows: list[dict[str, str]]) -> dict:
    return {
        "kind": "DOCUMENT_EVIDENCE_INVESTIGATION",
        "question": f"How well does the supplied evidence support the case claim about {lesson['focus']}?",
        "materials": [
            "this learner sheet with its complete evidence record",
            "course notebook or the blank recording table on this sheet",
            "pencil, keyboard, or another accessible response tool",
        ],
        "procedure": [
            "Read the case claim without deciding whether it is correct.",
            "Write a prediction: strongly supported, partly supported, or not supported.",
            "Read E1 alone and record what it supports and what it cannot decide.",
            "Repeat for each remaining evidence row; do not skip evidence that challenges the prediction.",
            "Tally the evidence by supports, challenges, or does not decide.",
            "Write a conclusion that cites at least two evidence IDs and is no broader than the supplied record.",
            "Name one additional observation or measurement that would make the conclusion stronger.",
        ],
        "recording_columns": ["Evidence ID", "Supports / challenges / does not decide", "Reason", "Limitation"],
        "recording_rows": len(evidence_rows),
        "safety": [
            "This route is desk work: do not add household substances, heat, electricity, cutting, or an outdoor collection.",
            "Take a pause or use a spoken, typed, drawn, or tactile response at any point without losing credit.",
        ],
        "cleanup": "Return the sheet and writing tool; recycle scrap paper. No sample or chemical waste is produced.",
    }


def bind_analysis_questions(
    questions: list[dict], lesson: dict, content: dict
) -> list[dict]:
    """Replace topic-substitution questions with prompts bound to shipped inputs."""
    count = len(content["supplied_evidence"]["rows"])
    evidence = f"E1-E{count}"
    focus = lesson["focus"]
    claim = content["case"]["claim_to_test"]
    unit_topics = ", ".join(lesson["unit"].get("topics", []))
    performance_task = lesson["unit"].get("performance_task", "the unit evidence product")
    prompts = {
        "ACTIVATE_PRIOR": (
            f"Before rereading the brief, classify the supplied candidate claim about {focus} as "
            f"supported, partly supported, or not supported. Then read {evidence}, revise the "
            "classification, and name the evidence ID that changed or confirmed your thinking."
        ),
        "ANALYZE_EVIDENCE": (
            f"Classify every supplied row {evidence} as supports, challenges, or does not decide "
            f"the candidate claim about {focus}. Cite the row and explain each classification."
        ),
        "APPLY_INDEPENDENT": (
            f"Independently evaluate this fully supplied case about {focus}: {claim} Use at least "
            f"two rows from {evidence}, correct the claim if needed, and state one limit."
        ),
        "APPLY_NEW_TASK": (
            f"Treat the printed candidate claim as the fresh case for {focus}. Decide whether "
            f"{evidence} supports it, show the evidence-to-conclusion reasoning, and write a more "
            "defensible replacement claim if it does not."
        ),
        "BUILD_PRODUCT": (
            f"Create a one-page evidence product for {focus} using only the supplied case and "
            f"{evidence}: one claim, at least two cited rows, the reasoning link, one counterpoint, "
            "and one revision after checking the success criteria."
        ),
        "CHECK_REVISE": (
            f"Check your response about {focus} against each success criterion. Revise one sentence "
            f"by adding or changing a citation to {evidence}; state exactly what the revision fixes."
        ),
        "CHECK_REVISE_NEXT_STEP": (
            f"Check the conclusion about {focus}, revise its weakest claim with a named row from "
            f"{evidence}, and name the next observation or model input that would resolve the "
            "remaining limitation."
        ),
        "COMMUNICATE_REPRESENTATION": (
            f"Communicate what the supplied record establishes about {focus} in a labelled diagram, "
            f"table, or paragraph. Include citations to at least two rows from {evidence} and mark "
            "where the representation stops being supported."
        ),
        "CONNECT_UNIT": (
            f"The supplied unit connections are: {unit_topics}. Choose one idea other than {focus}, "
            f"connect it to one row in {evidence}, and explain one way treating the two ideas as "
            "identical would be misleading."
        ),
        "DEMONSTRATE_MASTERY": (
            f"Complete all three parts for {focus}. (1) Select A: supported, B: partly supported, or "
            f"C: not supported for the candidate claim. (2) Justify the selection with {evidence}. "
            "(3) Rewrite the claim so every word is supported by the supplied record."
        ),
        "ERROR_ANALYSIS": (
            f"Locate the exact phrase in the candidate claim that conflicts with {evidence}. Name "
            f"the decisive evidence ID, explain the error about {focus}, and write a corrected claim."
        ),
        "ESSENTIAL_QUESTION": (
            f"Answer the printed unit question using {focus} as the example. Cite one row from "
            f"{evidence}, connect it to the answer, and state what the supplied record cannot decide."
        ),
        "EVIDENCE_QUALITY": (
            f"Which one row in {evidence} is strongest for evaluating the candidate claim about "
            f"{focus}? Name the row, explain why it is more direct than another supplied row, and "
            "name one input that would strengthen it."
        ),
        "EXPLAIN_WITH_EVIDENCE": (
            f"Explain {focus} in your own words using at least two specifically named rows from "
            f"{evidence}. Then explain why the candidate claim does or does not follow."
        ),
        "GUIDED_PRACTICE": (
            f"First compare E1 with E2 and write a provisional conclusion about {focus}. Then add "
            f"the remaining rows through E{count}, revise the conclusion, and explain the change."
        ),
        "INVESTIGATE": (
            f"Complete the route you chose. For the document/model route, use its printed procedure "
            f"and input table; for the H4 physical route, use the printed safe order and your own "
            f"blank record. Report the route, evidence IDs or model rows, conclusion about {focus}, "
            "uncertainty, and limitation."
        ),
        "LIMITATION": (
            f"Using the supplied case and {evidence}, state one conclusion about {focus} that the "
            "record supports and one question it cannot answer. Name the different observation, "
            "measurement, or model input the unanswered question would require."
        ),
        "MASTERY_FRESH_TASK": (
            f"Without copying a sentence from the brief, evaluate the printed candidate case about "
            f"{focus}. Cite {evidence}, write the reasoning in your own words, and correct the case "
            "claim so it fits exactly what the record establishes."
        ),
        "MODEL_BUILD": (
            f"Build a labelled model of {focus} that represents every supplied row in {evidence}. "
            "Annotate each model feature with its evidence ID, then show where the candidate claim "
            "fails or remains uncertain."
        ),
        "PERFORMANCE_EVIDENCE": (
            f"Build a checkable contribution to the supplied unit performance task — {performance_task} "
            f"— using the case and {evidence}. Include claim, evidence, reasoning, limitation, and a "
            "recorded revision."
        ),
        "PHENOMENON_QUESTION": (
            f"Use the printed case as today's phenomenon for {focus}. Record what the candidate "
            f"claim says, identify the mismatch with {evidence}, and pose a testable question naming "
            "what would change and what would be measured or classified."
        ),
        "PROVENANCE": (
            f"Audit the inputs used in your response about {focus}. Label {evidence} as SUPPLIED "
            "reference information with the provenance printed below the table; label any model "
            "value as MODEL OUTPUT and any value you calculate as CALCULATED."
        ),
    }
    return [
        {**question, "prompt": prompts.get(question["kind"], question["prompt"])}
        for question in questions
    ]


def build_executable_content(
    lesson: dict,
    course: dict,
    authority: dict,
    data_bearing: bool,
) -> dict:
    evidence_rows = _reference_rows(authority)
    phase_task = PHASE_TASKS.get(
        lesson["phase"],
        "Use the supplied evidence record to complete the stated learning objectives and cite evidence IDs.",
    )
    content = {
        "version": CONTENT_VERSION,
        "completion_mode": "PACKAGE_ALONE",
        "science_brief": [
            row["information"] for row in evidence_rows
        ],
        "case": {
            "title": f"Evidence check: {lesson['focus']}",
            "claim_to_test": _candidate_claim(authority, lesson["focus"]),
            "claim_status": "candidate claim; the learner decides from the supplied record",
        },
        "supplied_evidence": {
            "title": "Complete reference-evidence record for this lesson",
            "columns": ["Evidence ID", "Type", "Information"],
            "rows": evidence_rows,
            "provenance": (
                f"Manuel Academy Science learner brief for topic {authority['topic_key']}, "
                f"derived from the reviewed correctness source {authority['authored']['file']}."
            ),
        },
        "unit_connections": list(lesson["unit"].get("topics", [])),
        "unit_performance_task": lesson["unit"].get("performance_task", ""),
        "bound_task": {
            "question": (
                f"What does evidence E1 through E{len(evidence_rows)} justify about "
                f"{lesson['focus']}, and does it support the candidate claim?"
            ),
            "phase_directions": phase_task,
            "steps": [
                "Read the science brief and the candidate claim.",
                "Use the supplied evidence IDs; do not refer to an unseen source or an activity from another lesson.",
                phase_task,
                "Cite evidence IDs beside each conclusion and state one limit of the supplied record.",
                "Check the response against today's success criteria and revise one part.",
            ],
        },
        "materials_complete": True,
        "inputs_complete": True,
        "placeholder_free": True,
        "physical_result_disclosed_before_collection": False,
    }

    if data_bearing and course["family"] == "k8":
        investigation = _document_investigation(lesson, evidence_rows)
        content["investigation"] = investigation
        content["primary_route"] = {
            "kind": "DOCUMENT_INVESTIGATION",
            "materials": investigation["materials"],
            "procedure": investigation["procedure"],
            "safety": investigation["safety"],
            "recording_columns": investigation["recording_columns"],
            "cleanup": investigation["cleanup"],
        }
        content["equal_credit_route"] = {
            "kind": "ACCESSIBLE_EVIDENCE_SIMULATION",
            "complete": True,
            "materials": ["the evidence record on this sheet", "an accessible response tool"],
            "input": content["supplied_evidence"],
            "procedure": [
                "Have the evidence rows read aloud, enlarged, or converted to tactile/one-row-at-a-time cards.",
                "For each row, state supports, challenges, or does not decide and give the reason.",
                "Produce the same conclusion, limitation, and revision required by the primary route.",
            ],
            "same_scoring_ceiling": True,
        }
    elif data_bearing:
        alternative = HS_ALTERNATIVE_DATA[(course["course_id"], lesson["unit_number"])]
        content["primary_route"] = {
            "kind": "H4_PHYSICAL_INVESTIGATION",
            "authority": "The pinned H4 materials, safe order, stop conditions, and disposal rendered elsewhere on this sheet.",
            "source_task": lesson["student_activity"],
            "complete": bool(lesson["materials"]),
        }
        content["equal_credit_route"] = {
            "kind": "DELIVERED_MODEL_DATA_ALTERNATIVE",
            "complete": True,
            "materials": ["this supplied model-data table", "paper", "pencil", "calculator if desired"],
            "input": alternative,
            "procedure": [
                "Choose this route instead of the physical route; it earns the same maximum score.",
                "Read the model rule and label every supplied quantity as MODEL OUTPUT.",
                alternative["task"],
                "Show calculations, cite row labels, state a limitation of the model, and answer the lesson analysis questions.",
                "Do not combine these model outputs with measurements from the physical route or call them observations.",
            ],
            "same_scoring_ceiling": True,
            "does_not_predict_physical_route": True,
        }
    else:
        content["primary_route"] = {
            "kind": "BOUND_REFERENCE_EVIDENCE_TASK",
            "complete": True,
            "materials": ["this complete learner sheet", "course notebook or response space", "accessible response tool"],
        }
        content["equal_credit_route"] = {
            "kind": "ACCESSIBLE_RESPONSE_ROUTE",
            "complete": True,
            "materials": ["the supplied evidence record", "a spoken, typed, drawn, or tactile response mode"],
            "procedure": [
                f"Use the same E1-E{len(evidence_rows)} record and answer the same bound question.",
                "Respond in an accessible mode without changing the evidence or success criteria.",
            ],
            "same_scoring_ceiling": True,
        }

    return content


def production_materials(lesson: dict, course: dict, content: dict, data_bearing: bool) -> list[str]:
    """Return materials the rendered package actually supplies or names."""
    if data_bearing and course["family"] == "hs":
        source = [
            item
            for item in lesson["materials"]
            if not item.lower().startswith("no ")
            and "printed or on-screen text, data table, or model for this lesson"
            not in item.lower()
            and "unit-specific source, model, manipulatives, safe materials" not in item.lower()
        ]
        alternative = content["equal_credit_route"]["materials"]
        return list(dict.fromkeys([*source, *alternative]))
    if data_bearing:
        return list(content["primary_route"]["materials"])
    return list(content["primary_route"]["materials"])
