-- CURR-APPROVAL-01: durable human approval for exact curriculum draft revisions.
-- This migration does not materialize, stage, publish, activate, or roll back a release.

begin;

do $$
begin
  if current_user <> 'postgres' then
    raise exception 'Academy curriculum approval migration must run as postgres';
  end if;
end;
$$;

-- Preserve all current curriculum audit vocabulary, including the globally
-- earlier standards-review card when it is present in an integrated branch.
alter table academy_private.admin_audit_events
  drop constraint admin_audit_events_action_check,
  drop constraint admin_audit_events_resource_type_check;

alter table academy_private.admin_audit_events
  add constraint admin_audit_events_action_check check (action in (
    'admin_role.assign', 'admin_role.revoke', 'configuration.update',
    'engine.control', 'safety.triage', 'incident.acknowledge',
    'curriculum_draft.create', 'curriculum_draft.update',
    'curriculum_entity.create', 'curriculum_entity.update',
    'curriculum_entity.tombstone',
    'curriculum_draft.collaborator.add', 'curriculum_draft.collaborator.revoke',
    'curriculum_standard_review.update',
    'curriculum_approval.approve', 'curriculum_approval.changes_requested',
    'curriculum.approve', 'curriculum.publish',
    'release.activate', 'release.rollback'
  )),
  add constraint admin_audit_events_resource_type_check check (resource_type in (
    'admin_role_assignment', 'configuration', 'engine', 'safety_case',
    'incident', 'curriculum_draft', 'curriculum_entity',
    'curriculum_standard_review', 'curriculum_approval',
    'curriculum_release', 'application_release'
  ));

create or replace function academy_private.admin_audit_action_resource_is_allowed(
  candidate_action text,
  candidate_resource_type text
)
returns boolean
language sql
immutable
security invoker
set search_path = pg_catalog
as $$
  select (candidate_action, candidate_resource_type) in (
    ('admin_role.assign', 'admin_role_assignment'),
    ('admin_role.revoke', 'admin_role_assignment'),
    ('configuration.update', 'configuration'),
    ('engine.control', 'engine'),
    ('safety.triage', 'safety_case'),
    ('incident.acknowledge', 'incident'),
    ('curriculum_draft.create', 'curriculum_draft'),
    ('curriculum_draft.update', 'curriculum_draft'),
    ('curriculum_entity.create', 'curriculum_entity'),
    ('curriculum_entity.update', 'curriculum_entity'),
    ('curriculum_entity.tombstone', 'curriculum_entity'),
    ('curriculum_draft.collaborator.add', 'curriculum_draft'),
    ('curriculum_draft.collaborator.revoke', 'curriculum_draft'),
    ('curriculum_standard_review.update', 'curriculum_standard_review'),
    ('curriculum_approval.approve', 'curriculum_approval'),
    ('curriculum_approval.changes_requested', 'curriculum_approval'),
    ('curriculum.approve', 'curriculum_release'),
    ('curriculum.publish', 'curriculum_release'),
    ('release.activate', 'application_release'),
    ('release.rollback', 'application_release')
  );
$$;

create table public.academy_curriculum_draft_validation_snapshots (
  validation_snapshot_id uuid primary key default gen_random_uuid(),
  validation_sequence bigint generated by default as identity unique,
  draft_id uuid not null
    references public.academy_curriculum_drafts (draft_id) on delete restrict,
  draft_revision bigint not null check (draft_revision >= 1),
  base_release_id uuid not null
    references public.academy_curriculum_releases (release_id) on delete restrict,
  target_version text not null check (
    target_version ~ '^[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9.-]+)?$'
  ),
  schema_set_version text not null check (schema_set_version = '2.0.0'),
  engine_version text not null check (
    length(engine_version) between 1 and 80
    and engine_version ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,79}$'
  ),
  result_sha256 text not null check (result_sha256 ~ '^[0-9a-f]{64}$'),
  validation_status text not null check (validation_status in (
    'valid', 'invalid', 'incomplete', 'unavailable', 'error'
  )),
  publication_ready boolean not null,
  blocking_count integer not null check (blocking_count between 0 and 1000000),
  blocking_error_count integer not null check (
    blocking_error_count between 0 and blocking_count
  ),
  human_review_blocker_count integer not null check (
    human_review_blocker_count between 0 and blocking_count
  ),
  validated_at timestamptz not null default statement_timestamp(),
  validated_by uuid not null references auth.users (id) on delete restrict,
  constraint academy_curriculum_validation_gate_coherence check (
    publication_ready = (
      validation_status = 'valid'
      and blocking_count = 0
      and blocking_error_count = 0
      and human_review_blocker_count = 0
    )
  ),
  constraint academy_curriculum_validation_result_unique
    unique (draft_id, draft_revision, result_sha256)
);

create index academy_curriculum_validation_revision_idx
  on public.academy_curriculum_draft_validation_snapshots
  (draft_id, draft_revision desc, validation_sequence desc);

create table public.academy_curriculum_draft_approval_decisions (
  approval_id uuid primary key default gen_random_uuid(),
  decision_sequence bigint generated by default as identity unique,
  draft_id uuid not null
    references public.academy_curriculum_drafts (draft_id) on delete restrict,
  draft_revision bigint not null check (draft_revision >= 1),
  base_release_id uuid not null
    references public.academy_curriculum_releases (release_id) on delete restrict,
  target_version text not null check (
    target_version ~ '^[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9.-]+)?$'
  ),
  schema_set_version text not null check (schema_set_version = '2.0.0'),
  validation_snapshot_id uuid
    references public.academy_curriculum_draft_validation_snapshots
      (validation_snapshot_id) on delete restrict,
  validation_result_sha256 text check (
    validation_result_sha256 is null or validation_result_sha256 ~ '^[0-9a-f]{64}$'
  ),
  decision text not null check (decision in ('approved', 'changes_requested')),
  reason_code text not null check (reason_code in (
    'approval.ready',
    'changes.validation', 'changes.standards', 'changes.content_quality',
    'changes.references', 'changes.accessibility',
    'changes.safety_privacy', 'changes.other'
  )),
  decided_at timestamptz not null default statement_timestamp(),
  decided_by uuid not null references auth.users (id) on delete restrict,
  reviewer_role text not null check (reviewer_role = 'owner'),
  request_id uuid not null,
  constraint academy_curriculum_approval_decision_reason_check check (
    (decision = 'approved' and reason_code = 'approval.ready')
    or (decision = 'changes_requested' and reason_code like 'changes.%')
  ),
  constraint academy_curriculum_approval_validation_binding_check check (
    (decision = 'approved' and validation_snapshot_id is not null
      and validation_result_sha256 is not null)
    or decision = 'changes_requested'
  )
);

create index academy_curriculum_approval_history_idx
  on public.academy_curriculum_draft_approval_decisions
  (draft_id, draft_revision desc, decision_sequence desc);

create table academy_private.curriculum_approval_request_receipts (
  actor_user_ref uuid not null references auth.users (id) on delete restrict,
  request_id uuid not null,
  request_sha256 text not null check (request_sha256 ~ '^[0-9a-f]{64}$'),
  response jsonb not null check (
    jsonb_typeof(response) = 'object' and pg_column_size(response) <= 8192
  ),
  created_at timestamptz not null default statement_timestamp(),
  primary key (actor_user_ref, request_id)
);

alter table public.academy_curriculum_draft_validation_snapshots owner to postgres;
alter table public.academy_curriculum_draft_approval_decisions owner to postgres;
alter table academy_private.curriculum_approval_request_receipts owner to postgres;

alter table public.academy_curriculum_draft_validation_snapshots enable row level security;
alter table public.academy_curriculum_draft_validation_snapshots force row level security;
alter table public.academy_curriculum_draft_approval_decisions enable row level security;
alter table public.academy_curriculum_draft_approval_decisions force row level security;
alter table academy_private.curriculum_approval_request_receipts enable row level security;
alter table academy_private.curriculum_approval_request_receipts force row level security;

create function academy_private.curriculum_approval_reject_mutation()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  raise exception 'Curriculum approval evidence is append-only' using errcode = '55000';
end;
$$;

create trigger academy_curriculum_validation_snapshots_append_only
  before update or delete on public.academy_curriculum_draft_validation_snapshots
  for each row execute function academy_private.curriculum_approval_reject_mutation();
create trigger academy_curriculum_approval_decisions_append_only
  before update or delete on public.academy_curriculum_draft_approval_decisions
  for each row execute function academy_private.curriculum_approval_reject_mutation();
create trigger academy_curriculum_approval_receipts_append_only
  before update or delete on academy_private.curriculum_approval_request_receipts
  for each row execute function academy_private.curriculum_approval_reject_mutation();

-- This function is the database-owned role-to-capability mapping for this
-- boundary. Callers must name the exact frozen capability; broad role markers
-- and client-supplied capability arrays are never accepted as authority.
create function academy_private.curriculum_approval_require_actor(
  p_actor_user_ref uuid,
  p_required_capability text
)
returns text
language plpgsql
stable
security definer
set search_path = pg_catalog
as $$
declare
  actor_role text;
begin
  if auth.uid() is not null
     or not academy_private.operational_is_trusted_server()
     or p_actor_user_ref is null
     or p_required_capability not in ('curriculum:read', 'curriculum:approve') then
    raise exception 'CURRICULUM_APPROVAL_REQUIRED' using errcode = '42501';
  end if;
  select assignment.role into actor_role
  from public.academy_admin_role_assignments as assignment
  where assignment.user_id = p_actor_user_ref
    and assignment.status = 'active'
    and assignment.revoked_at is null
    and (assignment.expires_at is null or assignment.expires_at > statement_timestamp())
  order by assignment.assigned_at desc, assignment.id desc
  limit 1;
  if actor_role is null
     or (p_required_capability = 'curriculum:approve' and actor_role <> 'owner') then
    raise exception 'CURRICULUM_APPROVAL_REQUIRED' using errcode = '42501';
  end if;
  return actor_role;
end;
$$;

create function academy_private.curriculum_validation_snapshot_projection(
  p_validation_snapshot_id uuid
)
returns jsonb
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select jsonb_build_object(
    'validationSnapshotId', snapshot.validation_snapshot_id,
    'draftRevision', snapshot.draft_revision,
    'engineVersion', snapshot.engine_version,
    'resultDigest', snapshot.result_sha256,
    'status', snapshot.validation_status,
    'publicationReady', snapshot.publication_ready,
    'blockingCount', snapshot.blocking_count,
    'blockingErrorCount', snapshot.blocking_error_count,
    'humanReviewBlockerCount', snapshot.human_review_blocker_count,
    'validatedAt', snapshot.validated_at
  )
  from public.academy_curriculum_draft_validation_snapshots as snapshot
  where snapshot.validation_snapshot_id = p_validation_snapshot_id;
$$;

create function academy_private.curriculum_approval_decision_projection(
  p_approval_id uuid,
  p_current_approval_id uuid
)
returns jsonb
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select jsonb_build_object(
    'approvalId', decision.approval_id,
    'draftRevision', decision.draft_revision,
    'decision', decision.decision,
    'reasonCode', decision.reason_code,
    'validationSnapshotId', decision.validation_snapshot_id,
    'validationResultDigest', decision.validation_result_sha256,
    'reviewerRole', decision.reviewer_role,
    'decidedAt', decision.decided_at,
    'bindingStatus', case when decision.approval_id = p_current_approval_id
      then 'current' else 'superseded' end
  )
  from public.academy_curriculum_draft_approval_decisions as decision
  where decision.approval_id = p_approval_id;
$$;

create function academy_private.curriculum_approval_status_projection(p_draft_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog
as $$
declare
  draft_row public.academy_curriculum_drafts%rowtype;
  base_version text;
  latest_validation public.academy_curriculum_draft_validation_snapshots%rowtype;
  current_decision public.academy_curriculum_draft_approval_decisions%rowtype;
  stale_approval public.academy_curriculum_draft_approval_decisions%rowtype;
  approved_validation public.academy_curriculum_draft_validation_snapshots%rowtype;
  history jsonb;
  status_value text;
  gate_reason text;
  gate_eligible boolean := false;
  current_binding_id uuid;
  stale_binding_id uuid;
begin
  select * into draft_row
  from public.academy_curriculum_drafts
  where draft_id = p_draft_id;
  if draft_row.draft_id is null then return null; end if;
  select version into base_version
  from public.academy_curriculum_releases
  where release_id = draft_row.base_release_id;

  select * into latest_validation
  from public.academy_curriculum_draft_validation_snapshots
  where draft_id = p_draft_id and draft_revision = draft_row.revision
  order by validation_sequence desc
  limit 1;

  select * into current_decision
  from public.academy_curriculum_draft_approval_decisions
  where draft_id = p_draft_id and draft_revision = draft_row.revision
  order by decision_sequence desc
  limit 1;

  select effective.* into stale_approval
  from (
    select distinct on (decision.draft_revision) decision.*
    from public.academy_curriculum_draft_approval_decisions as decision
    where decision.draft_id = p_draft_id
      and decision.draft_revision < draft_row.revision
    order by decision.draft_revision desc, decision.decision_sequence desc
  ) as effective
  where effective.decision = 'approved'
  order by effective.draft_revision desc
  limit 1;

  if current_decision.decision = 'approved'
     and current_decision.validation_snapshot_id = latest_validation.validation_snapshot_id then
    status_value := 'approved';
    current_binding_id := current_decision.approval_id;
  elsif current_decision.decision = 'approved' then
    status_value := 'stale';
    stale_binding_id := current_decision.approval_id;
  elsif current_decision.decision = 'changes_requested' then
    status_value := 'changes_requested';
    current_binding_id := current_decision.approval_id;
  elsif stale_approval.approval_id is not null then
    status_value := 'stale';
    stale_binding_id := stale_approval.approval_id;
  else
    status_value := 'pending_review';
  end if;

  if current_decision.validation_snapshot_id is not null then
    select * into approved_validation
    from public.academy_curriculum_draft_validation_snapshots
    where validation_snapshot_id = current_decision.validation_snapshot_id;
  end if;
  if current_decision.decision = 'approved'
     and approved_validation.validation_snapshot_id is not null
     and approved_validation.draft_id = p_draft_id
     and approved_validation.draft_revision = draft_row.revision
     and approved_validation.base_release_id = draft_row.base_release_id
     and approved_validation.target_version = draft_row.target_version
     and approved_validation.schema_set_version = draft_row.authoring_schema_version
     and approved_validation.validation_snapshot_id = latest_validation.validation_snapshot_id
     and approved_validation.result_sha256 = current_decision.validation_result_sha256
     and approved_validation.validation_status = 'valid'
     and approved_validation.publication_ready
     and approved_validation.blocking_count = 0
     and approved_validation.blocking_error_count = 0
     and approved_validation.human_review_blocker_count = 0 then
    gate_eligible := true;
    gate_reason := 'approved';
  elsif current_decision.decision = 'changes_requested' then
    gate_reason := 'changes_requested';
  elsif status_value = 'stale' then
    gate_reason := 'approval_stale';
  elsif latest_validation.validation_snapshot_id is null then
    gate_reason := 'validation_missing';
  elsif not latest_validation.publication_ready then
    gate_reason := 'validation_blocked';
  else
    gate_reason := 'approval_missing';
  end if;

  select coalesce(jsonb_agg(
    academy_private.curriculum_approval_decision_projection(
      bounded.approval_id, current_binding_id
    ) order by bounded.decision_sequence desc
  ), '[]'::jsonb) into history
  from (
    select approval_id, decision_sequence
    from public.academy_curriculum_draft_approval_decisions
    where draft_id = p_draft_id
    order by decision_sequence desc
    limit 100
  ) as bounded;

  return jsonb_build_object(
    'schemaVersion', 1,
    'draftId', draft_row.draft_id,
    'draftRevision', draft_row.revision,
    'baseReleaseVersion', base_version,
    'targetVersion', draft_row.target_version,
    'schemaSetVersion', draft_row.authoring_schema_version,
    'status', status_value,
    'latestValidation', case when latest_validation.validation_snapshot_id is null
      then null else academy_private.curriculum_validation_snapshot_projection(
        latest_validation.validation_snapshot_id
      ) end,
    'currentDecision', case when current_decision.approval_id is null
      then null else academy_private.curriculum_approval_decision_projection(
        current_decision.approval_id, current_binding_id
      ) end,
    'staleApproval', case when stale_binding_id is null
      then null else academy_private.curriculum_approval_decision_projection(
        stale_binding_id, current_binding_id
      ) end,
    'history', history,
    'publishGate', jsonb_build_object(
      'eligible', gate_eligible,
      'reason', gate_reason,
      'approvalId', case when gate_eligible then current_decision.approval_id else null end,
      'draftRevision', draft_row.revision,
      'validationSnapshotId', case when gate_eligible
        then current_decision.validation_snapshot_id else null end
    )
  );
end;
$$;

create function academy_private.curriculum_approval_publish_gate_v1(
  p_draft_id uuid,
  p_draft_revision bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog
as $$
declare
  projection jsonb;
begin
  projection := academy_private.curriculum_approval_status_projection(p_draft_id);
  if projection is null then return null; end if;
  if (projection ->> 'draftRevision')::bigint <> p_draft_revision then
    return jsonb_build_object(
      'eligible', false, 'reason', 'approval_stale', 'approvalId', null,
      'draftRevision', (projection ->> 'draftRevision')::bigint,
      'validationSnapshotId', null
    );
  end if;
  return projection -> 'publishGate';
end;
$$;

create function academy_private.curriculum_approval_replay(
  p_actor_user_ref uuid,
  p_request_id uuid,
  p_request_digest text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog
as $$
declare
  receipt academy_private.curriculum_approval_request_receipts%rowtype;
begin
  if p_request_id is null or p_request_digest !~ '^[0-9a-f]{64}$' then
    raise exception 'CURRICULUM_APPROVAL_INPUT_INVALID' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(
    p_actor_user_ref::text || ':' || p_request_id::text, 0
  ));
  select * into receipt
  from academy_private.curriculum_approval_request_receipts
  where actor_user_ref = p_actor_user_ref and request_id = p_request_id
  for update;
  if receipt.request_id is null then return null; end if;
  if receipt.request_sha256 <> p_request_digest then
    raise exception 'CURRICULUM_APPROVAL_REPLAY_CONFLICT' using errcode = '40001';
  end if;
  return receipt.response;
end;
$$;

create function academy_private.curriculum_approval_append_audit(
  p_actor_user_ref uuid,
  p_draft_id uuid,
  p_target_version text,
  p_draft_revision bigint,
  p_previous_decision text,
  p_previous_reason_code text,
  p_decision text,
  p_reason_code text,
  p_correlation_id uuid
)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog
as $$
declare
  old_sub text := current_setting('request.jwt.claim.sub', true);
  old_role text := current_setting('request.jwt.claim.role', true);
  old_claims text := current_setting('request.jwt.claims', true);
  event_id uuid;
begin
  perform set_config('request.jwt.claim.sub', p_actor_user_ref::text, true);
  perform set_config('request.jwt.claim.role', 'authenticated', true);
  perform set_config('request.jwt.claims', jsonb_build_object(
    'sub', p_actor_user_ref, 'role', 'authenticated',
    'academy_principal_kind', 'admin_curriculum_approval_server'
  )::text, true);
  begin
    event_id := academy_private.append_admin_audit_event_v1(
      case when p_decision = 'approved'
        then 'curriculum_approval.approve'
        else 'curriculum_approval.changes_requested' end,
      'curriculum_approval', p_draft_id::text, p_target_version,
      p_draft_revision::text,
      jsonb_build_object(
        'state', coalesce(p_previous_decision, 'pending_review'),
        'status', coalesce(p_previous_reason_code, 'review.pending'),
        'revision', p_draft_revision,
        'version', p_target_version
      ),
      jsonb_build_object(
        'state', p_decision, 'status', p_reason_code,
        'revision', p_draft_revision, 'version', p_target_version
      ),
      case when p_decision = 'approved'
        then 'curriculum.approved' else 'corrective.action' end,
      p_correlation_id
    );
  exception when others then
    perform set_config('request.jwt.claim.sub', coalesce(old_sub, ''), true);
    perform set_config('request.jwt.claim.role', coalesce(old_role, ''), true);
    perform set_config('request.jwt.claims', coalesce(old_claims, ''), true);
    raise;
  end;
  perform set_config('request.jwt.claim.sub', coalesce(old_sub, ''), true);
  perform set_config('request.jwt.claim.role', coalesce(old_role, ''), true);
  perform set_config('request.jwt.claims', coalesce(old_claims, ''), true);
  return event_id;
end;
$$;

create function public.academy_admin_record_curriculum_validation_v1(
  p_actor_user_ref uuid,
  p_draft_id uuid,
  p_draft_revision bigint,
  p_engine_version text,
  p_result_digest text,
  p_status text,
  p_publication_ready boolean,
  p_blocking_count integer,
  p_blocking_error_count integer,
  p_human_review_blocker_count integer,
  p_required_capability text default null
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog
as $$
declare
  draft_row public.academy_curriculum_drafts%rowtype;
  existing_snapshot public.academy_curriculum_draft_validation_snapshots%rowtype;
  resolved_snapshot uuid;
begin
  perform academy_private.curriculum_approval_require_actor(
    p_actor_user_ref, p_required_capability
  );
  if p_required_capability <> 'curriculum:read'
     or p_draft_revision < 1
     or p_engine_version is null or length(p_engine_version) not between 1 and 80
     or p_engine_version !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,79}$'
     or p_result_digest !~ '^[0-9a-f]{64}$'
     or p_status not in ('valid', 'invalid', 'incomplete', 'unavailable', 'error')
     or p_blocking_count not between 0 and 1000000
     or p_blocking_error_count not between 0 and p_blocking_count
     or p_human_review_blocker_count not between 0 and p_blocking_count
     or p_publication_ready is distinct from (
       p_status = 'valid' and p_blocking_count = 0
       and p_blocking_error_count = 0 and p_human_review_blocker_count = 0
     ) then
    raise exception 'CURRICULUM_APPROVAL_INPUT_INVALID' using errcode = '22023';
  end if;
  select * into draft_row
  from public.academy_curriculum_drafts
  where draft_id = p_draft_id
  for key share;
  if draft_row.draft_id is null then
    raise exception 'CURRICULUM_APPROVAL_DRAFT_NOT_FOUND' using errcode = 'P0002';
  end if;
  if draft_row.revision <> p_draft_revision then
    raise exception 'CURRICULUM_APPROVAL_CAS_CONFLICT' using errcode = '40001';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(
    p_draft_id::text || ':' || p_draft_revision::text || ':' || p_result_digest, 0
  ));
  select * into existing_snapshot
  from public.academy_curriculum_draft_validation_snapshots
  where draft_id = p_draft_id and draft_revision = p_draft_revision
    and result_sha256 = p_result_digest;
  resolved_snapshot := existing_snapshot.validation_snapshot_id;
  if resolved_snapshot is not null and (
    existing_snapshot.base_release_id <> draft_row.base_release_id
    or existing_snapshot.target_version <> draft_row.target_version
    or existing_snapshot.schema_set_version <> draft_row.authoring_schema_version
    or existing_snapshot.engine_version <> p_engine_version
    or existing_snapshot.validation_status <> p_status
    or existing_snapshot.publication_ready <> p_publication_ready
    or existing_snapshot.blocking_count <> p_blocking_count
    or existing_snapshot.blocking_error_count <> p_blocking_error_count
    or existing_snapshot.human_review_blocker_count <> p_human_review_blocker_count
  ) then
    raise exception 'CURRICULUM_APPROVAL_INPUT_INVALID' using errcode = '22023';
  end if;
  if resolved_snapshot is null then
    insert into public.academy_curriculum_draft_validation_snapshots (
      draft_id, draft_revision, base_release_id, target_version,
      schema_set_version, engine_version, result_sha256, validation_status,
      publication_ready, blocking_count, blocking_error_count,
      human_review_blocker_count, validated_by
    ) values (
      p_draft_id, p_draft_revision, draft_row.base_release_id,
      draft_row.target_version, draft_row.authoring_schema_version,
      p_engine_version, p_result_digest, p_status, p_publication_ready,
      p_blocking_count, p_blocking_error_count,
      p_human_review_blocker_count, p_actor_user_ref
    ) returning validation_snapshot_id into resolved_snapshot;
  end if;
  return academy_private.curriculum_validation_snapshot_projection(resolved_snapshot);
end;
$$;

create function public.academy_admin_read_curriculum_approval_v1(
  p_actor_user_ref uuid,
  p_draft_id uuid,
  p_required_capability text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog
as $$
declare
  projection jsonb;
begin
  perform academy_private.curriculum_approval_require_actor(
    p_actor_user_ref, p_required_capability
  );
  if p_required_capability <> 'curriculum:read' then
    raise exception 'CURRICULUM_APPROVAL_REQUIRED' using errcode = '42501';
  end if;
  projection := academy_private.curriculum_approval_status_projection(p_draft_id);
  if projection is null then
    raise exception 'CURRICULUM_APPROVAL_DRAFT_NOT_FOUND' using errcode = 'P0002';
  end if;
  return projection;
end;
$$;

create function public.academy_admin_decide_curriculum_approval_v1(
  p_actor_user_ref uuid,
  p_draft_id uuid,
  p_draft_revision bigint,
  p_decision text,
  p_reason_code text,
  p_validation_snapshot_id uuid,
  p_request_id uuid,
  p_request_digest text,
  p_required_capability text default null
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog
as $$
declare
  actor_role text;
  draft_row public.academy_curriculum_drafts%rowtype;
  validation_row public.academy_curriculum_draft_validation_snapshots%rowtype;
  current_decision public.academy_curriculum_draft_approval_decisions%rowtype;
  created_approval uuid;
  replay jsonb;
  response jsonb;
begin
  actor_role := academy_private.curriculum_approval_require_actor(
    p_actor_user_ref, p_required_capability
  );
  if p_required_capability <> 'curriculum:approve'
     or p_draft_revision < 1
     or p_decision not in ('approved', 'changes_requested')
     or p_reason_code not in (
       'approval.ready',
       'changes.validation', 'changes.standards', 'changes.content_quality',
       'changes.references', 'changes.accessibility',
       'changes.safety_privacy', 'changes.other'
     )
     or (p_decision = 'approved' and p_reason_code <> 'approval.ready')
     or (p_decision = 'changes_requested' and p_reason_code not like 'changes.%')
     or (p_decision = 'approved' and p_validation_snapshot_id is null) then
    raise exception 'CURRICULUM_APPROVAL_INPUT_INVALID' using errcode = '22023';
  end if;
  replay := academy_private.curriculum_approval_replay(
    p_actor_user_ref, p_request_id, p_request_digest
  );
  if replay is not null then
    return academy_private.curriculum_approval_status_projection(p_draft_id)
      || jsonb_build_object('replayed', true);
  end if;

  select * into draft_row
  from public.academy_curriculum_drafts
  where draft_id = p_draft_id
  for update;
  if draft_row.draft_id is null then
    raise exception 'CURRICULUM_APPROVAL_DRAFT_NOT_FOUND' using errcode = 'P0002';
  end if;
  if draft_row.revision <> p_draft_revision then
    raise exception 'CURRICULUM_APPROVAL_CAS_CONFLICT' using errcode = '40001';
  end if;

  select * into current_decision
  from public.academy_curriculum_draft_approval_decisions
  where draft_id = p_draft_id and draft_revision = p_draft_revision
  order by decision_sequence desc
  limit 1;
  if current_decision.decision = 'changes_requested'
     or (current_decision.decision = 'approved' and p_decision = 'approved'
       and current_decision.validation_snapshot_id = p_validation_snapshot_id) then
    raise exception 'CURRICULUM_APPROVAL_TRANSITION_CONFLICT' using errcode = '40001';
  end if;

  if p_validation_snapshot_id is not null then
    select * into validation_row
    from public.academy_curriculum_draft_validation_snapshots
    where validation_snapshot_id = p_validation_snapshot_id;
    if validation_row.validation_snapshot_id is null
       or validation_row.draft_id <> p_draft_id
       or validation_row.draft_revision <> p_draft_revision
       or validation_row.base_release_id <> draft_row.base_release_id
       or validation_row.target_version <> draft_row.target_version
       or validation_row.schema_set_version <> draft_row.authoring_schema_version then
      raise exception 'CURRICULUM_APPROVAL_VALIDATION_BLOCKED' using errcode = '23514';
    end if;
  end if;
  if p_decision = 'approved' and (
    (select snapshot.validation_snapshot_id
     from public.academy_curriculum_draft_validation_snapshots as snapshot
     where snapshot.draft_id = p_draft_id
       and snapshot.draft_revision = p_draft_revision
     order by snapshot.validation_sequence desc
     limit 1) is distinct from p_validation_snapshot_id
    or validation_row.validation_status <> 'valid'
    or not validation_row.publication_ready
    or validation_row.blocking_count <> 0
    or validation_row.blocking_error_count <> 0
    or validation_row.human_review_blocker_count <> 0
  ) then
    raise exception 'CURRICULUM_APPROVAL_VALIDATION_BLOCKED' using errcode = '23514';
  end if;

  insert into public.academy_curriculum_draft_approval_decisions (
    draft_id, draft_revision, base_release_id, target_version,
    schema_set_version, validation_snapshot_id, validation_result_sha256,
    decision, reason_code, decided_by, reviewer_role, request_id
  ) values (
    p_draft_id, p_draft_revision, draft_row.base_release_id,
    draft_row.target_version, draft_row.authoring_schema_version,
    validation_row.validation_snapshot_id, validation_row.result_sha256,
    p_decision, p_reason_code, p_actor_user_ref, actor_role, p_request_id
  ) returning approval_id into created_approval;

  perform academy_private.curriculum_approval_append_audit(
    p_actor_user_ref, p_draft_id, draft_row.target_version, p_draft_revision,
    current_decision.decision, current_decision.reason_code,
    p_decision, p_reason_code, p_request_id
  );
  insert into academy_private.curriculum_approval_request_receipts (
    actor_user_ref, request_id, request_sha256, response
  ) values (
    p_actor_user_ref, p_request_id, p_request_digest,
    jsonb_build_object('approvalId', created_approval)
  );
  response := academy_private.curriculum_approval_status_projection(p_draft_id);
  return response || jsonb_build_object('replayed', false);
end;
$$;

alter function academy_private.admin_audit_action_resource_is_allowed(text, text) owner to postgres;
alter function academy_private.curriculum_approval_reject_mutation() owner to postgres;
alter function academy_private.curriculum_approval_require_actor(uuid, text) owner to postgres;
alter function academy_private.curriculum_validation_snapshot_projection(uuid) owner to postgres;
alter function academy_private.curriculum_approval_decision_projection(uuid, uuid) owner to postgres;
alter function academy_private.curriculum_approval_status_projection(uuid) owner to postgres;
alter function academy_private.curriculum_approval_publish_gate_v1(uuid, bigint) owner to postgres;
alter function academy_private.curriculum_approval_replay(uuid, uuid, text) owner to postgres;
alter function academy_private.curriculum_approval_append_audit(uuid, uuid, text, bigint, text, text, text, text, uuid) owner to postgres;
alter function public.academy_admin_record_curriculum_validation_v1(uuid, uuid, bigint, text, text, text, boolean, integer, integer, integer, text) owner to postgres;
alter function public.academy_admin_read_curriculum_approval_v1(uuid, uuid, text) owner to postgres;
alter function public.academy_admin_decide_curriculum_approval_v1(uuid, uuid, bigint, text, text, uuid, uuid, text, text) owner to postgres;

revoke all on table public.academy_curriculum_draft_validation_snapshots
  from public, anon, authenticated, service_role;
revoke all on table public.academy_curriculum_draft_approval_decisions
  from public, anon, authenticated, service_role;
revoke all on table academy_private.curriculum_approval_request_receipts
  from public, anon, authenticated, service_role;

revoke all on function academy_private.curriculum_approval_reject_mutation()
  from public, anon, authenticated, service_role;
revoke all on function academy_private.curriculum_approval_require_actor(uuid, text)
  from public, anon, authenticated, service_role;
revoke all on function academy_private.curriculum_validation_snapshot_projection(uuid)
  from public, anon, authenticated, service_role;
revoke all on function academy_private.curriculum_approval_decision_projection(uuid, uuid)
  from public, anon, authenticated, service_role;
revoke all on function academy_private.curriculum_approval_status_projection(uuid)
  from public, anon, authenticated, service_role;
revoke all on function academy_private.curriculum_approval_publish_gate_v1(uuid, bigint)
  from public, anon, authenticated, service_role;
revoke all on function academy_private.curriculum_approval_replay(uuid, uuid, text)
  from public, anon, authenticated, service_role;
revoke all on function academy_private.curriculum_approval_append_audit(uuid, uuid, text, bigint, text, text, text, text, uuid)
  from public, anon, authenticated, service_role;

revoke all on function public.academy_admin_record_curriculum_validation_v1(uuid, uuid, bigint, text, text, text, boolean, integer, integer, integer, text)
  from public, anon, authenticated, service_role;
revoke all on function public.academy_admin_read_curriculum_approval_v1(uuid, uuid, text)
  from public, anon, authenticated, service_role;
revoke all on function public.academy_admin_decide_curriculum_approval_v1(uuid, uuid, bigint, text, text, uuid, uuid, text, text)
  from public, anon, authenticated, service_role;

grant execute on function public.academy_admin_record_curriculum_validation_v1(uuid, uuid, bigint, text, text, text, boolean, integer, integer, integer, text)
  to service_role;
grant execute on function public.academy_admin_read_curriculum_approval_v1(uuid, uuid, text)
  to service_role;
grant execute on function public.academy_admin_decide_curriculum_approval_v1(uuid, uuid, bigint, text, text, uuid, uuid, text, text)
  to service_role;

comment on table public.academy_curriculum_draft_validation_snapshots is
  'Payload-free validation identities and bounded gate summaries for exact curriculum draft revisions.';
comment on table public.academy_curriculum_draft_approval_decisions is
  'Append-only human approval/change-request decisions bound to exact draft, revision, base, target, schema, and validation identities.';
comment on function academy_private.curriculum_approval_publish_gate_v1(uuid, bigint) is
  'Ungranted machine-readable approval seam for later release staging; it does not stage or publish.';

commit;
