import assert from "node:assert/strict";
import test from "node:test";
import {
  MAXIMUM_INTERVENTION_COUNT,
  MAXIMUM_STRATEGY_REFERENCES,
  MAXIMUM_TUTOR_MEMORY_ENTRIES,
  MAXIMUM_TUTOR_MEMORY_TTL_MS,
  MAXIMUM_UNDERSTOOD_STEP_REFERENCES,
  MinimizedTutorSessionEndSchema,
  TutorSessionMemoryStateSchema,
  TutorSessionMemoryStore,
} from "./index.js";
import { validateExact } from "../contracts/validation.js";

const baseScope = {
  scopeKind: "trusted-study-tutor-scope",
  householdScopeRef: "household-scope:opaque-a",
  learnerScopeRef: "learner-scope:opaque-a",
  sessionRef: "session:math-a",
  interactionRef: "interaction:tutor-a",
  lessonRef: "lesson:fraction-a",
} as const;

function openRequest(memoryRef = "memory:tutor-a") {
  return { memoryRef, scope: baseScope, ttlMs: 60_000 } as const;
}

function accessRequest(memoryRef = "memory:tutor-a") {
  return { memoryRef, scope: baseScope } as const;
}

test("accepts only bounded structured Tutor session state", () => {
  const store = new TutorSessionMemoryStore({ now: () => Date.parse("2026-08-13T20:00:00.000Z") });
  assert.equal(store.open(openRequest()).status, "accepted");
  const result = store.update({
    ...accessRequest(),
    patch: {
      strategiesTried: ["strategy:number-line", "strategy:equal-groups"],
      visualExplanationTried: true,
      hintLevelUsed: "concept-cue",
      currentConceptRef: "concept:fractions",
      currentMisconceptionHypothesisRef: "misconception:parts-not-equal",
      understoodStepRefs: ["step:identify-whole"],
      lastTutorAction: "show-example",
      interventionCount: 2,
    },
  });
  assert.equal(result.status, "accepted");
  if (result.status !== "accepted") return;
  assert.equal(validateExact(TutorSessionMemoryStateSchema, result.state).status, "accepted");
  assert.deepEqual(result.state.strategiesTried, [
    "strategy:number-line",
    "strategy:equal-groups",
  ]);
  assert.equal(result.state.persistenceAllowed, false);
  assert.equal(result.state.authoritativeStudyHistory, false);
  assert.equal(result.state.rawProseStored, false);
});

test("rejects raw transcripts and unrestricted prose fields", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  for (const forbiddenPatch of [
    { rawTranscript: "Learner said an entire private conversation." },
    { conversation: ["raw turn one", "raw turn two"] },
    { tutorProse: "The full explanation generated by Tutor." },
    { privateNotes: "Anything unrestricted." },
  ]) {
    assert.deepEqual(store.update({ ...accessRequest(), patch: forbiddenPatch }), {
      status: "rejected",
      code: "INVALID_MEMORY_PATCH",
      tutorMayUseMemory: false,
    });
  }
});

test("rejects diagnosis and personality fields", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  for (const forbiddenPatch of [
    { personality: "lazy" },
    { motivationLabel: "unmotivated" },
    { abilityLabel: "bad-at-math" },
    { emotionalDiagnosis: "anxious" },
    { disabilityDiagnosis: "private-diagnosis" },
  ]) {
    const result = store.update({ ...accessRequest(), patch: forbiddenPatch });
    assert.equal(result.status, "rejected");
    if (result.status === "rejected") assert.equal(result.code, "INVALID_MEMORY_PATCH");
  }
});

test("rejects direct credentials and secrets", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  for (const forbiddenPatch of [
    { password: "not-allowed" },
    { rawPin: "1234" },
    { apiKey: "secret" },
    { parentSecret: "private" },
    { siblingData: "private" },
  ]) {
    const result = store.update({ ...accessRequest(), patch: forbiddenPatch });
    assert.equal(result.status, "rejected");
    if (result.status === "rejected") assert.equal(result.code, "INVALID_MEMORY_PATCH");
  }
});

test("rejects cross-session access", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  const result = store.read({
    ...accessRequest(),
    scope: { ...baseScope, sessionRef: "session:math-b" },
  });
  assert.deepEqual(result, {
    status: "rejected",
    code: "MEMORY_SCOPE_MISMATCH",
    tutorMayUseMemory: false,
  });
});

test("rejects cross-learner and cross-household access", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  for (const scope of [
    { ...baseScope, learnerScopeRef: "learner-scope:opaque-b" },
    { ...baseScope, householdScopeRef: "household-scope:opaque-b" },
  ]) {
    const result = store.read({ ...accessRequest(), scope });
    assert.equal(result.status, "rejected");
    if (result.status === "rejected") assert.equal(result.code, "MEMORY_SCOPE_MISMATCH");
  }
});

test("rejects cross-interaction and cross-lesson access", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  for (const scope of [
    { ...baseScope, interactionRef: "interaction:tutor-b" },
    { ...baseScope, lessonRef: "lesson:fraction-b" },
  ]) {
    const result = store.read({ ...accessRequest(), scope });
    assert.equal(result.status, "rejected");
    if (result.status === "rejected") assert.equal(result.code, "MEMORY_SCOPE_MISMATCH");
  }
});

test("reset removes the scoped memory entry", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  assert.deepEqual(store.reset(accessRequest()), { status: "reset" });
  assert.deepEqual(store.read(accessRequest()), {
    status: "rejected",
    code: "MEMORY_NOT_FOUND",
    tutorMayUseMemory: false,
  });
});

test("enforces bounded active entry count without silent eviction", () => {
  const store = new TutorSessionMemoryStore({ maximumEntries: 2 });
  assert.equal(store.open(openRequest("memory:one")).status, "accepted");
  assert.equal(store.open(openRequest("memory:two")).status, "accepted");
  assert.deepEqual(store.open(openRequest("memory:three")), {
    status: "rejected",
    code: "MEMORY_CAPACITY_EXCEEDED",
    tutorMayUseMemory: false,
  });
  assert.equal(store.activeEntryCount, 2);
  assert.equal(MAXIMUM_TUTOR_MEMORY_ENTRIES, 32);
});

test("enforces strategy, understood-step, intervention, and TTL bounds", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  const tooManyStrategies = Array.from(
    { length: MAXIMUM_STRATEGY_REFERENCES + 1 },
    (_, index) => `strategy:s-${index}`,
  );
  const tooManySteps = Array.from(
    { length: MAXIMUM_UNDERSTOOD_STEP_REFERENCES + 1 },
    (_, index) => `step:s-${index}`,
  );
  for (const patch of [
    { strategiesTried: tooManyStrategies },
    { understoodStepRefs: tooManySteps },
    { interventionCount: MAXIMUM_INTERVENTION_COUNT + 1 },
  ]) {
    const result = store.update({ ...accessRequest(), patch });
    assert.equal(result.status, "rejected");
    if (result.status === "rejected") assert.equal(result.code, "INVALID_MEMORY_PATCH");
  }
  assert.deepEqual(
    store.open({
      memoryRef: "memory:too-long",
      scope: { ...baseScope, interactionRef: "interaction:too-long" },
      ttlMs: MAXIMUM_TUTOR_MEMORY_TTL_MS + 1,
    }),
    { status: "rejected", code: "INVALID_MEMORY_REQUEST", tutorMayUseMemory: false },
  );
});

test("expiry is deterministic and deletes expired state", () => {
  let now = Date.parse("2026-08-13T20:00:00.000Z");
  const store = new TutorSessionMemoryStore({ now: () => now });
  store.open({ ...openRequest(), ttlMs: 1000 });
  now += 1000;
  assert.deepEqual(store.read(accessRequest()), {
    status: "rejected",
    code: "MEMORY_EXPIRED",
    tutorMayUseMemory: false,
  });
  assert.equal(store.activeEntryCount, 0);
});

test("end-of-session minimization removes transient-only state and live memory", () => {
  const store = new TutorSessionMemoryStore();
  store.open(openRequest());
  store.update({
    ...accessRequest(),
    patch: {
      strategiesTried: ["strategy:number-line"],
      visualExplanationTried: true,
      hintLevelUsed: "guided-step",
      currentConceptRef: "concept:fractions",
      currentMisconceptionHypothesisRef: "misconception:parts-not-equal",
      understoodStepRefs: ["step:identify-whole"],
      lastTutorAction: "reteach",
      interventionCount: 3,
    },
  });
  const result = store.endSession(accessRequest());
  assert.equal(result.status, "ended");
  if (result.status !== "ended") return;
  assert.equal(validateExact(MinimizedTutorSessionEndSchema, result.checkpoint).status, "accepted");
  for (const transientField of [
    "strategiesTried",
    "visualExplanationTried",
    "hintLevelUsed",
    "currentMisconceptionHypothesisRef",
    "lastTutorAction",
  ]) {
    assert.equal(Object.hasOwn(result.checkpoint, transientField), false);
  }
  assert.equal(result.checkpoint.persistenceAllowed, false);
  assert.deepEqual(store.read(accessRequest()), {
    status: "rejected",
    code: "MEMORY_NOT_FOUND",
    tutorMayUseMemory: false,
  });
});

test("memory and minimized end state have no durable raw prose representation", () => {
  const store = new TutorSessionMemoryStore();
  const opened = store.open(openRequest());
  assert.equal(opened.status, "accepted");
  const ended = store.endSession(accessRequest());
  assert.equal(ended.status, "ended");
  const serialized = JSON.stringify({ opened, ended });
  for (const forbidden of [
    "rawTranscript",
    "conversation",
    "privateNotes",
    "diagnosis",
    "password",
    "parentSecret",
  ]) {
    assert.equal(serialized.includes(forbidden), false);
  }
  assert.equal(serialized.includes('"persistenceAllowed":false'), true);
  assert.equal(serialized.includes('"rawProseStored":false'), true);
});
