#!/bin/sh
# Regenerates src/registry.ts from the spec files present in src/specs/.
set -eu
cd "$(dirname "$0")/.."
{
  echo '// Generated by tooling/build-registry.sh — do not edit by hand.'
  echo "import type { LessonSpec } from './types.ts'"
  for f in src/specs/*.ts; do
    b=$(basename "$f" .ts)
    echo "import { $b } from './specs/$b.ts'"
  done
  echo ''
  echo 'export const ALL_SPECS: readonly LessonSpec[] = ['
  for f in src/specs/*.ts; do
    b=$(basename "$f" .ts)
    echo "  ...$b,"
  done
  echo ']'
} > src/registry.ts
